### ISSUE TITLE
C-AD 1.41 doesn't enable / override Firefox native cookie settings when installed

### ISSUE THREAD

**Issue by bendover22** [mrdokenny/Cookie-AutoDelete#100]
### Steps for anyone to reproduce the bug
Install C-AD 1.4.1 in Fx 54.0.1 x64 Linux.
Settings in Fx native cookie manager are UNcheck "Accept cookies from sites"; which automatically disables "allow 3rd party cookies.
Sites will not load cookies until in Fx prefs, you check   "Accept cookies from sites".
Otherwise, sites complain cookies must be enabled.

The 1st time I installed C-AD (same 1.4.1), I didn't change Fx native cookie manager settings.
The settings were UNchecked to allow cookies (as they've been for years).  But, on the 1st install, C-AD allowed temporary, gray or white cookies correctly & deleted them as expected.
Previously, I used Cookie Monster, that was uninstalled before installing C-AD - and C-AD worked correctly.

On uninstalling C-AD for a few days, then reinstalling & restart Fx, sites complain cookies aren't being allowed (though the site exceptions were in C-AD's whitelist ).  
When I enabled the Fx pref  "Accept cookies from sites", C-AD began allowing sites to set cookies.
I uninstalled / reinstalled C-AD a 3rd time, to make sure it wasn't an install error.  Same result.

Why did I not have to change Fx cookie mgr settings the **1st time** C-AD was installed & it worked  - (Accept cookies from sites was STILL unchecked - I looked).  But on the 2nd installation, cookies weren't allowed until I manually changed Fx cookie prefs?

If C-AD requires "Accept Cookies from Sites" box to be checked, shouldn't C-AD automatically check it / change the pref during installation?

### Your settings 
I used default settings for C-AD 1.4.1; active mode is enabled (1 min).

- OS/version: Mint 18.1
- Browser/version: Fx 54.0.1 x64
- Cookie AutoDelete version: 1.4.1

**Comment by mrdokenny** [comment]
>If C-AD requires "Accept Cookies from Sites" box to be checked, shouldn't C-AD automatically check it / change the pref during installation?

WebExtensions do not have access to that setting unforunately. The closest API that I can think of is probably the privacy API.

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/privacy/websites

**Comment by bendover22** [comment]
> WebExtensions do not have access to that setting unforunately. 
OK, thanks.  But I'm confused.
1.  I can't find in C-AD documentation that "Accept cookies from sites," must checked in preferences >Privacy, or else C-AD won't work?  Do instructions mention it (somewhere) that I missed, or does it need to added? 

 Kinda important point.  Not all users leave "Accept cookies from sites" checked, even if they've never used any cookie extensions.  Not all C-AD users will be former SDC users.  You'll soon be getting refugees from several legacy cookie managers.

2. I can't explain why the 1st C-AD install worked OK, when "Accept cookies from sites," was **not** checked.  Can anyone else explain that?  
I looked at all cookies settings after installing C-AD, while viewing 3rd party cookies setting  (also were unchecked).
Unless the about:config pref "network.cookie.cookieBehavior"  was changed to'1' (1=Allow cookies from originating server only ), but failed to put a checkmark by "Accept cookies from sites, I don't know how C-AD could've worked correctly.

**Comment by mrdokenny** [comment]
>I can't find in C-AD documentation that "Accept cookies from sites," must checked in preferences >Privacy, or else C-AD won't work? Do instructions mention it (somewhere) that I missed, or does it need to added?

I do tell people in the troubleshooting steps to reset all their network.cookies.* prefs in about:config which would cover that setting.

As a reference, here's what I'm using in the native cookie settings:

![capture](https://user-images.githubusercontent.com/17077613/29253103-1e3ce2ca-802a-11e7-8614-12028e2c9e44.PNG)

**Comment by bendover22** [comment]
Thanks.
OK, but since it's a critical requirement, that will likely happen to many users - since many disable all cookies, seems like it should be up front, in the How To Use steps, not just in troubleshooting.  Most users don't read troubleshooting steps **before** they try software, addons, etc. :)  Why make it harder for them?

You have 3rd party cookies enabled - keep till they expire. 8-|  Do you prefer tracking cookies, for some reason?  I guess they're cleared at session end, if  clear cookies is checked.  Still, that's a lot of tracking.  For sure, if I do medical, legal research, financial transactions, etc., I don't want tracking cookies.

**Comment by mrdokenny** [comment]
I noticed a lot of the sites that I use break when I turn third party cookies off :/ 

So accepting third party cookies ONLY FROM VISITED is the best next option.

I just added "You must enable cookies in the browser as this extension will replace the internal cookie manager." to the extension listing page.
