### ISSUE TITLE
Upload / Import feature not working

### ISSUE THREAD

**Issue by hackel** [mrdokenny/Cookie-AutoDelete#102]
I've just exported my cookie exceptions from Firefox permissions.sqlite file and am trying to import it into Cookie-AutoDelete.  Unfortunately when I do so, nothing happens.  I don't get an error message, it just acts as if nothing happens as soon as I choose the file to upload.

Please fix the UI to indicate if there is an error, and specify the expected format.  I am using a simple ascii text file containing one domain per line.

Edit: I finally figured out that the parser is looking for the first line of the file to contain `#defaultWhiteList`.  Obviously this is not particularly intuitive or expected at all.

**Comment by mrdokenny** [comment]
In a future release, it's probably going to switch to json objects
