### ISSUE TITLE
[FEATURE REQUEST] Mute notifications 

### ISSUE THREAD

**Issue by lfoppiano** [mrdokenny/Cookie-AutoDelete#1045]
**Describe the solution you'd like**

I'm not sure is possible at extension level, but I would like have the possibility to mute notifications. I find the notification useful as a reminder but the sound is sometimes quite annoying. 

**Describe alternatives you've considered**
Usually I disable the sound on my computer, however when I forget about it I get very loud sound after closing the first tab.

**Comment by kennethtran93** [comment]
Unfortunately this is a browser/OS configuration, not per-extension.  The only way to 'mute' an extension's notification is to not show any notification at all. That can be achieved by toggling the notification option in settings or the popup.

This issue/request is similar to #335.

**Comment by lfoppiano** [comment]
I partially solved (although is not a clean solution) by disabling the sound of all notifications in firefox (macOs) (https://stackoverflow.com/questions/27491672/disable-default-alert-sound-for-firefox-web-notifications)

**Comment by lfoppiano** [comment]
Thanks for your quick answer!
