### ISSUE TITLE
[BUG]  Firefox 86.0.1 Cookie-AutoDelete + Strict Privacy mode seems to be broken

### ISSUE THREAD

**Issue by Acid-Crash** [mrdokenny/Cookie-AutoDelete#1085]
**Firefox 86.0.1 Cookie-AutoDelete + Strict Privacy mode seems to be broken**

I have noticed that some cookies are present within the Primary section of the Firefox.
These cookies are clearly from the sites that are not Whitelisted by Cookie-AutoDelete.
I was thinking that this might be connected to the introduction of Total Protection feature in latest Firefox 
https://blog.mozilla.org/blog/2021/02/23/latest-firefox-release-includes-multiple-picture-in-picture-and-total-cookie-protection/
https://www.reddit.com/r/firefox/comments/lqj1zl/firefox_86_introduces_total_cookie_protection/

In the article it was mentioned that the feature is enabled if Strict Privacy mode is active

**To Reproduce**
- Enable Strict mode in privacy settings of the browser
- Browse the internet
- Wait for the notifications from the extensions that cookies are cleared 
- Observe if all cookies from visited sites are cleared by the Extension

**Expected Behavior**
All non Whitelisted cookies should be deleted by the extension

**Your System Info** 

- OS: Win 10x64
- Browser Info: Firefox 86.0.1
- CookieAutoDelete Version: 3.6.0

**Comment by Acid-Crash** [comment]
Hi @kennethtran93
Not sure what I am missing with this bug...

**Comment by kennethtran93** [comment]
@Acid-Crash you replaced the text in 'describe the bug' header instead of putting the text below the header.

This is also a duplicate of #807
