### ISSUE TITLE
[SUPPORT]  CAD seems to be unable to delete cookies.

### ISSUE THREAD

**Issue by armaguedes** [mrdokenny/Cookie-AutoDelete#1091]
Greetings.

I am presently running CAD 3.6.0 on Firefox v86.0.1x64, but this issue may have started -- or I started noticing it -- as early as 3.5.0 under v85*; CAD's options are shown in the picture below.

 ![c a d  settings](https://user-images.githubusercontent.com/80641951/111080810-12607800-84f8-11eb-81f7-d7860a3952e1.png)

I have Firefox Privacy set to "Strict", and I also run the following addons: ClearURLs, uBO, Privacy Badger, Ghostery, and Disconnect (for what it's worth). Otherwise, this is a Win10x64 machine, fully updated, and without any particular isse; Firefox also runs just fine, even if it sometimes hogs a bit too much of RAM (I regularly restart the browser).

A few weeks ago, I started noticing that in CAD's notification, the number of cookies "deleted" was going up, and the same domains kept appearing. At first, I thought the extension was just doing its thing, but the number kept going up [from 40ish at the time, and at 125 cookies now (from 53 domains), after the screenshot was taken]. It would seem every time I visit a new-to-me website, new cookies get stuck in this "state". Below are the "logs" (already a bit out-of-date).

![c a d  cleared cookies](https://user-images.githubusercontent.com/80641951/111082956-0201ca80-8503-11eb-8b10-5a41a6f64880.png)

So, my question is, how do I get CAD to start deleting non-whitelisted/greylisted cookies again? What is wrong with my setup?

This is my first support request -- or first entry ever, really -- in GitHub, so I apologise for any mistakes, and would appreciate any direction to improve this, if anything is out of place.

Thank you. Kind regards;
Bruno

**Comment by kennethtran93** [comment]
To save you some time, this is a duplicate of #807.

In the future, please utilize the search function available for issues with keywords (in your case 'strict'), and don't forget to check both open and closed issues.
