### ISSUE TITLE
[FEATURE REQUEST]  white/grey list from icon

### ISSUE THREAD

**Issue by brent9999** [mrdokenny/Cookie-AutoDelete#1097]
**Is your feature request related to a problem? Please describe.** 

none

**Describe the solution you'd like** 

Add ability to whitelist or greylist site or domain directly from the toolbar icon (as in similar add-ons).

**Describe alternatives you've considered** 

none

**Additional context**

**Comment by kennethtran93** [comment]
I'm not sure I understand the use case here.  Left clicking on the icon brings up the popup for you to add whitelist or greylist site directly.  You can also add a site when you right-click within a page.

**Comment by brent9999** [comment]
Sorry, I hadn't tried left clicking. My bad. I had only tried right clicking, and since right clicking does bring up several options, I assumed that feature would have been there. I should have tried left clicking too.
