### ISSUE TITLE
[Bug]  Firefox (Mac Catalina) extension causing hangs (spinning pinwheel) of many seconds

### ISSUE THREAD

**Issue by claudiopolis** [mrdokenny/Cookie-AutoDelete#1120]
### Acknowledgements

I acknowledge that I have read the above items

### Describe the bug

A few days ago I started getting the pinwheel on nearly every page load, with only two add-ons running (CAD and NoScript). I disabled both, and normal function resumed. I re-enabled NoScript, and for several days also no issues. Today I re-enabled CAD, and immediately got the problem again. 

Firefox version is 87.0, CAD is 3.6.0.

I'm happy to setup any recommended logging, Wireshark, etc., as directed to help solve the issue. Please advise. 

### To Reproduce

Open any website (whether whitelisted or not). 

### Expected Behavior

Normal loading of page without spinning pinwheel. 

### System Info - Operating System (OS)

MacOS 10.15.7

### System Info - Browser Info

Firefox 87.0

### System Info - CookieAutoDelete Version

3.6.0

**Comment by kennethtran93** [comment]
What are your CAD Settings, primarily the cleanup types?

**Comment by claudiopolis** [comment]
Thanks for your reply! And, I forgot to say, for the awesome extension!
Core settings export pasted below. Anything else I should share?

`{
  "settings": [
    {
      "name": "activeMode",
      "value": true
    },
    {
      "name": "cacheCleanup",
      "value": true
    },
    {
      "name": "cleanCookiesFromOpenTabsOnStartup",
      "value": false
    },
    {
      "name": "cleanExpiredCookies",
      "value": false
    },
    {
      "name": "contextMenus",
      "value": true
    },
    {
      "name": "contextualIdentities",
      "value": false
    },
    {
      "name": "debugMode",
      "value": false
    },
    {
      "name": "delayBeforeClean",
      "value": 15
    },
    {
      "name": "discardedCleanup",
      "value": true
    },
    {
      "name": "domainChangeCleanup",
      "value": false
    },
    {
      "name": "enableGreyListCleanup",
      "value": true
    },
    {
      "name": "enableNewVersionPopup",
      "value": true
    },
    {
      "id": "DEPRECATED - use default expressions",
      "name": "greyCleanLocalstorage",
      "value": false
    },
    {
      "name": "indexedDBCleanup",
      "value": true
    },
    {
      "name": "keepDefaultIcon",
      "value": false
    },
    {
      "id": "DEPRECATED - use localStorageCleanup",
      "name": "localstorageCleanup",
      "value": true
    },
    {
      "name": "localStorageCleanup",
      "value": true
    },
    {
      "name": "manualNotifications",
      "value": true
    },
    {
      "name": "notificationOnScreen",
      "value": 3
    },
    {
      "name": "pluginDataCleanup",
      "value": false
    },
    {
      "name": "serviceWorkersCleanup",
      "value": false
    },
    {
      "name": "showNotificationAfterCleanup",
      "value": false
    },
    {
      "name": "showNumOfCookiesInIcon",
      "value": true
    },
    {
      "name": "sizePopup",
      "value": 16
    },
    {
      "name": "sizeSetting",
      "value": 16
    },
    {
      "name": "statLogging",
      "value": true
    },
    {
      "id": "DEPRECATED - use default expressions",
      "name": "whiteCleanLocalstorage",
      "value": false
    },
    {
      "name": "contextualIdentitiesAutoRemove",
      "value": true
    }
  ]
}`

**Comment by kennethtran93** [comment]
Can you try disabling the cache cleanup and see if that does it?

We have had issues come in about the slowness and for most people it was the cache cleanup. I think it is still a Firefox issue if that is the case as all we do is request the cache cleanup for domains and it is up to Firefox to handle it.

**Comment by claudiopolis** [comment]
Seems to be working, thanks so much! I will close out the issue at the end of the day (UTC+8).

**Comment by kennethtran93** [comment]
Closing as resolved.

**Comment by asymmetric** [comment]
Can confirm that I had the same issue and disabling cache cleanup solved it. I have 1800 open tabs ATM so that might be part of the reason.

**Comment by redactedscribe** [comment]
@kennethtran93 I'm also experiencing this and I do not have Cache Cleanup enabled in CAD's settings.

As soon as I open Firefox, some of the tabs that try to load just hang with a blank background with a spinning circular icon until they eventually do. This also happens seemingly randomly during use of the browser and fairly often. When I disable CAD and restart Firefox, tabs always load instantly.

<details><summary>My CAD core settings (click):</summary>

```json
{
  "settings": [
    {
      "name": "activeMode",
      "value": true
    },
    {
      "name": "delayBeforeClean",
      "value": 15
    },
    {
      "name": "statLogging",
      "value": true
    },
    {
      "name": "showNumOfCookiesInIcon",
      "value": true
    },
    {
      "name": "showNotificationAfterCleanup",
      "value": false
    },
    {
      "name": "cleanCookiesFromOpenTabsOnStartup",
      "value": true
    },
    {
      "name": "contextualIdentities",
      "value": false
    },
    {
      "id": "DEPRECATED - use localStorageCleanup",
      "name": "localstorageCleanup",
      "value": true
    },
    {
      "name": "notificationOnScreen",
      "value": "5"
    },
    {
      "name": "domainChangeCleanup",
      "value": false
    },
    {
      "id": "DEPRECATED - use default expressions",
      "name": "greyCleanLocalstorage",
      "value": true
    },
    {
      "id": "DEPRECATED - use default expressions",
      "name": "whiteCleanLocalstorage",
      "value": true
    },
    {
      "name": "enableNewVersionPopup",
      "value": true
    },
    {
      "name": "debugMode",
      "value": false
    },
    {
      "name": "enableGreyListCleanup",
      "value": true
    },
    {
      "name": "keepDefaultIcon",
      "value": false
    },
    {
      "name": "sizePopup",
      "value": 16
    },
    {
      "name": "sizeSetting",
      "value": 16
    },
    {
      "name": "contextMenus",
      "value": false
    },
    {
      "name": "discardedCleanup",
      "value": true
    },
    {
      "name": "cacheCleanup",
      "value": false
    },
    {
      "name": "cleanExpiredCookies",
      "value": true
    },
    {
      "name": "indexedDBCleanup",
      "value": true
    },
    {
      "name": "localStorageCleanup",
      "value": true
    },
    {
      "name": "manualNotifications",
      "value": true
    },
    {
      "name": "pluginDataCleanup",
      "value": true
    },
    {
      "name": "serviceWorkersCleanup",
      "value": true
    },
    {
      "name": "contextualIdentitiesAutoRemove",
      "value": true
    }
  ]
}
```

</details>

The only other things that come to mind that I think are worth mentioning are that I'm using some regular expressions for site expressions, as well as some site expressions are simply notes that I've written which, if I try to resave them, CAD complains with "Spaces are not allowed in hostnames", so these were created before that check was in place. Edit: I've now removed them all and reimported only the valid ones.

This has been happening since maybe Firefox version 97-98?

CAD 3.7.0
Firefox 100.0.2
Windows 11

**Comment by redactedscribe** [comment]
@kennethtran93 Any idea why this could be still occurring? I've imported the same core/expressions settings files into a Chromium-based browser and the same hang isn't happening, so it looks like the bug only affects Firefox.

Thanks.
