### ISSUE TITLE
[Bug] On No-List Domains, Toolbar Button is the Wrong Color until a Cookie is Set

### ISSUE THREAD

**Issue by BoffinBrain** [mrdokenny/Cookie-AutoDelete#1133]
### Acknowledgements

- [x] I acknowledge that I have read the above items

### Describe the bug

There appears to be an issue with the toolbar button color when the site is not on any list, but no cookies have been set yet. As soon as one is set, the icon updates to red. When the site is greylisted or whitelisted, the icon color is always correct regardless.

This appears to be an issue in Firefox 88.0, but on Firefox 89.0b8 it appears to be even worse because the icon doesn't always update, even after refreshing the page.

### To Reproduce

1. Go to a website that's not on your lists. https://duckduckgo.com/settings#theme is a good example because switching themes is a quick and easy way to set/unset a cookie.
2. Notice the toolbar icon is initially blue.
3. Change the website theme. Notice the toolbar icon is now red when a cookie is set.

### Expected Behavior

The icon should have been red from the start.

### Screenshots

Before and after changing the website theme on DuckDuckGo...

![Firefox 88.0](https://user-images.githubusercontent.com/13255058/117206989-60547680-adeb-11eb-91ed-0d4c7cdf1147.png)

I can provide a video of my cycling through no/grey/blacklisting too if that helps.

### System Info - Operating System (OS)

Windows 10

### System Info - Browser Info

Firefox 88.0 and 89.0b8

### System Info - CookieAutoDelete Version

3.6.0

**Comment by kennethtran93** [comment]
> There appears to be an issue with the toolbar button color when the site is not on any list, but no cookies have been set yet. As soon as one is set, the icon updates to red. When the site is greylisted or whitelisted, the icon color is always correct regardless.

This is not a bug.  We keep the default CAD icon if there are no cookies on the site.  We only change it to red or yellow if there are cookies.  This was part of a request through #66.

> This appears to be an issue in Firefox 88.0, but on Firefox 89.0b8 it appears to be even worse because the icon doesn't always update, even after refreshing the page.

Hmmm...Not sure if this will prelude to a future bug.  Tab icon is supposed to be updated after a small amount of time after page is loaded.

EDIT:  The icon does update on mine in FF Dev edition / 89.0b8

**Comment by kennethtran93** [comment]
Closing as expected behaviour.  Unsure about the icon update in 89, but if that persists a new issue can be opened up.  We rely on the tab events telling us the page is loaded before we change the icon.

**Comment by BoffinBrain** [comment]
> This is not a bug. We keep the default CAD icon if there are no cookies on the site. We only change it to red or yellow if there are cookies. This was part of a request through #66.

To be honest, I think it's very unintuitive. I did see #66 in my searches before posting this bug report but the justifications seemed very odd. Wouldn't it have been better to keep the color purely as an indicator of list status, and rely on the number to show if a cookie is set? Well, if others have decided they like inconsistent behaviour, then all the power to them.

May I suggest a new third icon option in the settings?

**Comment by kennethtran93** [comment]
I can take a feature request for this, though will be low on priority.

**Comment by BoffinBrain** [comment]
That would be nice. Should I make one?

Also, I did some more testing on Firefox beta, which is now at 89.0b10, and the icon (along with the cookie counter) seems to be intermittently incorrect on my primary FF profile, but works fine on a new blank FF profile. Any idea what the cause could be? Should I make a ticket?

**Comment by kennethtran93** [comment]
If you can please.  Otherwise I may end up forgetting.
