### ISSUE TITLE
Delete cookies after certain time

### ISSUE THREAD

**Issue by atrasatti** [mrdokenny/Cookie-AutoDelete#114]
Instead of deleting all cookies as soon as I close the tab it would be nice to delete them a few days later. Maybe a week or a month. There are sites I visit regularly that use login and I'm happy to keep those cookies even when I close the browser, but if I don't visit the site for a certain amount of time it would be nice to have the cookies removed. A default of 30 days, maybe with a simple "number of days" picker would be sufficient.

This is a request for enhancement, not a bug.

**Comment by mrdokenny** [comment]
I think you should look for a different extension that edits the expiration date of the cookie. This extension uses an in-browser timer API which wouldn't work with 30 days as it would reset on browser restart.

**Comment by Thorin-Oakenpants** [comment]
@atrasatti 

1. set cookie lifetime policy
   * `network.cookie.lifetimePolicy`
   * values: 0=until they expire (default), 2=until you close Firefox, 3=for n days (see next pref)
2. set cookie lifetime in days (see above pref) - default is 90 days
   * `network.cookie.lifetime.days`

So set network.cookie.lifetimePolicy=3, and network.cookie.lifetime.days=30
