### ISSUE TITLE
How to import white/gray list from Self-Destructing Cookies?

### ISSUE THREAD

**Issue by msc-** [mrdokenny/Cookie-AutoDelete#115]
This is not a bug or enhancement request but the README doesn't offer any suggestions for discussion of this add-on.

Is there any way to import one's cookie lists from Self-Destructing Cookies? I can't even find a way to view them. "Edit Whitelist" in SDC brings up an empty list and there doesn't even seem to be a way to view its graylist - cookies deleted on browser exit. If there isn't a way ti import, consider this a request for enhancement.

Is it possible to run both SDC & this add-on together so I can manually transfer using the green or yellow SDC icon to guide me?

**Comment by mrdokenny** [comment]
>Is there any way to import one's cookie lists from Self-Destructing Cookies? I can't even find a way to view them. "Edit Whitelist" in SDC brings up an empty list and there doesn't even seem to be a way to view its graylist - cookies deleted on browser exit. If there isn't a way ti import, consider this a request for enhancement.

Currently, there's no way to do this using WebExtensions as the lists from SDC is built-in the browser.

>Is it possible to run both SDC & this add-on together so I can manually transfer using the green or yellow SDC icon to guide me?

I think you can run both of them at the same time.

**Comment by msc-** [comment]
I'm now running both of them.  The radio buttons show that cookie Auto-Delete appears to be remembering my choices but when I look at the white or grey lists they are both empty. Why?

I have the browser preferences set to remember cookies, except 3rd party cookies.

**Comment by msc-** [comment]
I'm now running both of them.  The radio buttons show that cookie Auto-Delete appears to be remembering my choices but when I look at the white or grey lists they are both empty. Why?

I have the browser preferences set to remember cookies, except 3rd party cookies.

**Comment by msc-** [comment]
Ahh! They show up after restarting the browser. That's rather obscure behavior. If you can't fix it, it merits a message on the Cookies White List page: don't expect to see new additions until after browser restart.

**Comment by mrdokenny** [comment]
You mean on the settings page? A refresh should suffice.

As for a fix, I'm working (slowly but surely) on migrating C-AD to React/Redux which would let the UI better reflect the extension state, which would remove the need for a refresh.

The test pilot for this was done on the dev channel of History AutoDelete.

**Comment by msc-** [comment]
Yes I mean on the settings page. Glad to hear you're working on it.

**Comment by mrdokenny** [comment]
Closing as "How to import white/gray list from Self-Destructing Cookies?" cannot be done.
