### ISSUE TITLE
[Bug]  Cleanup logs are all identical

### ISSUE THREAD

**Issue by ctr-n** [mrdokenny/Cookie-AutoDelete#1155]
### Describe the bug

I just noticed all cleanup logs show the same domains, even when the websites I visit are completely unrelated. I'm not sure if this has been happening for long or if it's recent since I never bothered to check cleanup logs until now.

To test if the cookies were being properly deleted, I logged in to some websites and checked if I've been logged out after the cookie cleanup notification pops up, and it seems like it is all working correctly and the respective cookies are being deleted despite the cleanup logs showing unrelated domains. (There has been one exception though- I noticed genshin-impact-map.appsample.com cookies aren't deleted as my preferences (markers on the map) are saved even after cookies are technically deleted. However I believe that's a different issue, probably related to issue #719.)

### To Reproduce

1. Go to any website
2. Close the tab so CAD deletes cookies
3. Check logs and see the cleanup log's domains are unrelated

### Expected Behavior

Cleanup log should show the correct domains.

### Screenshots

![screensh](https://user-images.githubusercontent.com/84939111/119897493-63e5a400-bf38-11eb-817d-fe8c6fa68aee.jpg)

(I censored one domain because it is vaguely personally identifiable.)

### System Info - Operating System (OS)

Windows 10

### System Info - Browser Info

Firefox 88.0.1

### System Info - CookieAutoDelete Version

3.6.0

### Additional Context

(Edit: I apologize if I should've added more information, am not explaining the issue correctly, or if there is some kind of fix that I'm not aware of; I'm not the most tech-savvy person.)

**Comment by kennethtran93** [comment]
Your issue may be related to bug #807. What privacy setting are you using?

**Comment by ctr-n** [comment]
My firefox privacy settings are set to "strict". Here's my CAD settings too, in case it's relevant:
![s1](https://user-images.githubusercontent.com/84939111/119906439-238d2280-bf46-11eb-823a-a610d006fca5.jpg)
![s2](https://user-images.githubusercontent.com/84939111/119906455-2c7df400-bf46-11eb-9ca6-218b52633bf5.jpg)
Also, looking at the settings now I noticed the "cleanup logs will not be generated for tabs in private browsing" warning, but in my case the logs from incognito still show up. Dunno if it's relevant but thought it was better to share either way.

**Comment by kennethtran93** [comment]
Yeah the strict setting is causing all cookie extensions issues at this time. See the referenced issue above for details.  Your cookies aren't being removed at this time. 

I'll look into the private browsing mode later on.

**Comment by ctr-n** [comment]
I checked the other thread and just to make sure, I should change my privacy settings to custom with cookies set to "cross-site tracking cookies", correct?

Also it seemed like my cookies were being deleted (at least on most websites) since on the websites I tested I was being logged out and/or getting those "accept cookies for this website" popups again as expected (with the exception of the website I mentioned on my first post). I can't find on the settings any option to check all my cookies or else I'd have a look at which ones are being deleted and which are stuck - if such a feature exists let me know and I'll have a look.

**Comment by kennethtran93** [comment]
> 
> 
> I checked the other thread and just to make sure, I should change my privacy settings to custom with cookies set to "cross-site tracking cookies", correct?

Yes.  However, keep in mind that we will not be able to remove existing cookies created through the strict setting, so those popups will still show those ones.


> Also it seemed like my cookies were being deleted (at least on most websites) since on the websites I tested I was being logged out and/or getting those "accept cookies for this website" popups again as expected (with the exception of the website I mentioned on my first post). I can't find on the settings any option to check all my cookies or else I'd have a look at which ones are being deleted and which are stuck - if such a feature exists let me know and I'll have a look.

I do not believe the cookies were getting deleted, despite our webextension telling you otherwise, we had blindly presumed that it would be deleted and haven't checked the actual return value (well this usually wasn't an issue up until now and have been mentioned in #719).  Only the logs would tell you which cookies were 'supposedly' deleted (click on each to get details for each cookie name/site).

**Comment by ctr-n** [comment]
Oh perhaps I didn't word things properly, but my logs kept showing the same stuck domains and weren't showing the domains that I was visiting, though those were still being deleted. For example, I visit website A, and the cleanup log shows websites B C D E (the stuck cookies) and not A, however my cookies from A were still being deleted despite not appearing on the logs. However I believe that might have been another unrelated bug because after clearing some cookies it seems that the logs show up the correct domains now (plus the "stuck" ones as expected), so it got solved by itself.

To attempt to clear those stuck cookies, I tried installing [another extension](https://addons.mozilla.org/en-US/firefox/addon/cookie-quick-manager/) and even though it allowed me to check all cookies that weren't deleted, the deleting option also didn't work. Don't know if that's an issue with that extension as well (it also hasn't been updated in 2 years) or if this means the problem is with firefox itself, since both your extension and theirs have a similar problem.

However I found out you can delete a specific website's cookies by clicking on the padlock on the address bar and then on "clear cookies and site data", which allowed me to delete the vast majority of those stuck cookies manually by visiting those pages one by one. Unfortunately there are still a few cookies that I can't delete as I can't visit some specific domains. Either way, most of them were deleted and hopefully no more will get stuck thanks to the privacy settings change you recommended- thank you for the help!

**Comment by kennethtran93** [comment]
> Oh perhaps I didn't word things properly, but my logs kept showing the same stuck domains and weren't showing the domains that I was visiting, though those were still being deleted. For example, I visit website A, and the cleanup log shows websites B C D E (the stuck cookies) and not A, however my cookies from A were still being deleted despite not appearing on the logs. However I believe that might have been another unrelated bug because after clearing some cookies it seems that the logs show up the correct domains now (plus the "stuck" ones as expected), so it got solved by itself.

I don't believe we apply any sorting to the cookies that are returned through the webextension API, so it's hard to say what is happening.  All we do at this time is go in order of how it is given to us and append the domain name if it is not already in the list of 'removed'.


> To attempt to clear those stuck cookies, I tried installing [another extension](https://addons.mozilla.org/en-US/firefox/addon/cookie-quick-manager/) and even though it allowed me to check all cookies that weren't deleted, the deleting option also didn't work. Don't know if that's an issue with that extension as well (it also hasn't been updated in 2 years) or if this means the problem is with firefox itself, since both your extension and theirs have a similar problem.

As mentioned, this is a Firefox problem, namely the new protection value is not yet available through the WebExtension API.


> However I found out you can delete a specific website's cookies by clicking on the padlock on the address bar and then on "clear cookies and site data", which allowed me to delete the vast majority of those stuck cookies manually by visiting those pages one by one. Unfortunately there are still a few cookies that I can't delete as I can't visit some specific domains. Either way, most of them were deleted and hopefully no more will get stuck thanks to the privacy settings change you recommended- thank you for the help!

Removing cookies through Firefox Preferences/Padlock icon goes through Firefox's own internal cleanup functions, not through WebExtension API.  You can try to go into Firefox Preferences area and see the full list of cookie domains and try to remove those as well, as long as you're okay with it.
