### ISSUE TITLE
whiteList is undefined

### ISSUE THREAD

**Issue by mcnesium** [mrdokenny/Cookie-AutoDelete#116]
### Describe the Bug/Feature

It does not delete cookies.

### Screenshot in which the bug can be seen

![screenshot from 2017-08-24 16-23-05](https://user-images.githubusercontent.com/476060/29671022-b65e0130-88e8-11e7-9b73-29b37d6da195.png)

### Steps for anyone to reproduce the bug

start `firefox -p`, create new profile, install Cookie-Autodelete from [amo](https://addons.mozilla.org/en-US/firefox/addon/cookie-autodelete/), enable Active Mode in the settings, log into twitter, close twitter tab. open a new tab, go to twitter.com -> still logged in.

The error message wrapped open in the screenshot is the one that appeared on closing the tab. the other two came up after reopening it.

### Your settings 

- OS/version: Manjaro Linux 17.02
- Browser/version: Firefox 55.0.2
- Cookie AutoDelete version: 1.4.3

**Comment by mrdokenny** [comment]
Probably related to #93

**Comment by mcnesium** [comment]
Don't know if really related, but I unchecked the Support for Firefox's Contextual Identities setting, and now it seems to work.
