### ISSUE TITLE
[FEATURE REQUEST] Allow cookie injection / whitelist individual cookie value

### ISSUE THREAD

**Issue by wavexx** [mrdokenny/Cookie-AutoDelete#1165]
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Is your feature request related to a problem? Please describe.

A common problem that occurs when clearing old cookies is that "do not track" cookies, or some other non-identifying cookies gets removed as well. This is, of course, CAD working as intended, no complaints here.

However, the user experience could be improved further by allowing certain cookies and/or key-values to stay set, and-or allow to reinject them to a fixed value when visiting the site.

This would allow to actually improve the user-experience by a huge margin. By having the consent/cookie opt-out settings preset, we avoid the subsequent request in the first place. These can be quite difficult to hide properly even with uBO.

### Describe the solution that you'd like

This is more of an RFC than a specific request. It's clear to me that the current behavior is fine, and shouldn't be made more complicated unless the user wants to dig deeper.

Having a dedicated page in the settings where we can put either value whitelist expressions for a domain pattern, or cookies to be injected to a domain pattern requires good technical knowledge in both identifying the cookie and setting the expression, but would already be a great start.

### Additional Context

Thinking loudly about this, a pre-baked list of "consent/cookie" opt-out values would currently be more effective than what we do with cosmetic filters in uBO. Many frameworks generate these with dynamic names (with css rules to match), so they can be quite tricky to hide.

It's also not about hiding either. Some cookies are set for age-limit restrictions, as a result the content itself is not accessible until explicitly set. In such cases there's nothing we can do with uBO.

**Comment by kennethtran93** [comment]
You can find and configure your entire list of Expressions through the extension settings > List of Expressions.

You can also configure a custom regular expression that would match multiple domains, and configure that expression to keep certain cookies (once the site has been visited at least once with cookies still in that site) by unchecking 'keep all cookies'.

We will not be checking any cookie values at this time - only the name/key of the cookie.

Also to keep the extension size small to start we are not including any baked-in expressions. Over in the discussions section, there is a topic for expressions that anybody (with a GitHub account) can make a reply to with their working expressions/cookie names.

**Comment by kennethtran93** [comment]
Ah I missed the part about cookie injection.

No we will not be injecting any user-created cookies into any site.  The only cookie injection we do is used to allow us to remove other site data types especially when those sites do not set any cookies.

**Comment by kennethtran93** [comment]
Closing as both portions of the request has been answered.  One will not be done, the other has been done already.
