### ISSUE TITLE
[BUG] Extension menu window not fully opening (UI)

### ISSUE THREAD

**Issue by lisandrocarmona** [mrdokenny/Cookie-AutoDelete#1169]
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Describe the bug

When I click in the extension icon in the browser toolbar, only a small line appears, not the full menu.

### To Reproduce

Just click over the extension icon to see the UI bug.
I tried to reopen the browser, uninstall and install extension again, and these did not solve the issue.

### Expected Behavior

Open the menu to opt for white/gray list, etc.

### Screenshots

![image](https://user-images.githubusercontent.com/6163906/121197067-605ef080-c847-11eb-891a-f77d4a5b80ab.png)

### System Info - Operating System (OS)

Windows 10 Pro x64

### System Info - Browser Info

Vivaldi 3.8.2259.42 (Stable channel) (64 bits)

### System Info - CookieAutoDelete Version

3.6.0

**Comment by kennethtran93** [comment]
Do you have any windows program /desktop program that may interfere or adjust the look of programs/windows?

**Comment by lisandrocarmona** [comment]
Hi, my monitor resolution is 1366 x 768 and text scale is 100%.
I can change for a higher resolution, but then I need to increase the text scale too.

**Comment by kennethtran93** [comment]
I'm not exactly sure what is causing it to not properly show up. Does it work in Google Chrome?

**Comment by lisandrocarmona** [comment]
Never mind. It's working on Linux (Vivaldi). I don't use Google Chrome.
I've exported all settings and filters, uninstall and install again. It's working now.
We can close this ticket. Thanks.
