### ISSUE TITLE
[SUPPORT]  Is it possible to delete cookies from main domain?

### ISSUE THREAD

**Issue by scmanjarrez** [mrdokenny/Cookie-AutoDelete#1172]
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Please describe what you need support with

Is it possible to delete cookies from main domains? e.g: hello.world.com --> world.com

I'm asking for the medium.com [subdomains](https://dltlabs.medium.com/set-up-a-hyperledger-fabric-state-database-as-a-couchdb-cluster-using-containerization-bba0c6a0ff98), that restrict the number of articles that you can read, deleting the cookies from the "clear cookies and site data" in firefox, remove cookies related with the domain and subdomain (effectively removing the restriction). However, if I clean the cookies with CAD, only cookies from subdomains are removed (still restricted).

**Comment by kennethtran93** [comment]
Normally cookies and configured site data to remove would be automatically done once that domain (subdomain and main domain) is nowhere to be found in any opened tabs. If you set an expression entry for it then you are saying you plan on keeping certain cookies/domains from being removed.

If you are in strict mode, you need to adjust your cookie settings to be 'cross-site tracking cookies' only as the 'cross-site cookies' is breaking all cookie webextensions. 

A feature request to have a list that removes specific cookies has already been made. Feel free to add a thumbs up to that request.
