### ISSUE TITLE
[SUPPORT] Should I whitelist subdomain or domain when wanting to keep a website logged in ? 

### ISSUE THREAD

**Issue by ng4ever** [mrdokenny/Cookie-AutoDelete#1178]
### Acknowledgements

- [x] I acknowledge that I have read the above items

### Please describe what you need support with

Which one or does it depend on the site ?

Thanks for any help.

**Comment by kennethtran93** [comment]
This depends on the site. Some domains use a subdomain for authentication (e.g. auth.example.com) and some subdomains aren't related to the main domain (e.g. example. wordpress.com vs another.wordpress.com vs wordpress.com)

**Comment by ng4ever** [comment]
> 
> 
> This depends on the site. Some domains use a subdomain for authentication (e.g. [auth.example.com](http://auth.example.com)) and some subdomains aren't related to the main domain (e.g. example. [wordpress.com](http://wordpress.com) vs [another.wordpress.com](http://another.wordpress.com) vs [wordpress.com](http://wordpress.com))

So how do I know what to whitelist please? Thanks.

**Comment by kennethtran93** [comment]
This depends on the site in question and how they store and fetch the cookies used for authentication and whatnot.

If you believe the site in question owns all the subdomains that you know of to date, it may be easier to just whitelist the entire domain.  If not, then the safer bet would be just the subdomain, though if your login/auth doesn't persist after the cookie cleanup, then you know you'll need to dig deeper and see which cookie(s) on the domain you need to keep based on what cookies from the domain was removed by us.

 It is not easy to assist with that portion without you telling me which site you need to configure it for.

**Comment by ng4ever** [comment]
> 
> 
> This depends on the site in question and how they store and fetch the cookies used for authentication and whatnot.
> 
> If you believe the site in question owns all the subdomains that you know of to date, it may be easier to just whitelist the entire domain. If not, then the safer bet would be just the subdomain, though if your login/auth doesn't persist after the cookie cleanup, then you know you'll need to dig deeper and see which cookie(s) on the domain you need to keep based on what cookies from the domain was removed by us.
> 
> It is not easy to assist with that portion without you telling me which site you need to configure it for.


Ok np sure. 

att.com the login where I have to keep putting in a code from my cell number to verify to sign in.

**Comment by kennethtran93** [comment]
You may be able to just whitelist the site itself and not the wildcard subdomains (att.com) and give it a shot.  If that doesn't work then you can try to whitelist all the subdomains within that site, or dig deeper into the cookies stored for that domain to see if you can find the one that keeps your device from being asked for a code every time.

Sometimes, depending on site configuration, sites will always require you to put in a code from your mobile unless you happened to check the box that 'saves' your device so you don't need a code too often on that specific device.  If you don't see a checkbox for that when prompted for the code, then you'll always need to enter in a code every login (even if the initial 'remember me' checkbox for your credentials are checked or you've saved the credentials through your browser).
