### ISSUE TITLE
[SUPPORT]  Automate export of expressions (scripting)

### ISSUE THREAD

**Issue by Snooober** [mrdokenny/Cookie-AutoDelete#1191]
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Please describe what you need support with

Is there a way to automate exporting expressions (i.e. in a bash script)?

**Comment by kennethtran93** [comment]
Sorry, but what you are referring to is outside our webextension capabilities at this point. You'd need to figure out how the browser stores the webextension data and go from there.

Were not going to make any native applications as that is not needed to be able to use a webextension.

A browser sync feature is in the works.
