### ISSUE TITLE
[Bug]  Does not appear to be working at all in the current version of Firefox

### ISSUE THREAD

**Issue by jmhale99** [mrdokenny/Cookie-AutoDelete#1209]
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Describe the bug

All cookies remain after a cleanup.  Each time a cleanup is performed, the same domains keep showing in the log as cleaned, but the cookies remain.

### To Reproduce

An example:
1. Ensure no cookies are present for politico.com.
2. Go to politico.com
3. Run a cleanup
4. Politico.com shows in the log as having cookies removed.
5. The cookies remain.

I have performed the same operation on Chrome with the extension and it works there.  I do not have containers enabled on Firefox.

### Expected Behavior

Expect the cookies to be removed.

### System Info - Operating System (OS)

Windows 10 Pro

### System Info - Browser Info

Firefox 91.0

### System Info - CookieAutoDelete Version

3.6.0

**Comment by drk002** [comment]
Confirmation. CAD does not work with the latest Firefox. (Does not clear cookies).

**Comment by kennethtran93** [comment]
What is your privacy setting at?

**Comment by jmhale99** [comment]
strict

**Comment by kennethtran93** [comment]
Strict mode in Firefox 86+ has never worked for any cookie webextensions due to their 'total cookie protection' which introduced a different way of storing cookies, to which the Firefox's WebExtension API has yet to implement (i.e. the 'double keying' value).  

Use standard mode, or use custom mode with cookie setting set to 'cross-site tracking cookies'.  (This would have been the 'strict' mode prior to version 86 - The 'standard' mode in 86+ appears to be similar to 'strict' mode pre-86).

@drk002 does this also apply to you?

Duplicate of #807.

**Comment by jmhale99** [comment]
That fixed it.  Thanks.

**Comment by kennethtran93** [comment]
No problem. You may need to manually delete the cookies created while in strict mode through the Firefox cookies and site data manager.

**Comment by fhtdtdj** [comment]
Same issue in "custom: cross-site cookies" mode; switched to "cross-site tracking cookies" mode and manually deleting the previously affected cookies seems to have fixed it. Thanks. Would be nice if you added a warning about this issue on the FF add-on page.

**Comment by kennethtran93** [comment]
Thanks. Yes strict mode sets cookie value to cross-site cookies.

Thanks for the reminder - I'll update it soon.

**Comment by ghost** [comment]
Not sure if this is helpful but this is working fine for me and my settings are more strict than the 'strict' mode (one notch shy of "thou shall not pass"):

![image](https://user-images.githubusercontent.com/58130821/129840365-58112014-9346-4741-9d7d-a9a6afe04752.png)

I did have cookies which refused to delete with the plugin on its first installation, those had to be removed via settings, but once they are deleted from there they can be created and deleted by the plugin at will.
