### ISSUE TITLE
No whitelist shown in settings

### ISSUE THREAD

**Issue by mcnesium** [mrdokenny/Cookie-AutoDelete#121]
### Describe the Bug/Feature

When entering the addon settings page from `about:addons`, the following error appears in the browser console:

![bildschirmfoto 2017-08-28 um 17 51 14](https://user-images.githubusercontent.com/476060/29781560-e0c35126-8c19-11e7-9dfb-536853f7c65e.png)

Then, the whitelist has no content, even though it does keep cookies of sites which I whitelisted from the icon's context menu. New entries will also not appear in the list, when trying to enter them via the settings page.

![bildschirmfoto 2017-08-28 um 17 55 01](https://user-images.githubusercontent.com/476060/29781614-0cfa4ee8-8c1a-11e7-93a9-6255ed25e252.png)

- OS/version: OSX 10.11.6
- Browser/version: Firefox 55.0.3
- Cookie AutoDelete version: 1.4.3

**Comment by ingelres** [comment]
I'm facing the same issue on FF 55.0.3 on a Debian 8. I've just replaced SDC by this extension and without the possibility to manually manage the white list, it's of little use (e.g., cannot add *.domain.com).

**Comment by mrdokenny** [comment]
>manually manage the white list, it's of little use (e.g., cannot add *.domain.com).

In an upcoming version, you'll be able to do so.

**Comment by ingelres** [comment]
The updated features for the next version is a good news, but the current version still has the issue reported here: There's an error in the JS code and the Cookie Whitelist section doesn't work at all (can't see or edit the whitelist).

**Comment by mrdokenny** [comment]
Maybe turn on e10s? See #117

**Comment by ingelres** [comment]
AFAICT, it is enabled on my FF (about:support show Multiprocess Windows: 1/1 (enabled by the user)).

**Comment by mrdokenny** [comment]
Try a `Restore Default Settings`. I think the whitelist data might be corrupted from entering a '*'.

**Comment by mcnesium** [comment]
restoring to default settings did not fix this for me

**Comment by ingelres** [comment]
It fixed it for me as well, I may indeed have tried to enter a URL with a star.

**Comment by mrdokenny** [comment]
Seems to be fixed so closing.
