### ISSUE TITLE
[FEATURE REQUEST]  ???

### ISSUE THREAD

**Issue by herbieerb** [mrdokenny/Cookie-AutoDelete#1219]
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Is your feature request related to a problem? Please describe.

Unfortunately I do not seem to be able to turn off the sounds.  They are really rather annoying.

### Describe the solution that you'd like

Under the Settings tab, it would be really great to have a toggle to turn sounds off and on.

**Comment by kennethtran93** [comment]
You can only turn off the sounds by turning off the notifications.  These are browser/device controlled, not extension controlled.  All we do is pass messages to the notification API.  There is no option there to turn off sound for specific notifications.

WebExtension Notifications are created through this: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/notifications/create with options through this: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/notifications/NotificationOptions
