### ISSUE TITLE
[Bug]  Chrome 'Clean All for this Domain' extremely slow or doesn't work at all

### ISSUE THREAD

**Issue by gcstang** [mrdokenny/Cookie-AutoDelete#1235]
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Describe the bug

When trying to clear cookies for a single domain using 'Clean All for this Domain' most of the time it never does anything or it takes minutes to actually clear the cookie.

### To Reproduce

Connect to company VPN
Go to a domain URL
Click on icon in browser
Select drop down on Clean
Click on 'Clean All for this Domain'
Wait

### Expected Behavior

Expect this to take much less time than it does and work, currently it hardly ever works even after waiting minutes

### System Info - Operating System (OS)

macOS 11.6

### System Info - Browser Info

Chrome 93.0.4577.82 (Official Build) (x86_64)

### System Info - CookieAutoDelete Version

3.6.0

**Comment by kennethtran93** [comment]
I doubt connecting to VPN would affect how the browser stores, processes and cleans up data but I could be wrong. 

'Clean All for this domain' will clean up the following additional browsing data types (not just cookies).

- Cache
- IndexedDB
- Localstorage
- PluginData (i.e flash - deprecated)
- Service Workers

In Firefox, cleaning up Cache seems to take a very long time (not a CAD bug), so maybe Chrome is also taking a while cleaning up Cache or another browsing data type as well.
If you simply want to clean up all cookies for that domain, you can use the option available for just the cookies on that domain.

**Comment by gcstang** [comment]
Nothing in "Other Browsing Data Cleanup Options" is checked.
I'll try just the cookies option

**Comment by kennethtran93** [comment]
@gcstang is this still an issue (aside from the Cache issue)?

**Comment by kennethtran93** [comment]
Closing as stale.
