### ISSUE TITLE
[SUPPORT]  Youtube Greylist (help to prevent cookie agreement every visit)

### ISSUE THREAD

**Issue by false-9** [mrdokenny/Cookie-AutoDelete#1241]
### Acknowledgements

- [x] I acknowledge that I have read the above items

### Please describe what you need support with

I am having an issue where I try to greylist 'https://www.youtube.com' in order to prevent the tedious cookie agreement dialogue box whenever I visit the site. However despite having greylisted the above as well as 'https://www.google.com' I am still faced with this annoying prompt every time I visit Youtube within the same browser session. I also get a CAD notification telling me the cookies having been deleted despite the exception. Maybe I'm not understanding Google/Youtube's domain structure properly or something and 'https://www.youtube.com' doesn't suffice for this? 

Expected: Having greylisted the domain, expect not to be met with cookie agreement on every visit within the browser session (after having once made my privacy choices).

Actual: CAD functions as normal despite the greylist entry and every time I click a link or visit the site I have to re-enter my cookie preferences.

Kind thanks.

**Comment by false-9** [comment]
@kennethtran93 [title edit]

**Comment by kennethtran93** [comment]
You need to remove the `https://www` portion of the domain expression in order for it to work.  Either use `*.youtube.com` or `youtube.com` as the domain expression.  Same with google.com and any other domains you want to greylist.

When you visit the site, you can use the CAD popup while on that site to automatically add either a white or grey list to the list of expressions.

If you've enabled cleanup for other browsing data types, those may need to be kept as well.  I haven't dug into exactly how the cookie preferences is stored.

**Comment by false-9** [comment]
> When you visit the site, you can use the CAD popup while on that site to automatically add either a white or grey list to the list of expressions.

Wow I'm dumb... I usually remove my toolbar icons for extensions for minimalist sake so this didn't even cross my mind. I also see the option in the right-click menu as well, whoops.

I will keep the correct domain expression in mind as well. Thanks for the support it is working now!
