### ISSUE TITLE
[SUPPORT]  Cookie-AutoDelete Blank Settings Tab

### ISSUE THREAD

**Issue by fragosgeorge** [mrdokenny/Cookie-AutoDelete#1255]
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Please describe what you need support with

Clicking on "Settings" command in drop-down menu for the settings of Cookie-AutoDelete only opens a new blank tab in Firefox.

**Comment by kennethtran93** [comment]
Which flavor and version of Firefox?  What other webextensions are you using?

**Comment by kennethtran93** [comment]
Closing as stale.
