### ISSUE TITLE
[FEATURE REQUEST]  Cleanup unused cookies after (selectable) 7 days

### ISSUE THREAD

**Issue by anttiryt** [mrdokenny/Cookie-AutoDelete#1265]
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Is your feature request related to a problem? Please describe.

I want to have chrome forget any site data / cookies for a site I haven't visited for a week or a month. 

FIrefox has this inbuilt on Network.cookie.lifetimePolicy (3).

I think this is great alternative for whitelisting cookie sites. If i frequent google mail daily, saving cookies is ok. If I read medium.com article once a month, please see me as a new visitor.

### Describe the solution that you'd like

Delete cookies / sitedata if they have not been used for some time.

### Describe alternatives you've considered

I was looking for other chrome addons but couldn't find any. Also chrome settings were of little use.

**Comment by kennethtran93** [comment]
I think this is a similar request to #707.  Let me know if it is not, otherwise I'll close as duplicate.
