### ISSUE TITLE
Enable "Enable Active Mode" by default

### ISSUE THREAD

**Issue by davidhedlund** [mrdokenny/Cookie-AutoDelete#127]
Self-Destructing Cook deleted cookies seconds after I closed tabs. In Cookie AutoDelete I have to check "Enable Active Mode" because its unchecked by default. Can you please change that?

**Comment by mrdokenny** [comment]
See https://github.com/mrdokenny/Cookie-AutoDelete/issues/104#issuecomment-323527793

**Comment by davidhedlund** [comment]
That make sense.
