### ISSUE TITLE
[Bug]  Why 

### ISSUE THREAD

**Issue by crazyyzarc** [mrdokenny/Cookie-AutoDelete#1272]
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Describe the bug

Not all data will be deleted. See third image

### To Reproduce

normal use

### Expected Behavior

Delete all data

### Screenshots

![2021-11-30_14-58-54-834_cyeLv](https://user-images.githubusercontent.com/4954535/144061147-248728d1-e346-42b7-bc50-9753b6866414.png)
![2021-11-30_14-59-32-034_ws0VO](https://user-images.githubusercontent.com/4954535/144061158-c60cfc51-b5c5-46bd-8a5b-b5940e3af932.png)
![2021-11-30_15-02-00-575_yPpCA](https://user-images.githubusercontent.com/4954535/144061388-62955441-75d8-45c8-8eb3-f760b8d240e0.png)

### System Info - Operating System (OS)

Windows 10

### System Info - Browser Info

Firefox 93

### System Info - CookieAutoDelete Version

3.6.0

**Comment by kennethtran93** [comment]
See #807 for the main reason why.

Strict Mode / Cross-Site Cookies option from Firefox 86-93 did not have any WebExtension APIs to handle the additional cookie parameters.

In addition, please update to Firefox 94. Firefox 94 has added additional API calls to handle this which I will be including in the next release to address the remaining partitioned cookies.
