### ISSUE TITLE
[Bug]Chrome Cookies Issue

### ISSUE THREAD

**Issue by redwolfe98** [mrdokenny/Cookie-AutoDelete#1286]
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Describe the bug

apparently chrome has a new folder, "network," at "C:\Users\Tom\AppData\Local\Google\Chrome\User Data\Default\Network" and it contains a file named "cookies." maybe this needs to be looked into?
also, there might be an issue with files within the "code cache\js" folder, at "C:\Users\Tom\AppData\Local\Google\Chrome\User Data\Default\Code Cache\js." maybe they need to be removed when CAD is clearing caches?

### To Reproduce

use chrome to browse webpages. look at data/files within the chrome folders.

### Expected Behavior

i expect CAD to remove cookies and cached temporary-files associated with the chrome browser.

### System Info - Operating System (OS)

windows 10-21H2

### System Info - Browser Info

Chrome Version 96.0.4664.110

### System Info - CookieAutoDelete Version

3.6.0

### Additional Context

i wanted to bring this issue to the CAD-developers attention.
https://community.ccleaner.com/topic/61744-ccleaner-not-deleting-chrome-cookies/

**Comment by kennethtran93** [comment]
We have no control over actual files on the OS.  All we can do is use the WebExtension API functions to remove cookies and browsing data.  You'll need to bring this up with Chrome browser team.
