### ISSUE TITLE
[SUPPORT] Not all storage data is deleted

### ISSUE THREAD

**Issue by jathri** [mrdokenny/Cookie-AutoDelete#1298]
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Please describe what you need support with

Hello,
when I close Firefox and then start it again, all cookies and storage data should be deleted provided that I enabled:
    Enable Cleanup for Discarded/Unloaded Tabs
    Enable Cache Cleanup
    Enable IndexedDB Cleanup
    Enable LocalStorage Cleanup
    Enable Plugin Data Cleanup
    Enable Service Workers
Because all (except pinned) tabs are unloaded at startup. Is this correct?
Yet some storage data is not deleted at startup. See https://i.imgur.com/Flu0gcq.png (github is only site loaded after restarting firefox so thats why cookies are present)
Is there a way to find out what is left? So I can make proper bug/feature request towards removing this data as well.
BR
jathri

Note: have Open previous windows and tabs checked (in firefox general settings). So many tabs are in tabstrip at startup. But all are (should be) unloaded.

**Comment by kennethtran93** [comment]
What rule/expression have you put into place?

> Because all (except pinned) tabs are unloaded at startup. Is this correct?

> Note: have Open previous windows and tabs checked (in firefox general settings). So many tabs are in tabstrip at startup. But all are (should be) unloaded.

I do not know which tabs are deemed to be unloaded by the browser at startup yet, so I cannot assist you there.  That is usually up to the browser to decide.  From what I read the tabs are only unloaded if there's not enough system/browser resources.

> Yet some storage data is not deleted at startup. 

We know that there may still be some data remaining.  If some are 64.0kb, then it may just be an empty indexedDB.  We do have some site data that we have not implemented yet as they weren't available to us in prior browser versions, and bugs/requests have been created for those already.  Those may be implemented in a future version.
