### ISSUE TITLE
[Bug] Plugin Not Loading. package is invalid

### ISSUE THREAD

**Issue by user625462** [mrdokenny/Cookie-AutoDelete#1299]
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Describe the bug

I tried to install the plugin as chrome web store, manually as CRX file and unpacked item but failed.

### To Reproduce

1."Add the extension to Chrome"
2."The package is invalid. Details: 'Variable $matchedExpression$ used but not defined.' "

### Expected Behavior

When you change Chrome's language to English (USA), the problem is solved and the plugin is loaded. But when I change the language to my native language (Turkish), the plugin is automatically deleted from the browser again.

### Screenshots

![Ekran görüntüsü 2022-01-10 112016](https://user-images.githubusercontent.com/96021006/148771596-0102e96b-628c-496b-9d43-c20f7339d6cc.jpg)
![Ekran görüntüsü 2022-01-10 144740](https://user-images.githubusercontent.com/96021006/148771622-c97a3705-8577-4cca-9da0-94c0caca325e.jpg)

### System Info - Operating System (OS)

Windows 10 Pro(21H2)

### System Info - Browser Info

Chrome 97.0.4692.71

### System Info - CookieAutoDelete Version

3.6.0

**Comment by hxvy0** [comment]
bende de aynı sorun var knks eklenti sadece firefoxta calistirabildim.

**Comment by kennethtran93** [comment]
This is included in 3.7.0 and has been released on Firefox.  Release on Chrome is awaiting its review.
