### ISSUE TITLE
[Bug]  Udemy cookies not clearing

### ISSUE THREAD

**Issue by sawft99** [mrdokenny/Cookie-AutoDelete#1300]
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Describe the bug

When using udemy and having all options checked for clearing out cookies, even after browser restarts the site remembers me

### To Reproduce

1. Use Udemy.
2. Login
3. I'm not sure if you need to do anything specific but I was watching videos.
4. Leaving site and waiting the configured time or even restarting the browser will allow you to log back in.

### Expected Behavior

Should clear cookies and similar files to ensure nothing is remembered about you.

### System Info - Operating System (OS)

Windows 10 Pro

### System Info - Browser Info

Chrome 97.0.4692.71

### System Info - CookieAutoDelete Version

3.6.0

**Comment by sawft99** [comment]
I'm not sure what needs to be done with this since it still shows as 'untested'. Is that in refrence to someone who's part of the project not testing or is there something else I need to do?

**Comment by kennethtran93** [comment]
Sorry I was busy and had this sitting in my inbox for a while.

What settings are you using and what expressions have you used?  Any cleanup logs from CAD that might tell us what's happening?

Do you have the restore tabs on restart option in Chrome enabled and was this domain part of the ones reopened on startup?

**Comment by sawft99** [comment]
I have all cleanup options checked except the 'domain change' option. I actually haven't been able to replicate this as of yet. Seems random at times. If you'd like to close that's fine. I'll just comment again if I can make it happen.

**Comment by kennethtran93** [comment]
Just keep in mind that if you have that site open and the 'restore tabs on restart' option enabled, we may not be able to clear the cookies before the site is reloaded on restart.
