### ISSUE TITLE
[Bug]  Chromebook Cleaning Not Working Anymore

### ISSUE THREAD

**Issue by Spiralpine** [mrdokenny/Cookie-AutoDelete#1302]
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Describe the bug

- Automatic cleaning ⇒ Not working
- Manual cleaning by pressing the “Clean” button ⇒ Not working
- The manual “Clean all for this domain” ⇒ Not working
- No Cleanup log generated

### To Reproduce

- Open any website
- The number of Cookies are shown
- Choose any of above mentioned actions
- No cleaning done
- No Cleanup log generated

### Expected Behavior

- Cleanup performed successfully
- Cleanup log generated

### System Info - Operating System (OS)

Google Pixelbook Chromebook, Chrome OS Version 97.0.4692.91 (Official Build) (64-bit)

### System Info - Browser Info

Chrome OS Version 97.0.4692.91 (Official Build) (64-bit)

### System Info - CookieAutoDelete Version

3.6.0

### Additional Context

What works:
The manual “Clean Cookies for this domain” ⇒ works with the notification shown, but the “Cleanup log” is NOT generated

CAD Settings:
All options are checked, except "Enable Debug Mode (Additional Console Outputs)”

**Comment by waaweech** [comment]
This issue can be closed as everything is working now. The issue appeared right after updating the Chrome OS to 97.0.4692.91 and rebooting the Chromebook. After a second reboot the issue I've reported disappeared all together and CAD is working as expected.

Excellent extension. Thank you very much.

**Comment by Spiralpine** [comment]
This issue can be closed as everything is working now. The issue appeared right after updating the Chrome OS to 97.0.4692.91 and rebooting the Chromebook. After a second reboot the issue I've reported disappeared all together and CAD is working as expected.

Excellent extension. Thank you very much.
