### ISSUE TITLE
[SUPPORT]  What settings should I make to force extension delete old cookies 

### ISSUE THREAD

**Issue by webcaptcha** [mrdokenny/Cookie-AutoDelete#1303]
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Please describe what you need support with

I've have Chromium installed for like 2 years.
Today I installed Cookie-AutoDelete extension and do settings:
https://i.imgur.com/byzBByr.png

Other settings I leave as a default. I have only three domains which I whitelisted in the settings.
But when I go to the Chromium cookies settings I see tons of cookies, basically that were there during two years.

I tried manually click yellow button "Clean, include opened tabs" but that doesn't help.

How to configure extension to delete cookies except which were whitelisted?

**Comment by kennethtran93** [comment]
What is your whitelist looking like?

**Comment by webcaptcha** [comment]
Thanks for helping me here

https://pastebin.com/3gAM2DfH

**Comment by kennethtran93** [comment]
Ah probably should have asked you this first - as you're using Chrome/Chromium browser, is the extension site access setting set to 'on all sites' (see first screenshot)?
![image](https://user-images.githubusercontent.com/6724477/151293849-dd8e772a-9e71-4fa7-b93d-c2678ea7fb67.png)

(You can access this either through the manage extensions and clicking on details for the extension or by right-clicking the extension icon (screenshot below)
![image](https://user-images.githubusercontent.com/6724477/151293973-da32ee46-136f-4189-9410-f91495d88dd0.png)

ref: https://support.google.com/chrome_webstore/answer/2664769?p=enable_extensions&visit_id=637788556356650750-3422889243&rd=1#extensionpermissions

As far as the list you provided me concerns it *should* have removed the cookies that aren't listed, provided the relevant permissions for the extension has been provided.

Note that if the site in question doesn't use cookies, we normally setup a cookie ourselves as this is the only way we can clear up any remaining non-cookie data, but if the all sites permissions aren't granted then we can't do anything about it.

**Comment by kennethtran93** [comment]
@webcaptcha is this still an issue?

**Comment by kennethtran93** [comment]
Closed as stale
