### ISSUE TITLE
[SUPPORT] Only subdomain cookies are showing up upon unchecking "Keep all cookies"

### ISSUE THREAD

**Issue by dovark** [mrdokenny/Cookie-AutoDelete#1326]
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Please describe what you need support with

Hello,
I'm on firefox 97, and I'm trying to customize what cookies I want to use by whitelisting a site, then unchecking "Keep all cookies". After doing this, it only shows cookies from the subdomain site, however it still shows the correct number of cookies. It does this on both the options "example.com" and "*example.com".

**Comment by kennethtran93** [comment]
There is a difference when using `*.example.com` (all subdomains including example.com) and `*example.com` (all domains ending with example.com).  Ensure you have the dot between the asterisk and domain.

Also if you are using strict mode, we are currently trying to implement the cookie containerization portion, so the cookies you would see may not reflect the actual amount of cookies that are in your system.
