### ISSUE TITLE
[Bug]  The "Other Browsing Data Cleanup Options" section is empty

### ISSUE THREAD

**Issue by ghost** [mrdokenny/Cookie-AutoDelete#1329]
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Describe the bug

Lack of checkboxes in "Other Browsing Data Cleanup Options".

### To Reproduce

Open CAD settings.

### Expected Behavior

Checkboxes.

### Screenshots

![image](https://user-images.githubusercontent.com/886325/157725038-72fa4268-936a-475e-adf1-c657b6950ea3.png)

### System Info - Operating System (OS)

Manjaro KDE

### System Info - Browser Info

Firefox 100

### System Info - CookieAutoDelete Version

3.6.0

**Comment by kennethtran93** [comment]
Thanks for the heads up.  As Firefox 100 is in the Nightly branch which is still a work in progress, I'll hold off on reviewing it until it gets to Beta/Web Developer Edition (early April) and see if it still persists then.

**Comment by ghost** [comment]
Also seeing this on nightly on Windows:

![image](https://user-images.githubusercontent.com/58130821/158529316-b79d7754-4b42-41d9-a019-d9fcdca8fb1b.png)
![image](https://user-images.githubusercontent.com/58130821/158529377-8ada8ed6-8ea4-4ae1-b49b-49f600907226.png)

Let me know if I can do anything to help.

**Comment by kennethtran93** [comment]
I'm curious if the 100 version has anything do do with it.

... Or the browser detect function, which only runs once on browser startup/extension enabled has detected Firefox to be Chrome or unknown...

**Comment by ghost** [comment]
Sounds plausible, I remember seeing something about testing the 3-digit version number in UA strings or something like that. I'll look into it....

```
browserDetect.prototype._cachedResult
"Firefox"
```

So that's working...

Also,
![image](https://user-images.githubusercontent.com/58130821/158730933-27480e3c-93f9-44ba-babb-7ff967cbf7de.png)

Seems OK there. I tried to dig a bit further but it's all obfuscated libs and I don't really have time to setup a build environment to make a debug build :( Is there a debug build available somewhere by any chance?

**Comment by ali-nz** [comment]
Unfortunately this issue still persists in the current beta.

**Comment by kennethtran93** [comment]
Looking into it.

Unfortunately with the delay in me coding stuff, we also need to add in a one-time user opt-in for personal information.

**Comment by kennethtran93** [comment]
Found the main culprit - my version number checks were done by string, not by number... 🤦, so "100" is less than "78" as the first character 1 is less than 7.

**Comment by kennethtran93** [comment]
While I did test it on my computer and it appears to be fixed with this patch, if any of you want to test it, head into the PR itself and follow the instructions to download the pre-compiled dev build for testing.

**Comment by ghost** [comment]
I've just updated Firefox to version 100 and having only the cookies removed is a true pain.
Considering the patch seems to fix CAD's version number, itself the culprit of the CAD 3.6.0 / Firefox 100 issue, may I ask when the developer intends to deliver the patched/updated version of CAD? Thanks.

**Comment by kennethtran93** [comment]
I was planning on trying to get the privacy-first user-consent working first, but seeing as 100 is released I'll try to get a version out shortly.
