### ISSUE TITLE
[FEATURE REQUEST]  change default choice for *list

### ISSUE THREAD

**Issue by Albirew** [mrdokenny/Cookie-AutoDelete#1341]
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Is your feature request related to a problem? Please describe.

i always have to untick some parameters when adding an item to whitelist (i always exclude cache, service workers and plugin data)

### Describe the solution that you'd like

simply adding an option in settings so we can set default behavior (what is ticked by default or not) when adding a new item:
- cache
- indexedDB
- local storage
- plugin data
- service workers
- cookies

### Describe alternatives you've considered

maybe the possibility to change all saved items in one go?
like "select all" then unticking one would also untick it on all others or something...

**Comment by kennethtran93** [comment]
A default behavior for creating new expression items is already a feature.

Documentation here: https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/Documentation#default-expression-options.  

While previously one could set defaults on the Settings page itself, that has been moved.
![image](https://user-images.githubusercontent.com/6724477/158928888-6ba1e47d-6175-4a1e-9c3d-11d84f3407c9.png)


From the CAD Settings, go to 'List of Expressions', then click on 'Create Default Expression options'.
![image](https://user-images.githubusercontent.com/6724477/158928249-8dcc2b86-b8b8-4687-ba20-432ba45e7367.png)

You should see new expression(s) as shown - this is where you can set your defaults.
![image](https://user-images.githubusercontent.com/6724477/158928315-f99c6ab3-61af-47ee-a0b4-2942fc2cb707.png)
(You'll find the the defaults for the greylist below all the whitelist ones)
![image](https://user-images.githubusercontent.com/6724477/158928384-baff7200-2753-4bda-86eb-d55c95917df6.png)

Simply toggle the ones you want.  If you're toggling 'Keep All Cookies', no cookie entries will be shown - those will populate for you once you create the new expression items.
