### ISSUE TITLE
[Bug]  Multiple expressions seperated by commas do not work as documented

### ISSUE THREAD

**Issue by jmbreuer** [mrdokenny/Cookie-AutoDelete#1350]
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Describe the bug

Entering a comma-separated list of matches as an expression gives an "Commas are only allowed in Regular Expressions" error message.

### To Reproduce

1. Go to https://orteil.dashnet.org/cookieclicker/
2. (using Cookie Quick Manager or similar) check the cookies set:
    1. a `cookieconsent_dismissed:yes` cookie on `.dashnet.org`
    2. the game save slot cookie on `orteil.dashnet.org`
3. I'd like to keep those cookies, so I whitelist both domains via CADs button
4. I have a look into CADs settings, specifically the expressions
5. For my inner Monk, and since I'm playing around with it, I have a look at the expression syntax and decide to put those two expressions together, like so: `dashnet.org,orteil.dashnet.org`

### Expected Behavior

I'd expect both cookies mentioned under 2.i and 2.ii above to be whitelisted.

### Screenshots

![Selection_034](https://user-images.githubusercontent.com/1792037/160003916-e91b9e71-d428-4d86-98cd-2459bf93f21b.png)

### System Info - Operating System (OS)

Linux

### System Info - Browser Info

LibreWolf 97.0.2-1

### System Info - CookieAutoDelete Version

3.6.0

### Additional Context

I played around with making one or the other part of the expression a regular expression, e.g. `/dashnet.org/,orteil.dashnet.org` or the other way around etc.

This leads to error messages like "Start slash detected, but missing end slash for Regular Expression.", or similar referring to the end slash, depending on where I put the RE.

**Comment by kennethtran93** [comment]
Hi @jmbreuer,

Apologies there - I should have clarified that it only works when adding new expressions through the textbox provided at the top.
![image](https://user-images.githubusercontent.com/6724477/160006065-bc783ea7-5b4e-41b2-82cd-003cf19a7c25.png)
which would then create the separate entries once the whitelist or greylist button is clicked upon.

Each entry can only take **one domain or one regular expression**, so you would either need to add a second entry for the second domain/subdomain, or make one regular expression that matches both those domains.

**Comment by jmbreuer** [comment]
Aah that answers that. Thank you!
