### ISSUE TITLE
[Bug] "Other Browsing Data Cleanup Options" has no settings

### ISSUE THREAD

**Issue by melusc** [mrdokenny/Cookie-AutoDelete#1365]
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Describe the bug

"Other Browsing Data Cleanup Options" has no settings to change (see screenshot).

### To Reproduce

1. Use Firefox *100*
2. Open settings -> CAD Settings
3. "Other Browsing Data Cleanup Options" is empty

### Expected Behavior

It should show a list of settings to change

### Screenshots

![image](https://user-images.githubusercontent.com/61409445/162730129-162fc396-f9a9-4040-9bab-bc5aa4b92dac.png)

### System Info - Operating System (OS)

Windows 11

### System Info - Browser Info

Firefox 100.0b3

### System Info - CookieAutoDelete Version

3.6.0

### Additional Context

I believe the issue lies in the fact that version numbers get compared as strings (Example <https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/blob/54c225e441dd439db1b84ed7a3f5102ed90c3a1d/src/ui/settings/components/Settings.tsx#L389>) and `'100' >= '78'` is `false`.

**Comment by ghost** [comment]
https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/1329
