### ISSUE TITLE
[Bug]  Does not delete cookies from tradingview.com

### ISSUE THREAD

**Issue by Majdoddin** [mrdokenny/Cookie-AutoDelete#1369]
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Describe the bug

 *.tradingview.com is added to gray list, using an expression. All data is checked to be deleted by restarting Firefox.
It seems it does not work. 
That does not happen by restarting Firefox, and CAD says there are some cookies there.

### To Reproduce

Add *.tradingview.com to the gray list with an expression. Let all the options checked.
Automatic Cleaning remains disabled.
open and login to tradingview.com (free version)
open a chart.
close fireforex
reopen firefox

### Expected Behavior

You need to sign in again to tradingview, if the data is deleted.
If I remove the cookies manually, from Firefox settings, I have to sign in again. 

### System Info - Operating System (OS)

Windows 10

### System Info - Browser Info

Firefox 99.0.1

### System Info - CookieAutoDelete Version

3.6.0

### Additional Context

I have to delete cookies from tradingview.com once a while, otherwise I start loosing my work there and other funny things happen.

**Comment by kennethtran93** [comment]
Cleanup on browser restart is only triggered when automatic cleanup is enabled. 

Once that is enabled, if the domain in question is part of your opened/restored tabs on startup, ensure that the 'Clean Cookies and other Site Data from Open Tabs on Startup' is also enabled.

**Comment by pflanzenandi** [comment]
I have the same problem with https://www.tradingview.com even tho I enabled all settings you mentioned.

**Comment by kennethtran93** [comment]
> I have the same problem with https://www.tradingview.com even tho I enabled all settings you mentioned.

Do you have the tab open or any tabs having that domain on restart?  If so it won't be cleaned up unless `Clean Cookies and other Site Data from Open Tabs on Startup` is checked as well.
