### ISSUE TITLE
[Bug] CAD makes Firefox browser hang without Cache Cleanup enabled

### ISSUE THREAD

**Issue by redactedscribe** [mrdokenny/Cookie-AutoDelete#1405]
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Describe the bug

Like https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/1120, however on Windows, and _without_ Cache Cleanup enabled (disabling it was the previous "solution" to the problem), the problem still persists.

As detailed in [my comment](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/1120#issuecomment-1141425033) on the linked issue:

<details><summary>My CAD core settings (click):</summary>

```json
{
  "settings": [
    {
      "name": "activeMode",
      "value": true
    },
    {
      "name": "delayBeforeClean",
      "value": 15
    },
    {
      "name": "statLogging",
      "value": true
    },
    {
      "name": "showNumOfCookiesInIcon",
      "value": true
    },
    {
      "name": "showNotificationAfterCleanup",
      "value": false
    },
    {
      "name": "cleanCookiesFromOpenTabsOnStartup",
      "value": true
    },
    {
      "name": "contextualIdentities",
      "value": false
    },
    {
      "id": "DEPRECATED - use localStorageCleanup",
      "name": "localstorageCleanup",
      "value": true
    },
    {
      "name": "notificationOnScreen",
      "value": "5"
    },
    {
      "name": "domainChangeCleanup",
      "value": false
    },
    {
      "id": "DEPRECATED - use default expressions",
      "name": "greyCleanLocalstorage",
      "value": true
    },
    {
      "id": "DEPRECATED - use default expressions",
      "name": "whiteCleanLocalstorage",
      "value": true
    },
    {
      "name": "enableNewVersionPopup",
      "value": true
    },
    {
      "name": "debugMode",
      "value": false
    },
    {
      "name": "enableGreyListCleanup",
      "value": true
    },
    {
      "name": "keepDefaultIcon",
      "value": false
    },
    {
      "name": "sizePopup",
      "value": 16
    },
    {
      "name": "sizeSetting",
      "value": 16
    },
    {
      "name": "contextMenus",
      "value": false
    },
    {
      "name": "discardedCleanup",
      "value": true
    },
    {
      "name": "cacheCleanup",
      "value": false
    },
    {
      "name": "cleanExpiredCookies",
      "value": true
    },
    {
      "name": "indexedDBCleanup",
      "value": true
    },
    {
      "name": "localStorageCleanup",
      "value": true
    },
    {
      "name": "manualNotifications",
      "value": true
    },
    {
      "name": "pluginDataCleanup",
      "value": true
    },
    {
      "name": "serviceWorkersCleanup",
      "value": true
    },
    {
      "name": "contextualIdentitiesAutoRemove",
      "value": true
    }
  ]
}
```

</details>

As my comment states:

> As soon as I open Firefox, some of the tabs that try to load just hang with a blank background with a spinning circular icon until they eventually do. This also happens seemingly randomly during use of the browser and fairly often. When I disable CAD and restart Firefox, tabs always load instantly.
>
> This has been happening since maybe Firefox version 97-98?

### To Reproduce

Not clear how to cause the issue to occur. It was a few Firefox versions ago that the problem occurred. Whether it was introduced by Firefox or a version of CAD I don't know. I will try to diagnose this a little further by resetting CAD to its default settings and see if the issue persists. Kind of reluctant to do so because I'll potentially be losing my current logins and other info. I will wait for any response first.

### Expected Behavior

Extension to not cause hangs, regardless if the Cache Cleanup settings option is enabled or not.

### System Info - Operating System (OS)

Windows 11

### System Info - Browser Info

Firefox 101.0.1

### System Info - CookieAutoDelete Version

3.7.0

### Additional Context

I am aware that duplicate issues shouldn't be opened but my attempts to mention the dev's username didn't appear to get any response. Close if need be, but any help would be greatly appreciated as this is an ongoing problem in my daily use and I would rather not disable CAD altogether and find a replacement extension.

**Comment by kennethtran93** [comment]
There's a possibly that Firefox may have either introduced something or started to deprecate something that CAD may still be using.  As you may have noticed, CAD version 3.6.0 had been out for a year or so, while Firefox has incremented their versions for a much shorter time span than this extension, so things may have been changed that we need to take into account.  Unfortunately, I don't have much time to debug this on my own at this time.

How many tabs do you have open in all your Firefox windows combined?

Maybe enable debug mode and check the extension console statements (instructions shown once enabled) if possible?  These don't persist on browser restart unfortunately.

The next version that is coming up that will have the option to keep your existing cache/indexeddb/localstorage/service workers when you enable those cleanups globally.  Perhaps at that time you could try to debug as well.

**Comment by redactedscribe** [comment]
Thanks for the response.

> How many tabs do you have open in all your Firefox windows combined?

148 at the moment. No tabs (even pinned tabs) load until clicked due to Firefox settings I've chosen, if that may matter.

> Maybe enable debug mode and check the extension console statements (instructions shown once enabled) if possible? These don't persist on browser restart unfortunately.

I'll look into it and report anything that looks suspicious.

> The next version that is coming up that will have the option to keep your existing cache/indexeddb/localstorage/service workers when you enable those cleanups globally. Perhaps at that time you could try to debug as well.

I could wait then. Any estimate of when the next version may be released?

**Comment by kennethtran93** [comment]
> > How many tabs do you have open in all your Firefox windows combined?
> 
> 148 at the moment. No tabs (even pinned tabs) load until clicked due to Firefox settings I've chosen, if that may matter.

No - that's usually the better setting so that (for all but the active tab/domain shown on restart), the site data would be cleaned up before the site has a chance to see it.


> > The next version that is coming up that will have the option to keep your existing cache/indexeddb/localstorage/service workers when you enable those cleanups globally. Perhaps at that time you could try to debug as well.
> 
> I could wait then. Any estimate of when the next version may be released?

I've pushed the next version for review to the individual browser extension stores.  These _should_ be approved and released in the next few days.

**Comment by redactedscribe** [comment]
Insights so far based on just toggling the Cleanup settings (I did not reset my settings to default and _Clean Existing Data for Newly Enabled Browsing Data Types_ was left enabled):

- Disabling both **IndexDB** _and_ **LocalStorage** is necessary to stop the hangs.
- **Plugin Data** and **Service Workers** cleanups are still enabled and do not cause hangs.
- If either **IndexDB** or **LocalStorage** is enabled, the CAD debug log shows a lot amount of "CleanupService.filterSiteData: LocalStorage cleanup returned true for ...".
  <details><summary>LocalStorage example (click):</summary>

  ```json
  15:42:30.072 CAD_3.8.0 - debug - CleanupService.filterSiteData: debug data.
  {
    "notProtectedByOpenTab": true,
    "notInAnyLists": false,
    "siteData": "LocalStorage",
    "isCADCookieNoExpression": false,
    "cleanSiteDataInExpression": true,
    "isRestartCleanup": false,
    "canCleanSiteData": true,
    "nonBlankCookieHostName": true,
    "notOpenTabAndCanClean": true,
    "CleanReasonObject": {
      "cached": false,
      "cleanCookie": false,
      "cookie": {
        "name": "BACKENDID",
        "value": "***",
        "domain": "some_artist.bandcamp.com",
        "hostOnly": true,
        "path": "/",
        "secure": true,
        "httpOnly": false,
        "sameSite": "no_restriction",
        "session": true,
        "firstPartyDomain": "",
        "partitionKey": null,
        "storeId": "firefox-default",
        "hostname": "some_artist.bandcamp.com",
        "mainDomain": "bandcamp.com",
        "preparedCookieDomain": "https://some_artist.bandcamp.com/"
      },
      "expression": {
        "expression": "*.bandcamp.com",
        "listType": "WHITE",
        "storeId": "default",
        "cleanLocalStorage": true,
        "cookieNames": [],
        "id": "DjVG3sdVr7",
        "cleanSiteData": [
          "LocalStorage",
          "IndexedDB",
          "PluginData",
          "ServiceWorkers"
        ],
        "cleanAllCookies": true
      },
      "openTabStatus": "reasonTabsWereIgnored",
      "reason": "reasonKeep"
    }
  } common-background-popup-setting.bundle.js:2:44103
  15:42:30.072 CAD_3.8.0 - debug - CleanupService.filterSiteData: LocalStorage cleanup returned true for some_artist.bandcamp.com
  common-background-popup-setting.bundle.js:2:44103
  ```
  </details>

  - The majority of debug messages are for the domain bandcamp.com which I visit often, and which also has a whitelisted expression `*.bandcamp.com`. Each artist on Bandcamp has their own domain, so there is a debug entry for each `some_artist.bandcamp.com` subdomain, so maybe this is a lot to process?
- The same debug messages as in the previous bullet point but for **Service Workers** is also present (again, Service Workers don't cause a hang but I thought the following snippet was possibly a clue).
  <details><summary>Service Workers log snippet (click):</summary>

  ```json
  15:33:17.695
  CAD_3.8.0 - debug - CleanupService.removeSiteData: Cleanup of hostnames in Firefox for serviceWorkers:
    "some_artist_1.bandcamp.com",
    ".some_artist_1.bandcamp.com",
    "www.some_artist_1.bandcamp.com",
    ".www.some_artist_1.bandcamp.com",
    "some_artist_2.bandcamp.com",
    ".some_artist_2.bandcamp.com",
    "www.some_artist_2.bandcamp.com",
    ".www.some_artist_2.bandcamp.com",
    (... for ~600 lines + ~200 more for other domains)
  [
  ```
  </details>

Something else observed:

If, say, IndexDB Cleanup is enabled and Firefox is then immediately quit, the Firefox windows closes, but some of its processes remain running in the background, one in particular with 2-3 MB/s of IO happening until the browser results in a crash after ~20s. It looks like another side effect of the amount of domains being processed perhaps? Something is slower than it should be at least.

CAD 3.8.0

**Comment by redactedscribe** [comment]
Update no. 2:

Interestingly, I just reset both my _core_ and _expression_ settings to default and then enabled _all_ Browsing Data Cleanup Options (_except Cache_ since I do not use that): I relaunched the browser and it loaded initial tabs without any comparable hang.

I then re-imported only my Core settings, and relaunched again. There seemed to be somewhat of a hang but I think it's a one-off due to the processing that I'm guessing is necessary after IndexDB or LocalStorage is enabled? I say a one-off because next I re-imported my expressions and relaunched the browser a third time: the initial tabs I chose to load now load much faster. Still a minor hang between launch and tab load, but that may just be Firefox firing up. A much improved speed (potentially the expected speed) compared to before where a spinning circle sometimes made an appearance.

My assumption is that something has now been cleared that was previously numerous, but I'm also under the impression this is a temporary fix as the hang may return a little day by day as I revisit whitelisted sites, Bandcamp with its many subdomains in particular. Checking the debug logs, I don't see any mention of bandcamp domains or others, other than the ones I tested to load.

Hopefully it helps @kennethtran93 once you have time to look into it.

**Comment by kennethtran93** [comment]
It's hard to say if this is a Firefox issue or if we're specifying too many domains into one call...

I also find it interesting that you decided to create a whitelist but essentially clean everything anyway...you wouldn't need to create an expression entry for this.

**Comment by redactedscribe** [comment]
> It's hard to say if this is a Firefox issue or if we're specifying too many domains into one call...

If it were a Firefox issue I'd think more Firefox users would have the same issue with CAD. The same could be said for people with a lot of previously visited domains, so I don't know. I'll have to report back if the issue returns, I assume when my browsing data adds up.

> I also find it interesting that you decided to create a whitelist but essentially clean everything anyway...you wouldn't need to create an expression entry for this.

If I'm not mistaken, the grey- and whitelist "Keep" options override the global "Clean" options (the ones discussed). I clean everything except cache by default and list what I want to keep. I whitelist the domains I trust and sometimes keep their LocalStorage if it's necessary for them to function too. To me there's nothing unusual about that approach, unless I'm missing something?

**Comment by kennethtran93** [comment]
> > I also find it interesting that you decided to create a whitelist but essentially clean everything anyway...you wouldn't need to create an expression entry for this.
> 
> If I'm not mistaken, the grey- and whitelist "Keep" options override the global "Clean" options (the ones discussed). I clean everything except cache by default and list what I want to keep. I whitelist the domains I trust and sometimes keep their LocalStorage if it's necessary for them to function too. To me there's nothing unusual about that approach, unless I'm missing something?

When they're checked when on whitelist, yes they keep (override) those from being cleaned up, however from this expression entry found in the logs given:
```json
"expression": {
  "expression": "*.bandcamp.com",
  "listType": "WHITE",
  "storeId": "default",
  "cleanLocalStorage": true,
  "cookieNames": [],
  "id": "DjVG3sdVr7",
  "cleanSiteData": [
    "LocalStorage",
    "IndexedDB",
    "PluginData",
    "ServiceWorkers"
  ],
  "cleanAllCookies": true
},
```
You're not having CAD keep anything you've enabled CAD to clean, so you're essentially cleaning up all cookies, indexeddb, localstorage, plugin data, and service workers for domains matching that expression, which is what your global CAD settings are configured to anyways (seeing as you've disabled cache cleanup).  This this entry acts the same as if you haven't configured it for that domain/wildcard.  If a cookie is found for a domain/expression not configured, it gets removed alongside whichever global data cleanup you've enabled (in your case indexeddb, localstorage, plugin data, service workers).

**Comment by redactedscribe** [comment]
> You're not having CAD keep anything you've enabled CAD to clean, so you're essentially cleaning up all cookies, indexeddb, localstorage, plugin data, and service workers for domains matching that expression

I see what you're saying. However, this shouldn't be cleaning up the cookies as I have "Keep All Cookies" enabled (which is the only reason the expression exists), but yes, everything else for that particular domain should be being cleared.

**Comment by kennethtran93** [comment]
> > You're not having CAD keep anything you've enabled CAD to clean, so you're essentially cleaning up all cookies, indexeddb, localstorage, plugin data, and service workers for domains matching that expression
> 
> I see what you're saying. However, this shouldn't be cleaning up the cookies as I have "Keep All Cookies" enabled (which is the only reason the expression exists), but yes, everything else for that particular domain should be being cleared.



My bad.  Seems I messed up with the variable name of that option in the backend.

Currently, it stands that `cleanAllCookies` with `true` is actually Keep All Cookies checked, so I'll need to rename that as well in the next version.

**Comment by redactedscribe** [comment]
Just to let you know, unfortunately as predicted, after a week of daily browser use, the spinning circle has begun to return. I suppose I'll have to disable and then re-enable IndexDB and LocalStorage cleaning to clean them out to regain normal tab-loading speed before the hangs become even longer.

**Comment by kennethtran93** [comment]
> Just to let you know, unfortunately as predicted, after a week of daily browser use, the spinning circle has begun to return. I suppose I'll have to disable and then re-enable IndexDB and LocalStorage cleaning to clean them out to regain normal tab-loading speed before the hangs become even longer.

Some other people were able to create some 'snapshot profile' of processes running in a capture.  Maybe this may help drill down what is actually causing this.  See https://profiler.firefox.com/ for details/usage.

**Comment by redactedscribe** [comment]
From my basic understand of looking at the captured info, I've noticed that there is a large contiguous pink Jank bar from anywhere between 2-7 seconds with CAD enabled. Disabling a couple extensions, then restarting and capturing, and doing the same again, progressively lessened any reported Jank until only a few hundred milliseconds of Jank was the largest reported.

Alternatively, after enabling all my typical extensions, disabling CAD, and recapturing, this also achieved a similar (maybe slightly better) effect: the largest Jank bar shown was 200-400 ms.

In my last test, I first disabled _Clean Existing Data for Newly Enabled Browsing Data Types_ and then disabled both the LS and IndexDB CAD setting and restarted. This capture also showed effectively the same as having disabled CAD altogether: just a couple hundred milliseconds of Jank. Re-enabling both LS and IndexDB and restarting brought back the hangs.

It looks like whatever CAD is doing is with LS and/or IndexDB is causing other extensions to slow down, because when I disable CAD (or simply disable LS and IndexDB), reported Jank is minimal and tabs load without large hangs.

**Comment by redactedscribe** [comment]
This seems to not have been a problem in the past few versions of Firefox (current 108.0.1). If it returns, I'll re-open the issue.

**Comment by redactedscribe** [comment]
@kennethtran93 Whatever the cause of this issue, it returned in Firefox v118, and upgrading to v119 is no different. I guess it's not Firefox itself at fault, but how CAD may manage IndexDB and LocalStorage, but I don't really know. It's likely related to my increased visiting of *.bandcamp.com URLs again. I will have to clear the IndexDB and LocalStorage like before to hopefully resolve this again. Ideally this wouldn't happen in the first place of course. Just to re-confirm, I disabled CAD and the hangs went away, enabling it reintroduced them.

**Comment by redactedscribe** [comment]
Interestingly, disabling and re-enabling both the IndexDB and LocalStorage CAD options (with browser restarts between disabling/re-enabling) did not help (and yes I have "Clean Existing Data for Newly Enabled Browsing Data Types" enabled).

What _does_ appear to help however is disabling "Enable Greylist Cleanup on Browser Restart". This removes the long hangs on Firefox start ups and shutdowns. It remains to be seen if hangs still occur during usage... This suggests that the having the IndexDB and LocalStorage options enabled may not be the root cause. Cleaning too much data may be causing the hangs. It's unclear. If I notice anything else, I will report it here.

My `_Default:GREY` is set to "Keep Cache until restart" and "Keep All Cookies until restart".

Clicking the yellow Clean button in the CAD popup also triggers the hang. Perhaps my cleaning expressions are too complicated or incorrect regex?

> It remains to be seen if hangs still occur during usage...

They do, I guess because of "Enable Automatic Cleaning" being enabled.
