### ISSUE TITLE
[BUG] Today Firefox Nightly + your ext 3.6.0 and 3.8.0 = ERROR

### ISSUE THREAD

**Issue by led9** [mrdokenny/Cookie-AutoDelete#1409]
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Describe the bug

After today update Firefox Nightly error appears =
"Error! 
Type error for parameter options (Unexpected property "origins") for browsingData.remove.
"
The error appears periodically - when the browser is launched, when the pages are opened.
I restored the old version, 3.6.0, the error still occurs.

If you turn off your expansion = error stops appearing.

Apparently, the developers of Firefox changed something again.

### To Reproduce

1. update firefox nightly
2. firefox nightly start - error appears

### Expected Behavior

no error

### System Info - Operating System (OS)

win 10 64

### System Info - Browser Info

firefox nightly today update (everyday new)

### System Info - CookieAutoDelete Version

3.8.0 and 3.6.0

### Additional Context

Now it’s time to fix ext, and not before.

**Comment by kennethtran93** [comment]
Please state the actual version of firefox nightly.

**Comment by gilic** [comment]
I have the same issue.
nightly 103.0a1 (2022-06-15) (64-bit)

**Comment by jtracey** [comment]
This is tracked by Mozilla as well: https://bugzilla.mozilla.org/show_bug.cgi?id=1774425

**Comment by kennethtran93** [comment]
I don't think a Bugzilla report is needed for this one - I believe the  browser feature detection function we were using to detect if it was Firefox was deprecated recently and would be removed in the near future (thus v103)

As the user agent is not reliable to determine the browser. I will need to figure out a function that only Firefox and Firefox Android would have but not in Chrome.

~I'll take some time over the weekend to look for a solution.~

...or draft up a patch for it as early as tonight since the preliminary research has been done as noted below.

**Comment by kennethtran93** [comment]
Until Chrome and other browsers decides to implement `browser.contextualIdentities` (containers), it may be safe enough to use that as a browser detection just to test if that object is available.

Source: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/contextualIdentities#browser_compatibility

**Comment by kennethtran93** [comment]
Try the build in the PR (follow the bot instructions to request a build or build it yourself) to see if it works in Nightly again.  I haven't tested this myself (as I don't have/use Nightly at this time).  If this doesn't fixes it, I'll probably have a better idea once Firefox Beta/Developer Edition starts using 103.

**Comment by gilic** [comment]
works for me now.

**Comment by led9** [comment]
**kennethtran93**, Create a test extension, please, so that im can try your solution. "Build in the PR" is completely incomprehensible. Can I just get a download link? If this platform does not allow - well, give a link to the file hosting

Figured out, sort of like -
on page https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/pull/1410
There is link = blue words "Build 2507168728" with link https://coveralls.io/builds/50079838
There is a button on that page "GitHub Action Run" with link https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/actions/runs/2507168728 , If you press it, then download links will appear.

Very convenient, just beauty, thanks, github

**Comment by led9** [comment]
**kennethtran93**
With this "pr" the error stopped appearing. Thank you!

**Comment by Chris1320** [comment]
I am currently running `3.8.1 - unreleased` for several hours, and the errors are now gone.

**Comment by killyourradio** [comment]
> Try the build in the PR (follow the bot instructions to request a build or build it yourself) to see if it works in Nightly again. I haven't tested this myself (as I don't have/use Nightly at this time). If this doesn't fixes it, I'll probably have a better idea once Firefox Beta/Developer Edition starts using 103.

Tested aswell, errors seem to be gone with the PR.

**Comment by kennethtran93** [comment]
> **kennethtran93**, Create a test extension, please, so that im can try your solution. "Build in the PR" is completely incomprehensible. Can I just get a download link? If this platform does not allow - well, give a link to the file hosting
> 
> Figured out, sort of like - on page #1410 There is link = blue words "Build 2507168728" with link https://coveralls.io/builds/50079838 There is a button on that page "GitHub Action Run" with link https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/actions/runs/2507168728 , If you press it, then download links will appear.
> 
> Very convenient, just beauty, thanks, github

To get the download link for the build, comment in the relevant PR with `/get-build` to get the latest build download links for that PR (which would only be valid for a minute).  These builds, by default, expires 90 days after it was built (or sooner if something went wrong or we manually delete them).  If I were to provide semi-permanent direct links to the builds, storing them in the PR comment history will not be cleaned up, thus in the off chance the people click on those links past the available date, it would return an error.

But I will try to get some form of static link going, with a caveat note that the link will expire on or after the 90 day date, if that makes it any easier.

**Comment by kennethtran93** [comment]
I've been trying to see if I can get the download links from that actions page into that Pull Request (PR), but seems to require a whole separate workflow process to execute _after_ the current workflow (the one that generates the build) is completed, not during the existing workflow as I cannot fetch the artifact ids that are at the end of each download link during the current workflow.

Other people have already requested something similar to GitHub already about being able to get/reference the freshly uploaded artifiacts/build metadata from the current workflow (not downloading them in another step)

**Comment by manuc66** [comment]
Hi,

The issue is now also reproducible on Firefox Beta: 103.0b4 (64 bits)

**Comment by kennethtran93** [comment]
Thanks for the update.  Anything Firefox 103+ is affected, with the fix in the linked PR.  I'll bump the version soon.

**Comment by Scrotastic** [comment]
Firefox beta here. I've had the extension disabled for the last couple of weeks because it's basically broken. I couldn't make heads nor tails of your PR instruction. Looking forward to you updating. TIA

**Comment by kennethtran93** [comment]
> Firefox beta here. I've had the extension disabled for the last couple of weeks because it's basically broken. I couldn't make heads nor tails of your PR instruction. Looking forward to you updating. TIA

I didn't think I made the PR instructions too hard...go into that PR, comment with `/get-build`, wait a moment (for three reactions to your command), refresh if need be, but a new comment would appear with your direct download links (which is only valid for a minute) for you to click on to download them.

**Comment by kennethtran93** [comment]
I'll just do a version bump to 3.8.1 to resolve this.

**Comment by kennethtran93** [comment]
3.8.1 has been approved/validated and released on Firefox addons.

**Comment by Scrotastic** [comment]
Resolved. Thank you.
