### ISSUE TITLE
[Bug]  Cookies not cleaning (at all)

### ISSUE THREAD

**Issue by quarkl8** [mrdokenny/Cookie-AutoDelete#1412]
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Describe the bug

Deletion of cookies does not occur, either manual or automatic - i.e. the extension is completely non-functional

### To Reproduce

Steps to reproduce the bug on Brave
1: Turn on CAD's autodelete setting.
2: Go to any website that is not gray or whitelisted
3: Check cookies library ([brave://settings/siteData](brave://settings/siteData)) to see if any from this website are stored.
4: Leave the website and wait for a few minutes/however long CAD is set to autodelete.
5: Check cookies library - the cookies are still there
6: Click "Clean" in CAD panel - button turns green and then back to yellow
7: Check cookies library again - cookies still there

### Expected Behavior

Cookies from non-listed websites should have been deleted by the extension.

### System Info - Operating System (OS)

MacOS Monterey

### System Info - Browser Info

Brave Version 1.40.105

### System Info - CookieAutoDelete Version

3.8.0

**Comment by kennethtran93** [comment]
What are your CAD Settings?

Did you also enable cleaning up the other site data stuff? 

From Chrome's site data pages, it shows not only cookies but other site data as well. 

If you're looking to clean up cache storage or some other stuff not clean able through CAD yet, there is already a request for it.

Are you able to show a screenshot of the domains and/or cookies that remained before or after the cleanup?

**Comment by quarkl8** [comment]
It appears as though some sites are cleaning, but not others. I am attaching before-after pictures of the cookies with checkmarks and X's for the whitelisted and non-listed sites respectively. Settings are close to default, 60 seconds automatic cleaning. I didn't know I could delete the other site data, how can I enable that?
<img width="676" alt="before cleaning" src="https://user-images.githubusercontent.com/100106421/175465307-3f26c09d-bfae-45f6-ab1d-f2b03b2a8d1e.png">
<img width="676" alt="after cleaning" src="https://user-images.githubusercontent.com/100106421/175465317-f0678021-ef1b-4d22-af1a-dc5999e1062a.png">

**Comment by kennethtran93** [comment]
So the web extension is currently working as it is configured to.  To clean up local storage and other site data, you'll need to go to the CAD Settings and find the 'browsing data' section to enable cleanup of those items (if you don't want to clean up existing site data item that you're about to enable, ensure you uncheck the relevant box just above the warning).

Then do the fine-tuning through your whitelisted and greylisted entries.  If you don't want to keep a site data type forever or until restart, uncheck them.

For Database storage, we have not implemented the ability to clean that up yet, and it has been requested already.

The only site data aside from cookies that we can clean up at this time are: indexedDB, local storage, cache (not cache storage), service workers, and the deprecated plugin data.

For the local storage item, we must have at least a cookie for that domain already set.  If the 3rd party does not set a cookie but uses other browsing data types, we would not be able to detect that site at all.  It has been noted already and we'll need to look into solving that issue in the future.

**Comment by kennethtran93** [comment]
Closing as currently working as expected.  Duplicate issues have been created already to add cleanup options for other browsing data types.
