### ISSUE TITLE
[Bug]  Here We Godamn Go Again!!

### ISSUE THREAD

**Issue by geedogz** [mrdokenny/Cookie-AutoDelete#1435]
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Describe the bug

Hi Kenneth,

Hope youre well. Its a merry-go-round with CAD again. I seriously would like to know why CAD retains 30MB of cookies when it should seriously keep ONLY less than 1MB. This has happened before, my complaints are no stranger to this thread at all. This problem went away before. But now its rearing its ugly head yet again.. why? I dont know. I close firefox, reopen it in hopes that cookies are refreshed and are deleted except for the very few I keep. But noooo. Whats going on here Ken?

### To Reproduce

nothing

### Expected Behavior

keeps many unnecessary cookies

### System Info - Operating System (OS)

10

### System Info - Browser Info

firefox

### System Info - CookieAutoDelete Version

3.8.1

**Comment by kennethtran93** [comment]
I'm curious to know how you reached the 30MB of cookies.

What is your current firefox privacy setting (see below for sample).  Unless you are using a specific setting, we have yet to fully integrate the firefox total cookie protection thing (#807), so anything else outside of the 'cross-site cookies (not isolate) ' setting may keep cookies that we cannot clean yet.
![image](https://user-images.githubusercontent.com/6724477/183324520-a61ce1a1-8a54-4e17-97a9-db3b7b2a4d99.png)

**Comment by geedogz** [comment]
> What is your current firefox privacy setting 

Its set to standard. 

Also, other sites I have never allowed to keep cookies without my permission are listed here:

**aol.com
worldstarhiphop.com
web.whatsapp.com
fnac.com
thewindowsclub.com**

Looking forward to any suggestions. Thanks, Ken.

.

**Comment by geedogz** [comment]
Hi Kenneth... wanted to know if you read my previous message. 

Also, is it better to use firefox's option of deleting all cookies when the browser closes in exception to specific cookies? The option in settings is: **"Delete cookies and site data when Firefox is closed"** and the option to allow specific cookies is: **"Manage Exceptions"**

Let me know your suggestions. Thanks.

**Comment by kennethtran93** [comment]
With the current standard in Firefox, it defaults to use isolated cookies which we haven't implemented yet, so some of those cookies we won't be able to remove yet.

You are free to use the built-in Firefox cookie management if you want to clean cookies on restart/close. Just note that the settings done through the firefox config is not interchangeable in the web extension.

**Comment by geedogz** [comment]
Hi kenneth,

Appreciate the reply. When do you think you will be able to update CAD to remove these isolated cookies?

**Comment by kennethtran93** [comment]
Can't guarantee anything, but I do have some vacation time off my current work coming up soon.

**Comment by geedogz** [comment]
Sounds good. greatly appreciate your dedication and time in making this my fav addon. It's no rush whatsoever. Thanks again Kenneth!

**Comment by kennethtran93** [comment]
Closing as duplicate of #807
