### ISSUE TITLE
[Bug]  Keep getting logged out of Feedly

### ISSUE THREAD

**Issue by ghost** [mrdokenny/Cookie-AutoDelete#1438]
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Describe the bug

I have `*.feedly.com` and `*feedly.com` whitelisted to preserve everything. However, several times a day, something is being inadvertently deleted and causing me to get logged out of Feedly. If I disable CAD, this never happens -- it only happens with CAD enabled.

### To Reproduce

1. whitelist `*.feedly.com` and `feedly.com`
2. login to feedly.com with Google auth
3. use the app for a day or two
4. notice you get logged out frequently

### Expected Behavior

Stays logged in forever.

### System Info - Operating System (OS)

macOS 12.5

### System Info - Browser Info

Chrome 104

### System Info - CookieAutoDelete Version

3.8.1

**Comment by kennethtran93** [comment]
>     2. login to feedly.com with Google auth

If you're accessing via third-party SSO (in this case Google Auth), you may also need to whitelist some of google's cookies as well as some of those google cookies may also be part of the auth chain such that when removed it will not keep your login active.  If Google Auth is just the Google Authenticator app (2FA codes), then it's a different story.

Try disabling the expired cookies option, if enabled, and see if it happens again. If it doesn't, then it may be something similar where expired cookies are clearing site data for that domain (bug fix in progress).

**Comment by ts1a** [comment]
Feedly doesn't use cookies to keep you logged in, it uses localStorage. I had this problem too. You can see this if you delete all the cookies and refresh the page.

**Comment by ghost** [comment]
<img width="628" alt="Screen Shot 2022-08-11 at 9 42 21 AM" src="https://user-images.githubusercontent.com/69643994/184161108-9f89ada5-e923-4542-8212-7b92071946c7.png">

This doesn't quite explain why I am still getting logged out more than once a day.

**Comment by ghost** [comment]
> > ```
> > 2. login to feedly.com with Google auth
> > ```
> 
> If you're accessing via third-party SSO (in this case Google Auth), you may also need to whitelist some of google's cookies as well as some of those google cookies may also be part of the auth chain such that when removed it will not keep your login active. If Google Auth is just the Google Authenticator app (2FA codes), then it's a different story.
> 
> Try disabling the expired cookies option, if enabled, and see if it happens again. If it doesn't, then it may be something similar where expired cookies are clearing site data for that domain (bug fix in progress).

I had `*.google.com` whitelisted and just now added `google.com` ~ not sure why that 2nd one was missing. I've also disabled the expired cookies options as you suggested.

Will report back here in a day or two with my results.

**Comment by kennethtran93** [comment]
As a sidenote, `*.google.com` will also match `google.com`, so there's no need for the 2nd one at this time.  Same with your `*.feedly.com` and `feedly.com` one.

Are you also using Google's clean cookie and site data on close (chrome://settings/cookies) or do you also use Chrome's cookie management stuff (i.e. add site to 'always clear cookies when windows are closed' and/or 'Site that can never use cookies')?  Configuration from this side is not interchangeable with CAD.  I also presume you're not using incognito/private browsing mode as default on chrome?

Feel free to enable the 'cleanup log and counter' to see which domains CAD is cleaning up (as well as the cookies related to those domains if any).

**Comment by ghost** [comment]
I've haven't been logged out in 2 weeks, so I would consider this issue resolved.

**Comment by paulmatheson** [comment]
But this also happens on iPad for me. Assuming it is more closely related to Google auth
