### ISSUE TITLE
[Bug]  Some cookies are not removed on Firefox version >102.0.1

### ISSUE THREAD

**Issue by thegeek1977** [mrdokenny/Cookie-AutoDelete#1439]
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Describe the bug

CAD does not work correctly on the current version of Firefox (103.0.2). Some (third party) cookies remain after it should be cleared. This is tested on a fully updated Manjaro Linux. It doesn't matter if the cookies are in container tabs or not.  This are not true for any websites, on the majority of sites the cookies are cleared as expected.

### To Reproduce

The Only Whitelist I have for youtube.com are for the PREF-cookie, this is to keep the settings across session for autoplay and
other things. I therefore expect this cookie to prevail of course.

On newest firefox: 

1 check the cookies:  Should be no cookies. If any cookies prevail, clear them out manually.
2 go to www.youtube.com
3 Check cookies again. You should now have several cookies from youtube.com, www.youtube.com and accounts.google.com
4 close tab and trigger expected deletion
5 Check cookies again: the cookies from youtube.com and www.youtube.com are gone but the cookies from accounts.google.com prevail

Now downgrade Firefox to 102.0.1, downgrade the profile with --allow-downgrade command argument or simply just make a cleanse of everything. The choice are yours but I am personally going with the downgrade approach. Then do the test again

1 check the cookies:  Should be no cookies. If any cookies prevail, clear them out manually.
2 go to www.youtube.com
3 Check cookies again. You should now have several cookies from youtube.com, www.youtube.com and accounts.google.com
4 close tab and trigger expected deletion
5 Check cookies again: Every cookies (execpt whitelisted of course) completely gone.

As soon as you upgrade Firefox to latest stable version the problem appears again

### Expected Behavior

Every cookie not whitelisted should be cleared out

### System Info - Operating System (OS)

Manjaro Linux X64 - fully updatedf on stable branch.

### System Info - Browser Info

Firefox > 102.0.1

### System Info - CookieAutoDelete Version

3.8.1

**Comment by kennethtran93** [comment]
Firefox 103's standard privacy now has Total Cookie Protection active by default.  Duplicate of #807 and others.  

If you want to go back to the previous way, you'll need to use the custom setting and change the cookie value to 'cross-site tracking cookies' (not the isolate one).

A overhaul of the current layout and logic is required to handle the isolation stuff.
