### ISSUE TITLE
[Bug]  When Will Update to Fix Isolated Cookies Be Fixed?

### ISSUE THREAD

**Issue by geedogz** [mrdokenny/Cookie-AutoDelete#1441]
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Describe the bug

Hi kenneth.. when will the new update come out to block isolated and cross-site cookies? 

### To Reproduce

Isolated cookies are not blocked

### Expected Behavior

block isolated cookies

### System Info - Operating System (OS)

10

### System Info - Browser Info

Firefox 103.0.2 

### System Info - CookieAutoDelete Version

3.6.0

**Comment by kennethtran93** [comment]
Duplicate of #807.  Asking it in a new issue will not speed things up.
