### ISSUE TITLE
[FEATURE REQUEST]  compatibility with old cookie managers

### ISSUE THREAD

**Issue by ingber** [mrdokenny/Cookie-AutoDelete#1449]
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Is your feature request related to a problem? Please describe.

Old cookie managers had a simple whitelist, e.g., one per line, like
*.google.com
OR
*.google.com,

### Describe the solution that you'd like

I'd like a json wrapper to include the above feature, so users can simply add one whitelist item at a time

### Describe alternatives you've considered

I've prepared a list in the above format.  I won't install auto-delete until this feature is added.

**Comment by kennethtran93** [comment]
You can already add one whitelist item at a time by using the textbox field in the 'List of Expressions' section of the CAD settings.  That text box accepts either one domain or comma-separated domains (which would then get auto-split into its own expression).  Once the textbox is populated, press the '+ Whitelist' to add new whitelist expressions (or simply press enter on the keyboard).

You can preset the default configuration for new expressions using the 'create default expressions option' button before you add new domains, or just add them and the default is keep everything (whitelist) or keep everything until restart (greylist).

![image](https://user-images.githubusercontent.com/6724477/206350667-98f1a6b8-934a-463a-930c-f7d0a0947f18.png)
