### ISSUE TITLE
[FEATURE REQUEST] Enable greylist autoclean on tab close

### ISSUE THREAD

**Issue by aeon3** [mrdokenny/Cookie-AutoDelete#1465]
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Is your feature request related to a problem? Please describe.

I have to restart the browser completely to activate the greylist cleanup.

### Describe the solution that you'd like

A way to cleanup greylist websites upon closing their tabs.

**Comment by kennethtran93** [comment]
Greylist is only for browser restart. 

If you need a site cleaned on tab close, simply do not include those sites in any lists, ensure you are not whitelisting or greylisting using a generic blanket wildcard '*' expression, and that the domain in question, when it's tab is closed, is not open in any other tabs or windows.
