### ISSUE TITLE
[FEATURE REQUEST]  Simple way to delete cookies on browser start for non-whitelisted domains

### ISSUE THREAD

**Issue by NightProgramming** [mrdokenny/Cookie-AutoDelete#1483]
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Is your feature request related to a problem? Please describe.

I would like a simple option that enables deletion of cookies on browser start for non-whitelisted domains.

There is `Enable Automatic Cleaning` but this also cleans after a tab is closed or domain is changed (meaning it cleans too often). There is also `Enable RestartList Cleanup on Browser Restart` but when checked, cookies for domains I haven't added any settings for (meaning no whitelist and no greylist) won't be deleted on a new browser start. There is also `Clean Cookies from Open Tabs on StartUp` but I think this only cleans cookies from domains that still have an open corresponding tab, so this doesn't work if the tabs are already closed. There is also `Enable Cleanup for Discarded` but this doesn't work if the tab is not in the tab strip any longer on browser start.

### Describe the solution that you'd like

A single simple option that accomplishes the desired behavior or alternatively there could be a way to specify the triggers for `Enable Automatic Cleaning` so that this feature is only executed for instance on browser start but not on `tab close` or ` domain change`.

**Comment by kennethtran93** [comment]
This is covered in the FAQ in the Wiki in this repository:  https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/FAQ:-Common-Questions-and-Issues#how-do-i-set-all-cookies-to-be-deleted-on-browser-restart-rather-than-on-tab-close

To clean all remaining sites on restart, simply add `*` (asterisk/star) as an entry to the greylist/restart list, through our settings page -> List of Expressions

Domain change trigger is currently a global setting, which can be disabled in the CAD settings.

**Comment by NightProgramming** [comment]
@kennethtran93 Thank you. I think this feature is a bit hidden. Maybe for the future it could be considered to make this feature more transparent (e.g. a dedicated option in the CAD settings)?

**Comment by kennethtran93** [comment]
Maybe.  However, there may be times where they only want specific container(s), not all, to have their things cleaned up on restart.  This wouldn't work then.  On Chrome, as I don't think they have containers yet (they have profiles, though would need to install the extension on each profile), this may be okay.

**Comment by NightProgramming** [comment]
@kennethtran93 Maybe the dedicated can be disabled / greyed out if there are custom grey list options that are different from a catch-all (*), and the option tooltip could tell that this option is currently disabled because of custom grey list entries.
