### ISSUE TITLE
Privacy Policy

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [mrdokenny/Cookie-AutoDelete#151]
Hey @mrdokenny :)

One thing I am in the process of doing with the ghacks user.js [wiki page for extensions](https://github.com/ghacksuserjs/ghacks-user.js/wiki/Appendix-B:-Extensions) is to add **Privacy Policy** links (like below). If an extension has one that respects privacy, awesome, if not, no such "badge" (and if it has one one that stinks, it will not be recommended). I can't seem to find one for C-AD. If you have one can you point it out to me that would be awesome, and if not, maybe create one? If its not important, then just close this ticket :) TIA

* [uBlock Origin](https://addons.mozilla.org/firefox/addon/ublock-origin/) <sup>✔ [Privacy](https://github.com/gorhill/uBlock/wiki/Privacy-policy)</sup> | [GitHub](https://github.com/gorhill/uBlock)

Edit: or you can just add it to AMO (not sure how you apply that per release)

* [Decentraleyes](https://addons.mozilla.org/firefox/addon/decentraleyes/) <sup>✔ [Privacy](https://addons.mozilla.org/en-US/firefox/addon/decentraleyes/privacy/)</sup> | [GitHub](https://github.com/Synzvato/decentraleyes)  << AMO example

**Comment by ke-d** [comment]
https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/Privacy-Policy

Is this satisfactory?

**Comment by Thorin-Oakenpants** [comment]
Looks good to me :+1: ... welcome to the ✔ club :)
