### ISSUE TITLE
[SUPPORT]  "Show Notification After Automatic Cleanup" This no longer appears.

### ISSUE THREAD

**Issue by beehiveharvest** [mrdokenny/Cookie-AutoDelete#1513]
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Please describe what you need support with

Recently (probably around Firefox 110.0.1)
"Show Notification After Automatic Cleanup".
This is no longer displayed.

I have not changed any settings.
I can't find any reports of this, so is this happening only in my environment?

BTW, I am currently using Firefox Setup 111.0.1.

**Comment by kennethtran93** [comment]
While I am not sure about version 110.0.1, in 111.0, Firefox has switched to using native OS notifications. Check your OS configuration to ensure Firefox notifications are allowed.

**Comment by beehiveharvest** [comment]
Thank you for your response.
I am on Windows 10 and had Firefox notifications turned on. I see that they used to appear at the bottom of the Firefox window, but now they appear in the Windows 10 notification area.
The notification time was 2 seconds, so if I re-set this number of seconds longer, I will be able to see it in the Windows notification.

**Comment by kennethtran93** [comment]
Closing as self-resolved.  In the future there may be an option to not auto close notifications.  In the meantime, set it to a larger value.
