### ISSUE TITLE
[SUPPORT]  Documentation is incomplete

### ISSUE THREAD

**Issue by mrx23dot** [mrdokenny/Cookie-AutoDelete#1519]
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Please describe what you need support with

Documentations 
- https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/Documentation
- https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/FAQ:-Common-Questions-and-Issues
are incomplete.

I was looking for 
- what's the difference between grey and whitelist exception.
- what's the difference between  *.domain and domain in whitelist (as I know cookie is valid for entire domain)

Please update doc and not just answer here.
Thanks!

**Comment by kennethtran93** [comment]
> I was looking for
> 
>     what's the difference between grey and whitelist exception.

The answer to this question already exists and can be read here: https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/FAQ:-Common-Questions-and-Issues#what-do-all-the-cleanup-options-mean as well as https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/Documentation#whitelist (readded header link) and https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/Documentation#greylist (readded header link)

The documentation had been slightly reworded in some instances to prepare for upcoming language change, but was held back for various reasons.  Basically RestartList = GreyList and KeepList = WhiteList. I've reupdated the wiki to re-include those terminology. Eventually, more lists/groups would be made available.

> 
>     what's the difference between  *.domain and domain in whitelist (as I know cookie is valid for entire domain)

The answer for this question already exists and can be read here: https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/Documentation#enter-expression
> 
> 
> Please update doc and not just answer here. Thanks!

Let us know if there's still something not clear.

**Comment by mrx23dot** [comment]
Thank you!
