### ISSUE TITLE
[Bug] Windows Ding on popup

### ISSUE THREAD

**Issue by abitawoods1** [mrdokenny/Cookie-AutoDelete#1548]
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Describe the bug

I made a mistake, inadvertently, by engaging updates on Windows 11 (cumulative 22h2 KB5026372), .and. on an extension (either CAD to 3.8.2 or containers ....), using firefox (also recently updated to 113)

I am often in a browser, opening and closing windows, for work, and so the notification pops up regularly for deleted cookies and etc. But, until the updates I just did, they slid in quietly, and stacked (usually, 2 per tab/domain). Silence was a welcome treat, for the CAD notices, but I still want to get dinged on the irregular notifications.

But, now .... no more silence.
Am I missing something? I remember last week not noticing the CAD notices (other than the visual out of the corner of my eye). Is there a way to stop the ding, for CAD, but not for all notifications ?

Another hazy memory ... i seem to remember that the CAD notice popped up on the monitor where I had FF open, or even within the browser window.

Has all this changed? From FF ? CAD ? Win11 ?

### To Reproduce

.

### Expected Behavior

Silent notifications

### System Info - Operating System (OS)

OS: x86-64 Windows (22621.1702)

### System Info - Browser Info

Firefox 113 (20230504192738)

### System Info - CookieAutoDelete Version

3.8.2

### Additional Context

Acknowledgements

    I acknowledge that I have read the above items

Describe the bug

I made a mistake, inadvertently, by engaging updates on Windows 11 (cumulative 22h2 KB5026372), .and. on an extension (either CAD to 3.8.2 or containers ....), using firefox (also recently updated to 113)

I am often in a browser, opening and closing windows, for work, and so the notification pops up regularly for deleted cookies and etc. But, until the updates I just did, they slid in quietly, and stacked (usually, 2 per tab/domain). Silence was a welcome treat, for the CAD notices, but I still want to get dinged on the irregular notifications.

But, now .... no more silence.
Am I missing something? I remember last week not noticing the CAD notices (other than the visual out of the corner of my eye). Is there a way to stop the ding, for CAD, but not for all notifications ?

Another hazy memory ... i seem to remember that the CAD notice popped up on the monitor where I had FF open, or even within the browser window.

Has all this changed? From FF ? CAD ? Win11 ?
To Reproduce

.
Expected Behavior

.
Screenshots

No response
System Info - Operating System (OS)

    OS: x86-64 Windows (22621.1702)

System Info - Browser Info

Firefox 113 (20230504192738)
System Info - CookieAutoDelete Version

3.8.2
Additional Context

    activeMode: true
    delayBeforeClean: 2
    discardedCleanup: true
    domainChangeCleanup: false
    enableGreyListCleanup: true
    cleanCookiesFromOpenTabsOnStartup: false
    cleanExpiredCookies: true
    siteDataEmptyOnEnable: true
    cacheCleanup: true
    indexedDBCleanup: true
    localStorageCleanup: true
    pluginDataCleanup: false
    serviceWorkersCleanup: false
    contextualIdentities: true
    contextualIdentitiesAutoRemove: true
    statLogging: true
    showNumOfCookiesInIcon: true
    keepDefaultIcon: false
    showNotificationAfterCleanup: true
    manualNotifications: true
    notificationOnScreen: 3
    enableNewVersionPopup: true
    sizePopup: 14
    sizeSetting: 14
    contextMenus: true
    debugMode: false

**Comment by kennethtran93** [comment]
Firefox updated its notifications to use native system notifications as of Firefox 111.  We have no control how notifications are generated after we send it off through the webextension API.

As such, you now have to make a choice
- keep using the native system notifications (which also shows in the action center for the predefined time)
  - You'll need to go to your system settings and mute all notifications from Firefox then.
- Switch back to the old Firefox notifications
  - requires tweaking `about:config` yourself: search for `alerts.useSystemBackend` and change to `false`
