### ISSUE TITLE
[FEATURE REQUEST]Can whitelist be excluded during manual clearance???

### ISSUE THREAD

**Issue by StrollStars** [mrdokenny/Cookie-AutoDelete#1549]
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Is your feature request related to a problem? Please describe.

Automated cleaning will always leave some content outside the whitelist.

### Describe the solution that you'd like

By clicking the manual clearance button, domains within the whitelist can be excluded.

### Describe alternatives you've considered

This can only be done through the browser settings.

**Comment by kennethtran93** [comment]
I'm currently not clear/understanding on this request.  Can you elaborate some more?

**Comment by StrollStars** [comment]
@kennethtran93 Currently, when I click the "clear" button in the extension, all content from all domains is cleared. I would like to be able to preserve the content from domains on my whitelist.

**Comment by kennethtran93** [comment]
> @kennethtran93 Currently, when I click the "clear" button in the extension, all content from all domains is cleared. I would like to be able to preserve the content from domains on my whitelist.

Which clean button are you using?  Which browser are you using?  The default clean button (not in dropdown) and the first clean button inside dropdown does respect the whitelist and greylist.

**Comment by StrollStars** [comment]
@kennethtran93 Sorry, it was my mistake. I might have used the browser's built-in cleaning function.
