### ISSUE TITLE
Auto-delete not working at all

### ISSUE THREAD

**Issue by FunkyBrewster** [mrdokenny/Cookie-AutoDelete#157]
### Describe the Bug/Feature
Title says it all. The badge appears red for all non-whilelisted sites, but even though I set the timer to 0, cookies are still there even after closing and reopening tabs or even FF itself. Websites "remembering" things they shouldn't tipped me off that something wasn't right, and in Options > Privacy > Remove Individual Cookies, I can see a long list of cookies that shouldn't be there including doubleclick.net and other which I haven't even visited directly.
With Active Mode checked, a notification about deleted cookies appears, but nothing actually seems to be deleted.  Even click Cookie Cleanup doesn't remove all cookies.
I must be doing something wrong if no one else is having this issue, but I'm totally at a loss. Self-Destructing Cookies always worked, and I don't have any other extensions installed except AdBlock. Is this a configuration problem?

### Screenshot in which the bug can be seen

(![cookies](https://user-images.githubusercontent.com/32188453/30731181-c7e6bd64-9fa6-11e7-837e-93f0e6258f58.jpg)
### Steps for anyone to reproduce the bug
Using the default options for Cookie Auto-Delete, visit a few websites, not white-listed, whose cookies remember your behavior (logins, articles accessed, etc.). Close the tabs and close FF. Open it and re-visit those sites. Also look at the cookie list in Options > Privacy.

### Your settings 
Default settings. Tried setting the timer to 0. Tried using/not using Active Mode.

- OS/version: Windows 10 Pro
- Browser/version: Firefox 55.0.3
- Cookie AutoDelete version: 1.4.0

**Comment by ke-d** [comment]
This sounds like either [first-party isolate](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/75) is on or [maybe an issue when the timer is set to 0](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/137).

Could also try clearing all cookies manually and seeing if any new cookies get deleted.

**Comment by SW1FT** [comment]
This just happened to me on 2.0.0b1, all my cookies were wiped after I restarted the browser after updating to this version of CAD. The add-on basically does not work at all at the moment.

I don't have 1st party isolate, but I do have the timer set to 0.

**Comment by ke-d** [comment]
@SW1FT Did the white and grey list import ok? It seems like the import didn't work and it just deleted all the cookies because there was nothing in the lists.

Feel free to send me a copy of your `storage.js` in `browser-extension-data\CookieAutoDelete@kennydo.com` so I can test the migration more since I only tested with mine. Thanks.

**Comment by SW1FT** [comment]
No, the import didn't work. Then I made a new whitelist and CAD was still deleting cookies every time I closed a tab.

This is my `storage.js` now:
`{"contextualIdentitiesEnabledSetting":false,"delayBeforeClean":"0","cookieDeletedCounterTotal":0,"activeMode":true,"statLoggingSetting":false,"showNumberOfCookiesInIconSetting":false,"notifyCookieCleanUpSetting":false,"defaultWhiteList":["crowdin.com","duckduckgo.com","facebook.com","opskins.com","reddit.com","sa-mp.com","soundcloud.com","thothapp.com","twitch.tv","youtube.com","zengm.com","github.com","forums.gamersfirst.com","mozilla.locamotion.org","pontoon.mozilla.org","accounts.firefox.com","bugzilla.mozilla.org","faceit.com","steamcommunity.com","store.steampowered.com","addons.mozilla.org","dropbox.com"],"cookieCleanUpOnStartSetting":false,"enableGlobalSubdomainSetting":false,"defaultWhiteList-Grey":[],"migration_1":true,"state":"{\"lists\":{\"default\":[{\"expression\":\"accounts.google.com crowdin.com duckduckgo.com facebook.com ffbans.org gamersfirst.com kaspersky.com locamotion.org mozilla.org opskins.com reddit.com sa-mp.com soundcloud.com thothapp.com twitch.tv youtube.com zengm.com github.com forums.gamersfirst.com mozilla.locamotion.org pontoon.mozilla.org accounts.firefox.com\",\"storeId\":\"default\",\"listType\":\"WHITE\",\"id\":\"SkIBxwfj-\",\"regExp\":\"^accounts\\\\.google\\\\.com crowdin\\\\.com duckduckgo\\\\.com facebook\\\\.com ffbans\\\\.org gamersfirst\\\\.com kaspersky\\\\.com locamotion\\\\.org mozilla\\\\.org opskins\\\\.com reddit\\\\.com sa-mp\\\\.com soundcloud\\\\.com thothapp\\\\.com twitch\\\\.tv youtube\\\\.com zengm\\\\.com github\\\\.com forums\\\\.gamersfirst\\\\.com mozilla\\\\.locamotion\\\\.org pontoon\\\\.mozilla\\\\.org accounts\\\\.firefox\\\\.com$\",\"cookieNames\":[]}]},\"cookieDeletedCounterTotal\":303,\"cookieDeletedCounterSession\":38,\"settings\":{\"activeMode\":{\"id\":\"SJZEevGi-\",\"name\":\"activeMode\",\"value\":true},\"delayBeforeClean\":{\"name\":\"delayBeforeClean\",\"value\":\"0\",\"id\":\"H1wtZDzsW\"},\"statLogging\":{\"name\":\"statLogging\",\"value\":true,\"id\":3},\"showNumOfCookiesInIcon\":{\"name\":\"showNumOfCookiesInIcon\",\"value\":true,\"id\":4},\"showNotificationAfterCleanup\":{\"name\":\"showNotificationAfterCleanup\",\"value\":true,\"id\":5},\"cleanCookiesFromOpenTabsOnStartup\":{\"name\":\"cleanCookiesFromOpenTabsOnStartup\",\"value\":false,\"id\":6},\"contextualIdentities\":{\"name\":\"contextualIdentities\",\"value\":false,\"id\":7}},\"cache\":{\"browserDetect\":\"Firefox\"}}"}`

**Comment by ke-d** [comment]
@SW1FT 

![capture](https://user-images.githubusercontent.com/17077613/30751855-7a21b55c-9f6f-11e7-9427-679a9342e35b.PNG)

Do the lists show something like that? Because that's not right. Each domain is supposed to be separate like this.

![capture2](https://user-images.githubusercontent.com/17077613/30751979-cee536f4-9f6f-11e7-9934-3973f2af5421.PNG)

**Comment by SW1FT** [comment]
@mrdokenny Yes, it displays like the first image. I already fixed this and it's no longer deleting whitelist cookies.

**Comment by ke-d** [comment]
@SW1FT I think I solved the issue with the migration. The settings did migrate properly but it never got saved. So on a restart, everything will get reset to default. I'm going to push out beta 2.

**Comment by ke-d** [comment]
@SW1FT You can verify if it's fixed in beta 2 by going into `about:debugging`, click `Debug` in C-AD, then in the console put `browser.storage.local.remove(["state", "migration_1"]);` and press enter. This basically deletes the storage format in 2.X.X and a flag saying that the migration happened. 

Afterward, you can restart once for the migration and then another time to see if the settings stick. Thanks for testing.

**Comment by FunkyBrewster** [comment]
I didn't import anything when I installed CAD, and my privacy.firstparty.isolate is set to false. Deleting all cookies manually from FF's settings does delete them, but they reappear as soon as I start visiting websites again. I've changed the Timer setting to 0.1 minutes and it seems to be deleting more cookies than before.  

The timer delete function is deleting *some* cookies, but not others. I'll keep testing with the timer setting changed, but it looks like a lot of cookies are still not getting deleted. I don't really want to just wipe all cookies based on a timer. I would be better to have them removed when the tab that set them is closed.

Should I wait for version 2?

**Comment by phonphen** [comment]
i have same problem when set timer to 0 in version 1.xx
but when i set timer to 0.01, the problem gone

**Comment by ke-d** [comment]
@FunkyBrewster @phonphen 

I think something happened with Firefox (in 55?) because setting it to 0 worked before. Maybe a fix so that when it's 0, it puts in 0.01 instead?

Edit: Relevant code in 1.X.X
https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/blob/master/src/background.js#L33

Actually looking at it, it might be better to just bypass creating the alarm and just call the cleanup function directly when it's 0.
