### ISSUE TITLE
[Bug] Popup panel shows suggestion that wouldn't apply for the current domain (www.domain.com not showing)

### ISSUE THREAD

**Issue by WhyNotHugo** [mrdokenny/Cookie-AutoDelete#1585]
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Describe the bug

When I visit `www.patreon.com`, CAD offers two possible patterns to greylist/whitelist: `patreon.com` and `*.patreon.com`.

The second suggestion is fine: it matches any subdomain of `patreon.com`. However, the first one matches only the apex domain` patreon.com`, but not the currently open domain `www.patreon.com`.

This leads to a common mistake: I visit a domain, I have a suggestion to whitelist it, I do, but it turns out that the suggestion does not apply to the domain that I'm looking at.

### To Reproduce

1. Visit `www.patreon.com`.
2. Open the addon popup panel.

### Expected Behavior

The first suggestion should be for `www.patreon.com`, which would match the currently open page.

### Screenshots

![image](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/assets/730811/6b02c6d3-ba14-492a-8b13-1ad6ea996907)

### System Info - Operating System (OS)

Alpine Linux, Edge

### System Info - Browser Info

firefox-115.0.1-r3

### System Info - CookieAutoDelete Version

3.8.2 (I'm very happy that the addon lets copy-paste that from the panel, that's super handy, thanks!)

### Additional Context

Obviously I used `www.patreon.com` as an example here, but this applies to any non-apex domain.

**Comment by kennethtran93** [comment]
Probably unclear in the documentation and I guess the popup UI, but if you only configure the main domain, `www` is the only 'subdomain' that is implicitly included in the main domain config with no subdomains.

Any rules that have been configured to apply will show up in the popup as well.  If you had clicked on the greylist/whitelist auto-add button on either entry, you should see one of the following entries (or both if you clicked both):
![image](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/assets/6724477/19e3bbb2-57df-4b18-a784-31268c090314)

This lets you know that you have a configuration for that domain.

If you visit a non-www domain, there will be a suggestion entry included for the subdomain only (note that in this case, there will not be a main domain only as you are already accessing the site from a subdomain):
![image](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/assets/6724477/32ce525e-37d3-48b6-99e9-a0b2df552090)
Note that the domain shown in the top-left of the popup will usually include any subdomains in the URL, with the exception of `www`.

I've updated the documentation slightly to reflect this better.
https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/Documentation#enter-expression
