### ISSUE TITLE
[Bug] Documentation "Enable Plugin Data Support" has dead link to "developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Plugins".

### ISSUE THREAD

**Issue by dreirund** [mrdokenny/Cookie-AutoDelete#1587]
### Describe the bug

[Documentation "Other Browsing Data Cleanup Options" -> "Enable Plugin Data Support"](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/Documentation#other-browsing-data-cleanup-options) has a link to "[developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Plugins](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Plugins).

This link target does no longer exist; I get a

> ## *Page not found*
> 
> *Sorry, the page `/en-US/docs/Mozilla/Add-ons/Plugins* could not be found.*

### To Reproduce

1. Go to https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/Documentation#other-browsing-data-cleanup-options,
2. Open the link to https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Plugins,
3. See a "Page not found" website.

### Expected Behavior

See the documentation.

### System Info - Operating System (OS)

Artix GNU/Linux

### System Info - Browser Info

Firefox Developer Edition 116.0.b4

### System Info - CookieAutoDelete Version

3.8.2

**Comment by kennethtran93** [comment]
Thanks for the heads up.  I've updated that section accordingly.
