### ISSUE TITLE
[FEATURE REQUEST] Additional option. Disable Cookies

### ISSUE THREAD

**Issue by waniaa1** [mrdokenny/Cookie-AutoDelete#1617]
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Is your feature request related to a problem? Please describe.

Too many plug-ins in the browser. I would like to reduce their number by adding options to your extension.

### Describe the solution that you'd like

Hello. I would like to congratulate you on a very good expansion. The only thing it lacks is the option to block cookies on every page. That is, the option that extensions have (Disable Cookies 1.4.0). Could you add an option to block cookies on visited websites, and a list where you can add addresses, e.g. (*.google.*/*,*.msn.com:*/*). And that cookie blocking works for all hosts, subdomains and domains.

**Comment by kennethtran93** [comment]
Duplicate request for a 'blacklist' type feature.
