### ISSUE TITLE
[FEATURE REQUEST]  Delete direcotries

### ISSUE THREAD

**Issue by AtomicRobotMan0101** [mrdokenny/Cookie-AutoDelete#1619]
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Is your feature request related to a problem? Please describe.

When clearing cookies, the CAD does not _delete the directories_.

Using Linux Mint Cinnamon 21.3 in this example, the directory /home/USERNAME/.mozilla/firefox/FOO.default-release/storage/default contains a zillion directories from site that have been purged.

Some also contain additional subdirectories which contain significant tracking info. They are called "/cache/morgue/foo".... there is very little info on the web as to what these are. (other than a self-described `file` descriptor of ".`final: snappy framed data`"

It would be good CAD can be modded to delete these remnants. (I do understand that the plugin simply calls available libs/APIs and this may not be achievable)

In this screenshot, which shows only a tiiiiny percentage of the folders, the following URLs have been purged by CAD....

_AskUbuntu, CloudFlare, dwcdn, microsoft (!!!), ebay, docker, pi-hole, electrek, the "wikis", finviz (???), mediadelivery..._

There are 178 directories, but I have only 10 rules.

![Screenshot from 2024-04-18 17-45-17](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/assets/64177332/a649b76e-ff4f-4232-9574-809b4729a383)

### Describe the solution that you'd like

Delete old, redundant and unused directories.

### Describe alternatives you've considered

Writing a shell script that could be called post-CAD.

If CAD could easily expose a simple list of rules URLs (so I dont need to monch on parsing XML, etc) then the shell could be run, obliterating these garbage files.

**Comment by kennethtran93** [comment]
I don't believe we can remove any directories unless it is exposed through the web extension API.  It would normally be up to the browser to do this I believe, or as you said your own shell script.
