### ISSUE TITLE
FR: Also clear localStorage

### ISSUE THREAD

**Issue by waqas** [mrdokenny/Cookie-AutoDelete#165]
### Describe the Bug/Feature
It does delete cookies as the name implies but some websites store identifying information in local/html5 Storage also. If possible, can this also delete that?
Thanks.

Firefox 57b5

**Comment by ghost** [comment]
https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/44

**Comment by ke-d** [comment]
Duplicate of #44
