### ISSUE TITLE
UX Improvement (on OSX?)

### ISSUE THREAD

**Issue by elsbrock** [mrdokenny/Cookie-AutoDelete#166]
### Describe the Bug/Feature

The popup/font size is too big in relation to other UI elements.

### Screenshot in which the bug can be seen

<img width="764" alt="grafik" src="https://user-images.githubusercontent.com/77769/31150586-77ec70b4-a894-11e7-87d8-c5ab304d8865.png">

### Steps for anyone to reproduce the bug

open popup

### Your settings 

- OS/version: macOS High Sierra 10.13
- Browser/version: Firefox 57.0b4 (64-Bit)
- Cookie AutoDelete version: 1.4.4

**Comment by ghost** [comment]
Look at this https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/pull/163

**Comment by ke-d** [comment]
Closing as this is already done.
