### ISSUE TITLE
Adding to Whitelist Bug

### ISSUE THREAD

**Issue by Joel889** [mrdokenny/Cookie-AutoDelete#167]
### Steps for anyone to reproduce the bug
Enable Active Mode
Go to: https://pay.reddit.com/
Select "Never clean" by clicking on Cookie Auto Delete button
Close tab
Wait for Active Mode to run
All reddit cookies are deleted.

Workaround: add reddit.com to whitelist (and not pay.reddit.com).

### Your settings 

- OS/version: Windows
- Browser/version: Firefox 56
- Cookie AutoDelete version: 1.40

**Comment by ke-d** [comment]
Look at #163

**Comment by ke-d** [comment]
In 2.X.X, popup has an option to add `*.reddit.com`, `pay.reddit.com`, or `*.pay.reddit.com`.
