### ISSUE TITLE
Allow users to enter their own regular expressions

### ISSUE THREAD

**Issue by grenzor** [mrdokenny/Cookie-AutoDelete#169]
Currently it looks like all user entered expressions are converted to regular expressions but this doesn't allow users to enter their own regular expressions. Doing so will be extremely useful for user-defined specificity for some rules.

**Comment by ke-d** [comment]
If you can convince me of specific use cases, I might consider it.

As it stands, I don't see how this would be useful vs. making more confusing for the user (not everyone can do RegExp).

**Comment by grenzor** [comment]
I agree this is for more expert users so users would have to do something extra to use it (e.g. tick box to enter regular expression).

^((?!google.com|github.com|yahoo.com).)*$ - matches all domains except defined

This is just one example from me, someone who really knows very little regexp but since regexp is extremely flexible I'm sure it would benefit more advanced users. Honestly, I was originally thinking of this suggestion more for your H-AD addon not C-AD as C-AD regexp is useful for cookie domains where the other can be applied to the whole URL but it can still be useful here since RegExp support is already implemented.

**Comment by seansfkelley** [comment]
When I first saw the changes this was also my first thought. I don't have a use-case off the top of my head now, but I thought it was strange that the UI displayed the regex when it wasn't editable/relevant.

**Comment by geniekoechling** [comment]
A use case would be a regex for the private IPv4 adresses:

`(^127\.)|(^10\.)|(^172\.1[6-9]\.)|(^172\.2[0-9]\.)|(^172\.3[0-1]\.)|(^192\.168\.)`

or ranges of hostnames like `srv000.example.com - srv099.example.com` without allowing every subdomain.

**Comment by kennethtran93** [comment]
Those following this:  I'm working on getting the cookie list populated based on the domain regexp. It will be included in the next version.
