### ISSUE TITLE
UI issue in settings - [object Promise]

### ISSUE THREAD

**Issue by raretrack** [mrdokenny/Cookie-AutoDelete#170]
### Describe the Bug/Feature
On the Settings > Cookie Whitelist page the light grey bar has two clickable menu options: [object Promise] and Default. The former looks like a bug?

### Screenshot in which the bug can be seen
![objectpromise](https://user-images.githubusercontent.com/20622687/31305754-0c3ec194-ab39-11e7-9b8d-e19cde582e82.png)

### Your settings 

- OS/version: Windows 10 Pro 64-bit (version 1607)
- Browser/version: Firefox 56.0 (normal browsing mode)
- Cookie AutoDelete version: 1.4.4

**Comment by ke-d** [comment]
You have Container Mode on and it might be fixed in 2.X.X.

**Comment by raretrack** [comment]
> You have Container Mode on and it might be fixed in 2.X.X.

Ah, OK. I will disable that feature for now as I'm not using Containers yet. Thanks for the reply.
