### ISSUE TITLE
No cookies deleted in FF on Ubuntu

### ISSUE THREAD

**Issue by lianergoist** [mrdokenny/Cookie-AutoDelete#172]
There seems to be an issue in Firefox 56.0 on Linux (Ubuntu 17.10 Beta). 

The problem: no cookies are deleted **when I close a tab or close Firefox**....

Cookie AutoDelete **will** delete the cookies if I click "Cookie Cleanup", and "Clear all cookies for this domain" also works as expected, but closing tabs or closing FF does not 'trigger' deleting cookies.

It is not a Cookie-AutoDelete issue, because [CookiErazor](https://addons.mozilla.org/en-US/firefox/addon/cookierazor) has the same problem, but you may want to know there is an issue here. 

- Ubuntu 17.10
- FF 56.0
- Cookie AutoDelete version: 1.4.4

**Comment by ke-d** [comment]
Did you enable active mode? Also, there are troubleshooting steps on the addon page.

**Comment by lianergoist** [comment]
Ups... Sorry I didn't read the troubleshooting on the addon page. With active mode it seems to work perfect. Thanks. And again, sorry.

But..., I don't understand why active mode isn't default. I mean, the name of the extension is Cookie AutoDelete, so one will expect it to delete cookies automatically. Right? ;-)

I don't really understand this: "This extension does not clean cookies automatically until you click "Active Mode". This gives you the chance to add sites to the WhiteList."

You have all the time from you load the site in a tab and until you close it, or close firefox, to add it to a gray- or whitelist. Right? I can't really see any problems in making "Clean After Tab Close" default behaviour. 

But apart from that, cool extension! Thanks!

**Comment by ghost** [comment]
The author has said that he "never liked" how Self-Destructing Cookies deletes all cookies after installation. I disagree and I think that "active mode" should be on by default as well.

**Comment by ke-d** [comment]
>You have all the time from you load the site in a tab and until you close it, or close firefox, to add it to a gray- or whitelist. Right? I can't really see any problems in making "Clean After Tab Close" default behaviour.

Nope. A cleanup occurs when the background script of C-AD starts when active mode is on. This means a cleanup occurs whenever the extension gets installed or restarts (either from browser restart or extension update). So if active mode enabled is the default, all of the cookies **will** get deleted **without** any chance of *recovery*.
