### ISSUE TITLE
Feedback about new interface (on mobile)

### ISSUE THREAD

**Issue by ghost** [mrdokenny/Cookie-AutoDelete#174]
### Describe the Bug/Feature

Popup could be wider:

![2017-10-09-13-11-44](https://user-images.githubusercontent.com/886325/31335861-b092e754-acf4-11e7-8e06-b8a987895bef.png)

![2017-10-09-13-11-37](https://user-images.githubusercontent.com/886325/31335891-d27a5c1c-acf4-11e7-9f04-755fda91a28c.png)

On first run after update, Settings -> List of expressions - only first row of the table was visible:

![2017-10-09-13-15-16](https://user-images.githubusercontent.com/886325/31335932-fc14cf08-acf4-11e7-992a-ee3f4989c121.png)

![2017-10-09-13-15-09](https://user-images.githubusercontent.com/886325/31335863-b2d38c8a-acf4-11e7-88b7-cd3b1abe85de.png)

This fixed itself after refresh or two.

### Your settings 

- OS/version: 4.4.2 480x800 DPR 1.5
- Browser/version: Firefox Nightly
- Cookie AutoDelete version: 2.0.0b4

**Comment by ghost** [comment]
Also, not mobile, but small screen:

![screenshot_20171009_134753](https://user-images.githubusercontent.com/886325/31336800-ceee6896-acf8-11e7-9890-8f4c1936c837.png)

Content must be scrolled by width of side menu.

**Comment by ke-d** [comment]
I probably won't do the popup issue until a later release since debugging on mobile is harder than on desktop.

**Comment by ghost** [comment]
@mrdokenny can this side menu be auto-closed on some events? On menu click / mouse out / on page click?
Can last used page be saved?

Now, every time I go to Settings, Release Notes are shown. I must click this relatively small button to open menu, go to Cookie Settings or List of Expressions, and then click again, to do anything.

**Comment by fichtennadel** [comment]
What about adding a "quick 'add to WL' option" in FF menu on Android, like SDC had? 

On mobile it's currently quite many steps to add domains, on a hard to read/navigate UI (elements are to small).

**Comment by ghost** [comment]
Bit small, but usable.

@fichtennadel I propose, you create new issue for your request.
