### ISSUE TITLE
Can't view the mobile interface for changing extension's settings

### ISSUE THREAD

**Issue by doronbehar** [mrdokenny/Cookie-AutoDelete#175]
### Describe the Bug/Feature

As the title suggests, I can't reach any page on which I can manage the extension's settings, I just press the button on the app's settings and I get no reaction..

It seems somewhat related to #174, #140 and #12 but My situation seems much worse than in those issues.

### Steps for anyone to reproduce the bug

1. Open Firefox browser
2. Navigate to http://example.com
3. Press the 3 dots button at the top of the UI
4. Press `Cookie AutoDelete`

No response.

### Your settings 

- OS/version: Android 7.1.2 (Lineage OS nightly), no GAPPS
- Browser/version:  Fennec F-Droid/ 56.0
- Cookie AutoDelete version: 1.4.4

**Comment by ke-d** [comment]
You are using FF 56 on Android. In #12, only FF 57 has the APIs required for the popup and the options menu to work. So I can't really do anything at this point except wait for FF 57+.

**Comment by doronbehar** [comment]
Thanks for your comment, but I wonder:
Have you ever used Ublock origin on the mobile?
With the same firefox version I reported this issue, I don't experience a similar problem with uBlock origin. It looks great:

![ublock origin settings on mobile](https://framapic.org/o1uDeDwxihRZ/tXPN3395wicx)

Do they use a different API then Cookie AutoDelete?
