### ISSUE TITLE
Badge colors not eye friendly

### ISSUE THREAD

**Issue by SSoulaimane** [mrdokenny/Cookie-AutoDelete#176]
I cannot see the number on the badge until I move my head closer to the screen. White on blue/orange is  not a confortable combination to human eyes. I don't experience this issue with other extensions that also leverage dynamic badge information display, two of which I happen to be using confortably are ublock origin and https everywhere, and both of these use white on black badges.

**Comment by ke-d** [comment]
Duplicate of #66 

Also, it's supposed to be a monochromatic color to the icon.
