### ISSUE TITLE
Cookies not deleting from "Firefox Multi-Account Containers" tabs

### ISSUE THREAD

**Issue by RyanTG** [mrdokenny/Cookie-AutoDelete#177]
### Describe the Bug/Feature

**Background:** Mozilla recently released the [Firefox Multi-Account Containers](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/) addon. 

**Issue:** The cookies aren't clearing from the Containers.

**More details:** When using this Containers addon, you can either open tabs in "no container", or in a container. Some containers include "Personal" "Work" "Bank" "Shopping". All of the open tabs that use the same container category can talk to each other (aka share cookies and stuff), but they are silo'd from other container categories. I've found that when you close the tabs in a container, the cookies persist. If you close tabs that are _not_ using a container, the cookies delete as expected.

### Steps for anyone to reproduce the bug

1. Install the [Firefox Multi-Account Containers](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/) addon.
2. Set Cookie-AutoDelete to Active Mode, and "Clean after tab close".
3. Open a new tab using the "Personal" Container. 
4. In that tab, log into a website (in my case, I logged into gmail).
5. Close the tab.
6. Open a new tab using the "Personal" Container.
7. In that tab, navigate to gmail (if that's what you logged into previously).

Result: You'll still be logged into gmail.

### Your settings 

- OS/version: Manjaro Linux
- Browser/version: Firefox 56
- Cookie AutoDelete version: 1.4.0

I also reproduced it on Windows 10, Firefox 56, addon version 1.4.0.

**Comment by ke-d** [comment]
There's an extra setting that you must toggle. The setting is there because other browsers don't have Containers.

**Comment by RyanTG** [comment]
Ah, "Enable Support for Firefox's Contextual Identities (EXPERIMENTAL Firefox 53+)".

Gotcha. I'll close this.

THANKS!

**Comment by RyanTG** [comment]
Hmm, even after enabling that settings, and waiting a minute before reopening that container, the cookie isn't deleted.

**Comment by RyanTG** [comment]
This was resolved by restarting the browser.

So, perhaps the setting could be edited to say, "Enable Support for Firefox's Contextual Identities (EXPERIMENTAL Firefox 53+) (Restart Required)"

Thanks again for your addon. Glad to see you're filling the shoes of Self-Destructing Cookies.

**Comment by ke-d** [comment]
It actually shouldn't require a restart, but glad to see it working. :)
