### ISSUE TITLE
Popup blinking

### ISSUE THREAD

**Issue by scmanjarrez** [mrdokenny/Cookie-AutoDelete#183]
### Describe the Bug/Feature
Everytime I click on the icon, the popup starts blinking.

### Screenshot in which the bug can be seen
![issue](https://user-images.githubusercontent.com/9284124/31580836-67b5fc04-b15b-11e7-9336-ff086bd5dd08.gif)

### Steps for anyone to reproduce the bug
1. Click the icon
2. Add the current domain to the whitelist, clicking in the "Add to whitelist" button.

### Your settings 

- OS/version: Windows 10 Pro, 1703, x64.
- Browser/version: Mozilla Firefox 56.0.1, x64.
- Cookie AutoDelete version: 2.0.0

**Comment by wilfriedh** [comment]
Same for me on two computers: 
Tower with Win7Pro 64bit, 
Laptop with Win10Home 64bit
both with
Browser/version: Mozilla Firefox 56.0.1, x64.
Cookie AutoDelete version: 2.0.0

**Comment by wilfriedh** [comment]
Version 2.0.1 fixes this for me.

**Comment by scmanjarrez** [comment]
Already fixed in [last release, 2.0.1](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/releases/latest)
