### ISSUE TITLE
Feature Request: Need a way to edit whitelist

### ISSUE THREAD

**Issue by plaguedemons** [mrdokenny/Cookie-AutoDelete#189]
### Describe the Bug/Feature
Hi, Please add a menu selection to edit the whitelist. I added entries that I think I want to delete. Thanks.

### Your settings 

- OS/version: Windows 10 Home Premium
- Browser/version: Firefox 56
- Cookie AutoDelete version: 2.0.0

**Comment by ke-d** [comment]
You can already edit the whitelist. There's a trashcan icon that shows up in the first column of the table.
