### ISSUE TITLE
Clicking on icon when on a page protected by basic auth triggers login dialogue

### ISSUE THREAD

**Issue by webbson** [mrdokenny/Cookie-AutoDelete#190]
As title says. When auth is entered nothing happens. Clicking on the icon again triggers login dialogue again. 

- OS/version:  Windows 10
- Browser/version: Firefox 56
- Cookie AutoDelete version:  2.0.0

**Comment by ke-d** [comment]
Could you add a picture or elaborate more?

**Comment by ghost** [comment]
Test page for basic authentication http://browserspy.dk/password-ok.php
Works for me.

**Comment by webbson** [comment]
I'm logged in to a page with basic auth. When I'm clicking on the cookie auto-delete icon I get this login screen:
![Login screen](https://i.imgur.com/hOaysHS.png)

If I enter my credentials and click the cookie auto-delete icon again I get the same login dialog again (repeated each time I click it).

I'm also using Multi-Account Containers if that might have something to do with it.

**Comment by ke-d** [comment]
You should probably whitelist that site then.

**Comment by realityexists** [comment]
I'm experiencing this as well on particular site, even though it doesn't happen on http://browserspy.dk/password-ok.php. @mrdokenny can I email you the URL?
