### ISSUE TITLE
debug cookies needed to login?

### ISSUE THREAD

**Issue by gliptak** [mrdokenny/Cookie-AutoDelete#194]
While trying to login into O365, I get the following message:

"Your browser is currently set to block cookies. You need to allow cookies to use this service."

Is there a way to identify which paths need to be whitelisted (in addition to ```*.office365.com```)?

Thanks

**Comment by chiraag-nataraj** [comment]
Are you using other privacy addons (like uMatrix)? For example, I've gotten that before when I whitelisted a site if I forgot to also allow access to those cookies through uMatrix.

**Comment by ghost** [comment]
@gliptak  are you blocking third-party cookies in browser preferences?

**Comment by gliptak** [comment]
@chiraag-nataraj  Yes, I have ```uBlock Origin```. I disabled uBlock Origin, Cookie AutoDeletion, MultiAccount Containers, and after restart still cannot login. The UI still displays the Containers visuals, so for now I think Containers broker this ...

@gwarser With FF 56.0, the ```3rd party cookies``` checkbox no longer seem to available.

I still would like to understand how this can be debugged. Thanks
