### ISSUE TITLE
2.0.1 Greylist and Browser Startup Clarification

### ISSUE THREAD

**Issue by MarkRH** [mrdokenny/Cookie-AutoDelete#195]
- OS/version:  Windows 7 Pro 64bit
- Browser/version:  Firefox 57beta8
- Cookie AutoDelete version: 2.0.1

I understand that the Greylist is used to clear cookies on browser start; however, apparently it was only supposed to work if auto-clean was on and 2.0.1 "fixed" that.  Well, if auto-clean is enabled, then won't all the cookies not in the whitelist get auto-deleted anyway?

I guess it catches the ones left from tabs that were open when you closed the browser?

I suppose that makes more since as auto-delete being disabled should not allow for deletion at startup either.  Think I've answered my own question.   But, I wonder if an option to clean the greylist on startup even if auto-delete is disabled could be added? Hmm

**Comment by ke-d** [comment]
https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/FAQ:-Common-Questions-and-Issues#how-do-i-set-all-cookies-to-be-deleted-on-browser-restart-rather-than-on-tab-close
