### ISSUE TITLE
Undelete option

### ISSUE THREAD

**Issue by Winter84** [mrdokenny/Cookie-AutoDelete#196]
It would be nice to be able to undelete the cookies just deleted, for example if you see cookies deleted for a site that you would like to whitelist. You could then undelete the cookies, whitelist the site, and let the remaining cookies be deleted the next time or delete them immediately with a cleanup. This would prevent losing the wanted cookies.

I am using
- Browser/version: Just installed Firefox 56.0
- Cookie AutoDelete version: 1.4.4

**Comment by DJTai** [comment]
If I understand this correctly, do you mean like having a Recycle Bin/Trash setting? That sounds interesting...You could have Auto-clean set to disable. That way nothing is really deleted until you want it to. More of a hassle, but it could get you by until this feature is added (if at all possible).

**Comment by chiraag-nataraj** [comment]
Just as a note, this setting existed/exists in SDC (Self-Destructing Cookies), and while I never really used it (I let it clear everything and then added whatever whitelists I needed), it seems like a reasonable feature to have :slightly_smiling_face:

**Comment by ke-d** [comment]
![untitled](https://user-images.githubusercontent.com/17077613/50621799-30b09f00-0ebd-11e9-8b11-8fd9590d57d3.png)

How this feature looks like
