### ISSUE TITLE
Cookies in containers not deleted

### ISSUE THREAD

**Issue by ghost** [mrdokenny/Cookie-AutoDelete#197]
### Describe the Bug/Feature
If we add domain to whitelist in Work container, cookies will not be deleted in Banking container.

### Steps for anyone to reproduce the bug

- create clean Firefox profile
- install CAD
- configure CAD to support Firefox Container Tabs
- add `*.mozilla.org` to Whitelist in Work container (firefox-container-2)
- enable Auto-clean
- close two mozilla.org tabs you should have in clean profile on first start
- cookies will be deleted (because this is "default" container)
- create new Banking container (firefox-container-3)
- open mozilla.org
- close mozilla.org tab
- cookies will not be deleted

### Your settings 
Delay is set to 0.1 to speed things up. No difference with 0 or 1.
```
{"state":"{\"lists\":{\"default\":[],\"firefox-container-2\":[{\"expression\":\"*.mozilla.org\",\"storeId\":\"firefox-container-2\",\"listType\":\"WHITE\",\"id\":\"H1ugOn7pb\",\"cookieNames\":[]}]},\"cookieDeletedCounterTotal\":9,\"cookieDeletedCounterSession\":9,\"settings\":{\"activeMode\":{\"name\":\"activeMode\",\"value\":true,\"id\":\"B1AQOhQTb\"},\"delayBeforeClean\":{\"name\":\"delayBeforeClean\",\"value\":\"0.1\",\"id\":\"SJxfmu2Qpb\"},\"statLogging\":{\"name\":\"statLogging\",\"value\":true,\"id\":3},\"showNumOfCookiesInIcon\":{\"name\":\"showNumOfCookiesInIcon\",\"value\":true,\"id\":4},\"showNotificationAfterCleanup\":{\"name\":\"showNotificationAfterCleanup\",\"value\":true,\"id\":5},\"cleanCookiesFromOpenTabsOnStartup\":{\"name\":\"cleanCookiesFromOpenTabsOnStartup\",\"value\":false,\"id\":6},\"contextualIdentities\":{\"id\":\"rJL1_3XaZ\",\"name\":\"contextualIdentities\",\"value\":true}},\"cache\":{\"browserDetect\":\"Firefox\",\"default\":\"Default\",\"firefox-default\":\"Default\",\"firefox-private\":\"Private\",\"firefox-container-1\":\"Personal\",\"firefox-container-2\":\"Work\",\"firefox-container-3\":\"Banking\",\"firefox-container-4\":\"Shopping\"}}"}
```

- OS/version: Linux Mint 18.2
- Browser/version: Firefox 57.0b9
- Cookie AutoDelete version: 2.0.1

**Comment by ghost** [comment]
I think this not work, because settings are not initialized. You probably skip deleting when iterating over containers if settings for container is nonexistent. I have red icon only in Default and Work container - Dafault may be here all the time, and Work is "touched" when I created first entry in whitelist. 

I tested this again, by adding empty rule to all lists and then removing it (just click +Whitelist on every container and then Delete) and this seems to fix this problem for me. I will test this again in clean profile and confirm.
Edit:
Seems to be the case.

**Comment by hcbraun** [comment]
Cookies in containers are not deleted. Neither on close or startup. For me the add-on has no effect at all on the cookies of a container.

- Cookie AutoDelete 2.0.1
- Multi-Account Containers 4.0.3
- Firefox 56.0.1 / Linux

I tried the +Whitelist workaround without success.

**Comment by ghost** [comment]
Just to be sure - you have "Auto-clean" enabled?

**Comment by hcbraun** [comment]
- Enable Automatic Cleaning? Delay Before Cleaning:Minute(s)?
- Log Total Number Of Cookies Deleted?
- Show Number of Cookies for that Domain?
- Show Notification After Cookie Cleanup?
- Clean Cookies from Open Tabs on Startup?
- Enable Support for Firefox's Container Tabs?

All the options are enabled. Cleaning set to 1 minute. 

Its easy to reproduce for me:
- Open new tab
- Browse to a new site with cookies
- Close tab
- Press yellow add-on button "Clean"

With a default tab i get the pop "Cookies were deleted" notification. Doing the same with a container tab shows no notification and the site cookies show up under Preferences / Privacy&Security / Show Cookies

Firefox cookie settings:
- Accept cookies from websites: On
- Accept third-party cookies: Never
- Keep until: they expire
- Clear history when Firefox closes: On
-- Browsing & Download History: Off
-- Cookies: Off
-- Active Logins: On
-- Cache: On
-- Form & Search History: Off

**Comment by ghost** [comment]
When you type `privacy.userContext` in about:config page, are these filtered settings set to **true**?

https://wiki.mozilla.org/QA/ContainersTestPilot#Container_Prefs

**Comment by ghost** [comment]
[On my Firefox 56, Containers are not enabled by default](https://wiki.mozilla.org/QA/ContainersTestPilot#Summary_.26_Purpose:). Even enabling them in CAD not work. I must enable them manually from about:config. After that, I must add and remove any rule to all containers to initialize settings, then deleting works. One issue - names of containers are wrong (undefined), but this fixes itself after restart.

**Comment by hcbraun** [comment]
It is set to true:
privacy.userContext.enabled;true

I just installed the add-on and did not edit anything in about:config for containers:
https://addons.mozilla.org/en-GB/firefox/addon/multi-account-containers/
