### ISSUE TITLE
Allow cookie until the browser is closed (Grey List Support)

### ISSUE THREAD

**Issue by Primokorn** [mrdokenny/Cookie-AutoDelete#20]
Hi,
Thanks for working on this WebExtension!
Could you also add a feature to only allow cookies of a domain for the current session. As soon as the browser is closed the cookies are deleted.

**Comment by mrdokenny** [comment]
I was considering adding a setting that basically does a "Cookie Cleanup (Ignore Open Tabs)" on startup (no APIs for performing actions on shutdown yet), which should cover your use case unless you have another use case for that feature.

**Comment by Primokorn** [comment]
It doesn't cover my feature request.

Here is what I mean:
* I have 3 opened tabs : site A, B and C.
* I close site B
* Several minutes later I open site B again and I'd like to have my cookies until I close the browser.

Actually I visit several websites during a session but they aren't always open. I close and open them several times a day.
Thanks.

**Comment by mrdokenny** [comment]
To make it easier on myself and for whitelist backwards compatibility, I am probably going to implement this as a grey list similar to how [Cookies Exterminator](https://addons.mozilla.org/en-US/firefox/addon/cookies-exterminator/) does it.

**Comment by Primokorn** [comment]
Do you mean the '_keep until browser exit_' option? (I have never installed this addon).
FWIW Self-Destruction Cookies has this feature.

**Comment by mrdokenny** [comment]
Grey list is similar to whitelist except grey list is the sites that you want to keep cookies until the browser is closed (or in this case on start b/c of lack of APIs).

Whitelist will be the sites that you want to keep cookies permanently.

I have the necessary architecture in place of this because of [Containers](https://testpilot.firefox.com/experiments/containers/)(which have a separate whitelist for each Container)

**Comment by IllegalCactus** [comment]
Just wanted to +1 this request. What I like about Self Destructing Cookies is the three options it gives (Allow, clear on browser exit, clear on tab close).

It sounds like the combination of whitelist and graylist + active mode will allow this same functionality?

**Comment by mrdokenny** [comment]
> What I like about Self Destructing Cookies is the three options it gives (Allow, clear on browser exit, clear on tab close).

I'll have something similar like:

- No list
- Add to GreyList?
- Add to WhiteList?

as radio buttons in the popup. This means that a site can only be in one of these three states.

**Comment by IllegalCactus** [comment]
Cool, thanks! I like the icon suggestion in https://github.com/mrdokenny/Cookie-AutoDelete/issues/47 as well, that's pretty much what I had in mind with my comment above.

**Comment by mrdokenny** [comment]
Got some UI work done today. Still not functional yet but it's a good start. :)

![screenshot 2017-06-15 17 07 11](https://user-images.githubusercontent.com/17077613/27206606-5c9e2814-51ed-11e7-8702-4dbb237c5bec.png)

**Comment by mrdokenny** [comment]
Anyone can think of a better wording or phrase for "No list"? I feel like it might not make sense for most people or it might not translate well to other languages. The other 2 ("Add to GreyList?" and "Add to WhiteList") are ok in my opinion.

**Comment by welwood08** [comment]
In my opinion it's not obvious what "GreyList" means, I'd suggest something like:

- Clean on tab close
- Clean on exit
- Never clean

If I recall correctly, this is similar language to Self-Destructing Cookies, which I suspect many new users will be familiar with.

As for the UI, it doesn't make sense for a host to be able to exist on both whitelist and greylist, so I'd suggest combining those 2 views and just having some sort of indicator as to the mode of operation for each host (perhaps even radioboxes/dropdown to switch between on tab close and on exit).

**Comment by mrdokenny** [comment]
@welwood08

> In my opinion it's not obvious what "GreyList" means, I'd suggest something like:
Clean on tab close
Clean on exit
Never clean

Good start. I would go one step further and do this:

- Clean on tab close 
- Clean on restart (GreyList)
- Never clean (WhiteList)

Just to make a clear connection. Either way I'll have explanation somewhere in the options UI.

> As for the UI, it doesn't make sense for a host to be able to exist on both whitelist and greylist, so I'd suggest combining those 2 views and just having some sort of indicator as to the mode of operation for each host (perhaps even radioboxes/dropdown to switch between on tab close and on exit).

I like that idea but I think for the MVP and to make it easier for me to code I'll leave the WhiteList and GreyList there for now.

**Comment by mrdokenny** [comment]
Testing is available in 1.4.0b1. Please test it and give your feedback and report bugs as well. 😄 

GreyList goes pretty well with the setting "Clean Cookies from Open Tabs on StartUp" (used to be named "Enable Cookie Cleanup on Startup") 

With that setting enabled, the cleanup on start will clean cookies on the greylist of a site regardless if that site is open.

Ex. Google.com is in the greylist and currently open. With "Clean Cookies from Open Tabs on StartUp" enabled, the cleanup on start will clear google.com even though it is in a open tab.

Since extension restarts count as browser restarts, a good way to test the greylist is to restart the extension. In Firefox, you can load the xpi temporary and reload it in about:debugging. In Chrome, you have to enable developer tools to enabled extension restarts.

**Comment by IllegalCactus** [comment]
New interface looks good! - would you prefer bug reports in this issue or new issues?

I noticed that after adding a site to the greylist or whitelist in the popup, it's not possible to add it to 'no list' in the popup, you have to go into the addon settings page and remove it there. Clicking 'Clean After Tab Close' doesn't do anything, and after closing and reopening the popup dialogue the radio is unchecked again. Seems the radio toggle isn't removing the site from the whitelist properly?

**Comment by Primokorn** [comment]
Same issue here (FF 54.0)

**Comment by mrdokenny** [comment]
@IllegalCactus @Primokorn 

>New interface looks good! - would you prefer bug reports in this issue or new issues?

Bug reports relating to the feature should probably go into their respective feature issue.

I haven't added code that updates the setting page whitelist/greylist when you make changes in the popup. Have you guys tried refreshing the settings page after making changes in the popup? 

It works fine on my end.

**Comment by Primokorn** [comment]
Here are all the steps that I did on [this website](https://celu.fr/):
1. Cookies set to **Clean on browser restart**
2. Log in to my account
3. Refresh the webpage ==> no changes
4. Refresh the addon from about:debugging
5. Refresh the webpage => cookies are cleared

On the same webpage:
1. Open the Cookie AutoDelete pop-up
2. Select **Clean after close tab**
3. Click outside of the pop-up
4. Open the Cookie AutoDelete pop-up ==> **Clean on browser restart** is checked

**Comment by mrdokenny** [comment]
Ah thanks @Primokorn  for the STR 👍 
I think it might be a problem with restarting the extension from about:debugging.
It might work fine if you are restarting normally, but I'll do some more testing.
According to console, 
`TypeError: this.cookieWhiteList.get(...) is undefined[Learn More]`
the WhiteList object in memory didn't get reset from storage on a restart in about:debugging. So I'll have to see what's that about.

**Comment by mrdokenny** [comment]
I fixed that issue and added the updated fr locale in 1.4.0b2.

So Containers have their separate default white/grey lists from the non-Containers Mode, and that "Clean after close tab" button was trying to remove it from the Container Mode default lists rather than the Non-Container Mode default lists.

**Comment by IllegalCactus** [comment]
Ah, makes sense, I had a feeling it might be that `cookieStoreId` was wrong, but couldn't figure out why 😃  Thanks for the quick response.

**Comment by mrdokenny** [comment]
Yeah with all the settings and new features interacting with each other, there's bound to be some bugs, but it should be good for daily use (I typically use the beta versions in my main profile to see if its good for daily use). 

If you find any more bugs, please report them and have a clear STR.
