### ISSUE TITLE
How to Export/Import Whitelist/Greylist

### ISSUE THREAD

**Issue by thierrybo** [mrdokenny/Cookie-AutoDelete#201]
From the addon page, it is stated "Easily Export/Import your Whitelist/Greylist". But I did not found any function to do that !?

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/886325/31834063-02bd0222-b5cd-11e7-8596-96a9bc46a16d.png)

**Comment by thierrybo** [comment]
Ha, thanks, I did not noticed the left bar before!

**Comment by ghost** [comment]
>I did not noticed the left bar before!

Hidden under button?
Your screen resolution is below 1300 width?

**Comment by thierrybo** [comment]
no, the left bar has the same colour as my bookmark bar!
http://pix.toile-libre.org/upload/original/1508536101.png
