### ISSUE TITLE
Error when cleaning cookies

### ISSUE THREAD

**Issue by ztoser** [mrdokenny/Cookie-AutoDelete#202]
Whenever auto-clean is triggered, or if I manually click "Clean" or "Clean, include open tabs", none of the cookies are deleted (as verified by Preferences/Privacy/Show cookies). In these cases, an error log appears in the browser log:

TypeError: contextualIdentitiesObjects.forEach is not a function
backgroundBundle.js:877:17

Cleaning cookies for single domains works. I disabled all my other extensions, but the issue still persists. I tested the issue on a clean profile, and surprisingly, it works there. Migrating to a new profile could be a workaround, but I thought the error message above might lead the developer to a useful fix.

- OS/version: up-to-date Arch Linux
- Browser/version: Firefox 56.0.1
- Cookie AutoDelete version: 2.0.1

**Comment by ke-d** [comment]
It seems like you have Containers turned on in the extension but not in the browser.

**Comment by ztoser** [comment]
Indeed, thank you. After disabling that setting in the extension, everything works fine.
