### ISSUE TITLE
It doesn't delete cookies with Multi-Account Containers 4.0.3 add-on

### ISSUE THREAD

**Issue by 01011970** [mrdokenny/Cookie-AutoDelete#203]
### Describe the Bug/Feature

It doesn't delete cookies with Multi-Account Containers 4.0.3 add-on

### Your settings 

- OS/version: Windows 10
- Browser/version: FF 57.0b10 64bit
- Cookie AutoDelete version: 2.0.1

**Comment by ghost** [comment]
Check this https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/197#issuecomment-337523756

**Comment by ke-d** [comment]
Duplicate of #197
