### ISSUE TITLE
What are * cookies?

### ISSUE THREAD

**Issue by luisvalenzuelar** [mrdokenny/Cookie-AutoDelete#204]
I just installed the extension. It's great! However, I do not know the difference between a "normal" and an * cookie.

For instance, in this site I get these cookies:

- github.com

- *.github.com

Is the former jyst www.github.com and the latter referring to every domain which has github.com as "extension"? 

If I want to whitelist the cookie that enables me to log in to this site, which one should I whitelist?

Thanks!

**Comment by ke-d** [comment]
Subdomain cookies. So for google.com, having *.google.com will protect cookies from drive.google.com, mail.google.com, etc.
