### ISSUE TITLE
Suggestion: add option to clear local storage

### ISSUE THREAD

**Issue by Jumbo-Gram** [mrdokenny/Cookie-AutoDelete#205]
Thanks for your great work! Just a quick suggestion: could you maybe add an option to also clear "local storage" and "database storage" objects? Plenty of sites these days use "local storage" so clearing cookies automatically is of no practical use if the same site is permitted to use "local storage" as a (semi-)persistent storage medium. Thanks again! :)

**Comment by ghost** [comment]
https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/44

**Comment by Jumbo-Gram** [comment]
Duplicate of #44. Thanks, gwarser.
