### ISSUE TITLE
Cookie Autodelete doesn't work at all [resolved]

### ISSUE THREAD

**Issue by somethingsomething123** [mrdokenny/Cookie-AutoDelete#207]
EDIT: Please ignore this issue. I'd been messing about with Firefox all day. Restarted Macbook, reinstalled Firefox, seems to be working ok when manually cleaning cookies. The other thing that was confusing me is that it doesn't auto-clean if you quit Firefox, seems to only auto-clean when closing tabs.

Firefox 56.0.1, Mac OSX Sierra 10.12.6

Cookie Autodelete isn't working at all. To test it, I went to bbc.co.uk, manually cleaned the cookies and they're still there.

I've followed the troubleshooting procedures (including the known problem with privacy.firstparty.isolate), uninstalled Firefox, deleted all profiles, preference data etc, re-downloaded and installed Firefox using the default settings and it's still not working.

Any ideas?

Thanks

**Comment by ke-d** [comment]
>auto-clean if you quit Firefox, seems to only auto-clean when closing tabs.

Actually, it auto-cleans on browser restart cause there's no API for that last time I looked.
