### ISSUE TITLE
Cookie Autodelete not working at all

### ISSUE THREAD

**Issue by vajravrtti** [mrdokenny/Cookie-AutoDelete#208]
### Describe the Bug/Feature
Cookie Autodelete is not deleting any cookies at all.
It used to work fine.
I suspect the problem began with Firefox 56.

### Steps for anyone to reproduce the bug
Fresh Firefox installation.
Do not change any Firefox settings.
Install just the Cookie Autodelete extension.
Set all Cookie Autodelete options.
Access various sites that set cookies.
No cookies are deleted even after restarting the browser.
No notifications are displayed.

### Your settings 
- OS/version:  Ubuntu 16.04 LTS
- Browser/version:  Firefox 56.0 (64-bit)
- Cookie AutoDelete version: 2.0.1

**Comment by ghost** [comment]
>Set all Cookie Autodelete options.

Including support for Firefox Container Tabs?

**Comment by vajravrtti** [comment]
It seems that setting  pref _privacy.userContext.enabled_ to **true** did the trick. But why does Cookie Autodelete depend on a new pref that is **false** by default? I had never heard about Container Tabs before you mentioned it, as I believe most of the users haven't either. If you have notifications off, as most probably do, you won't notice the cookies are not being deleted.

**Comment by vajravrtti** [comment]
My bad. Now I see I shouldn't have checked the 'Enable Support for Firefox's Container Tabs' option. But why are the users allowed to enable support for a function that is disabled in the browser? Why not enable the support for container tabs based just on pref _privacy.userContext.enabled_, without user intervention?

**Comment by ke-d** [comment]
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/contextualIdentities

>Before Firefox 57, the contextualIdentities API is only available if the contextual identities feature is itself enabled. If an extension tried to use the contextualIdentities API without the feature being enabled, then method calls would resolve their promises with false.

> From Firefox 57 onwards, if an extension that uses the contextualIdentities API is installed, then the contextual identities feature will be enabled automatically. Note though that it's still possible for the user to disable the feature using the "privacy.userContext.enabled" preference. If this happens, then contextualIdentities method calls will reject their promises with an error message.
