### ISSUE TITLE
"Delay Before Cleaning" doesn't work well

### ISSUE THREAD

**Issue by Primokorn** [mrdokenny/Cookie-AutoDelete#21]
Hi,

I'd like to give 20 seconds before clearing the cookies of a closed tab.
_1 minute is the default value_

* When I put 0.5 the field becomes empty (wrong format)
* When I put 0,5 the new value is saved but the cookies are deleted right after closing the tab. **No delay**.

**Comment by mrdokenny** [comment]
> When I put 0.5 the field becomes empty (wrong format)
Interesting so when you type in 0.5 and click save, the field just disappears? Maybe it's a different character set that you are using that's not compatible with the HTML input field because I don't have this issue.

**Comment by Primokorn** [comment]
Where are you living? The dot may work in your country but not in France.
Is the comma working on your end?

[Here is a video](https://ncloud.zaclys.com/index.php/s/f95rStXWrrWj2VA)

**Comment by mrdokenny** [comment]
> Is the comma working on your end?

No, but I think I found the issue. I had to change where it was creating the timer from parseInt to parseFloat. I validated the change on a fr locale version of Firefox.

**Comment by mrdokenny** [comment]
[Cookie-AutoDelete_Firefox_Dev_051917_1244.zip](https://github.com/mrdokenny/Cookie-AutoDelete/files/1015386/Cookie-AutoDelete_Firefox_Dev_051917_1244.zip)

This is a fresh build off the Development branch. Rename this to .xpi and go to about:debugging and load this extension temporary and see if it fixes for you. :)

**Comment by Primokorn** [comment]
Yeah, fixed! :)
