### ISSUE TITLE
WhatsApp cookies keep being cleaned, even when they're whitelisted

### ISSUE THREAD

**Issue by chiraag-nataraj** [mrdokenny/Cookie-AutoDelete#211]
### Describe the Bug/Feature

I run WhatsApp Web in a "Chats" container (which includes many other sites - Messenger, Slack, RocketChat, Telegram, etc.). I have whitelisted all of their cookies, at least within the "Chat" container. However, upon restart, the WhatsApp cookies (and _only_ the WhatsApp cookies) are cleared and I need to scan the QR code again.

### Steps for anyone to reproduce the bug

1. Set up WhatsApp Web to always launch in a specific container.
2. Go to WhatsApp Web and whitelist the cookies for `web.whatsapp.com`, `*.web.whatsapp.com`, and `*.whatsapp.com` (all of the available options).
3. Log in and verify that it's working.
4. Close the browser and open it again.
5. Note that WhatsApp Web has logged you out.

### Your settings 

- OS/version: Debian sid/experimental
- Browser/version: Firefox 57 beta 9
- Cookie AutoDelete version: 2.0.1

**Comment by ghost** [comment]
`*.whatsapp.net` ?

**Comment by chiraag-nataraj** [comment]
But the cookies are being stored by `web.whatsapp.com`.
![2017-10-27-213843_1366x768_scrot](https://user-images.githubusercontent.com/14947779/32130087-f92cf35e-bb56-11e7-86cb-d5322836e86b.png)
As you can see here, `web.whatsapp.com` is in the whitelist for the "Chats" container.
![2017-10-27-214102_1366x768_scrot](https://user-images.githubusercontent.com/14947779/32130098-2c2d247c-bb57-11e7-9834-ed4290a93dca.png)

**Comment by ke-d** [comment]
Interesting. Does the same thing occur when the extension or auto-clean is disabled?

**Comment by chiraag-nataraj** [comment]
I will test and report back. Also, probably a related issue: if Firefox crashes (e.g. if I forcefully close it by using `kill`) and it goes to session restore, all cookies are cleared, even the ones on the whitelist.

**Comment by chiraag-nataraj** [comment]
It seems to not be an issue if auto-clean is disabled.

**Comment by chiraag-nataraj** [comment]
Hmm. Seems to not be an issue after I disabled and re-enabled auto-clean (just restarted Firefox and the WhatsApp cookies were preserved).

[edit] The issue seems to be back. I presume it won't be an issue if I disable auto-clean, but I'd rather not (since that is the main reason I installed the extension!). It's also weird that no other websites seem to be affected by this, at least as far as I can tell.

**Comment by chiraag-nataraj** [comment]
What's also weird is that I never get a notification about relevant cookies being cleaned (I disabled notifications, but reenabled them for various reasons, this being one of them). So on further thought, I don't think it's the auto-clean doing it. I'm not quite sure what is...

**Comment by efolch** [comment]
FF57 + Win10
Same problem here, and indeed it's weird. If I disable Cookie Autodelete, Whatsapp keeps you logged in, but with Cookie Autodelete enabled, no matter what *.whatsapp.com cookies you whitelist, you get logged out when restarting browser or after sleep/standby the laptop.
It gets weirder: I dumped the FF's cookie storage (" sqlite3 cookies.sqlite .dump >cookies.txt") and there're no Whatsapp cookies in there at all. Neither with or without Cookie Autodelete running. However, they are listed in the GUI as seen in the screenshot from "chiraag-nataraj" above (28-Oct).
Does FF store cookes selectively in storages other than cookies.sqlite? Does Cookie Autodelete play nice with that?

**Comment by efolch** [comment]
Found something that seems to work: whitelist ".web.whatsapp.com", starting with a dot. It should be included in the *.whatsapp.com, but apparently it isn't. Maybe there's a bug in how the regex are parsed?

**Comment by chiraag-nataraj** [comment]
Hmm, I see. I just used https://github.com/jiahaog/nativefier to create an electron app so I don't have to deal with this anymore. There's an additional benefit in that I can restrict it a lot more than I can when it's running inside of my regular browser, and it doesn't have access to any other cookies :slightly_smiling_face:

**Comment by efolch** [comment]
Update: nope, it didn't totally solve the issue. Apparently it works when restarting FF, and after sleep/standby (which didn't work before), but it doesn't keep the whatsapp session logged when changing networks (ie: from home to cafe).

**Comment by ke-d** [comment]
Closing since OP resolved the issue.

**Comment by jay-to-the-dee** [comment]
I am also facing this exact issue. Will try the ".web.whatsapp.com" workaround and report back :)

**Comment by jay-to-the-dee** [comment]
Interestingly enough I am also running Linux like OP (except Ubuntu 16.04 instead of Debian), and now Firefox 60 (so Post Quantum and WebExtensions like OP).  Also this is last tested with Cookie AutoDelete 2.2.0 (should be the latest).

**Comment by chiraag-nataraj** [comment]
It actually works for me now. I basically just whitelisted everything on that page (I have a dedicated profile for chats, etc. now) and I don't have any issues anymore.

**Comment by efolch** [comment]
I never really got a clear idea of what is going on, but finally I succeeded with a config setting that is good enough. I've enabled the "local storage" support, with containers disabled (I don't use them that much). Not sure if any of these things makes any difference.

However waht I think made some difference is that I've greylisted instead of whitelisted whatsapp domains. This makes me read the QR once per FF session, but as that may last days or weeks it's good enough. 

Off-topic: after GDPR, I'm now having problems with slashdot.org. Even when I whitelist or greylist it, and accept the warning and privacy settings, they keep poping up.

**Comment by chiraag-nataraj** [comment]
> Off-topic: after GDPR, I'm now having problems with slashdot.org. Even when I whitelist or greylist it, and accept the warning and privacy settings, they keep pop[p]ing up.

Huh, weird. Possibly need to whitelist another domain as well (slashdotmedia.com?).

**Comment by efolch** [comment]
> Huh, weird. Possibly need to whitelist another domain as well (slashdotmedia.com?)

Dunno. Developer tools doesn't show any cookie outside slashdot.org, and if I enable uMatrix to see what's going on, the GDPR message is not shown at all.
