### ISSUE TITLE
In about:blank, "clear all cookies for this domain" deletes all cookies

### ISSUE THREAD

**Issue by tummychow** [mrdokenny/Cookie-AutoDelete#212]
### Describe the Bug/Feature

In about:blank, "clear all cookies for this domain" will actually delete all your cookies, including the ones on the whitelist. Which kind of makes sense, since an empty url would match all TLDs, but it feels like an unnecessary footgun to me. I think noop would be more natural behavior.

### Steps for anyone to reproduce the bug

1. navigate to about:blank
2. in that tab, open cookie autodelete and "clear all cookies for this domain"

### Your settings 

- active mode on with 1min delay
- show cookies for active domain
- clean cookies from open tabs on startup
- enable check for subdomains

My whitelist is just github.com and reddit.com. I don't use containers.

- OS/version: arch linux
- Browser/version: 55.03 x64
- Cookie AutoDelete version: 1.4.4

**Comment by ghost** [comment]
Why Firefox 55 and why CAD 1.4.4?

I cannot confirm on Fx57, CAD 2.0.1

**Comment by ke-d** [comment]
Can't reproduce either on Fx 58 and C-AD 2.0.1.

>Why Firefox 55 and why CAD 1.4.4?

I set the min version to C-AD 2.X.X to 56.

**Comment by tummychow** [comment]
Ah, if it's already been fixed in a newer version then I'll wait for the update. Thanks.
