### ISSUE TITLE
Automatic Cleaning 1 minute delay not consistent.  Sometimes cookies cleared immediately.

### ISSUE THREAD

**Issue by gopherit** [mrdokenny/Cookie-AutoDelete#213]
I have the Automatic Cleaning set to 1 minute.  Sometimes when I close a tab, cookies for that tab's domains are _immediately_ deleted.  Other times they are deleted within 5-10 seconds, but definitely not 60 seconds.

- OS/version:  Windows 7 SP1 64-bit
- Browser/version:  Firefox 57b12 64-bit
- Cookie AutoDelete version:  2.0.1

**Comment by ke-d** [comment]
Are you sure you didn't close a tab 1 min prior to closing another tab _making_ it seem instantaneous? A lot can happen in that one min especially with active opening and closing and it depends on how you perceive it.

Also, this issue doesn't have reproduce steps so I can't do anything about it.

**Comment by gopherit** [comment]
It's difficult to reproduce the issue, so my apologies.  I have noticed something similar to what you describe though.  Let's say I have many tabs open:  Website A, Website B, Website C in Tab A, Tab B, Tab C.

Let's say I close Tab A for Website A.  And 30 seconds later I close Tab B for Website B.  My expectation is that the cookies for Website A will be deleted after 1 minute of closing Tab A, and the cookies for Website B will be deleted after 1 minute of closing Tab B.

But for some reason, I notice that cookies for _both_ Website A and Website B are deleted at the same time instead of 1 minute after their respective tabs are closed.

**Comment by ke-d** [comment]
Ah yes. How cleanup works is that it takes a "snapshot" of all open domains at the time of cleanup. So if you closed website A, waited 55 secs, then closed website B and C, at 60 secs, all cookies from A, B, C get deleted regardless of the individual tab close since the delay timer only started ticking after the first tab close.

**Comment by gopherit** [comment]
I understand now, thanks.  So there's currently only one delay timer instead of delay timers that take a snapshot of each tab?  Maybe a future enhancement?  =)

Thanks for explaining it.

**Comment by MarkRH** [comment]
Ahh.. I wondered if something like this was going on.

**Comment by ke-d** [comment]
I'm going to wontfix this one since the added complexity is not worth potential debugging since I'm using 2 separate timers APIs (WebExtension Alarm API and setTimeout Web API).
