### ISSUE TITLE
[UX] Purpose of input box in whitelist settings unclear

### ISSUE THREAD

**Issue by rugk** [mrdokenny/Cookie-AutoDelete#214]
### Describe the Bug/Feature
I can input anything into the search, it does not show me anything. Neither an error nor a result.
No error shown in the F12 console.

BTW, you should improve the UX here:
* When the search fails, an error/… should be shown to the user.
* There may be a search button. You cannot expect anyone (especially touch users 😉 ) to press the enter key in that field

### Screenshot in which the bug can be seen

Video here: 
[cookiedel.zip](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/files/1425523/cookiedel.zip)

### Steps for anyone to reproduce the bug
Enter something into the search field in the settings.

### Your settings 

- OS/version: Fedora 26
- Browser/version: Firefox 56
- Cookie AutoDelete version: 2.0.1

**Comment by ke-d** [comment]
That's not a search field. That's an input box to enter sites to the greylist/whitelist. You already made an issue about it in #120

**Comment by rugk** [comment]
Ahh, right. Should have remembered that one… so git it wrong the second time. Especially as the input still only shows a domain name etc. as a placeholder…

That thing is clearly an UX issue. Even when you want to keep the functionality (for now), it should show some user feedback, when the domain has been added, so the user knows (what/) that something happened.

**Comment by chiraag-nataraj** [comment]
But the added domain shows up below in the whitelist/greylist area...

**Comment by rugk** [comment]
You only see it if you have less than, say, 10 entries. Because it (naturally) does not scroll down, when you add the domain.

**Comment by chiraag-nataraj** [comment]
I guess one easy fix is putting the most recent entries on top?

**Comment by ke-d** [comment]
Closing as I will probably do #120 or some form of it *eventually*
