### ISSUE TITLE
Deletes cookies of whitelisted pinned subdomain/tab/port

### ISSUE THREAD

**Issue by rugk** [mrdokenny/Cookie-AutoDelete#215]
### Describe the Bug/Feature

I have a domain (https://)`sub.domain.example:8080`, which is pinned to Firefox, so that the tab is shown at the start.
The problem could be related to the fact:
* that it is not using (one of the) the default port
* it is a pinned tab
* it is a subdomain(?)
* it is an internal LAN-service(?)

I have whitelisted the item `*.sub.domain.example` and `sub.domain.example`, as this is what the addon recommends/shows in the popup. I have even manually whitelisted `sub.domain.example:8080` trying to mitigate this bug.

### Steps for anyone to reproduce the bug

1. Visit such a site.
2. Try to set it on the whitelist.

### Your settings 

- OS/version: Fedora 26
- Browser/version: Firefox 56
- Cookie AutoDelete version: 2.0.1

Container tabs are enabled, only tested in default container.

**Comment by ke-d** [comment]
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/cookies/Cookie

Compare your cookie domain/host to what you have it on the whitelist.

**Comment by rugk** [comment]
Hmm… what should I use the API doc there for? I don't know how you use it, so…

**Comment by ke-d** [comment]
@rugk Is this still a problem?

**Comment by rugk** [comment]
I think no, did not experience it again.

**Comment by gcb** [comment]
This is the only mention of non-standard ports. I'm assuming from my observations using the extension that adding a host/ip without port will affect all ports, correct?
