### ISSUE TITLE
FF57beta12, v2.0.1: Not Counting Cookies at Twitch.tv

### ISSUE THREAD

**Issue by MarkRH** [mrdokenny/Cookie-AutoDelete#218]
### Describe the Bug/Feature
Noticed when I went to twitch.tv that the cookie counter on the button is 0 even though it does delete the 17 cookies or so when I leave the tab.  It also doesn't count them if I whitelist *.twitch.tv.  Actually, this only happens in the **Beta** Twitch version. The non-beta does show the cookie count.

### Screenshot in which the bug can be seen

https://i.imgur.com/Td8yqkl.png

### Steps for anyone to reproduce the bug

Go to https://go.twitch.tv/ and view the Beta mode.

### Your settings 
- OS/version:  Windows 7 Pro 64bit
- Browser/version: Firefox 57beta12
- Cookie AutoDelete version: 2.0.1

**Comment by ke-d** [comment]
I believe the beta twitch is using localstorage now.
