### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Exatice72** [mrdokenny/Cookie-AutoDelete#219]
I am unable to install this plugin!
With Android and Firefox 56 (the newest to date) and the plugin requires Firefox 57...
![noinst](https://user-images.githubusercontent.com/33261338/32235061-bb643f54-be5e-11e7-92f4-9d548c5618e5.jpg)

**Comment by ke-d** [comment]
Please read the description. C-AD on FF Android does require 57 because of certain APIs.
