### ISSUE TITLE
Plan about Firefox forks and bug cookie exeception aren't saved 

### ISSUE THREAD

**Issue by WagnerGMD** [mrdokenny/Cookie-AutoDelete#221]
`ResumeMessageError = "CookieAutoDelete could not be installed because it isn't compatible [...]"`

Hello,

as you can guess, I had just try the installation and the result was a failure with **Waterfox** and **Cyberfox** (under Windows 10_x64_v1607). Because for now, I will assume it can't be.
Then I'm wonder do you have any plan ?

The trouble concern **CookieAutoDelete_v2.0.1** and the previous one too (called **CookieAutoDelete_v2.0.0**).

**About exception :**
First of all, the cookies are block and that's why I need a **ExceptionList**.
Despite the **WhiteList** and the **GreyList**, there is one trouble related to CookieAutoDelete. Because as for now, it can't add any website to list **Cookie Exception.** (yes empty and you can check that on the page : **about:preferences#privacy** via the button **Exceptions...**)
At the contrary; it works perfectly fine with another addon (such as [CookieKeeper_v1.9.3.1 ](https://addons.mozilla.org/en-US/firefox/addon/cookiekeeper/#desktop) just to give one example). Then it will be nice if you can correct the trouble or add new list.

Kind regards.

**Comment by ke-d** [comment]
It all depends on whether the required APIs exists on those forks.

**Comment by WagnerGMD** [comment]
And what about the **ExceptionList** ? You didn't answer to that part (it isn't related to them but only Firefox).

**Comment by WagnerGMD** [comment]
Do we have to send one request to Mozilla ? (Which mail adress ?) Because the WebExtensions doesn't purpose one API ? That's why you can't made (for now) one **ExceptionList** ?
Unless you had forgot to answer ?

**PS :** Because the list (Exceptions cookies) stay empty (and yes even with Cookie-AutoDelete_v2.1.0).
As reminder, you can check it with the button **Exceptions...** on the page **about:preferences#privacy**

**Comment by ke-d** [comment]
@WagnerGMD CAD maintains it's own whitelisting as there's no API currently that can access the Exception page under about:preferences#privacy

**Comment by WagnerGMD** [comment]
Thank you @mrdokenny that's a clear answer.  Do you know Mozilla plan ? Did they announced an date for such API ?
With a little pressure, I imagine Mozilla will understand they need to correct it. Because for the people, it could be true : that's a huge lack. That's why the people will wait a long time until they finally migrate to Firefox Quantum (to resume, at this moment the WebExtensions aren't yet ready or too limited)

**Comment by ke-d** [comment]
@WagnerGMD I think the closest access to the Exception list is the [contentSettings ](https://developer.chrome.com/extensions/contentSettings)API which exists in Chome but not in Firefox yet.

**Comment by WagnerGMD** [comment]
Do you believe : it's perhaps possible to import this **contentSettings** API in Firefox ?

Unless there is one Chrome addon which wiil be compatible with Firefox too ? Now the both are supposed to be **WebExtensions**. But it can't done at this moment (lot of issues or limits, etc), right ?

What about the latest (**Firefox_v59** or **Firefox_v60**) ? I'm wonder if Mozilla has provided the missing API ? Otherwise, can we ask (or request) a new API ? Sorry I had forgot the mail adress (Which artiche ? Where ? When ? etc)....

**Comment by ke-d** [comment]
@WagnerGMD Look at #43

**Comment by WagnerGMD** [comment]
**Just one reminder :**
```
lockPref("network.cookie.cookieBehavior",2);
lockPref("network.cookie.lifetimePolicy",2);
```
I had take a look @mrdokenny but for me, it's too much... and it has been a long while (almost 3 months and I didn't count the time before (that's the worst : because **Firefox_v57** was published almost 8 months ago)).
 
Then I'm wonder :
- as today, could you resume the situation ?
- there is any improvements with the latest **Nightly** (aka **Firefox_v62**) ?
- the **ExceptionList** was forgotten or frozen ?
- it's possible finally to replace **CookieKeeper** ?
- unless the API is still missing ? They work on it ?
- can we do something to get another API and another addon(s) ?
- Mozilla need's a report (feedback, pressure, complaints, etc) ?
- what about Chrome ? There is one addon ? There is another way to process ?
- any plans about **Cookie-AutoDelete** ? Even in the futur ?

At least, it would be nice if you can search and help to clarify the current state. **To resume, what's the Mozilla opinion on this subject ?**
