### ISSUE TITLE
How to turn off notification window

### ISSUE THREAD

**Issue by odiasodias** [mrdokenny/Cookie-AutoDelete#226]
### Describe the Bug/Feature

There is no way to turn off that annoying notifications window!

### Your settings 

- OS/version: 
- Browser/version: 
- Cookie AutoDelete version:

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/886325/32493990-2d99b7a0-c3c0-11e7-853c-d5b1e3e06604.png)

**Comment by odiasodias** [comment]
Thank You very much




Get Outlook for Android

**Comment by tkoham** [comment]
THese should really, really be off by default.

**Comment by odiasodias** [comment]
I agree...




Get Outlook for Android







On Thu, Nov 9, 2017 at 4:30 AM +0000, "tkoham" <notifications@github.com> wrote:












THese should really, really be off by default.

**Comment by chiraag-nataraj** [comment]
Nah - notifications are helpful when you're trying to debug, which is most of us when we first start using this addon.

**Comment by ke-d** [comment]
>Nah - notifications are helpful when you're trying to debug, which is most of us when we first start using this addon.

Yes, otherwise how else would you know that it's working properly other than looking in the native cookie manager.
