### ISSUE TITLE
default settings on initial (first-time) install

### ISSUE THREAD

**Issue by r0flm4k3r** [mrdokenny/Cookie-AutoDelete#228]
### Describe the Bug/Feature

After I installed this add-on in Firefox (was prompted as a suggestion, since I was using SelfDestructingCookies, which is no longer maintained), the default was "Disabled". 

Expected to be Enabled by default, and in fact, the documentation supports this expectation -- documentation states "Enabled" is the default setting.

For that matter, hitting the "Restore defaults" button, also resets it to "disabled".

### Screenshot in which the bug can be seen

<img width="1268" alt="screen shot 2017-11-07 at 5 29 44 pm" src="https://user-images.githubusercontent.com/960282/32523606-a4384b8a-c3e1-11e7-8bae-780c5e924335.png">

### Steps for anyone to reproduce the bug

How it happened for me: Using Firefox, installed Cookie-AutoDelete for the first time. 

### Your settings 

- OS/version: MacOS Sierra 10.12.6
- Browser/version: Mozilla Firefox 56.0.2 (64-bit)
- Cookie AutoDelete version: Cookie AutoDelete 2.0.1

**Comment by ke-d** [comment]
https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/FAQ:-Common-Questions-and-Issues#why-is-active-mode-off-by-default
