### ISSUE TITLE
Can't change Settings -- just brings up Welcome web page

### ISSUE THREAD

**Issue by tparker24** [mrdokenny/Cookie-AutoDelete#229]
### Describe the Bug/Feature

I wanted to turn off the Notifications window, so I clicked on Settings, but it just brings up a Welcome web page.

### Your settings 

- OS/version:  Windows 7
- Browser/version:  Firefox 56.0.2
- Cookie AutoDelete version:  2.0.1

**Comment by ghost** [comment]
Try this button if menu is not visible:
![image](https://user-images.githubusercontent.com/886325/32581012-7252bb8e-c4e8-11e7-848d-44b19b006621.png)

**Comment by tparker24** [comment]
Thanks, but I don't see that button.  Here's what I see in Firefox:

![button](https://user-images.githubusercontent.com/33501387/32583348-673090a6-c4b0-11e7-8670-1bfcc0c4805f.jpg)

And when I click on Settings, it just brings up a Welcome web page.

**Comment by tparker24** [comment]
Aha!  I see that button now ... it's on that Welcome page!   Way up in top left corner.  Not labelled or anything, so I never really noticed it.

Anyway, thanks for steering me in the right direction!
