### ISSUE TITLE
Download failure

### ISSUE THREAD

**Issue by DrBartolo** [mrdokenny/Cookie-AutoDelete#230]
I have a really simple issue - I cannot get the addon in the first place!  Over the last few days, on different PCs and laptops, all I get is:

The addon could not be downloaded because of a connection failure

Any idea what is going on or when this will no longer happen?

**Comment by CraigS26** [comment]
Happens to me with Every 57 App; Gingerbread Man in FF Forum enlightened me as follows:
Rt Clk on "Add to Firefox" link and Select "Save Link As" (dnloaded to my desktop);
Open "Manage Your Addons"/ Clk Cog button by Search/ Clk "Install Addons from File" .... Browse to saved Dnload and Dbl-Clk on it/ Works every time.

**Comment by DrBartolo** [comment]
That did work for me - eventually!  I had to install the addon in safe mode though otherwise it still refused to load.
