### ISSUE TITLE
Evernote web fails to load when using this plugin.

### ISSUE THREAD

**Issue by DanielJMaxwell** [mrdokenny/Cookie-AutoDelete#231]
### Describe the Bug/Feature
If you go to Evernote.com and log in, you get a blank page. It happens whether or not evernote.com and *.evernote.com are whitelisted.

### Screenshot in which the bug can be seen
It's a blank page.

### Steps for anyone to reproduce the bug
Go to evernote.com. Log in. 

### Your settings 

- OS/version: 
Windows 7
- Browser/version: 
Firefox 56.0.2
- Cookie AutoDelete version: 
2.0.0

**Comment by chiraag-nataraj** [comment]
Works for me:
![2017-11-09-075918_1366x768_scrot](https://user-images.githubusercontent.com/14947779/32606601-ef03045a-c523-11e7-812e-c446f713573b.png)
Can you describe any other addons you have installed?

[edit] Just for the record, I only disabled uMatrix to get this to work. I didn't need to disable Cookie AutoDelete or change my defaults (actively clean anything that isn't being used or in one of the whitelists).

**Comment by ghost** [comment]
May be browser bug. Should work in 57.

**Comment by DanielJMaxwell** [comment]
The only add-on that seems to make a difference is the self-destructing cookies addon. When it's installed the Evernote page works, when not installed, it doesn't. Regardless of whether Cookie Auto-Delete it installed. 

It looks like this may be due to some garbage the self-destructing cookies add-on is leaving behind, so possibly not a Cookie Auto-Delete issue after all. I'm closing the issue.
