### ISSUE TITLE
"Clear cookies for this domain" button does nothing

### ISSUE THREAD

**Issue by wodim** [mrdokenny/Cookie-AutoDelete#232]
- OS/version: Windows 10
- Browser/version: Firefox 58.0b1 
- Cookie AutoDelete version: 2.0.1

**Comment by ke-d** [comment]
Need more information as this is not a complete bug report.

**Comment by wodim** [comment]
Okay. Steps to reproduce:

1. Open a webpage

2. Click on the Cookie AutoDelete button in the toolbar

3. Click "Clear cookies for this domain"

4. Reload webpage. Cookies have not been cleared

**Comment by ke-d** [comment]
Any specific websites?

**Comment by wodim** [comment]
All

**Comment by wodim** [comment]
https://i.imgur.com/WWy1VzZ.gifv

**Comment by ke-d** [comment]
I see now. Look at #75
