### ISSUE TITLE
Clicking 'Edit expression' should focus for text input

### ISSUE THREAD

**Issue by ghost** [mrdokenny/Cookie-AutoDelete#234]
### Describe the Bug/Feature

When I click the Edit expression button, I have to manually click the domain input box afterwards. It should focus the keyboard unto the domain input automatically

### Your settings 

- OS/version: GNU/Linux
- Browser/version: Firefox 56
- Cookie AutoDelete version: 2.0.1

**Comment by ke-d** [comment]
Resolved in #295
