### ISSUE TITLE
Web browser keep sending notifications while I'm not logged in Twitter   

### ISSUE THREAD

**Issue by semente** [mrdokenny/Cookie-AutoDelete#236]
twitter.com isn't whitelisted or greylisted but I'm still receiving web browser push notifications related to my account. I guess the push notification mechanism don't use session cookies or can be used to track you around, otherwise, should Cookie-AutoDelete erase notification sessions too?

### Steps to reproduce the bug

- Login to Twitter
- Make sure twitter.com isn't on white and grey lists if it is the case
- Allow web notifications
- Logoff from Twitter, close Twitter tabs, close/reopen the browser, whatever...
- If you are mentioned or whatever notification Twitter sends, the browser will notify you

### Settings 

- OS/version: Debian GNU/Linux 9
- Browser/version: Firefox 57 (beta channel)
- Cookie AutoDelete version: 2.0.0

**Comment by ke-d** [comment]
I think that might be a Service Worker in `about:serviceworkers` so it's not something CAD can remove.

**Comment by semente** [comment]
Yea, probably... I will close this issue.
