### ISSUE TITLE
Cookie auto delete delay in seconds

### ISSUE THREAD

**Issue by ItsOnlyBinary** [mrdokenny/Cookie-AutoDelete#241]
please put cookie auto delete delay into seconds to allow finer control.

**Comment by ke-d** [comment]
https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/73#issuecomment-311493047

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/alarms/create#Parameters

> On Chrome, unless the extension is loaded unpackaged, alarms it creates are not allowed to fire more than once per minute. If an extension tries to set delayInMinutes to a value < 1, or when to a value < 1 minute in the future, then the alarm will fire after 1 minute. If an extension tries to set periodInMinutes to a value < 1, then the alarm will fire every minute.

Despite this limitation on Chrome, using the API is the only thing that's consistent across browsers. Using any other method such as setTimeout in an extension's background page is not guaranteed beyond maybe ~10 seconds and up.

**Comment by ItsOnlyBinary** [comment]
oops i did do a quick search for similar questions but forgot to search closed too :( my bad...

if this isnt a limitation on FF would setting 0.1 be valid? (im not having a good day.. found my answer)

Thanks for quick reply.
