### ISSUE TITLE
Unable to export expressions

### ISSUE THREAD

**Issue by aesthicc** [mrdokenny/Cookie-AutoDelete#242]
### Describe the Bug/Feature
"Export Expressions" loads blank screen: moz-extension://b9b4a118-e605-9a40-beae-daf70c58b8ef/settings/settings.html#tabExpressionList

Navigation to toplevel data: URI not allowed (Blocked loading of: “data:text/plain;charset=utf-8,{
  "defau...”)
ContentRestore.jsm:242:8

- OS/version: macOS 10.13
- Browser/version:  Firefox 58
- Cookie AutoDelete version: 2.0.0

**Comment by xeonchen** [comment]
Would you try Firefox 59 and see if it has been fixed?
I had the same issue before, but it works perfectly on my Nightly (59.0) now.

**Comment by ke-d** [comment]
Should probably try a new profile as it works here.
