### ISSUE TITLE
Container Tabs can't be disabled in FF57

### ISSUE THREAD

**Issue by xenopeek** [mrdokenny/Cookie-AutoDelete#245]
Regardless of the "Enable Support for Firefox's Container Tabs" setting on the Cookie Settings page, Firefox enables Container Tabs when Cookie AutoDelete is installed. Container Tabs can't be disabled while Cookie AutoDelete is enabled.

In Firefox' Preferences the setting "Enable Container Tabs" gets locked to enabled and is greyed out with the notice: 

> An extension, Cookie AutoDelete, requires Container Tabs.

Disabling Cookie AutoDelete immediately unlocks the "Enable Container Tabs" setting.

Could the need for Container Tabs be made optional?

- OS/version: Arch Linux 64-bit
- Browser/version: Firefox 57.0
- Cookie AutoDelete version: 2.0.1

**Comment by zzzeek** [comment]
this issue is very inconvenient b.c. now I'm forced to have "open in new container tab" in my context menu

**Comment by French77** [comment]
> Could the need for Container Tabs be made optional?

The choice to use the option would indeed be neat

> Support for Container Tabs (Firefox 53+ Only)

I doubt if this function is only valid for or from,i'm not sure :)

`about:config` 
Settings:
![Screenshot](https://i.imgur.com/q2ZV7kd.png"Screenshot")


- OS/version Sonya Mint 18.2 Cinnamon 64-bit

- Browser/version:Firefox Quantum 57.0

-  Cookie AutoDelete version: 2.0.1

**Comment by ghost** [comment]
This is indeed bothering for anyone who wishes to **not** use the Container feature and who has set about:config (or via user.js) settings accordingly.

What I don't understand is that Cookie-Autodelete fixes itself to Container _**regardless** of the "Enable Support for Firefox's Container Tabs"_ setting on the Cookie Settings page.

Generally speaking I dislike an extension overlapping a user's choices when it is not stricto sensus required by the extension, especially when the extension provides a setting understood as avoiding it ("Enable Support for Firefox Container Tabs").

I truly appreciate Cookie-Autodelete, runs flawlessly, smartly thought and designed, but I'd wish it leave alone my choice regarding the Container settings. Whatever I write in my user.js file regarding privacy.usercontext.* it is systematically overwritten by Cookie-Autodelete on Firefox start. Please do remove this overwriting provided of course that the user has unchecked the extension's "_Enable Support for Firefox's Container Tabs_" option.

**Comment by ke-d** [comment]
Depends on #152
