### ISSUE TITLE
Delete cookies and localstorage on tab close

### ISSUE THREAD

**Issue by iinc** [mrdokenny/Cookie-AutoDelete#246]
Self-Destructing Cookies had this feature but it is now a legacy extension and Cookie-AutoDelete was recommended as a replacement.

"Gets rid of a site's cookies and LocalStorage as soon as you close its tabs."

**Comment by chpio** [comment]
https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/44

**Comment by ke-d** [comment]
Duplicate of #44
