### ISSUE TITLE
Import BkUp - Lost White List Cookies No-Show in FF 57 List

### ISSUE THREAD

**Issue by CraigS26** [mrdokenny/Cookie-AutoDelete#247]
Win 7-64 Hm Prem/ FF 57(64) / Ckie AD Ver 2.0.1

Moderate Expertise.....
ALL my Whitelist Cookies and some Gray Listed somehow disappeared in List of Expressions and I easily Imported a Saved .json BkUp  to L of Expr - Except - the Restored White Listed Cookies didn't appear back in FF 57 Options/ Prv & Sec/ SHOW Cookies Module. 
Problem is I Can't recall IF I Closed the Browser Session first and Then Looked, BUT (to be sure) what is required to get the Whitelist Cookies back into the FF 57 Cookie List via Imported BkUp?

**Comment by ke-d** [comment]
You need to use the template if it's a bug and provide more info or else I can't reproduce.
