### ISSUE TITLE
difference between firefox chrome for protected cookies

### ISSUE THREAD

**Issue by rezad1393** [mrdokenny/Cookie-AutoDelete#248]
when I use addon editthiscookie in firefox and protect and cookie then use cookie-autodelete to remove cookies , that protected cookie remains.
but if firefox that cookie also get deleted.
is it firefox-vs-chrome related or is it this addon issue?

I wanted it to remain not deleted (chrome behavior).

**Comment by ke-d** [comment]
I'm just using the delete cookies API, so if there is a difference, it's probably a difference with FF vs Chrome.
