### ISSUE TITLE
Optional subdomain-specific cookie protection settings

### ISSUE THREAD

**Issue by practik** [mrdokenny/Cookie-AutoDelete#249]
As far as I can tell, cookie protection currently works on a domain basis:  If I open `subdomain-a.example.com` and `subdomain-b.example.com` in two different tabs, no cookies from `example.com` or any of its subdomains get deleted until I close both tabs.

Most of the time that's great, I wouldn't want it any other way.  But sometimes it would be nice if I could set CAD to delete all the cookies from `subdomain-a` even though I still have `subdomain-b` open.  A typical case for me is:  I'm working on a file in Google Docs in one tab and doing Google searches in another.  After I close the Google Docs tab, if I want to make its cookies go away, I have to either close the search tab or manually remove the cookies.

Would it be possible to add this functionality?  (Or is it already possible and I just can't see how to do it?)

**Comment by ke-d** [comment]
I tried this in development of before v1.0 and found that it broke a couple of the websites that I use (logged out of sites). So now the algorithm protects `*.example.com`'s cookies if you have any of the example.com and it's subdomains open in a tab. Try turning on `Clean Cookies from Open Tabs on Startup`

**Comment by practik** [comment]
`Clean Cookies from Open Tabs on Startup` is not a solution here – that would require me to restart the browser to clear the unwanted cookies, which is even more of a hassle than closing extra tabs or manually deleting cookies.

I agree that subdomain-specific cookie protection/deletion doesn't make sense as a default approach, but I was asking whether it could be added as an option that users could choose for specific websites. I hope you'll still consider that request.

If not, I _think_ I can achieve what I want by using Container Tabs, but at the moment I can't test it because of #256.

**Comment by practik** [comment]
Looks like Containers is not the solution either :-(  I've opened #262 to address this.

**Comment by wagnerand** [comment]
Could you reconsider re-opening this? I'd love to have subdomain matching for open tabs checking as well.
