### ISSUE TITLE
Keep all and clean specific

### ISSUE THREAD

**Issue by DirkNie** [mrdokenny/Cookie-AutoDelete#251]
Hi,
it would be nice to be able to keep all cookies, but delete some specific once. Like it was possible in the AddOn selectivecookiedelete. I need this for my Zimbra eMail account, to get the login every FF startup.

May be it is possible in the actual version. But I did not find out the configuration for that. 
When I put "*" in whitelist the gray list entries will not be processed anymore.
May be a order function for the enties would be the solution.

TIA
  Dirk

**Comment by ke-d** [comment]
I don't think can support this usecase since it is completely different to what C-AD is (codebase wise) and it would require a significant rewrite.
