### ISSUE TITLE
FF57 unable to delete expressions

### ISSUE THREAD

**Issue by bbw22** [mrdokenny/Cookie-AutoDelete#258]
### Describe the Bug/Feature

In the CAD settings -> list of expressions: unable to delete expressions. The trash can icon is there. When you mouse over it a popup shows "remove expression", icon changes color when moused over. However, clicking the icon does nothing.

### Steps for anyone to reproduce the bug

add expressions via the drop down when at a site
Open settings.
click list of expressions
(try to) delete an existing expression

### Your settings 

see attached image for settings
![cad-settings](https://user-images.githubusercontent.com/33813590/32995327-505205fa-cd38-11e7-98aa-9b34f73b084f.png)

- OS/version: macOS 10.13.1
- Browser/version: FireFox 57.0
- Cookie AutoDelete version: 2.0.1

**Comment by ElectricFeet** [comment]
Strange. I have the exact same OS/Browser/C-AD versions, but cannot reproduce this (with those C-AD settings, or my own different settings).

What are your FF cookie settings ? Did you import the expressions or insert them manually?

**Comment by bbw22** [comment]
All expressions were created from the plugin/icon on the toolbar. If that is what you mean by manual.

FF cookie settings are attached
![cad-ff-cookie-settings](https://user-images.githubusercontent.com/33813590/33055834-b16de2cc-ce47-11e7-9400-161ed330fa8b.png)

And actually the expression wouldn't delete with the previous FF version (56.0.2). I thought it was another addon conflicting. When I restarted FF after removing that other addon (NoScript) it upgraded to FF 57, and I still couldn't remove the expression.

**Comment by practik** [comment]
I can't reproduce this either, and my versions are the same as yours too, except I'm on macOS 10.12. My CAD and FF cookie settings are a bit different, but when I set them to be the same as yours I still have no problem deleting expressions.

There's one FF cookie setting that doesn't show in your screenshot, though I'm not sure it's relevant: In your history clearing settings, are cookies set to be cleared when Firefox closes?

**Comment by bbw22** [comment]
I finally got the expression to delete. Since the edit button worked I tried to edit to see what would happen. Edited the expression by adding 3 spaces at the end. Saved it. Decided to see if deleting would work. The expression deleted!

practik, the reply I put in here a couple of days ago didn't happen. Please see the settings you were looking for. 


![ff-cookie-custom-settings](https://user-images.githubusercontent.com/33813590/33218711-fed6d352-d103-11e7-9dcb-707411a754f7.png)

**Comment by BondiBear** [comment]
same problem with FF57.0.2.

the edit/delete workaround works for now.

**Comment by ke-d** [comment]
I can't reproduce it either, but the issue seems to be resolved.

**Comment by bbw22** [comment]
Using FF 57.0.3 and Cookie Auto Delete 2.0.1 cannot delete an expression added via the drop down. Forced to use the edit workaround to delete the expression.
