### ISSUE TITLE
Documentation / Restore defaults conflict

### ISSUE THREAD

**Issue by ElectricFeet** [mrdokenny/Cookie-AutoDelete#260]
### Describe the Bug/Feature
Documentation says:

> **Enable Automatic Cleaning**
> - Disabled: Extension can be used manually with the popup buttons.
> - Enabled: This is Self Destructing Cookies **default mode** [my bold]. Automatic Cleaning happens on tab close.

However, C-AD Settings > Cookie Settings > `Restore Default Settings` button _disables_ Automatic Cleaning. So they are in conflict. 

I suggest that `Restore Default Settings` button should _enable_ Automatic Cleaning.

p.s. I've posted a few times, without thanking you for your efforts on this. Thanks! Any more help I can give &mdash; on the documentation side or the UI/UX side (not the coding side, sadly) &mdash; let me know.

**Comment by ke-d** [comment]
What I meant is that SDC has auto-clean as default on install. CAD will not have it as default because of https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/FAQ:-Common-Questions-and-Issues#why-is-active-mode-off-by-default

**Comment by ke-d** [comment]
I removed that part, so it shouldn't be in conflict anymore. :)
