### ISSUE TITLE
Support Removal Of Zombie and Flash Cookies

### ISSUE THREAD

**Issue by zero77** [mrdokenny/Cookie-AutoDelete#261]
Can you please add support for the removal of some other types of cookies like zombie and flash cookies.
Thanks

**Comment by ke-d** [comment]
https://addons.mozilla.org/en-US/firefox/addon/clear-flash-cookies/

Might as well not reinvent the wheel since all you can do with the API at this point since there's no clear by hostname.

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/browsingData/removePluginData

**Comment by zero77** [comment]
Thanks for your response but, what about zombie cookies.
en.wikipedia.org/wiki/Zombie_cookie

**Comment by ke-d** [comment]
I think these are the cookies in `SiteSecurityServiceState.txt`? If so, delete all the contents and make it read-only.

**Comment by zero77** [comment]
> A zombie cookie is an HTTP cookie that is recreated after deletion. Cookies are recreated from backups stored outside the web browser's dedicated cookie storage.

They can be stored in different locations, I think the above is a good explanation of what they are, as it’s a generalised term.

Also, there’s **some** examples of the storage they use hear.

https://en.wikipedia.org/wiki/Zombie_cookie

**Comment by davidhedlund** [comment]
@mrdokenny 
* The WebExtention [https://addons.mozilla.org/en-US/firefox/addon/self-destructing-cookies-1/?src=search](https://addons.mozilla.org/en-US/firefox/addon/self-destructing-cookies-1/) is used to remove zombie cookies. Can you reuse the source code from it?
* Can you please add the term "Zombie cookie" and "" to https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/FAQ:-Common-Questions-and-Issues#what-is-the-state-of-the-webextension-api-to-clean-x-data ?

**Comment by davidhedlund** [comment]
@mrdokenny 
* The WebExtention [Self Destroying Cookies ](https://addons.mozilla.org/en-US/firefox/addon/self-destructing-cookies-1/) is used to remove zombie cookies.
* The WebExtention [Clear Flash Cookies ](https://addons.mozilla.org/en-US/firefox/addon/clear-flash-cookies/) is used to remove Local shared objects (LSOs), commonly called (Flash cookies).


Can you reuse the source code from them?

**Comment by davidhedlund** [comment]
https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/406
