### ISSUE TITLE
Make it compatible with first-party isolation

### ISSUE THREAD

**Issue by Homme-Nuage** [mrdokenny/Cookie-AutoDelete#266]
First-party isolation is described [here](https://www.ghacks.net/2017/11/22/how-to-enable-first-party-isolation-in-firefox/)

It looks like a very useful feature, but there's a conflict with Cookie Autodelete which prevents it from deleting first-party cookies. 

Is it possible to fix this? 

My settings:

- OS/version: Windows 7 service pack 1
- Browser/version: Firefox 57
- Cookie AutoDelete version: 2.0.1

**Comment by solracsf** [comment]
WebExtension API cookie (used by the extension) is **not** compatible with `privacy.firstparty.isolate`

**Comment by Homme-Nuage** [comment]
Ok. It seems the problem comes from Firefox and will be fixed eventually.

**Comment by Omen-of-Peace** [comment]
For reference:
Meta FPI bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1299996
Cookie add-ons bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1381197

(links provided by user Brainfart in the comments of the GHacks article)

**Comment by Homme-Nuage** [comment]
Yeah, I had read his/her comment.

**Comment by solracsf** [comment]
Should be ok in Firefox 58: https://hacks.mozilla.org/2017/11/new-in-firefox-58-developer-edition/

> Access brand new website privacy controls like first-party isolation and fingerprinting resistance, added as part of the ongoing Tor Uplift.

**Comment by Homme-Nuage** [comment]
Nice.

**Comment by haarp** [comment]
Seems to be a dupe of #75

**Comment by ke-d** [comment]
Duplicate of #75
