### ISSUE TITLE
Add lifetime setting

### ISSUE THREAD

**Issue by gmariani** [mrdokenny/Cookie-AutoDelete#267]
There was a legacy plugin called Cookie Time ( https://addons.mozilla.org/en-US/firefox/addon/cookie-time/ ) which I used up until FF57 came out. Unfortunately the developer didn't update it to a WebExtension. I much preferred that style of managing cookies to your method. Instead of deleting cookies automatically after a tab close, it deleted cookies after they reached a certain age. Could you add this kind of feature? I don't want to have to figure out what cookies i want whitelisted, or greylisted, or have them be deleted too soon. If i could just set them to expire after 2 weeks if they aren't used that would be perfect. No setting or thinking required. They just go away if not used.

**Comment by ke-d** [comment]
Sounds like you need a different extension than CAD. IMO, it should be possible to do as a WebExtension.
