### ISSUE TITLE
Whitelist simple host names / .local hosts

### ISSUE THREAD

**Issue by TheRealestMVP** [mrdokenny/Cookie-AutoDelete#269]
On my network we access various local servers with their simple hostname, i.e. `http://server15` instead of  `http://server15.example.org`. Unfortunately I'm not able to white list all local servers without having to whitelist each one of them individually.

Also, some projects/services make use of the ".local" domain, e.g. `http://myproject.local`. I guess `.local` is considered a TLD by Cookie AutoDelete, that's why `*.local` is not offered as a white list option.

So here is my suggestion: Add two options to the configuration:

- auto whitelist simple host names (local network)
- auto whitelist local domains (localhost and the .local domain)

For users familiar with regular expressions, #169 would solve the problems above, but maybe having more simple options would be useful.

**Comment by masgo** [comment]
You can add `*.local` by yourself. Just go into the options to the list of expressions. There is a textbox on top where you can type *.local and whitelist it yourself.

Regarding the simple host names: I support your request. 

But, one should add to the documentation what simple hostnames mean. It is **not** true that these are all local network nodes. Simple host names are found by your DNS system by applying the dns suffix and searching for them. This could mean that the host is somewhere else. This is important to know if you do not use a DNS Server which you fully trust.

**Comment by ke-d** [comment]
Btw something that's not commonly known (that I should probably add to the doc) is that adding `*` does work in matching a bunch of sites. Like you can use something like `gi*b.com` to match `github.com` and `gitlab.com`
