### ISSUE TITLE
Whitelist Entries should be in alphabetical order

### ISSUE THREAD

**Issue by sabret00the** [mrdokenny/Cookie-AutoDelete#27]
Currently they're in the order you add them in which makes them harder to scan.

**Comment by mrdokenny** [comment]
Sounds reasonable

**Comment by B00ze64** [comment]
Yeah, +1 on that!

**Comment by mrdokenny** [comment]
WhiteList and GreyList are automatically sorted when entering the settings page and also when you export them.
