### ISSUE TITLE
Feature request : Be able to delete LSO and DOM local storage data

### ISSUE THREAD

**Issue by LaurentGrenet** [mrdokenny/Cookie-AutoDelete#274]
As a former user of CookieKeeper (unfortunately no more usable in Quantum), I would find great to retrieve two options existing in CookieKeeper : Delete Flash LSO and DOM local storage data as well as cookies.
Of course, Whitelist and Greylist should apply also to these data, and Flash LSO and DOM of whitelisted sites have to be preserved as well.
Ideally, delete LSO / delete DOM storage are options user can set, or not

**Comment by zero77** [comment]
[I think localstorage support is under development](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/44)

**Comment by ke-d** [comment]
Flash objects cannot be cleaned by host yet due to API limitations. Localstorage is under #44

**Comment by B00ze64** [comment]
There is this extension for LSO: https://github.com/cpeterso/clear-flash-cookies
