### ISSUE TITLE
Auto-cleanup and Delay

### ISSUE THREAD

**Issue by Begoodee** [mrdokenny/Cookie-AutoDelete#278]
### Describe the Bug/Feature
If Delay Before Cleaning set to 0. Auto-cleanup deletes cookies only if tab closed by mouse gesture. If it has been closed by mid click or CTRL+ W cookies are not deleted. If Delay Before Cleaning set to 1 everything is OK.

### Your settings 

- OS/version: Windows 10 
- Browser/version: Firefox 57.0.1 (64 bit)
- Cookie AutoDelete version:

**Comment by ke-d** [comment]
Duplicate of #223
