### ISSUE TITLE
[Feature request] we should be able to search for domains we white/black-listed

### ISSUE THREAD

**Issue by js-d-coder** [mrdokenny/Cookie-AutoDelete#279]
I am using the latest version of this extension as of today. It will be very handy if you provide a search box to search for domain users white/black-listed. As one uses this extension the list of websites grows longer and sometimes I would like to search and remove a domain if needed.  
Thanks a lot for this extension, very handy!

**Comment by ke-d** [comment]
I would rather have a search box for #120.

For your use case, you could just use ctrl+F
