### ISSUE TITLE
[Feature request] This extension should delete local storage of non-whitelisted websites

### ISSUE THREAD

**Issue by js-d-coder** [mrdokenny/Cookie-AutoDelete#280]
Some websites put [local storage data](https://support.mozilla.org/en-US/kb/permission-store-data) to store some data offline for later use. It can also be used to track you even if you delete their cookies and _I think YouTube does that._  
It will be great if this extension can delete local storage of non-whitelisted websites along with their cookies.  
Thanks.

**Comment by practik** [comment]
Already in the works; see #44

**Comment by ke-d** [comment]
Duplicate of #44
