### ISSUE TITLE
cookies from file:// tab not cleared

### ISSUE THREAD

**Issue by practik** [mrdokenny/Cookie-AutoDelete#282]
The help interface for Adobe Acrobat 9 is a set of locally stored HTML documents that open in your browser when you click the Acrobat Help menu item. I did that today and later discovered that the interface had set a number of cookies, which were still hanging around even though the tab that had created them had been closed for hours.

These particular cookies seem pretty harmless – they're just session cookies that appear to be used for navigating the help interface – but I wanted to report the issue anyway since it seems like it could potentially be a problem in other cases.

Unfortunately, the only way I know to reproduce this is to use Acrobat 9 (a pretty old version) as I outlined above.

(C-AD 2.0.0 on FF 57 on macOS 10.12)

**Comment by chiraag-nataraj** [comment]
I think CAD has trouble clearing cookies without a hostname (or a blank hostname). See also #301.

**Comment by grenzor** [comment]
Possibly related but cookies from 127.0.0.1 aren't deleted either (could be the same for localhost and other local network IPs)

**Comment by ke-d** [comment]
Closing as this is related to #482
