### ISSUE TITLE
Cookies are deleted on tab close but not browser close

### ISSUE THREAD

**Issue by antgustech** [mrdokenny/Cookie-AutoDelete#285]
### Steps for anyone to reproduce the bug

Go to some website and do something that stores your actions in a cookie (like logging in).
Close  the entire browser and open it and go to the same site again. The cookie is still there.  
Cookies only get deleted when closing a tab, not closing the entire browser.

### Your settings 

- OS/version: Linux Mint 18.3
- Browser/version: Firefox 57.0.1
- Cookie AutoDelete version: 2.0.0

**Comment by ke-d** [comment]
There's no way currently to do actions on close reliably. So what webextensions have to do currently is to do actions on browser start.

**Comment by kennethtran93** [comment]
Closing stale issue.

If your browser is set to reopen those tabs when browser starts up again, then it would technically still be 'open' upon browser start.
