### ISSUE TITLE
Settings panel covering up the settings

### ISSUE THREAD

**Issue by d0mf1g** [mrdokenny/Cookie-AutoDelete#286]
![image](https://user-images.githubusercontent.com/33993948/33856203-6680bb3c-de95-11e7-8023-e32797ea492f.png)

Firefox 57.0.2
Windows 10
CAD v2

Expanding the panel in the settings menu covers up the settings. I have to click on the panel to "hide" it again before I can read the settings. A workaround would be to just keep the panel in permanent position and have the settings positioned to the right of the panel.

**Comment by d0mf1g** [comment]
Btw it's a screen resolution issue.

This is happening on 1280x1024. I'm assuming resolutions lower than this also have the same issue.

**Comment by kennethtran93** [comment]
This is possibly a bug in the CSS media query, since there's one for min 1300px but not really for max 1300px (the one after the min 1300px is max 48em, though presumably the min 1300px was originally min 48em).  

I can submit PR a quickfix to this in a moment.

**Comment by zero77** [comment]
This is still happening on android although, the update has improved it.

**Comment by kennethtran93** [comment]
@zero77 Screenshot, and perhaps browser as well as size of display and/or device used would help.  Thanks.

**Comment by zero77** [comment]
@kennethtran93 
The screen is 6.2 and I am using Firefox nightly.

![screenshot_20180105-165222](https://user-images.githubusercontent.com/16563034/34619278-8cc1abfa-f239-11e7-9178-c1297a3ed234.jpg)

**Comment by kennethtran93** [comment]
@zero77 Found the culprit.  

The bug this time is within the bootstrap css itself, where the css class 'row' has margin-left and margin-right at -15px.  I'm presuming that even smaller screens without opening the menu is also affected by the partial display of checkboxes.

I don't know if that was intentionally set by the bootstrap team or by @mrdokenny, but if margin-left is changed to 0px (and may as well do it for margin-right), then that solves the problem.
