### ISSUE TITLE
Delete service workers

### ISSUE THREAD

**Issue by rugk** [mrdokenny/Cookie-AutoDelete#287]
### Describe the Bug/Feature

Maybe it would also be useful to clear the service workers too. They can cache things or so, but likely also be used to store "tracking cookie"-like things.

And they can run in the background when websites are not open. One can open `about:serviceworkers` (or `chrome://inspect/#service-workers` in Chrome/ium) to look what service workers you already run.

**Comment by ke-d** [comment]
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/browsingData/DataTypeSet

It's part of browsingData but the hostname attribute doesn't work for it yet.

**Comment by chiraag-nataraj** [comment]
You might find [Web API Manager](https://github.com/snyderp/web-api-manager) useful. It's more for blocking the APIs in the first place, but...might be worth looking into?

**Comment by ghost** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1632990

**Comment by sdht0** [comment]
@kennethtran93: in case you missed the above message, this feature will also be available in FF77 and can be implemented along with #171 and #551. Hopefully all these together implies CAD will finally have feature parity with FF's "Manage cookies and site data" on a per-hostname basis.

**Comment by kennethtran93** [comment]
@sdht0 Thanks!  It will be worked upon once I get existing bugs/regresions fixed.

**Comment by kennethtran93** [comment]
Whoops ignore the staleness.

**Comment by kennethtran93** [comment]
Need some testers over at #798.  To download the zip file, follow the latest instructions given through github-actions bot
