### ISSUE TITLE
[Bug] Cookies Are Not Cleared When Delay Is Disabled

### ISSUE THREAD

**Issue by zero77** [mrdokenny/Cookie-AutoDelete#289]
From what I am seeing the cookies are not being cleared if the `Enable Automatic Cleaning? Delay Before Cleaning X Minute(s)` option has not been checked.

**Comment by ke-d** [comment]
Well yeah, cause you didn't enable "Enable Automatic Cleaning?" so it doesn't automatically clean cookies after the delay.

**Comment by zero77** [comment]
Can you please enable this option by default, because it isn’t already.

**Comment by ke-d** [comment]
https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/FAQ:-Common-Questions-and-Issues#why-is-active-mode-off-by-default
