### ISSUE TITLE
Clicking Run Now produces invalid message

### ISSUE THREAD

**Issue by gmariani** [mrdokenny/Cookie-AutoDelete#29]
Clicking run now, clears cookies but the alert box shows nonsense. See attached.
![screenshot 2017-05-21 23 02 00](https://cloud.githubusercontent.com/assets/5058619/26291042/a202f84e-3e79-11e7-91eb-05d1474518e1.png)

**Comment by mrdokenny** [comment]
That's not my extension, This is the GitHub repo for [Cookie AutoDelete](https://addons.mozilla.org/en-US/firefox/addon/cookie-autodelete/)
