### ISSUE TITLE
[Bug] Cookies not deleted in Waterfox 56

### ISSUE THREAD

**Issue by The-Twisted-Samurai** [mrdokenny/Cookie-AutoDelete#298]
### Bug details
Cookies aren't deleted in Waterfox 56. I'm using the recommended about:config settings by [privacytools.io](https://www.privacytools.io/#about_config) _except anything cookie related (including the first party isolate setting)._

I tried to force clean the cookies using the button "Clean, including open tabs" and even then no cookies were deleted.

### Screenshot in which the bug can be seen
https://i.imgur.com/sDxSfxs.png

I have never reset the counter for Cookie AutoDelete.
### My settings 
- OS/version: Windows 10
- Browser/version: Waterfox 56
- Cookie AutoDelete version: 2.0.1

**Comment by grahamperrin** [comment]
Can you provide troubleshooting information? From the Help menu.

**Comment by The-Twisted-Samurai** [comment]
I am not sure what you mean. There are only 4 options in the hamburger menu. And "Help" is not one of them. And neither is help in any of the 4 options themselves (i.e. their pages).

**Comment by grahamperrin** [comment]
about:support

**Comment by The-Twisted-Samurai** [comment]
Below is the about:support raw text data and normal text.
[Support Raw.txt](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/files/1589215/Support.Raw.txt)
[Support.txt](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/files/1589216/Support.txt)

I hope these help.

**Comment by ke-d** [comment]
Did you clear all cookies and see if new ones get deleted? Generally, if Waterfox is a direct fork of FF 56, then all the APIs should be there.

**Comment by The-Twisted-Samurai** [comment]
Yes that was one of the first things I tried. Unfortunately, it doesn't delete any cookies. I even enabled the pop-up to display cookies deleted, but it never shows up. I have to manually purge all cookies myself.

**Comment by ke-d** [comment]
I tested it with a portable version of default Waterfox and cookies are deleted as expected.

**Comment by The-Twisted-Samurai** [comment]
Hmm... I'll test it out with a completely new profile on Waterfox then. 

Will give you an update shortly

**Update:** Cookie AutoDelete is working for a fresh new profile. I'm assuming it's something related to my original profile. I'll delete all extensions and their data and then reinstall. That should fix the problem.

It's safe to say you can mark this as closed then. Thanks for helping me out!

**Comment by ke-d** [comment]
No problem.

**Comment by grahamperrin** [comment]
@The-Twisted-Samurai FYI https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/513#issuecomment-482822105
