### ISSUE TITLE
Whitelist and containers

### ISSUE THREAD

**Issue by Agiarga** [mrdokenny/Cookie-AutoDelete#299]
### Describe the Bug
I recently noticed cookies not being deleted (even-though I get the notification they are deleyed) on my main profile. So I created a new profile with only "Multi-Account Containers" and "Cookie AutoDelete" and noticed on this profile the "List of Expressions" is for all containers (I don't have the row of tabs that I have on my usual profile. 

### Screenshot in which the bug can be seen
https://imgur.com/a/C3cMM

### Steps for anyone to reproduce the bug
* create a profile
* add "Multi-Account Containers" extension
* add "Cookie AutoDelete" extension

The containers aren't listed in "Cookie AutoDelete" settings

### Your settings 
- OS/version: Linux
- Browser/version: latest Nightly 
- Cookie AutoDelete version: 2.0.1

**Comment by ke-d** [comment]
You didn't enable Container Mode in the settings.

**Comment by Agiarga** [comment]
Oups, sorry I missed that setting. Thank you. Now I can set white-lists per containers.

But I still have an issue. I have created a container for YouTube and youtube.com is whitelisted for that container (and that container only). When I close a "default" tab browsing YouTube the cookies are deleted as expected. But if I go to YouTube in a tab of the "Personal" (or any other) container, the cookies **aren't deleted** after the tab is closed. I hope it's clear. Should I create an other issue?

**Comment by Agiarga** [comment]
I tested a bit more. In fact, cookies from any site aren't deleted if they are open in a container tab.

**Comment by ke-d** [comment]
I think that's #197. Should be fixed in the latest beta on AMO.

**Comment by Agiarga** [comment]
Yes, I installed the beta and it works as expected.
Thank you.
