### ISSUE TITLE
Every time I start the browser (57.0.3 now), it cleans 3 cookies from some unknown domain

### ISSUE THREAD

**Issue by MarkRH** [mrdokenny/Cookie-AutoDelete#301]
### Describe the Bug/Feature

Every time I start the browser (57.0.3 now), it cleans 3 cookies from some unknown domain, even if all I do is start the browser, close it, open it. I have auto-clean enabled and the greylist is the default "^$"

![image](https://user-images.githubusercontent.com/8035962/34425666-aac372b0-ebf3-11e7-8c4d-abd6515d61cf.png)

It's looks like it is these cookies:
![image](https://user-images.githubusercontent.com/8035962/34425764-b98eb4d4-ebf4-11e7-9ad7-9f89cf671801.png)

To reproduce, not sure.. probably something specific to this installation somehow. Could it be some extension created cookies?  

- OS/version:  Windows 7 Pro 64bit
- Browser/version: Firefox 57.0.3
- Cookie AutoDelete version:  2.0.1

**Comment by MarkRH** [comment]
Well, while disabling some extensions to troubleshoot, I decided to manually delete those cookies in the list. Now, they are not re-appearing with same extensions enabled.  Is it possible CAD wasn't actually able to delete these cookies so it just kept trying to every time?

**Comment by ke-d** [comment]
>Is it possible CAD wasn't actually able to delete these cookies so it just kept trying to every time?

Most likely...

I'm not even sure how blank hostname cookies happen tbh, so it's hard to debug. If anyone knows how to create a cookie without a hostname let me know.

**Comment by Joel889** [comment]
> If anyone knows how to create a cookie without a hostname let me know.

Download a webpage and then open it from your hard drive.

**Comment by MarkRH** [comment]
That could be. I did save a complete Twitch Subscription webpage and then open it.  Troubleshooting Roboform not filling a pay form issue.

**Comment by ke-d** [comment]
Closing as this is related to #482
