### ISSUE TITLE
Whitelist login cookies / specific cookies?

### ISSUE THREAD

**Issue by Gmarcott42** [mrdokenny/Cookie-AutoDelete#306]
I was wondering if it is possible to whitelist specific cookies from a domain, instead of everything from that domain?  My issue is that whenever I log in to twitch.tv, Firefox remembers my password but I need to go through the two-step authentication after every time I close the browser.  I looked around and I think there is a specific two-factor authentication cookie that is being deleted.  Could I whitelist that one specifically and delete anything else that twitch tracks?

**Comment by ke-d** [comment]
Duplicate of #68
