### ISSUE TITLE
Popup window size frequently becomes too small on macOS Chrome

### ISSUE THREAD

**Issue by uu1t** [mrdokenny/Cookie-AutoDelete#311]
### Describe the Bug

When opening popup window, frequently it appears only in an moment and then becomes too small.
This happens on Chrome for Mac, not Windows (I confirmed on Windows 10).

### Screenshot in which the bug can be seen

![popup_fails](https://user-images.githubusercontent.com/35105763/34637158-1781dcf6-f2f3-11e7-9c3d-8da66abcf6bc.gif)

### Your settings 

- OS/version: macOS v10.13.2
- Browser/version: Chrome v63.0.3239.132
- Cookie AutoDelete version:  2.0.1 and latest commit (905dc5d)

**Comment by ke-d** [comment]
I don't have a Mac, so I can't verify or fix this, but I'll accept PRs for this.

**Comment by uu1t** [comment]
I think this is a Chrome's issue which hasn't been fixed for several years.  
Here is the issue: https://bugs.chromium.org/p/chromium/issues/detail?id=428044

**Comment by ansell** [comment]
Can confirm, happens about 1 in 5 times

**Comment by ghost** [comment]
I've seen this bug occur randomly on several macOS Chrome extensions for some years, not just Cookie-AutoDelete.

**Comment by ke-d** [comment]
Closing as this should have been fixed.
