### ISSUE TITLE
browser restart fails to delete session cookie

### ISSUE THREAD

**Issue by fanyangto** [mrdokenny/Cookie-AutoDelete#312]
### Describe the Bug/Feature
This may be a serious security bug.  I am using firefox 57 and the latest addon 2.0.

When logged into a financial web site, usually you will receive a session cookie and some persistent cookies. The session cookie must be deleted upon firefox restart. The persistent cookies stay until their expiration typically. With the addon, white list / gray list could turn a persistent cookie into a session cookie behavior - i.e. delete them upon firefox shutdown, before the expiration.  However, white list/gray list should not affect session cookie behavior, for example, by changing a session cookie into a persistent cookie that can survive ff restart. 

That's exactly what happens. I logged into a banking web site, and add the site domain to the white list. 
This is supposed to only keeps the persistent cookies. But when I restart the firefox, the session cookie remains and I am still logged into the web site. 

Looks like the addon has completely replaced the built-in cookie manager, but there is a big security hole here. Am I doing something wrong? 

### Your settings 

add a banking web site to the white list. 
Auto delete enabled

- OS/version:  win 10
- Browser/version:  FF 57.0.3
- Cookie AutoDelete version: 2.0.0

**Comment by ke-d** [comment]
CAD doesn't modify the cookie directly so it could be something external. Does the issue happen with CAD disabled?

**Comment by fanyangto** [comment]
Good catch. I did what you suggested and found the session cookie is not deleted even when the CAD addon is disabled. 

To rule out the site issue, I also tried with IE (MSFT edge) and the session cookie IS deleted. 

So this means something wrong with the FF 57.0.2 or some other addons interfering with it. I am going to test the FF 57.0.2 without any addon (reinstall) and see what happens. Will report back.

**Comment by fanyangto** [comment]
After a series of experiments with a complete fresh install of FF 57.0.2 with no addon, I found the problem was firefox restore tabs from last time. If tab restoration is enabled, then session cookies are not cleared. You logged right back in. 

Don't you guys think this is a FF bug? I can't imagine anyone wants to design it this way: a convenient tab restoration feature turns into a permanent logged on feature. 

If you think this is a bug, I will probably figure out a way to file a bug with FF.

**Comment by fanyangto** [comment]
Looks like this is an expected FF beahvior. I just never noticed it before. See this

https://support.mozilla.org/en-US/questions/943191

I will close this issue.
