### ISSUE TITLE
Add "Turn alert sound on/off" in settings?

### ISSUE THREAD

**Issue by Maximpulse** [mrdokenny/Cookie-AutoDelete#315]
When Cookie-AutoDelete clears out some cookies it plays a sound.
It would be nice if there were an option to silence that sound in Settings.
In other words, please add a "Turn alert sound on/off" in Settings.
I have only used Cookie-AutoDelete for a day so far, so maybe I am unaware of a place to find this missing/desired feature.
Otherwise Cookie-AutoDelete seems to be doing exactly what it promised. I am pleased and amazed.

**Comment by ke-d** [comment]
I assuming this is mobile so go to the settings to turn off notifications. I don't think there's a way to control which types of notifications it does. You might be able to do it via the mobile OS.

I'm just using the notification API so I have no control over what it does in each browser.
