### ISSUE TITLE
CAD version 2.1.0 - *New Permissions Support Issue*

### ISSUE THREAD

**Issue by prog-amateur** [mrdokenny/Cookie-AutoDelete#317]
Hello, 
I see an icon from Firefox asking me to upgrade Autocookies to the latest version (2.0.1). 
However, in the popup, it is requesting me to accept the new privacy settings : 
- to clear history, cookies, and data (it is OK for me)
- to have access to privacy settings and modify it (this I don't understand the meaning)

This is the 1st time I see such popup request despite several addons related to privacy. 

Please, could you explain more in details what is the change here ? 
Thank you very much. 

- OS/version: Ubuntu 17.10
- Browser/version: Firefox
- Cookie AutoDelete version: my current version is 2.0.0 and the popup occurs when I upgrade to 2.0.1.

**Comment by overdodactyl** [comment]
I believe the privacy API is needed to detect if first party isolation is enabled

see #75

**Comment by prog-amateur** [comment]
Thank you very much. You did well to combine both topics. 
Did the main developer confirmed your suggestion ? I see no answer from the link #75 
Thank you !

**Comment by planet0** [comment]
You can see the developer mentioning this in the 2.1.0 release notes on the [Firefox Add-ons page](https://addons.mozilla.org/en-US/firefox/addon/cookie-autodelete/).

> - Added: Localstorage Support (Firefox 58+, BrowserData API requested)
> - Added: First Party Isolation Support (Firefox 59+, Privacy API requested)

**Comment by tanstafel** [comment]
But there is still the question why this extension wants to modify privacy settings. Read-only access should be enough here. Or can these permissions not given in this granularity?

**Comment by ke-d** [comment]
> Or can these permissions not given in this granularity?

The permissions are all or nothing. Pretty much reading if FPI is enabled or not.

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/privacy

Unfortunately the privacy API is not part of the optional permissions.

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/optional_permissions

**Comment by ghost** [comment]
I am concerned too about releasing permissions other than to read only. When I saw the list of regular permissions that my previous cookie eater used, it did not require altering "my privacy settings." I see no reason why this should happen. I would have no issue giving that permission on my phone but my desktop or laptop is another issue entirely. I still do not know why your add-on should need permission to alter my privacy settings and all or nothing is not an acceptable option for me. So I guess I won't be updating and will look for another alternative or go back to the previous version of my cookie eater by using something other than the most current firefox.

**Comment by ke-d** [comment]
@cvillegal 

> When I saw the list of regular permissions that my previous cookie eater used, it did not require altering "my privacy settings."

It's more of the wording of the permission that causes concern. 

Either way the privacy API gives access to these settings which isn't a lot tbh:

network.networkPredictionEnabled
network.peerConnectionEnabled
network.webRTCIPHandlingPolicy
services.passwordSavingEnabled
websites.firstPartyIsolate
websites.hyperlinkAuditingEnabled
websites.protectedContentEnabled
websites.referrersEnabled
websites.resistFingerprinting
websites.thirdPartyCookiesAllowed
websites.trackingProtectionMode

As I said before, it's for reading the value of `websites.firstPartyIsolate` because the cookie API requires an extra attribute `firstPartyDomain` to be added. Although adding it breaks compatibility.

https://bugzilla.mozilla.org/show_bug.cgi?id=1381197#c16

Without dynamically adding and removing the `firstPartyDomain` based on the value of `websites.firstPartyIsolate`, CAD won't automatically remove FP cookies if FPI is on and non-FP cookies if FPI is off.

**Comment by Birger52** [comment]
Getting complicated.

What is the need to Clear the browser history?
That is the wording in the request to alter persmissions.
I use my browser history. And off hand, there is no connection to cookies - not one that is needed anyway.
So like cvillegal above, I'll have to say, I am encined to find something else, to remove the crumbs...

**Comment by Yyuzu** [comment]
A comment about privacy settings:

First party isolate is quite new, and if you find another extension which does not require the permissions to access privacy settings, it most certainly won't work properly (see mrdokenny's explanation).

I think any cookie deletion extension will require access to privacy settings from now on, or won't be able to cover all setups.

**Comment by Birger52** [comment]
But maybe I can fiind one, that does not want to clear my browser history....

**Comment by Yyuzu** [comment]
Well I'm pretty sure it doesn't delete history, the "_delete recent history, cookies and relevant data_" (approximate translation in english from my french version) permission seem to englobe rights related to cookies and I'm pretty sure CAD only uses it to do a thorough job on cookies.

@mrdokenny will most certainly explain better than me.
Anyways, the code is opensource, you can just browse it.

**Comment by ke-d** [comment]
@Birger52 

>What is the need to Clear the browser history?

That's the browsingData API which is required to clear localstorage by host in #44

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/browsingData

>
    browser cache
    cookies
    downloads
    history
    local storage
    plugin data
    saved form data
    saved passwords


The browsingData API includes history as an optional parameter but it's not used in CAD so no worries there. Any extension that wants to clear localstorage by hostname would require this permission.

Also take any permission wording with a grain of salt.

**Comment by kennethtran93** [comment]
This issue is now being closed due to:
 - Staleness
 - older CAD version.
