### ISSUE TITLE
Upgrade to 2.1.0 does not migrate minutes to seconds in setting

### ISSUE THREAD

**Issue by fichtennadel** [mrdokenny/Cookie-AutoDelete#319]
### Describe the Bug/Feature
Upgrade to 2.1.0 does not migrate minutes to seconds in setting, it just changes the unit.
I had "2 minutes" for delay before cleaning, after upgrade to 2.1.0 it was "2 seconds" instead of 120 seconds.

### Screenshot in which the bug can be seen
![image](https://user-images.githubusercontent.com/2324670/34818555-6680a046-f6bb-11e7-9cb8-0d6b2ccb1116.png)

### Steps for anyone to reproduce the bug
Upgrade to 2.1.0 with custom setting for delay before cleaning

### Your settings 
- OS/version: Win7x64
- Browser/version: FF 57.0.4
- Cookie AutoDelete version: 2.1.0

**Comment by planet0** [comment]
Can confirm, mine was previous set to 3 minutes, now set as 3 seconds. macOS 10.13.2, Firefox 58.0b15, Cookie AutoDelete 2.1.0

**Comment by ke-d** [comment]
The reason why I didn't want to do this is because migration code does have its fair amount of problems. It's better that I just leave it alone (since it's minor), then to introduce a random bug where on startup that value gets multiplied by 60 every time.
