### ISSUE TITLE
After upgrade to 2.1.0 lots of alerts about deleted cookies

### ISSUE THREAD

**Issue by gitressa** [mrdokenny/Cookie-AutoDelete#322]
After the recent upgrade there are lots of alerts about "Cookies were deleted. 14 Deleted Cookies from:" every time a tab is closed. I don't remember getting this many alerts before ...
Great add-on by the way, love it!

**Comment by Yyuzu** [comment]
Same here.

I recently activated first party isolate, but then I read about a bug here with it, so I disabled the option and removed all cookies. But it still happens after these steps.

Cheers

**Comment by ke-d** [comment]
@gitressa Clear all your cookies. I noticed that the cookie API has some problems removing "blank" cookies. 

@Kyoshiro-san When flipping the FPI setting, restart the browser.

**Comment by gitressa** [comment]
Thanks @mrdokenny, that seems to have fixed it. I get much less frequent alerts, and they seem to be relevant.

**Comment by Yyuzu** [comment]
Thanks @mrdokenny, I already did restart the browser but I had the same issue as gitressa.
Clearing all cookies fixed it.
