### ISSUE TITLE
After upgrade to 2.1.0 clicking 'Restore Default Settings' resets counter

### ISSUE THREAD

**Issue by sfrommarin** [mrdokenny/Cookie-AutoDelete#324]
### Screenshot in which the bug can be seen

![image](https://user-images.githubusercontent.com/35433266/34920377-a4216e40-f926-11e7-9b14-d980a1999bb8.png)

### Your settings 

- OS/version: Windows 10, 64
- Browser/version: 57.0.4 64-bit
- Cookie AutoDelete version: 2.1.0

**Comment by ke-d** [comment]
I'm going to say this is similar to #217. That button is more of a "Reset Extension Data" and I'm considering adding another button.
