### ISSUE TITLE
On Huawei Nova, asks for Camera and Mic permission when importing

### ISSUE THREAD

**Issue by steffchep** [mrdokenny/Cookie-AutoDelete#325]
### Describe the Bug

On Huawei Nova, the Plugin requests Camera and Microphone access when I want to import a list of domains from a file. This makes no sense to me - I've granted access to the storage, which ought to be enough. If I decline the other two, nothing happens when I tap on the import button. 

### Your settings 

- OS/version: Android 6
- Browser/version: 57.0.4
- Cookie AutoDelete version: current, installed 16. Jan. 2018

**Comment by ke-d** [comment]
I'm thinking this might be due to how Firefox on Android works since probably all extensions with an import (ublock origin) would probably request the same permission. 

On my end there's nothing that can be done since this is not CAD's problem.
