### ISSUE TITLE
Session Restore screen leads to all non-whitelisted cookies being deleted

### ISSUE THREAD

**Issue by chiraag-nataraj** [mrdokenny/Cookie-AutoDelete#326]
### Describe the Bug/Feature

If the browser crashes and restarts, all cookies not on a whitelist are cleared, even if the tabs using those cookies are about to be restored. Admittedly, this is probably because my delay is set to 0. Still, this will happen with any reasonably short delay.

### Steps for anyone to reproduce the bug

1. Ensure a short delay (< 5 seconds is probably enough).
2. Open a bunch of non-whitelisted sites (for example, I open GitHub and log in).
3. Crash the browser in some way (probably a SIGKILL is enough?).
4. Open the browser again. You should be at the session restore screen.
5. Notice that all of the non-whitelisted cookies are cleared, even for tabs that will be opened after the session is restored.

### Your settings 

Delay set to 0. Autoclean enabled. Container and LocalStorage support enabled (but I'm pretty sure I've seen this in previous versions, before LocalStorage support was introduced).

- OS/version: Debian Linux sid/experimental
- Browser/version: Firefox 58.0b14
- Cookie AutoDelete version: 2.1.0

**Comment by ke-d** [comment]
It makes sense since no open tabs are open. So cleanup wouldn't protect any sites if it's not open or whitelisted.

https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/FAQ:-Common-Questions-and-Issues#what-do-all-the-cleanup-options-mean

I'm not sure if the WebExtension API has anything to grab those links from session restore though, so I'll have to look into it.

**Comment by Yyuzu** [comment]
Hi,

I don't know if that's easier or not but maybe you can detect a crashed session restore tab is opened and postpone cleaning until it's been looked into ? But that'd stop cleaning if the user keeps the session restore tab open, so maybe it should come with a warning of some sort.

Also, people using session manager extensions may have problems like this one, a quick (but not fail proof) solution would be to postpone cleaning for like 30s (configurable) after browser start ? I'd most certainly fix the problem for most users who restore their session immediately after restarting on crash.

Cheers

**Comment by chiraag-nataraj** [comment]
@mrdokenny Right, the behavior makes sense...it's just sub-optimal from a user perspective. So I guess this is more of a feature request than anything else?

**Comment by ke-d** [comment]
Since #196 is done, it should be possible to undelete any deleted cookies. So closing this in favor of that approach.
