### ISSUE TITLE
Use built-in Chrome Whitelist

### ISSUE THREAD

**Issue by B00ze64** [mrdokenny/Cookie-AutoDelete#33]
Good day.

I am new to Chrome, so maybe this cannot be done, but why is this extension using its OWN Whitelist?? There is a Whitelist built right into Chrome, and it supports subdomains, why not add the Whitelisted sites to that? Because with two Whitelists, it means twice the work if you have for example 3rd party cookies disabled - for some sites you will have to whitelist inside Cookie-AutoDelete, and then you will have to go into Chrome settings to whitelist related 3rd party providers (some payment processors require cookies).

Thank you.

**Comment by mrdokenny** [comment]
> I am new to Chrome, so maybe this cannot be done, but why is this extension using its OWN Whitelist?? 

To my knowledge, there's no API to access Chrome's whitelist. And I also don't think there's an easy way to export those unlike my own whitelist implementation.

> Because with two Whitelists, it means twice the work if you have for example 3rd party cookies disabled - for some sites you will have to whitelist inside Cookie-AutoDelete, and then you will have to go into Chrome settings to whitelist related 3rd party providers (some payment processors require cookies).

WhiteList those third party sites in that case.

**Comment by B00ze64** [comment]
Yeah, I was afraid of that - I'm used to Firefox where, for now, it is easy to modify the built-in list. Thanks for looking into it. As for 3rd parties, sure, but they will have to be WhiteListed in 2 places since I have disabled 3rd party cookies inside Chrome (the default). It gets crazier with uMatrix running on top, that's 3 places to manage! I'll close...
