### ISSUE TITLE
Restore Default Settings clears Expression List

### ISSUE THREAD

**Issue by sedlund** [mrdokenny/Cookie-AutoDelete#330]
### Describe the Bug/Feature

Clicking 'restore default settings' clears my expressions.  I thought this would just reset the check boxes above it.   I'm not sure that it should clear the expressions.  Or it should be made clear that is going to happen.

### Your settings 

- OS/version: chromeos
- Browser/version: chrome 63
- Cookie AutoDelete version: 2.1.0

**Comment by ke-d** [comment]
Duplicate of #217
