### ISSUE TITLE
Feature Request: Enable (firefox) mobile browsers have *silent* notifications

### ISSUE THREAD

**Issue by doronbehar** [mrdokenny/Cookie-AutoDelete#335]
I have disabled notifications on my mobile firefox because I don't want to get notifications with sound every time cookies are deleted. It could be great though if these notifications could be there but silent and without an icon in the notifications bar.

**Comment by ghost** [comment]
In my LineageOS based on Android 7.1 notification can be configured to disable sound.

**Comment by doronbehar** [comment]
The point of this feature request is that I won't have to touch the global settings of firefox' notifications.

**Comment by ke-d** [comment]
https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/276#issuecomment-349486023

Unless someone other extension has done it before but according to the documentation, I don't think there's a way for other extensions to control how are they displayed in every OS, since the API is suppose to be OS independent.

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/notifications/NotificationOptions

**Comment by AlexVallat** [comment]
There's a bug for tracking SnackBar (successor to Toast) support for WebExtensions that would be ideal for this: https://bugzilla.mozilla.org/show_bug.cgi?id=1415817

**Comment by belling** [comment]
I understand this isn't necessarily easily done and this comment isn't necessarily helpful, but man this is driving me crazy on MacOS.

**Comment by mehdisadeghi** [comment]
Is there any solution or any hack to remove the "notification" permission of the addon? Following [this guide](https://support.mozilla.org/de/questions/1257097) I ran the following code in addon debugging pane to remove the permission but it didn't change anything:

    browser.permissions.remove({permissions: ['notifications']})
    .then(msg => console.log('succeess'))
    .catch(err => console.log('failed' + err))

Is there any hack to disable notification of only this addon?

Thanks

**Comment by kennethtran93** [comment]
To disable notifications (I.e. You don't want to see it in the android notification system) , you should be able to simply uncheck the highlighted option below.  

This wasn't the right issue to comment in as the people above want to keep the notifications enabled but not be alerted (I.e sound/vibrate). 

![20191029_025347](https://user-images.githubusercontent.com/6724477/67756844-fab64b80-f9f7-11e9-9999-717d8c80ad21.jpg). 
That hack is probably only temporary and most likely only works on desktop browser versions. . If you removed notifications and still have it enabled in the addon settings then it may or may not crash. 

Unfortunately it is the operating system itself that does the notification alert option for the global Firefox. 

We cannot remove the notification permission from the addon itself as there is a notification checkbox in the settings of the addon itself. We probably shouldn't request the notification permission at runtime as we don't want to annoy the user with a request permission popup everytime they start the browser.

**Comment by kennethtran93** [comment]
Closing as it is a browser limitation.  We do not control how the browsers/desktop/mobile does their notifications.
