### ISSUE TITLE
Not working - cookies not being deleted

### ISSUE THREAD

**Issue by imimapcc** [mrdokenny/Cookie-AutoDelete#336]
On browser startup the addon reports cookies were removed but it hasn't actually removed them. In the next notification (on closing a Tab) it again reports having removed all cookies, including new ones and previously reported ones (ie the list keep growing) and so on. 

Manually deleted cookies - no change. 
Removed and re-installed add-on - no change.

- OS/version: Linux Mint 18.2 Sonya
- Browser/version: FF 57.0.4 (32-bit)
- Cookie AutoDelete version: 2.1.1

**Comment by ke-d** [comment]
Seems like you have `privacy.firstparty.isolate` on? #75
