### ISSUE TITLE
Addon not doing anything in Firefox 58

### ISSUE THREAD

**Issue by anon88391** [mrdokenny/Cookie-AutoDelete#337]
Like in the title, the addon just doesn't do anything in FF 58. Tested in a fresh VM, cookies are never deleted, notifications don't appear when ticked, deleted cookie counter does not increment and stays at 0.

- OS/version:  Windows 10
- Browser/version:  Mozilla Firefox 58.0
- Cookie AutoDelete version:  2.1.0

**Comment by ke-d** [comment]
Are you sure you don't have `privacy.firstparty.isolate` on? #75 

In FF 58 and CAD version 2.1.1, it should now notify you if you have it on.
