### ISSUE TITLE
LocalStorage cleanup not working

### ISSUE THREAD

**Issue by TheRealestMVP** [mrdokenny/Cookie-AutoDelete#338]
Firefox was updated to v58 and I was excited to try out the new LocalStorage cleanup feature in 2.1.0. But it doesn't seem to work.

I started with a empty profile (no cookie or LocalStorage data stored) and with LocalStorage cleanup enabled in CAD.

I now visit twitter.com and youtube.com and check for cookies and LocalStorage data in the Firefox preferences. Both sites both stored cookies and LocalStorage data. But there is no "CookieAutoDelete" cookie as I would expect.

I close the tabs and get the notification popup 3 seconds later that cookies for twitter.com and youtube.com have been deleted. I check in Firefox preferences again. Cookies are gone, but LocalStorage remains.

Additional observation: I visit a site that does NOT set any cookies or LocalStorage (localhost), and the "CookieAutoDelete" cookie is set there. At a first glance, for me, it seems like the "set CAD cleanup cookie" logic is inverted...

Can anyone confirm?

**Comment by ke-d** [comment]
>I close the tabs and get the notification popup 3 seconds later that cookies for twitter.com and youtube.com have been deleted. I check in Firefox preferences again. Cookies are gone, but LocalStorage remains.

`Site data` probably refers to IndexDB which cannot be cleaned yet by hostname

Use the test sites I provided here:

https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/44#issuecomment-353769132

>Additional observation: I visit a site that does NOT set any cookies or LocalStorage (localhost), and the "CookieAutoDelete" cookie is set there. At a first glance, for me, it seems like the "set CAD cleanup cookie" logic is inverted...

That's normal since extensions don't know if a site uses localstorage or not. CAD will preemptively set the cleanup cookie.

**Comment by TheRealestMVP** [comment]
> Site data probably refers to IndexDB which cannot be cleaned yet by hostname

Okay, thanks. I wasn't aware that those are different things. Damn, another privacy disruptive browser feature :-/

> That's normal since extensions don't know if a site uses localstorage or not. CAD will preemptively set the cleanup cookie.

I see. Sorry, got that wrong in the first place.
