### ISSUE TITLE
Delete only localstorage or cookies

### ISSUE THREAD

**Issue by sebast889** [mrdokenny/Cookie-AutoDelete#341]
It can be useful for some sites to keep localstorage but clear cookies (and vice versa). Can there be a way to only clear localstorage or cookies on a per-site basis? Maybe two boxes where user can input whitelist domains for example "Don't clear cookies for these sites (this will still clear LS)" and "Don't clear localstorage for these sites (this will still clear cookies)"

**Comment by ke-d** [comment]
This enhancement is not trivial to implement as it affects the whitelist/greylist code as well as the cleanup code. I'll consider if there's a lot of upvotes.

**Comment by LaurentGrenet** [comment]
Yes, would be great !

**Comment by ke-d** [comment]
Closing since 3.0.0 is out.
