### ISSUE TITLE
OFF (not possible to ON) in Private Browsing (Firefox)

### ISSUE THREAD

**Issue by rastamanf1** [mrdokenny/Cookie-AutoDelete#343]
### Describe the Bug/Feature

It is impossible to activate **Cookie AutoDelete** in Firefox's [Private Browsing](https://support.mozilla.org/en-US/kb/private-browsing-use-firefox-without-history) mode. It is though possible in Chrome's Incognito mode (https://support.google.com/chrome_webstore/answer/2664769?hl=en - see "See an extension in incognito mode").

### Screenshot in which the bug can be seen

![cookie_autodelete__firefox_privatebrowsing](https://user-images.githubusercontent.com/33658251/35560914-1f7bc614-05af-11e8-8051-4ce8024eced5.JPG)

### Steps for anyone to reproduce the bug

Open a **New Private Window** in Firefox browser (with Cookie AutoDelete installed).

### Your settings 

- OS/version: Windows 7 Professional (64-bit SP1)
- Browser/version: Firefox ESR (52.6.0 32-bit)
- Cookie AutoDelete version: 1.4.4

**Comment by ke-d** [comment]
Version 2.X.X and the latest version of Firefox already cleans cookies in private mode.
