### ISSUE TITLE
Expired/Session Cookies Not Cleared

### ISSUE THREAD

**Issue by Graeme-L** [mrdokenny/Cookie-AutoDelete#344]
### Expired/Session Cookies Not Cleared

Date expired and session cookies are not cleared if the tab containing them is open at startup, either by setting the option to remember open windows and tabs or by pinning the tab.

Cookies for sites not open at startup are handled as expected.

The "Clean Cookies from Open Tabs on Startup" cleans up cookies from other associated sub-domains but does not solve the problem.

I first noticed this through sites like Twitch which can set CSRF session tokens for individual paths on the site and Youtube witch can set session cookies with the ID of the video if you have multiple pages open at once. The number of cookies stored for both sites was increasing over time for me and further investigation showed the old session cookies and cookies past their expiration date.

I have verified this behavior on a newly created profile with only Cookie AutoDelete installed.

### Steps for anyone to reproduce the bug
- Create a clean profile
- Install Cookie AutoDelete
- Visit a site that sets session cookies and whitelist the site.
- Examine a session cookie for the site to verify it exists.
- Restart the browser and verify the session cookie has been deleted but others remain.
- Set the browser option to remember open windows and tabs or open the test site and pin the tab.
- Examine a session cookie for the site to verify it exists.
- Restart the browser and verify the session cookie has not been deleted and contains the same data from the previous session.

### Versions
- OS/version: Windows 10 1709
- Browser/version: Firefox 58.0.1
- Cookie AutoDelete version: 2.1.0

**Comment by ke-d** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=576347

I think this is a FF bug.

**Comment by kennethtran93** [comment]
Note that this will only remove expired cookies.  As long as that domain has open tabs, we will not clean those cookies on startup, even if it is a session cookie, unless `clean cookies from open tabs at startup` is enabled.  Note that the domain/tab in question may have already completely loaded before CAD had a chance to clean it up.
