### ISSUE TITLE
Toolbar icon pop-up too small..

### ISSUE THREAD

**Issue by tjwoosta** [mrdokenny/Cookie-AutoDelete#346]
This is more of a support request than a bug report, the firefox add-on page directed me here for support.

When I click the toolbar icon the pop-up settings window thing is far too small for some reason (see image).

https://s17.postimg.org/yelrdg99p/cookieautodelete.png

I don't know what is causing it. Its a fresh firefox install with a newly created profile.

In the screenshot you can see I have ublock origin, noscript, https everywhere, secure password generator, and decentraleyes installed as well as cookie autodelete, but I uninstalled them to be sure and the problem remains without them installed.

None of the other add-ons shown have this problem, they are normal readable size like one would expect.

- OS/version: Windows 8.1
- Browser/version: Firefox 58.0.1 64bit
- Cookie AutoDelete version: 2.1.1

**Comment by ke-d** [comment]
It looks like some weird scaling going on with your Windows? What's your screen resolution?

If I recall Windows 8.1 had some weird scaling issues on high res displays.

**Comment by tjwoosta** [comment]
Its just plain old 1080p, no special scaling or text size settings I'm aware of. Ive never experienced anything else have scaling issues.

**Comment by ke-d** [comment]
Similar problems with other extensions?

**Comment by tjwoosta** [comment]
No, only this one, all others Ive tried work perfectly.  I'm able to get around it by manually entering expressions in the settings page, but it would be nice if I could do it with the toolbar button.

**Comment by tjwoosta** [comment]
I just found a fix!  
In Firefox options 
General > Language and Appearance > Fonts & Colors
Click the "Advanced..." button and set a minimum font size (the default was none) 
Setting it to 12 looks about right. I think this may mess up some web pages though

**Comment by ke-d** [comment]
I don't think minimum font size is suppose to be blank. Anyways glad to see it working.
