### ISSUE TITLE
Cookie AutoDelete fingerprint

### ISSUE THREAD

**Issue by crssi** [mrdokenny/Cookie-AutoDelete#348]
On other already too long topic a fellow @anewuser asked a [question](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/44#issuecomment-363183067):

> Using a fixed path name makes it easy to fingerprint Cookie AutoDelete users: [https://anewuser.github.io/dom-examples/web-storage/index.html](https://anewuser.github.io/dom-examples/web-storage/index.html)
Can you set it to a different random string every time a new dummy cookie is created?

I am sure you will investigate, but posting a new issue anyway just for a reminder.

Cheers

**Comment by anewuser** [comment]
He added the fix before closing that issue:  https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/commit/23718defff338d8fa03b45e29200e7fd1fc90a9d

**Comment by crssi** [comment]
This was fast. @mrdokenny is a TZAR. :+1: 
Thank you
