### ISSUE TITLE
OPERA support - any programmer to work on it?

### ISSUE THREAD

**Issue by rastamanf1** [mrdokenny/Cookie-AutoDelete#349]
_Hello everyone,_

although this is not an issue, I would like to ask, whether is there any programmer around, who would be willing to **"clone" Cookie AutoDelete** for the [OPERA browser](https://addons.opera.com/en/).

I, unfortunately, don't have the knowledge and the author, **Kenny Do**, doesn't have the time (as he [replied](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/pull/342#issuecomment-362098552) to my [question](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/pull/342#issue-292699000)).

_Thanks in advance to you!_

**Comment by ke-d** [comment]
Not sure how well this works but there's this:

https://addons.opera.com/en/extensions/details/download-chrome-extension-9/?display=en

and

https://chrome.google.com/webstore/detail/cookie-autodelete/fhcgjolkccmbidfldomjliifgaodjagh

**Comment by rastamanf1** [comment]
Thanks for the tip, @mrdokenny!

Unfortunately, it seems NOT to work for Cookie AutoDelete - some general icon (none of [yours](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/tree/2.X.X-Branch/extension/icons)) appears in the panel, positioning the cursor over it displays "Cookie AutoDelete", but clicking the icon returns "**File not found**".

E. g. for [uBO-Extra](https://github.com/gorhill/uBO-Extra) it seems to work, though.

**Comment by anewuser** [comment]
Try posting your request on https://forums.opera.com/ too. Maybe some developer will take it.

**Comment by rastamanf1** [comment]
Thanks, @anewuser, I'll try.

**Comment by rastamanf1** [comment]
Interestingly, **Cookie AutoDelete** somehow started working in [Opera](http://www.opera.com/). Did you modify something, @mrdokenny? Or maybe Opera Software AS reworked their [Install Chrome Extensions](https://addons.opera.com/en/extensions/details/download-chrome-extension-9/) add-on? Or did Cookie AutoDelete only need some time to acclimate in the new environment? Who knows... **miracle, mystery...**

So or so, do you thinkg that there is **any difference between native and this "virtualized" install?**

**Comment by anewuser** [comment]
@rastamanf1 only the install is what you describe as "virtualized". After installed, extensions run as native ones and even get updated automatically - but might try to make use of APIs and features not available on Opera yet, so you may run into bugs not present on other browsers.

> only need some time to acclimate in the new environment?

😆

**Comment by rastamanf1** [comment]
@anewuser, the 

> Cookie AutoDelete only needed some time to acclimate in the new environment

was meant as a joke :). But Cookie AutoDelete really wasn't running even after several Opera restarts and even OS reboots - just now, after several days, it mysteriously started. :)

THANKS FOR the other info - GOOD NEWS!

**Comment by hipunk** [comment]
After restarting Operabrowser it seems to be working, but watch what it looks like in the menubar:
![screenshot opera cookie autodelete](https://user-images.githubusercontent.com/11931747/37712098-226ff594-2d13-11e8-9418-960c3913607e.png)

**Comment by rastamanf1** [comment]
@hipunk, yep, that's what I see, too... but otherwise it works.

**Comment by skjerns** [comment]
I can happily announce that the newest version of Opera is working again!

**Comment by kennethtran93** [comment]
Closing as per comment above.
