### ISSUE TITLE
It shows deleted cookies that never exist

### ISSUE THREAD

**Issue by Primokorn** [mrdokenny/Cookie-AutoDelete#35]
Hi,
Here is an example:
* I open this website: [Android Police](http://www.androidpolice.com/)
* uMatrix says there's one request for cookies but I block it:
![capture](https://cloud.githubusercontent.com/assets/5938828/26553834/b1043e1a-448d-11e7-962a-8ba86cde17fc.PNG)
* After closing the tab, Cookie AutoDelete tells me that it removed 1 cookie from androidpolice.com. That's not possible.
![capture2](https://cloud.githubusercontent.com/assets/5938828/26553887/e0e9cd16-448d-11e7-93f7-41b31899e320.PNG)

**Comment by mrdokenny** [comment]
Is the cookie actually placed in "Show Cookies" in Firefox settings? There's a chance that it might have gotten placed cause the extension literally grabs any cookies that the Cookie API can see.

**Comment by Primokorn** [comment]
Yes I have it:
![capture](https://cloud.githubusercontent.com/assets/5938828/26618302/303407c2-45da-11e7-8373-d92b2da0101e.PNG)
So is it a Firefox bug?

**Comment by mrdokenny** [comment]
I don't use uMatrix personally but I think uMatrix is not blocking the placement of the cookie. So it's probably a uMatrix bug rather than Firefox.

**Comment by Radagast** [comment]
FWIW, I use uMatrix with Cookie AutoDelete but I was unable to reproduce this.

**Comment by Primokorn** [comment]
Actually I think there's no bug.
Read [this wiki](https://github.com/gorhill/uMatrix/wiki/Cookies) page of uMatrix.
CookieAutodelete removes the cookie that I see in the Firefox settings but the cookie never left my browser.
