### ISSUE TITLE
Feature request: macOS Safari extension. 

### ISSUE THREAD

**Issue by ghost** [mrdokenny/Cookie-AutoDelete#354]
I see you work on Chrome and Firefox, but not Safari. Wish you did (I use Chrome and Safari), thanks.

**Comment by ke-d** [comment]
From what I can tell, Safari doesn't use the same API as Firefox and Chrome, so this would be a completely different code base.

**Comment by Noleli** [comment]
I wonder if @el1t could weigh in on what might be involved, since they ported [uBlock Origin](https://github.com/el1t/uBlock-Safari) to Safari.
