### ISSUE TITLE
Automatic cache clearing

### ISSUE THREAD

**Issue by elaine-jackson** [mrdokenny/Cookie-AutoDelete#356]
### Describe the Bug/Feature

Clear a website's cached files. Websites can view files stored in the cache to track you the same way cookies are used to track you.

### Screenshot in which the bug can be seen

N/A

### Your settings 

N/A

- OS/version: macOS
- Browser/version: Firefox
- Cookie AutoDelete version: 2.1.0

**Comment by ke-d** [comment]
While this keep coming up, I'll probably just implement it without checking for idleness (like in SDC) since that requires an extra permission.

So I'm thinking a setting like:

`Clear cache every X minutes`

**Comment by elaine-jackson** [comment]
Awesome - glad to see this project improving - I would set firefox to clear everything on exit however I want the past few hours of history and I whitelisted duckduckgo's settings so deleting everything on exit also isn't an option. Adding built in cache purging solves that problem :)

**Comment by ZIEXED** [comment]
Checking for idleness would be very helpful, just a small notice that explains why the permission is needed would be enough

**Comment by CodingMarkus** [comment]
This feature is already implemented. See screenshots below. 

![Screen Shot 2021-04-21 at 01 20 41](https://user-images.githubusercontent.com/26418089/115475479-fca14980-a23f-11eb-9e71-fc11a116a84f.png)

You can also opt out by domain.
Has someone forgotten to close it?

**Comment by kennethtran93** [comment]
Ah I missed this one in the list. Clearly I didn't search well enough myself.

Thanks.
