### ISSUE TITLE
Site Data Cleanup

### ISSUE THREAD

**Issue by elaine-jackson** [mrdokenny/Cookie-AutoDelete#357]
### Describe the Bug/Feature

Firefox shows many websites have stored "site data" which might be able to be used to store a unique identifier. I think the extension should allow users to have a website's "site data" automatically cleared. Thoughts?

### Screenshot in which the bug can be seen

<img width="708" alt="screen shot 2018-02-15 at 4 41 35 pm" src="https://user-images.githubusercontent.com/8227641/36282606-a5f14eea-126f-11e8-8560-4893596e4274.png">

### Your settings 

- OS/version: macOS
- Browser/version: Firefox
- Cookie AutoDelete version: 2.1.0

**Comment by ke-d** [comment]
Site data is I believe to be IndexedDB which is #171 

The status of that is I'm waiting for an API that can clear IndexedDB by host.
