### ISSUE TITLE
[Feature Request] Channel ID and Database Storage Cleaning In Chrome

### ISSUE THREAD

**Issue by zero77** [mrdokenny/Cookie-AutoDelete#361]
Can you please add support for cleaning the Channel ID and Database Storage cookies in chrome.

They are shown hear chrome://settings/siteData and are currently only cleared if you do it manually.
Thanks

**Comment by ke-d** [comment]
From what it looks like, browsingData API for Chrome doesn't support cleaning other browsing data by host. So there's no point in implementing it since other cleaning extensions do similar stuff already.

**Comment by wiredrunner** [comment]
Is there an active Chromium bug open for this? I know Google deprecated support for token binding which is the supposed reason behind Channel IDs but I see new Channel IDs (unblockable trackers) all the time.

**Comment by kennethtran93** [comment]
Seeing as browsingData API still doesn't support cleaning these by hostname, I will close this issue for now.  If and when these are clearable by hostname/domain, feel free to open a new issue (referencing this issue as well) or comment on this one.
