### ISSUE TITLE
Container-Specific Expressions are not cleaned up

### ISSUE THREAD

**Issue by stoically** [mrdokenny/Cookie-AutoDelete#362]
Hi, thanks for your work on Cookie AutoDelete!

### Describe the Bug/Feature

When disabling all container-relevant Add-ons, the containers are reset. After that, the internal `cookieStoreId` is reused, again starting with `firefox-container-1`. So if containers are reset, Expressions defined by Cookie AutoDelete can end up in the wrong container

### Steps for anyone to reproduce the bug

1. Fresh profile
2. Install latest CAD
3. Create Container in `about:preferences#containers` named "Test"
4. Open Tab in "Test" container and navigate to example.com
5. Set Expression for example.com
6. Disable CAD
7. Create Container in `about:preferences#containers` named "Test2"
8. Open Tab in "Test2" container and navigate to example.com
9. Check the expressions

![cad](https://user-images.githubusercontent.com/29637501/36631562-60c34e2c-1972-11e8-86d5-76d1e8d14ba9.gif)

### Your settings 

Container support enabled

- OS/version: Ubuntu 16.04
- Browser/version: Firefox 58.0.2
- Cookie AutoDelete version: 2.1.0

### Note

[`contextualIdenties.onRemoved`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/contextualIdentities/onRemoved) could help with that. If you identify this as a bug I could look into providing a PR

Related: https://github.com/mozilla/multi-account-containers/issues/864

Best regards

**Comment by ke-d** [comment]
contextualIdentities events are only supported in FF 57 so I would have to bump it the min version for next version.

Also, is the cookieStoreId being reused in Firefox or in CAD?

**Comment by stoically** [comment]
The cookieStoreId is reused from Firefox if the containers are reset, so they start with `firefox-container-1` again, or more specifically with `firefox-container-5`. However, I just realized that `onRemoved` wouldn't help in the case described in this Issue since that event isn't fired when containers are reset, and even if it got fired, CAD would be disabled in this case and couldn't react to it.

If containers are removed normally (without reset), the cookieStoreId isn't reused, so that's no problem.

So this is actually an edge-case and I don't see any sane way for CAD to work around that. I think the way to go would probably be to file an Firefox platform bug to request that container ids are unique through the lifetime of a Firefox profile.

**Comment by cecoates** [comment]
Containerise is interesting in that it seems to look for the container names, and it creates them if they don't exist yet.

(For example, if I have a Containerise rule for "Google" and one already exists, it'll stick the site in that container)

Would using the container name instead of the number work?

**Comment by kennethtran93** [comment]
> Would using the container name instead of the number work?

The only problem is names can be duplicated, despite being different containers.

**Comment by kennethtran93** [comment]
Re-routing this as a feature request to show expressions for lists whose container was removed.  That way the users can remove it themselves.

Meant to rename title instead of creating a new issue/request

**Comment by kennethtran93** [comment]
> So this is actually an edge-case and I don't see any sane way for CAD to work around that. I think the way to go would probably be to file an Firefox platform bug to request that container ids are unique through the lifetime of a Firefox profile.

For those reading this, Mozilla has marked this as intentional.  Therefore, nothing will be done for this portion.  Because we already require containers on install, we expect that to be available. If that is not available (most likely overridden in about:config), the lists will appear as Invalid Container starting in 3.5.0.

I'll work on the `onRemoved` event shortly.

**Comment by kennethtran93** [comment]
v3.6.0 / #820 now has the ability to monitor container events (only when it is active), thus resolving the remaining portion of this issue.
