### ISSUE TITLE
Whitelist - please clarify wildcard meaning

### ISSUE THREAD

**Issue by masgo** [mrdokenny/Cookie-AutoDelete#364]
### Feature

This is more of a request for documentation than a feature request. 

It is not clear (for me) what happens when I only whitelist `*.example.com` **but not** `example.com`.

Will cookies from example.com be also whitelisted? So, does `*.example.com` include `examples.com` or not. If it does include it, it would be good if clicking on "whitelist *.example.com" would also activate the example.com whitelist button.

**Comment by stoically** [comment]
I guess a "How expression work"-link somewhere in the popup or preferences to the wiki would be nice to have, since it is explained there: https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/Documentation#enter-expression

**Comment by masgo** [comment]
Oh, mea culpa. Since so many projects do not use the wiki but work with  README.md and other markdown files I did not even check the wiki. 

The documentation there is sufficient. Just link the whole wiki on the "About" page, right above "Report issues and suggest features". 

Maybe put it also in the README.md of the project.

**Comment by webberian** [comment]
Thanks @stoically for the Wiki link. However, I'm still a bit confused, since `www` technically also is a subdomain of `example.com`. 
So even when I'm sure a website only uses the address `www.example.com`, according to the current Wiki information I would have to use `*.example.com` if I really wanted to include the www subdomain, no?

**Comment by stoically** [comment]
@davdavf `example.com` would not include `www.example.com`, while `*.example.com` would include `www.example.com`, that's correct. What you can do is add `*.example.com` and after that click the edit button (pen) and change it to `www.example.com` - which would make it include explicitly only `www.example.com`.

**Comment by ke-d** [comment]
If I recall correctly `example.com` would match `www.example.com` because the `www.` is ignored.

**Comment by stoically** [comment]
Seems like you're correct

https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/blob/378732431b2c5cb6c43299b7f3c4c705a092e0f2/src/services/libs.js#L17-L18

Might be worth mentioning that in the wiki as well.

**Comment by zekeblue** [comment]
Still not totally clear to me.  Does *.example.com include example.com?  Most often we are presented with both to decide between.  If *.example.com is designated as white or gray, does example.com also have to acted on or is that redundant?

Thanks

**Comment by zekeblue** [comment]
Anyone?

**Comment by ke-d** [comment]
>Does *.example.com include example.com?

@zekeblue Yes

https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/Documentation#enter-expression

As for this issue, I just updated the addon listing page to include those links, and I will be mentioning those links in the readme as well as the about page.

**Comment by zekeblue** [comment]
Thank you for clarifying.
