### ISSUE TITLE
The close button of the Cookie-AutoDelete Popup should never be exactly over the Browser's close button

### ISSUE THREAD

**Issue by luebbe** [mrdokenny/Cookie-AutoDelete#367]
### Describe the Bug/Feature
This is a usability enhancement. On windows the Cookie-AutoDelete popup appears at the top right corner of the monitor. If the browser is in full-screen mode, the popup's close button is exactly on top of the browser's close button. If I want to close the popup, and I'm a little bit too late, I close my browser instead.

Suggestion:
- Position the popup relative to the browser window (e.g. over the browser's toolbar instead of the title bar)
- Make the corner of the popup configurable (e.g. bottom right is less obtrusive)

### Steps for anyone to reproduce the bug
- Try for yourself. You need a little "unlucky" timing.

### Your settings 

- OS/version: Windows 10
- Browser/version: FF 58.02
- Cookie AutoDelete version: 2.1.2

**Comment by ke-d** [comment]
Do you have a screen shot?

**Comment by luebbe** [comment]
Here you go:
![cookieautodeletepopup](https://user-images.githubusercontent.com/3872576/37642236-b2d29990-2c1c-11e8-8442-e6124553fcf6.png)
Maybe this info plays a role too:
- I have a dual monitor setup with a second monitor to the right of the primary.
- My windows toolbar is at the top
- FF is in full-screen mode on the primary monitor
- FF has just been updated to 59.01-64Bit
- Cookie AutoDelete is still 2.1.2

Could other FF Plugins get in the way?!?

**Comment by ke-d** [comment]
Oh extensions don't have control for how the notification popups appear, since the whole point of the notification API is that you can just use it and the browser is responsible for how it appears on different OSes.

Though on my windows machine, the notification appears on the bottom left.

**Comment by luebbe** [comment]
I wonder, how the browser decides where to place the popup. At home I got the same monitor setup, but I have the toolbar at the bottom. Here (Windows 10) the popups show up at the bottom right. On your PC it's bottom left.
Is the way that the browser places the popup tied to the place where windows shows the windows popups?

**Comment by rugk** [comment]
> Is the way that the browser places the popup tied to the place where windows shows the windows popups?

No. I guess it may look for your tzaskbar's position on Windows, but I am not sure. Follow https://bugzilla.mozilla.org/show_bug.cgi?id=1155505 to find out when native Windows 10 notifications get into FF. (other OSes already use it)

**Comment by kennethtran93** [comment]
Closing this issue as browser limitations.  Nothing we can do about this.
