### ISSUE TITLE
Cookie AutoDelete extension installation doesn't sync with Firefox Sync

### ISSUE THREAD

**Issue by echosa** [mrdokenny/Cookie-AutoDelete#369]
### Describe the Bug/Feature
When I install most other extensions from "Firefox Add-ons", I can then sync Firefox on my other computer and the extensions I installed on the first computer will automatically install on the second. This extension does not do that. Everything else syncs fine: other add-ons, preferences, open tabs, etc. Am I doing something wrong, or is this extension specifically not syncing?

### Steps for anyone to reproduce the bug

1. Have two separate installations of Firefox without Cookie AutoDelete. (Separate computers, VMs, etc.)
2. Setup Firefox Sync on each installation of Firefox. (Using the same account, of course.)
3. Install Cookie AutoDelete on one Firefox.
4. Sync that Firefox.
5. Sync the other Firefox.

### Your settings 

- OS/version: Windows 10 (the computer with the extension installed) and macOS 10.13.3 (the computer to which the extension is not syncing)
- Browser/version: Firefox 59.0 on both computers. This was also an issue in previous versions.
- Cookie AutoDelete version: 2.1.2

**Comment by ke-d** [comment]
You are talking about the extension itself right and not the extension settings like in #30

**Comment by echosa** [comment]
That's correct. The extension itself.

**Comment by ke-d** [comment]
It seems like it's a browser bug. Let's see if other people report the same.

**Comment by echosa** [comment]
Is there anything I could try or test for you in the meantime? All my other extensions sync, just not this one.

**Comment by echosa** [comment]
In case it helps, I've found another extension that has this same issue: [Temporary Containers](https://github.com/stoically/temporary-containers/issues/111).

**Comment by ke-d** [comment]
This may or not be related but both Temporary Containers and CAD use the Containers API.

**Comment by echosa** [comment]
Deleted my previous comment, as it was on the wrong issue. Temporary Containers finally synced over, but CAD still has not. I've seen other reports, so I think this issue is already reported for Firefox. I'll check, and report it if not.

**Comment by gmariani** [comment]
Having the same issue, CAD does not sync to other profiles.

**Comment by Ulimn** [comment]
I installed the extension on my Windows 10 machine and it does not get synced to either the other Windows 10 machine or the Ubuntu 18.04 one.

**Comment by echosa** [comment]
It seems as if this is no longer a problem, at least for me. Closing. Reopen if it's still an issue for others.
