### ISSUE TITLE
duration of the notifications

### ISSUE THREAD

**Issue by m-i-k-e-y** [mrdokenny/Cookie-AutoDelete#37]
It would be really nice to be able to set the time how long the notifications are displayed. Currently they are displayed for about 10 sec, I would like to reduce that to 3-4 sec.

**Comment by mrdokenny** [comment]
There's missing Notification APIs in Firefox that exists in Chrome so this is is not possible to do right now.

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/notifications/NotificationOptions#Browser_compatibility

**Comment by m-i-k-e-y** [comment]
Thanks for looking into this.
