### ISSUE TITLE
twitter forgets login even if no cookies are set to delete

### ISSUE THREAD

**Issue by zzcool500** [mrdokenny/Cookie-AutoDelete#370]
i use vivaldi browser, every time i exit the browser it forgets my twitter login, no matter how much i've whitelisted it still forgets.

**Comment by ke-d** [comment]
You probably set the Vivaldi browser to delete all cookies on shutdown. CAD can't affect browser settings so the best thing is to set it to not do that and just let CAD manage your cookies.

**Comment by zzcool500** [comment]
I set Twitter as an exception


---- Kenny Do skrev ----


You probably set the Vivaldi browser to delete all cookies on shutdown. CAD can't affect browser settings so the best thing is to set it to not do that and just let CAD manage your cookies.

**Comment by ke-d** [comment]
in both Cookie AutoDelete and Vivaldi?

**Comment by zzcool500** [comment]
Not vivaldi


---- Kenny Do skrev ----


in both Cookie AutoDelete and Vivaldi?
