### ISSUE TITLE
Not working on some websites

### ISSUE THREAD

**Issue by chetanbasuray** [mrdokenny/Cookie-AutoDelete#375]
### Describe the Bug/Feature
On www.hybris.com/en the cookies created after accepting the cookie policy are never deleted.

### Your settings 
I have Chrome Version 65.0.3325.181 (Official Build) (64-bit) for mac

- OS/version: macOS High Sierra 10.13.3
- Browser/version: Chrome Version 65.0.3325.181
- Cookie AutoDelete version: 2.1.2

**Comment by ke-d** [comment]
Still works fine for me. Cookies are deleted when all tabs of that site is closed if you don't know how CAD works.
