### ISSUE TITLE
What about "Net Cookies" in Appdata?

### ISSUE THREAD

**Issue by jj123** [mrdokenny/Cookie-AutoDelete#377]
### Describe the Bug/Feature

When I do a scan with SuperAntiSpyware it always finds lots of "Net Cookies" in the following location:
Appdata/Local/Microsoft/Windows/NetCookies/xxxxx.

I'm using "Cookie AutoDelete" with Firefox, but it's obviously not deleting the "Net Cookies".
Are those Adobe/Macromedia "Flash Cookies"?

Whatever they are, what app will delete those automatically when I close the tab?

Or are those Flash Cookies which supposedly make returning to a site faster as it is storing some of the data in the Flash Cookie?

Just scanned with SAS and there were 302 of those.
Meanwhile with normal cookies Cookie AutoDelete does its job and deletes them when I close a tab (unless I've given special instructions).

### Your settings 

- OS/version: Windows 10 Home
- Browser/version: Firefox 58.0.1 (64-bit)
- Cookie AutoDelete version:   2.1.2

**Comment by xopez** [comment]
It can't be cookies from Firefox itself.
I guess it's something with Internet Explorer or Microsoft Edge.

**Comment by ke-d** [comment]
Yeah I agree with @xopez. This seems like another browser cookies.
