### ISSUE TITLE
Android google search history not cleard

### ISSUE THREAD

**Issue by markwellis** [mrdokenny/Cookie-AutoDelete#381]
Using firefox address search, google search history is not cleared between requests. If I change the google settings (down the bottom of the page) to "Do not save seaches", it is not saved between requests (I assume this is in the cookie and this is cleared)

I've attached screen shots.
![screenshot_20180409-160521](https://user-images.githubusercontent.com/5102352/38506083-6838cf70-3c08-11e8-993e-e894091d938e.png)
![screenshot_20180409-160534](https://user-images.githubusercontent.com/5102352/38506084-68550a96-3c08-11e8-8823-cbeb168e0c5a.png)
![screenshot_20180409-160808](https://user-images.githubusercontent.com/5102352/38506085-6872c298-3c08-11e8-9d9a-f25616ae5e55.png)

I hope this is clear. I'm on the Default settings,

- OS/version: 
Android 7.1.1 moto G5S plus

- Browser/version: 
Firefox 59.0.2 android

- Cookie AutoDelete version: 
2.1.2

**Comment by kennethtran93** [comment]
According to this issue in Firefox Focus for Android https://github.com/mozilla-mobile/focus-android/issues/1306 , the history appears to be stored in localStorage.

**Comment by ke-d** [comment]
Hmm I feel like it should have been deleted under enabling Localstorage Cleanup, so maybe it's a problem with FF Android?

**Comment by rhutchinzon** [comment]
If I select 'Clear localstorage for this domain' while google is open, the history is cleared.  Close the google tab, and google cookies are deleted.  So localstorage is not being cleared automatically with the cookies.  
Localstorage Cleanup is checked in settings.
I'm not sure whether this happens with all sites.

**Comment by ke-d** [comment]
@rhutchinzon See this [comment](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/486#issuecomment-454221440).

**Comment by kennethtran93** [comment]
Closing this issue as browserbug and can't fix at this time as webextensions and android localstorage is still not implemented yet.

If it gets implemented again, feel free to raise this issue or start a new one and reference this one.
