### ISSUE TITLE
Missing Privacy Policy & Terms of Service

### ISSUE THREAD

**Issue by DemeRain** [mrdokenny/Cookie-AutoDelete#382]
### Describe the Bug/Feature 
According to the Firefox permissions, this add-on can:

    Access your data for all websites
    Clear recent browsing history, cookies, and related data
    Display notifications to you
    Read and modify privacy settings
    Access browser tabs

Where is your privacy policy and/or terms of service?  I am having trouble finding it.  

### Screenshot in which the bug can be seen
![image](https://user-images.githubusercontent.com/38267873/38591795-91bf331c-3d06-11e8-9572-e5134dca82ab.png)

### Steps for anyone to reproduce the bug 
I can find no mention of a privacy policy or terms of service on your homepage located at: https://github.com/Cookie-AutoDelete/Cookie-AutoDelete.  
Please note, other Firefox addons do list a privacy policy their GitHub page.
I really like your add-on.  But if I am to continue to use it, this information must be disclosed.  

### Your settings 

- OS/version: Windows 10 & Mac OS 10
- Browser/version: Firefox Quantum 59.0.2
- Cookie AutoDelete version: 2.1.2

**Comment by ansell** [comment]
https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/Privacy-Policy

**Comment by DemeRain** [comment]
Much appreciated! 

Just a suggestion, add a link to the privacy policy on your GitHub homepage.  Considering the current headlines, I'm not going to be the only one inquiring about these things.  That privacy policy is not in an obvious location. However I do thank you for the plain language.

**Comment by momonala** [comment]
Just curious, why does the app need to "Access your data for all websites"? Thanks

**Comment by ghost** [comment]
Because, CAD will be very limited if cookies of only some pages will be accessible https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/cookies

>In order to use this API [cookies api], an add-on must specify the "cookies" API permission in its manifest, **along with host permissions for any sites for which it wishes to access cookies**.
