### ISSUE TITLE
Unable to add URLs to whitelist

### ISSUE THREAD

**Issue by diamond-lizard** [mrdokenny/Cookie-AutoDelete#383]
### Describe the Bug/Feature

Unable to add URL.  Clicking on the "ADD URL" button after typing in a URL does nothing.

### Steps for anyone to reproduce the bug

From a fresh install of Cookie AutoDelete, open its preferences, type in a URL, click "ADD URL"

![cookie-autodelete-whitelist](https://user-images.githubusercontent.com/31175456/38651968-c221eaba-3db8-11e8-96eb-69f186723729.png)

Alternatively, just click "Never Clean (WhiteList)" from the Cookie AutoDelete menu.  That also does not add anything to the whitelist.

### Your settings 

- OS/version: Gentoo Linux, amd64, kernel 4.15.9-ck
- Browser/version: Firefox 52.6.0, 64 bit
- Cookie AutoDelete version: 1.4.4

Please note that I'm running the NoScript extension, which disables javascript.  I'm not sure if that matters or not.

**Comment by kennethtran93** [comment]
I don't think the old version is being maintained since I believe this was supposed to be a webextension.  Use Self-Destructing Cookies if you are on legacy extensions.

Some javascript is used in the extension, though I am not sure if NoScript is blocking extension pages.
Just my two cents here.

**Comment by ke-d** [comment]
1.4.4 is unsupported. Also you don't need the `https://` part.
