### ISSUE TITLE
Temporarily disable Auto-Clean

### ISSUE THREAD

**Issue by dacav** [mrdokenny/Cookie-AutoDelete#384]
#### Scenario:

I want to buy a plane ticket. The procedure will redirect me to from the flight company website to the website of my bank, and later I get a further redirection to the flight company's website. I don't want to whitelist any of these sites, but at the same time I'm very likely to lose my session in between redirects.

I'm usually disabling Auto-Clean in this situation, but then I forget to re-enable it when I'm done with the transaction.

#### Feature:

Would it be feasible to have `Autoclean Enable` + `Autoclean Temporarily Disabled` + `Autoclean Disabled` as options?

**Comment by kennethtran93** [comment]
Does the greylist option not work for you?  Greylist supposedly clear cookies upon browser restart.

**Comment by ke-d** [comment]
I agree, you are better off greylisting those sites, so it's automatic every time and you don't have to deal with toggling to `Autoclean Temporarily Disabled`.

**Comment by dacav** [comment]
It could be a solution. Next time I'll have to do a plane ticket or so, I'll try.

The only problem I can foresee is about redirections. Say `A -> B -> C -> B -> A`. You have to be aware of all of the sites. If you did not greylist `B` you would lose the session right after the `B -> C` redirection, and get a broken workflow with `C -> B -> A`.

**Comment by chiraag-nataraj** [comment]
I know this probably isn't that helpful, but I have a "FailSafe" profile which doesn't have any extensions and launches in permanent private browsing mode, which means any tracking only lasts for the session. I often find it easier to use that than try to figure out which of my myriad extensions in my normal profile might break the site :joy:

**Comment by Grossdm** [comment]
Am I overlooking something, or does this not have an obvious solution?

Just disabling the addon would solve this use case, would it not?

**Comment by kennethtran93** [comment]
> Am I overlooking something, or does this not have an obvious solution?
> 
> Just disabling the addon would solve this use case, would it not?

There's a reason why we didn't mention that in the first place...
As from the first post:
> _I'm usually disabling Auto-Clean in this situation, but then I forget to re-enable it when I'm done with the transaction._

**Comment by kennethtran93** [comment]
A similar feature request has been made in #535.  Closing this one for that as that may just be a better solution if we do implement it.
