### ISSUE TITLE
Deleting HSTS "cookies" ?

### ISSUE THREAD

**Issue by Yyuzu** [mrdokenny/Cookie-AutoDelete#385]
Hi,

Is there a way for an extension to delete HSTS information for a website ?

For instance, Firefox is storing HSTS "cookies" in SiteSecurityServiceState.txt profile file. This could be used to obtain a list of visited sites or even allow some tracking (see https://thehackernews.com/2018/03/hsts-supercookie-tracking.html )

Cheers

**Comment by ke-d** [comment]
https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/FAQ:-Common-Questions-and-Issues#what-is-the-state-of-the-webextension-api-to-clean-x-data

You can set `SiteSecurityServiceState.txt` to read only or use FPI.

**Comment by ansell** [comment]
Had to look up FPI myself, so for those others who also aren't aware of what FPI refers to, it is "First-party isolation". It is a relatively recent Firefox feature:

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/cookies#First-party_isolation

https://www.ghacks.net/2017/11/22/how-to-enable-first-party-isolation-in-firefox/

**Comment by Yyuzu** [comment]
@mrdokenny Thank you very much, I already had FPI active, but I wasn't aware it was protecting from accessing other site's HSTS info.

Although, are you sure it is the case ? HSTS "cookies" are not real cookies, it's information stored into a txt file in the profile, and I don't know how Firefox handles it.

**Comment by Thorin-Oakenpants** [comment]
^^ https://bugzilla.mozilla.org/show_bug.cgi?id=1323644  FF54+

**Comment by Yyuzu** [comment]
Perfect, thank you @Thorin-Oakenpants :)
