### ISSUE TITLE
Always show notification when manually clearing cookies

### ISSUE THREAD

**Issue by haarp** [mrdokenny/Cookie-AutoDelete#386]
I think it would be useful to show the notification when manually clearing cookies via the toolbar icon, even if the notification is disabled in the settings.

This way the user has some certainty that the button he just clicked had an effect.

Thanks!

**Comment by ke-d** [comment]
If many people want this as the default I can do it but I'm implementing #209 which will allow you to see the log without needing to enable notifications. So this request could be redundant tbh.

**Comment by kennethtran93** [comment]
Update:  This feature will be implemented as a nice side effect while working on Right-Click context menus.  After moving the relevant functions from the popup to the Libs section, I enhanced it further.

Notifications will now be shown regardless of setting for the manual cleanup of this domain for cookies and localStorage, with a brief removal counter for each.

**Comment by kennethtran93** [comment]
If you know how to test an unsigned extension, feel free to try it out through the linked PR #753

**Comment by jtheletter** [comment]
I disagree that this new feature would be desirable. I certainly disagree with it being pushed on all users without an opt-out.
