### ISSUE TITLE
Facebook Cookies

### ISSUE THREAD

**Issue by jeakmc** [mrdokenny/Cookie-AutoDelete#388]
### Describe the Bug/Feature

Facebook cookies are not white listed, but when clean cookies, FB cookies remain

### Your settings 

- OS/version: Mac 10.12.6
- Browser/version: Firefox/59.0.2 
- Cookie AutoDelete version: 2.1.2

**Comment by jeakmc** [comment]
Anyone have any idea why Facebook cookies (not white listed) do not delete when click on clean

**Comment by ghost** [comment]
Why you think they remain? Where you see them?

**Comment by jeakmc** [comment]
Yes ... When I go to the "show cookies" in the Firefox preferences, the cookies for FB are there ... even though FB not white listed and after cleaning the cookies ... others  not white list do not remain

**Comment by ke-d** [comment]
Feel free to try the latest beta which has the cleanup log to see why those cookies are not being deleted.

**Comment by Yyuzu** [comment]
Just checking here, when you cleanup cookies, do you still have a facebook tab or window opened somewhere ? The site might be creating cookies with requests between the cleanup and your check.

**Comment by jeakmc** [comment]
Tab is closed.  Even can quit firefox and restart with blank page and FB cookie is still there .... even cleaning before quitting or after restarting.

Can even manually delete FB cookies and after opening FB the cookies come back, as expected, but remain despite cleaning

Is anyone else have this with FB cookies

**Comment by jeakmc** [comment]
Could the Facebook cookies have something different so the cannot be auto deleted?

**Comment by ghost** [comment]
Maybe some extension is setting them?

**Comment by jeakmc** [comment]
gwarser ... that was it.  Thanks

It was  Facebook Container

Facebook Container by Mozilla

Prevent Facebook from tracking you around the web. The Facebook Container extension for Firefox helps you take control and isolate your web activity from Facebook.

**Comment by ghost** [comment]
Then enable containers support in CAD

**Comment by javenschuetz** [comment]
It was facebook containers for myself. Enabling container support killed them. However, apparently this conflicts with deleting localStorage which seems non ideal

**Comment by ke-d** [comment]
Side effects are described in #371. Personally, I haven't noticed anything too terrible with both settings on.
