### ISSUE TITLE
No update for Firefox (stuck at 1.2.0)

### ISSUE THREAD

**Issue by Primokorn** [mrdokenny/Cookie-AutoDelete#39]
Hi,
The Chrome extension has been updated to 1.3.0 several days ago but I'm still on 1.2.0 for Firefox.
Is there an issue with Firefox?
Thank you.

**Comment by mrdokenny** [comment]
Review Process :( 166/210. Cookie AutoDelete (and probably other extensions with a moderately sized codebase) has problems with long reviews in AMO. First time it took about [3 months](https://discourse.mozilla-community.org/t/submitted-addon-more-than-a-month-ago-stuck-at-124-update-review-completed/14584/11) and it was getting stuck at certain parts of the queue. 

At the current rate of this update queue, probably 1-2 weeks.

Do you need a signed version by any chance?

**Comment by Primokorn** [comment]
Wow! It's the first time that I'm checking an extension on 2 browsers.
I know the first submission to AMO takes a while but I didn't know that we have such a delay for updates...
I'm going to grab the update from the releases tab.

**Comment by mrdokenny** [comment]
It's not signed so unless you are on FF Developer or Nightly ([and turn off signing](https://wiki.mozilla.org/Add-ons/Extension_Signing)), it won't install.

**Comment by Primokorn** [comment]
Oh yes you're right then please send a signed version.

**Comment by mrdokenny** [comment]
I added the unlisted signed version under the 1.3.0 release (I added the RC because AMO won't allow me to upload the same '1.3.0' version). Also note that it's unlisted, so it won't autoupdate.

**Comment by mrdokenny** [comment]
I think it might be possible to set up the automatic builds to do automatic signing using AMOs API, so maybe something I look into in the future.

**Comment by Primokorn** [comment]
Auto-updates are always disabled on my end.
Update done, thanks.
