### ISSUE TITLE
Suggested option: Whitelist saved Firefox logins

### ISSUE THREAD

**Issue by davidhedlund** [mrdokenny/Cookie-AutoDelete#394]
I suggest a new option, "Whitelist domains in the native Saved Logins".

The saved logins can be located in Firefox: Edit -> Preferences -> Privacy & Security (about:preferences#privacy) -> Saved Logins...

The "Enable Automatic Cleaning" option is enabled for me so I'm always logged out if I don't whitelist the domains in Cookie Autodelete, something I have to do each time I save a new login in the browser which is not convenient. The proposed suggestion could save me time from doing that.

**Comment by ke-d** [comment]
I'll have to get back to you if this is possible through current WebExtension APIs (which I believe that they don't have one currently).

**Comment by ke-d** [comment]
Sorry for the super late response, but I found a related bug for this feature.

https://bugzilla.mozilla.org/show_bug.cgi?id=1324919

So not possible currently.

**Comment by kennethtran93** [comment]
As this issue is blocked by browser limitations, I'm going to close this issue.  If and when extensions can access the Firefox backends again, then feel free to revive this or start a new one.
