### ISSUE TITLE
Crashes FireFox on any IPv6 website

### ISSUE THREAD

**Issue by lightswitch05** [mrdokenny/Cookie-AutoDelete#398]
### Describe the Bug/Feature

This extension crashes Firefox if you open any website using an IPv6 address. 

Example, Cloudflare's DNS service: https://[2606:4700:4700::1111]/ (IPv6 version of https://1.1.1.1/)

### Steps for anyone to reproduce the bug

Go to any IPv6 web address in firefox with this extension enabled

### Your settings 

- OS/version: Macbook Pro High Sierra 10.13.4
- Browser/version: Firefox 60.0.1
- Cookie AutoDelete version: 2.2.0

**Comment by zcater** [comment]
Can't confirm with 60.0.2 ESR on Linux. Site loads fine.

**Comment by lightswitch05** [comment]
I also opened up a bug with Firefox that includes a crash report https://bugzilla.mozilla.org/show_bug.cgi?id=1470156

**Comment by lightswitch05** [comment]
Firefox confirmed this bug and is working on a fix. I'm fine with this ticket being closed unless you wish to leave it open for tracking

**Comment by lightswitch05** [comment]
This is fixed in FireFox 63
