### ISSUE TITLE
FF List Of Exeption Edit Bug

### ISSUE THREAD

**Issue by Acid-Crash** [mrdokenny/Cookie-AutoDelete#399]
### Describe the Bug
In List Of Exemption when editing particular entry there isn't enough width for UI buttons. This might be fixed when changing from `width: calc(100% - 70px)` to `width: calc(100% - 90px)`

### Screenshot in which the bug can be seen

![image](https://user-images.githubusercontent.com/32600318/40666182-c748f0ea-6367-11e8-9eca-ff4eab3c4cbd.png)

### Steps for anyone to reproduce the bug

- Open List Of Exemption
- Try to edit any entry
- Observe how height for the entry is increased

### Your settings 
- OS/version: Win 10x64 RS3
- Browser/version: Firefox 60.0.1 (64-bit)
- Cookie AutoDelete version: 2.2.0

**Comment by kennethtran93** [comment]
If you would like to give it a try, head on over to PR #713 and download the latest build (in comments) and let me know if there's any tweaks that need to be looked into.

**Comment by Acid-Crash** [comment]
Hi @kennethtran93 
Not sure if suggestion was addressed to me.
Still, I have tested the latest build.
The issue I've reported seems to be fixed.
However, I've noticed that UI elements become bigger, that doesn't look good with default DPI
Tested on Nightly 78.0a1 (2020-05-06) (64-bit), Win 10x64

![изображение](https://user-images.githubusercontent.com/32600318/81283594-94c11580-9065-11ea-9851-5108658b4c3c.png)

**Comment by kennethtran93** [comment]
May have to do with the extra info added on the cleanup log line regarding private browsing.  I'll add a line break to the sentences so that it doesn't take up that much more room.  I still haven't figured out how to scale down the popup as an option yet.
