### ISSUE TITLE
"-" or number in top-level domain

### ISSUE THREAD

**Issue by noooz** [mrdokenny/Cookie-AutoDelete#40]
I have cookies for domains like "srv-test01" and "test.i2p".
In both cases I get the following exception in chrome:

`background-webpack.js:133 Uncaught (in promise) TypeError: Cannot read property '0' of null
    at Object.extractBaseDomain (background-webpack.js:133)
    at CleanupService.cleanCookies (background-webpack.js:248)
    at browser.cookies.getAll.then (background-webpack.js:327)
    at <anonymous>
`

When I get this exception no cookies are deleted. Even for other domains.

**Comment by mrdokenny** [comment]
Thanks for reporting and adding console logs. It really helps. 

Are "srv-test01" and "test.i2p" top level domains like "a.srv-test01" and "b.test.i2p"? 

Because what extractBaseDomain() does is it takes something like "sub.sub.domain.com" and it returns "sub.domain.com" using RegExp.

**Comment by noooz** [comment]
"srv-test01" and "test.i2p" are the full domain names.
Like in http://srv-test01/ and http://test.i2p/

**Comment by mrdokenny** [comment]
Can you test 1.3.1 under releases?

https://www.howtogeek.com/120743/how-to-install-extensions-from-outside-the-chrome-web-store/

**Comment by m-i-k-e-y** [comment]
At work we have such a domain, too. Just tested version 1.3.1 with that site and the regex error is gone.

**Comment by mrdokenny** [comment]
@m-i-k-e-y Are the cookies from those domains deleted as expected?

**Comment by mrdokenny** [comment]
Ok I updated the releases page to include a unlisted signed version of 1.3.1 for Firefox and Chrome users should be getting the 1.3.1 update soon.

**Comment by noooz** [comment]
Wow! So quick! It work's. Thank you very much.

**Comment by m-i-k-e-y** [comment]
@mrdokenny Yes, they are. Thanks
