### ISSUE TITLE
Setings toolbar button looses button text 

### ISSUE THREAD

**Issue by LordYanaek** [mrdokenny/Cookie-AutoDelete#401]
Hello. I really like this add-on as it makes managing cookies so much easier (or it should) but i have a strange bug making it hard to use. Sometimes (not always but often) the menu/pop-up that shows when you click the toolbar icon and allows you to whitelist/greylist websites looses all text for the buttons making it extremely hard to use. You can see an example of this on the screenshot below.

![screenshot](https://user-images.githubusercontent.com/4322192/40711366-44ff99c4-63fb-11e8-846c-819f8fbd4ac0.png)

Note that, as you can see (in french, sorry for that) the buttons are still working if i can point the tiny blue/grey dots but without text it's rather annoying to change those settings and i have no way of knowing which line is related to the specific page or the domain.

I didn't see anything on the console and still havn't found what triggers that issue.

**My settings**
Windows 10
Mozilla Firefox 60.0.1 (64 bits)
Cookie AutoDelete 2.2.0

**Comment by kennethtran93** [comment]
I'm using Windows 10 Pro with Firefox 61.0 64-bit latest version as of this post and it works fine for me.  Is there another plugin/extension that may be causing that issue?

**Comment by kennethtran93** [comment]
#380 was a very similar issue and was solved by the user removing WindowBlinds which solved their problem.  Do you have this installed?

**Comment by ke-d** [comment]
Has this been solved? @LordYanaek

**Comment by LordYanaek** [comment]
Hi. Sorry i was on holiday when the answer came and didn't realise it had been answered until now.

Yes, i have WindowBlinds, the default windows UI is becoming increasingly ugly with each new version and our options for customizing it get reduced at the same time. It's my computer, not one of MS employees so i like it my way, probably got this habit working on Linux systems. Anyway, if i have to choose between WB and a Firefox add-on i'll keep WB.

It was set to ignore Firefox however so in theory shouldn't have affected it. I unloaded it to test and currently the icons show correctly but as i said, the issue didn't always occur. I'll file a bug report to Stardock anyway in case WindowBlinds still somehow affects applications even when it's set to ignore.

If really it's related to WB a workaround could be to temporarily unload it before starting FF and then restarting it as i still have the icons after restating WB when FF was already running. Maybe FF could be auto-started before WB but i'm not a Windows Guru and don't know if it's possible to precisely control the order in which processes are auto-started.

**Comment by ke-d** [comment]
Looks like it's an external issue so closing.
