### ISSUE TITLE
Opera support: a one-line change

### ISSUE THREAD

**Issue by zedug** [mrdokenny/Cookie-AutoDelete#402]
v2.2.0 broke in Opera, with whitelisted cookies being deleted.

After some tinkering around the offending function is getStoreId in backgroundBundle.js

Simply adding an OR to support Opera, ie replacing

`if (storeId === "firefox-default" || !getSetting(state, "contextualIdentities") && storeId !== "firefox-private" && state.cache.browserDetect === "Firefox" || state.cache.browserDetect === "Chrome" && storeId === "0") {`

with

`if (storeId === "firefox-default" || !getSetting(state, "contextualIdentities") && storeId !== "firefox-private" && state.cache.browserDetect === "Firefox" || state.cache.browserDetect === "Chrome" && storeId === "0" || state.cache.browserDetect === "Opera" && storeId === "0") {`

does the trick.

I'm not familiar with git so I figured it would be simple to mention this here rather than trying to figure out how to do a proper merge request....

**Comment by czhang03** [comment]
Please support opera. I have been using this extension on firefox for a long time and have recently switched to opera. This is the only good cookie deleter I know of. Thank you so much.

**Comment by ke-d** [comment]
Done.
