### ISSUE TITLE
doesn't work most of the time

### ISSUE THREAD

**Issue by zzcool** [mrdokenny/Cookie-AutoDelete#404]
i tried two different extensions for cookie cleaners and none work the way they should, i have whitelisted cookies on both cookiecleaners but cookies still find a way to make past, one cookie cleaner is set to autoremove cookies like every few seconds, this one is set to clear all cookies on close, and yet i still find github as a cookie in my chrome can't check on vivaldi as i can't check cookies there, none of my cookie cleaners did anything to remove it, i have other specific websites too whose cookies aren't touched no matter what i do, no cookiecleaner has ever worked the way it should, twitter somehow forgets it's login every single time so now i use the twitter app on windows, outlook forgets it's login too now so i can't use outlook either.

i use x64 windows 10 with chrome and vivaldi

EDIT:i just got a popup notification that github cookie was removed, but when i check my cookie list i still see github in it?

github.com: Clean because github.com is not in the White/Grey lists or in any open tabs

but i still have a github cookie

**Comment by ke-d** [comment]
Probably the cookie is corrupted to the point where the cookie removal API can't remove it since you said you tried multiple cookie cleaners. In this case, it's up to the browser makers to fix it.

**Comment by murphy625** [comment]
Doesn't work for me either..   are my cookies corrupted to?   LOL..   Software is crap
