### ISSUE TITLE
Document all cookie types and their API status

### ISSUE THREAD

**Issue by davidhedlund** [mrdokenny/Cookie-AutoDelete#406]
Can you please add all common terms for the cookie types listed in https://en.wikipedia.org/wiki/HTTP_cookie#Terminology and their API status to https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/FAQ:-Common-Questions-and-Issues#what-is-the-state-of-the-webextension-api-to-clean-x-data ?

* Session cookie, also known as an in-memory cookie, transient cookie or non-persistent cookie
* Persistent cookie
* Secure cookie
* Http-only cookie
* Same-site cookie -- Supporting Same-Site Cookies in Firefox 60 - https://blog.mozilla.org/security/2018/04/24/same-site-cookies-in-firefox-60/
* Third-party cookie
* Supercookie -- The Mozilla Foundation maintains the Public Suffix List (https://publicsuffix.org/) for the security and privacy policies of its Firefox web browser
* Zombie cookie -- The WebExtention [Self Destroying Cookies ](https://addons.mozilla.org/en-US/firefox/addon/self-destructing-cookies-1/) is used to remove zombie cookies.
* Local shared objects (LSOs), commonly called Flash cookies -- The WebExtention [Clear Flash Cookies ](https://addons.mozilla.org/en-US/firefox/addon/clear-flash-cookies/) is used to remove Local shared objects (LSOs), commonly called (Flash cookies).

**Comment by davidhedlund** [comment]
https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/261

**Comment by ke-d** [comment]
For all intents and purposes, almost all types "cookies" are treated would be considered the same thing by the WebExtension API anyways. In addition, some types of "cookies" are going to be defunct anyways with flash going away. I'm more interested in other site data other than cookies and also would like to keep that section simple.
