### ISSUE TITLE
store is not defined

### ISSUE THREAD

**Issue by slavkoja** [mrdokenny/Cookie-AutoDelete#407]
### Describe the Bug/Feature

I recently created new/fresh profile for my FF 56 (i have some extensions, which still have no replacement in 57+). I created it mostly due CAD, becaue it doesn't clean whitelisted cookies. I install most of my extensions from old profile, and imported CAD's lists. At startup in terminal i see a lot of repeating errors:
```
Extension error: TypeError: store is undefined moz-extension://f00fb2d9-d55a-4d7e-bc12-578d24af91c9/backgroundBundle.js 742
[[Exception stack
onTabUpdate@moz-extension://f00fb2d9-d55a-4d7e-bc12-578d24af91c9/backgroundBundle.js:742:13
Current stack
runSafeSyncWithoutClone@resource://gre/modules/ExtensionUtils.jsm:63:129
runSafeWithoutClone@resource://gre/modules/ExtensionCommon.jsm:174:38
fire@resource://gre/modules/ExtensionChild.jsm:771:71
receiveMessage@resource://gre/modules/ExtensionChild.jsm:773:76
_callHandlers/<@resource://gre/modules/MessageChannel.jsm:587:17
_callHandlers@resource://gre/modules/MessageChannel.jsm:586:14
_handleMessage/deferred.promise<@resource://gre/modules/MessageChannel.jsm:651:7
_handleMessage@resource://gre/modules/MessageChannel.jsm:648:24
receiveMessage@resource://gre/modules/MessageChannel.jsm:163:5
]]
```
All seems to work, the cookies are deleted as expected, but the strange thing is, that with old profile these messages are missing (but CAD is not working properly).

- OS/version: Funtoo Linux
- Browser/version: FF 56.0
- Cookie AutoDelete version:  	2.2.0

**Comment by ke-d** [comment]
Looks like the CAD's storage got corrupted. At this point, CAD is using some newer features in later FF so I won't be able to support older versions any longer. You could try copying the extensions settings directly from the old profile.

**Comment by Mathnerd314** [comment]
I get the same error in FF 65 Developer Edition, Windows, Cookie AutoDelete v2.2.0, and a relatively fresh profile. It suggests there is a bug of some kind.
