### ISSUE TITLE
French translation is bad

### ISSUE THREAD

**Issue by mooms06** [mrdokenny/Cookie-AutoDelete#409]
Hi,

You've translated `cookies` by `temoins`, but in French we use the term `cookie` as well, nobody knows what's a `temoin` is in this context (it means `witness` in French and nothing else).

I think you should keep the original name of the extension, `Cookie AutoDelete` is way better (and shorter) than `Suppression automatique des témoins`, or even `Suppression automatique des cookies` (the correct translation).

It freaked me out when I seen it, because I installed `Cookie AutoDelete`, not `Suppression automatique des témoins`.

edit: , can you also consider adding an option to keep the english version ?
I much prefer an English version than a broken and confusing French translation.

Regards.

**Comment by Yyuzu** [comment]
I must say I felt like a criminal when I discovered my extensions was eliminating witnesses :-)

**Comment by mooms06** [comment]
Indeed, I had not considered it like that, it's even worse than I had thought :)

**Comment by ghost** [comment]
Help translating, mark invalid translations, and propose your own in Crowdin https://crowdin.com/project/cookie-autodelete

**Comment by mooms06** [comment]
Done. Please approve my changes.

**Comment by anewuser** [comment]
_Témoin_ is used in Quebec. If possible, you may want to consider creating separate translations for Canadians and the rest of the francophonie to avoid edit wars.

https://www.google.com/search?hl=en&q=site%3Aca+fichier+t%C3%A9moin

**Comment by mooms06** [comment]
Yes, that could be a good solution.
Also, an option to choose the translation inside the extension should be a good thing (I much prefer using English than a broken translation).

**Comment by ke-d** [comment]
> Also, an option to choose the translation inside the extension should be a good thing (I much prefer using English than a broken translation).

Not sure if possible with current WebExtension APIs, but the original issue seems to be resolved. I'll eventually push the CrowdIn changes before the next release.
