### ISSUE TITLE
Cookie AutoDelete prevents Firefox webclipper from working

### ISSUE THREAD

**Issue by antec001** [mrdokenny/Cookie-AutoDelete#411]
### Your settings 

- OS/version: 
- Browser/version: 
- Cookie AutoDelete version: 

Windows 10 Pro version 1803
Firefox 60.0.2 64 bit.
Cookie AutoDelete 2.2.0
Evernote Webclipper 6.13.2 (3283464/1.1.0.926)

When I try to clip a webpage, the Evernote log in box pops up.  When I log in, the Evernote box disappears and the page isn't clipped.

**Comment by Grossdm** [comment]
On Windows, IrfanView is a nice image viewer with an easy to use screen capture feature. Just FYI. 

https://www.irfanview.com

**Comment by ke-d** [comment]
Maybe whitelist/greylist the Evernote site?

**Comment by antec001** [comment]
That seemed to do it, thanks!
________________________________
