### ISSUE TITLE
Recover deleted cookies

### ISSUE THREAD

**Issue by lvsunz3748** [mrdokenny/Cookie-AutoDelete#413]
### Your settings 

- OS/version: 
- Browser/version: 
- Cookie AutoDelete version:

**Comment by lvsunz3748** [comment]
HELP! Just added Cookie AutoDelete 2.2.0 to Firefox 60.0 & all cookies were deleted before I knew how to proceed. Cookie Log shows all deleted cookies- how can I recover deleted cookies? Running Win 10, 64 bit. Thank you.

**Comment by ke-d** [comment]
Unfortunately there's no way to recover cookies at this point, the tracker for that is #196
