### ISSUE TITLE
CCleaner

### ISSUE THREAD

**Issue by Jmailatunseenis** [mrdokenny/Cookie-AutoDelete#414]
CCleaner still sees a lot of cookies.
Or are they not to supose to go away after an x period of secondes?

**Comment by kennethtran93** [comment]
Did you enable autodelete? It should generally autodelete on browser startup, unless manually triggered.  Also note that this extension, only detects that browser's cookies, even though it is available for both Firefox and Chrome.

**Comment by Jmailatunseenis** [comment]
Yes, i did.
But i still use Firefox 56.0 and i don’t want to go to Quantum.
Maybe there is the problem :)

**Comment by kennethtran93** [comment]
Yes the extension has migrated into 2.x which requires Quantum/ 57.0+ as it's now a webextension, hence future Firefox versions have updated APIs. v1.x isn't maintained anymore.

**Comment by Jmailatunseenis** [comment]
Oke thanks..
Have a nice day.

**Comment by ke-d** [comment]
https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/FAQ:-Common-Questions-and-Issues#what-is-the-state-of-the-webextension-api-to-clean-x-data

HSTS
