### ISSUE TITLE
Feature Request: One Click Cookie Delete Toolbar Shortcut

### ISSUE THREAD

**Issue by AirplaneRandy** [mrdokenny/Cookie-AutoDelete#415]
I'm finding it a hassle to delete cookies using this add on. I would like the ability to add a shortcut to the toolbar that allows me to press "Clean, include open tabs" in just one click. Normally that would require three steps instead of just one;

1. Press the Icon
2. Open the Clean drop down menu
3. Press "Clean, include open tabs"

Can you guys just simply allow us to add a toolbar button that works in a single click? 
Toolbar Buttons would include;
"Clean, include open tabs"
"Clear cookies for this domain"
"Clear localstorage for this domain"
"Clean"

Thanks.

EDIT: I may suggest that if you right click the proposed shortcut icon, it brings down the normal Cookie AutoDelete Menu.

**Comment by kennethtran93** [comment]
Unfortunately both Firefox and Google Chrome's right-click on icon shows a context menu, which I am not sure if that's changeable to show the custom CAD menu instead (though it may be able to show additional options such as the clean options).  Also I don't think Chrome has any options to have duplicate copies of the shortcut icon on the toolbar.

**Comment by ke-d** [comment]
There's always the page action.

**Comment by kennethtran93** [comment]
This may be resolved through using right-click context menus.  See PR #753.  Right-click has all clean options (under a submenu) if right-clicking the icon / page.

> EDIT: I may suggest that if you right click the proposed shortcut icon, it brings down the normal Cookie AutoDelete Menu.

That is not possible as the right-click cannot be overridden, but only have items added onto it as is done through this PR.
