### ISSUE TITLE
Feature request: Selective cookie cleaning

### ISSUE THREAD

**Issue by agyild** [mrdokenny/Cookie-AutoDelete#416]
Being able to selectively clean cookies would be beneficial. Especially in cases where the `COOKIE_LANG` is language preference and `COOKIE_TRACK` is for tracking. In this case the user would be able to keep `COOKIE_LANG` but delete `COOKIE_TRACK` for that particular domain.

**Comment by jrie** [comment]
Following along, there is a add-on which does exactly allow you to do this already what you ask for:
https://addons.mozilla.org/en-US/firefox/addon/flag-cookies/

It's source is also on github:
https://github.com/jrie/flagCookies

And it's actively developed.

I don't want to argue it's a replacement for Cookie-AutoDelete, but it provides another level of control for exactly this use case.

**Comment by ghost** [comment]
@agyild your suggestion, but reversed - https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/68
Will allow to keep the whitelisted ones (including specific cookies, selected by name) and delete all the others.

**Comment by ke-d** [comment]
I'm going to close this in favor of #68 as it make sense currently with the codebase.
