### ISSUE TITLE
Suggestion: moveable pop-up

### ISSUE THREAD

**Issue by fentonh1** [mrdokenny/Cookie-AutoDelete#418]
Firefox 61.0.1, Mac  OS 10.13.5, most recent version of AutoDelete

Suggestion: The pop-up announcing the number of cookies which have been deleted appears in the upper left-hand corner of the window. This is annoying and gets in the way. Why not include a "settings" option to specify the location of this pop-up in  the window?

Your add-on is very helpful, keep up the good work.

**Comment by ke-d** [comment]
https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/FAQ:-Common-Questions-and-Issues#why-cant-i-move-the-notification-pop-up
