### ISSUE TITLE
type error in error console of Firefox

### ISSUE THREAD

**Issue by m-i-k-e-y** [mrdokenny/Cookie-AutoDelete#42]
After installing the signed version of 1.3.0 for Fx, I found the following in the error console:

Error: Error: Type error for parameter alarmInfo (Error processing delayInMinutes: NaN and infinity are not valid) for alarms.create. background-webpack.js:532:2
	onError moz-extension://cd1d3b97-c00d-4870-a1e7-30a92517fbe0/background-webpack.js:532:2

Since I browsed a couple of sites, I'm not sure which one triggered this. Might have been different sites, as the error was logged about 10 times to the error console.

Correct me if I'm wrong (I'm no expert for js or Firefox code), but looking at the code, it seems that the parameter 'minutes' is not defined when calling browser.alarms.create.

- OS/version: Win 10 x64
- Browser/version: Firefox 53.0.3 x64
- Cookie AutoDelete version: signed 1.3.0 for Fx

**Comment by mrdokenny** [comment]
Probably something to do with #21 

Can you try resetting the active mode timer to 1.

**Comment by m-i-k-e-y** [comment]
I will try.

**Comment by m-i-k-e-y** [comment]
I'm pretty sure it has something to do with it. I've set the value to 0.5 and now the value is not shown in the settings, its blank.

The language of the OS and Firefox is german, so probably I will try to use 0,5 instead of 0.5.

**Comment by m-i-k-e-y** [comment]
After setting the value to 1, this error is not logged anymore. 
And cookies are deleted again automatically. This stopped working before, I just realized this after I got a notification after I changed the value back to 1.

**Comment by m-i-k-e-y** [comment]
Next update:

changing the value to 0,5 doesn't cause the error to be logged to the console and cookies are deleted automatically after half a minute (what I wanted). The setting did not disappear this time after closing and reopening the settings of the extension.

So one has to enter floating point values the way they are written by the locale used in Firefox.

Thanks
