### ISSUE TITLE
Microsoft Edge support

### ISSUE THREAD

**Issue by xopez** [mrdokenny/Cookie-AutoDelete#421]
Hello,

i have a quick question because i want to switch to Microsoft Edge.
Are you able to add support for it?
The Browser already has a cookie API.
https://docs.microsoft.com/en-us/microsoft-edge/extensions/api-support/supported-apis#cookies

**Comment by ghost** [comment]
There are many other privacy-oriented browsers that would be great to be the next ones to receive support from this addon. Why would you be concerned about cookies collecting data & privacy in general, and use MS Edge? 

Even tho Chrome is no better than Edge (privacy-wise) it's widely used so it makes sense supporting Chrome, plus, more people = more donations = better addons for all. But Edge... why Edge?

**Comment by ke-d** [comment]
Last time I tried CAD in Edge, it just didn't work at all. So there still needs to be some API parity with Firefox/Chrome for CAD to just work.

**Comment by chiraag-nataraj** [comment]
I guess this won't be an issue anymore since Edge is moving to a Chromium skin.

**Comment by kennethtran93** [comment]
I will close this since #542 is more feasible at this point.
