### ISSUE TITLE
Blacklist Only?

### ISSUE THREAD

**Issue by kmand** [mrdokenny/Cookie-AutoDelete#423]
### Your settings 

- OS/version: 
- Browser/version: 
- Cookie AutoDelete version:

**Comment by kmand** [comment]
I am probably off base here. What I really want is just a blacklist of sites I want  to have cookies autodeleted. Is tjhis the wrong extnesion?

**Comment by kennethtran93** [comment]
Normally people want to delete unwanted cookies, especially from (unknowing) third-party cookies and whatnot,.  Try another extension if blacklisting is what you want.

**Comment by ke-d** [comment]
Duplicate of https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/134
