### ISSUE TITLE
Is Cookie-Autodelete redundant if Temporary Containers is active?

### ISSUE THREAD

**Issue by Futureknows** [mrdokenny/Cookie-AutoDelete#428]
I run Firefox Temporary Containers in AUTO mode. As far as I know, all cookies and storage for every page is isolated in every tab, and deleted when the tab is closed.

Is Cookie-Autodelete totally redundant in this scenario?

**Comment by Yyuzu** [comment]
If you have setup permanent containers, cookies will remain in these.
