### ISSUE TITLE
Feature Request: Export core Settings, not only Grey/Whitelisting rules

### ISSUE THREAD

**Issue by Hostn4me** [mrdokenny/Cookie-AutoDelete#429]
Hello,

I just started using this extension and I love it. I'm well aware that you can import and export your grey/whitelist settings (which is awesome), and although I know the actual core settings of the extension aren't very lengthy, it would still be nice if you one could export them in order to enable faster browser and/or extension configuration, especially for those users who either use multiple profiles within Firefox (among other browsers), work off of different machines, and/or routinely reinstall their browsers and/or format their computers.

Of course I will not be totally bummed out if this feature is not added. However, considering it should be an easy feature to implement and would definitely help myself as well as others, I figured I'd go ahead and request it. Lastly, please forgive me if this feature already exists and I have somehow overlooked it. I've looked in every place I can think of and there are only so many places to look so that is why I arrived at the conclusion that it does not yet exist.

Thanks in advance.

**Comment by kennethtran93** [comment]
That may be doable on the settings page easily, though it may be a separate config file instead of the combined settings plus config.  There may be a way to also get the grey/white lists as well but it may take slightly longer to code that portion.

**Comment by kennethtran93** [comment]
Try the latest build in #713 - import/export of core settings.  Note that this will be stored as a separate file for now.  Cannot be merged into the expression one at this time.
