### ISSUE TITLE
[Feature request] List cookies of current domain

### ISSUE THREAD

**Issue by rctgamer3** [mrdokenny/Cookie-AutoDelete#433]
### Describe the Feature

If CAD says there are 10 cookies for GitHub - i'd like to know what the cookies are. I don't need to be able to act on them, but it helps make a concious decision whether to grey/whitelist the current domain.

**Comment by ke-d** [comment]
Duplicate of https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/272
