### ISSUE TITLE
Compromise between privacy and convenience with Cookie AutoDelete (CAD) and Firefox Containers?

### ISSUE THREAD

**Issue by elprice7345** [mrdokenny/Cookie-AutoDelete#434]
I'm using Firefox with the extension Cookie AutoDelete and the Auto-clean option enabled.

I'm trying to find the proper balance between privacy and convenience.

For example, I log into Gmail and stay logged in as long as my browser session stays open. I close my browser and then have to login again. In some situations that's the correct behavior, but on my home desktop, the convenience of remaining logged in outweighs the inconvenience of having to login again especially with the additional steps of 2-factor authentication.

Is there any way to reduce or eliminate the tracking done by Google, Facebook, etc., while staying logged in between browser sessions?

Would Firefox containers help? Could I whitelist Facebook in CAD and force it to open only in the Facebook container or does that defeat the purpose of the extension? 

- OS/version: Windows 10 x64
- Browser/version: Firefox 61.0.2 x64
- Cookie AutoDelete version: 2.2.0

**Comment by ghost** [comment]
All this would be solved if only this issue was solved
https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/68

You could whitelist the specific cookie responsible for login/sessions and auto-delete all the others.

**Comment by elprice7345** [comment]
Thanks for the background @Zig-03. 

> You could whitelist the specific cookie responsible for login/sessions and auto-delete all the others.

Based on reading the thread you referenced, this doesn't seem possible with CAD?

**Comment by ke-d** [comment]
Containers do help a lot in being logged in certain sites while keeping your main profile clean.

**Comment by bendover22** [comment]
@elprice7345 - I know this is a closed issue, but if "privacy" at any level is important, then using Google services is the wrong path.  If you've researched how they actually operate; what they've done in the past (often got sued & lost) and will undoubtedly do again, and you're still OK with them, that's fine.  Just be an informed consumer.

There are lots of "privacy respecting" email providers with free or low cost accounts, that don't have a close, personal, lucrative relationship with intelligence agencies in several countries.
