### ISSUE TITLE
Cookies deleted, but not local storage

### ISSUE THREAD

**Issue by gbhug5a** [mrdokenny/Cookie-AutoDelete#436]
On opening the browser, I go to Options/ Privacy&Security/CookiesandSiteData/ManageData, and I see several sites with local site storage, but no cookies, and those sites are not on my white list.  There should be no local storage preserved for them.  Examples - Google, CNBC.

- OS/version:  Windows 7/64 
- Browser/version: Firefox 61.0.2
- Cookie AutoDelete version: 2.2.0

Edit:  I do have Local Storage Cleanup enabled.

**Comment by ke-d** [comment]
![manage cookies](https://user-images.githubusercontent.com/17077613/44936010-ead5a580-ad27-11e8-8ca5-1b156f3a4aa7.png)

This stuff is IndexedDB and will be adding a button to manually clear those.

**Comment by gbhug5a** [comment]
I wanted to update this.  It's possible I had something set wrong for my original post here.  Since then, things seem to be operating properly.  In fact, I now never see any local site storage.  Ever.  I think this matches the expected behavior when you have CAD's Local Storage Cleanup enabled - since FF doesn't provide API local storage control by site, CAD just deletes all local storage.  The downside is that whitelisted sites have their local storage deleted too.  Well, maybe this will get sorted out at some point.

**Comment by ke-d** [comment]
Seems to be resolved.
