### ISSUE TITLE
Throw some indication that cleanup failed

### ISSUE THREAD

**Issue by ssokolow** [mrdokenny/Cookie-AutoDelete#437]
### Describe the Bug/Feature

Currently, if [first-party isolation](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies#First-party_isolation) is enabled, Cookie AutoDelete silently fails to do anything while also producing the following error message in the browser console.

> Error: First-Party Isolation is enabled, but the required 'firstPartyDomain' attribute was not set.

See [the MDN page](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies#First-party_isolation) for details.

> The `cookies.get()`, `cookies.getAll()`, `cookies.set()` and `cookies.remove()` APIs all accept a `firstPartyDomain` option.
When first-party isolation is on, you must provide this option or the API call will fail and return a rejected promise. For `get()`, `set()`, and `remove()` you must pass a string value. For `getAll()`, you may also pass `null` here, and this will get all cookies, whether or not they have a non-empty value for `firstPartyDomain`.
When first-party isolation is off, the `firstPartyDomain` parameter is optional and defaults to an empty string.  A non-empty string can be used to retrieve or modify first-party isolation cookies. Likewise, passing `null` as `firstPartyDomain` to `getAll()` will return all cookies.

I'd prefer if Cookie AutoDelete could be used in concern with first-party isolation for stronger anti-tracking protection, but, at the very least, you should attach a promise rejection handler that pops up some kind of notification that "Cookie AutoDelete is in a non-functional state because..."

### Steps for anyone to reproduce the bug

1. Set up Cookie AutoDelete
2. Toggle `privacy.firstparty.isolate` to `true` in `about:config`
3. Trigger a cookie cleaning (Probably optional. The errors seem to happen at steady intervals even if I don't attempt to clear cookies.)

### Your settings 

* [x] Enable Automatic Cleaning? Delay Before Cleaning: 15 Second(s)?
* [x] Enable Cleanup on Domain Change?
* [x] Enable Cleanup Log and Counter?
* [x] Show Number of Cookies for that Domain?
* [x] Show Notification After Cookie Cleanup: 3 Second(s)?
* [x] Clean Cookies from Open Tabs on Startup?
* [x] Enable Support for Firefox's Container Tabs?
* [x] Localstorage Cleanup (Firefox 58+)?

(This was a hassle to copy over. Did I miss some kind of ready-to-copy-and-paste dump like CanvasBlocker and Firefox's `about:support` have?)

- OS/version: Kubuntu Linux 14.04.5 LTS
- Browser/version: 62.0b19 (64-bit)
- Cookie AutoDelete version: 2.2.0

(For the OS version, might I suggest pointing Linux users at the `lsb_release -a` command, if they have it installed?)

**Comment by ke-d** [comment]
Hmm from what I recall, you have to either restart the browser or just the extension after flipping the FPI pref. This is due to on startup, it checks for either the pref on startup and applies different things.

**Comment by ssokolow** [comment]
Huh. Looks like you're right... though I did now run into another silent failure.

Unless I uncheck "Localstorage cleanup", the FPI-enabled configuration fails with this error on the console and no other indication:

> Error: Type error for parameter options (Error processing hostnames.0: Error: Invalid hostname ) for browsingData.removeLocalStorage.

**Comment by ke-d** [comment]
Interesting, FPI does affect localstorage by clearing them when toggled in FF. It might be trying to delete localstorage objects that doesn't exist.

**Comment by ssokolow** [comment]
Either way, it's not exactly safe to silently fail to clear cookies in either situation. There should be some kind of notification so the user knows that the clearing failed.

**Comment by ke-d** [comment]
That localstorage thing might be related to https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/pull/431.
