### ISSUE TITLE
[Feature Request] Delete regardless of other opened tabs

### ISSUE THREAD

**Issue by nerbrume** [mrdokenny/Cookie-AutoDelete#438]
Hi,

Would it be possible to have CAD delete cookies on tab close/domain change even if another tab is opened on the same domain ?

The main use case for me is google : I often end up with a lot of (unrelated) google searches tabs kept open, resulting in the google cookies being kept until I close the browser.
I ideally would like this to be a per-domain setting, but a global setting would be nice too.

**Comment by ke-d** [comment]
I feel like this is similar to a blacklist #134
