### ISSUE TITLE
Ccleaner supercookies

### ISSUE THREAD

**Issue by stasplayer** [mrdokenny/Cookie-AutoDelete#439]
### Your settings 

- OS/version: 
- Browser/version: 
- Cookie AutoDelete version:

**Comment by stasplayer** [comment]
Firefox saves some cookie info in a text file that ccleaner deletes but cookie auto delete does not.
"SiteSecurityServiceState.txt"
This is in the profiles folder and are considered supercookies
Win 10 64 bit
firefox 61.0.2
CAD 2.2.0

**Comment by ke-d** [comment]
https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/FAQ:-Common-Questions-and-Issues#what-is-the-state-of-the-webextension-api-to-clean-x-data

Use First Party Isolation or make that file read me only.
