### ISSUE TITLE
Pending approval of translations on Crowdin

### ISSUE THREAD

**Issue by spodermenpls** [mrdokenny/Cookie-AutoDelete#440]
The new German locale strings are pending for approval since May (among other languages). I've finished the last missing ones, and would like to see them approved and integrated into the next Cookie-AutoDelete version. Is @mrdokenny still the owner/maintainer of this repository and the Crowdin project, or did someone else take over? And if so, who could approve the Crowdin translations and push for an update?

**Comment by ke-d** [comment]
Done, I'll merge when I'm the next build is ready.

**Comment by spodermenpls** [comment]
Thanks a lot!
