### ISSUE TITLE
Sound

### ISSUE THREAD

**Issue by danenbarger** [mrdokenny/Cookie-AutoDelete#441]
### Your settings 

- OS/version: 
- Browser/version: 
- Cookie AutoDelete version:

**Comment by danenbarger** [comment]
I have only a great desire to switch off the sound. I try to concentrate and the damn ding interrupts. If you cannot remove it, I will need to uninstall the app.

**Comment by ke-d** [comment]
Turn off notifications in the settings. Are you on phone?

**Comment by danenbarger** [comment]
Thank you. I was looking at the wrong settings.

Best,
