### ISSUE TITLE
Site storage issue

### ISSUE THREAD

**Issue by gbhug5a** [mrdokenny/Cookie-AutoDelete#442]
I opened issue #436 with the problem that Firefox site storage was being left in place for sites that were not on the whitelist.  Since then, I've developed the opposite problem.  The Storage column under Manage Data is always completely empty, and Clear Data always shows zero usage for Cookies and Site Data.  Yet Storage Inspector and ongoing changes to webappsstore.sqlite show that the site storage system is being used.  Local storage usage was visible in all the right places in the beginning with FF v61 and CAD, but became hidden as described above shortly after I posted #436.   I don't know if it's related to something I changed in CAD, or something completely different.  I've tried deleting the sqlite file, but that didn't help.  If not a CAD issue, any suggestions for fixing this would be appreciated.

Windows 7/64
FF v61 and v62
CAD v2.2.0

**Comment by ke-d** [comment]
The UI for ` Cookies and Site Data` doesn't update immediately from what I've seen. You have to refresh the page to see if cookies were populated. If anything else, try resetting your profile.
