### ISSUE TITLE
Cleanup on Domain Change.

### ISSUE THREAD

**Issue by DiagonalArg** [mrdokenny/Cookie-AutoDelete#444]
Given this issue: https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/Documentation#enable-cleanup-on-domain-change

would you consider having a "shared cookie" list for domains.  Eg, to log in to addons.mozilla.org, the domain flips over to accounts.firefox.com, before returning.  I would like the cookies to be shared between those two, but when all relevant tabs are closed, then the cookies should go away.

So the idea is that you'd have your {white,grey} lists and a "shared cookie" or "linked domain" list.

Thanks for your work!

**Comment by Existencielle** [comment]
I think it would be better to pressure the creators of those websites to not do that anymore, as it's a bad practice (can create a big security risk), rather than to work around it.

**Comment by DiagonalArg** [comment]
While I in principle agree, as it stands to even log in, I have to greylist the firefox domain, because otherwise when it comes back from accounts.firefox.com to mozilla, the cookie is deleted and I'm immediately logged out.  It seems to me better to have a bad solution until such time as the wider world can be prevailed upon to change their behavior.  Though if you have a way of doing that quickly, I'd be supportive.

**Comment by Existencielle** [comment]
Have you tried increasing your "Delay before cleaning" setting?
Maybe that could help...

**Comment by DiagonalArg** [comment]
The delay would have to be loner than I spend on the (in this example) Mozilla website, so that the firefox key will be preserved until I'm done.  That could be 5 minutes, or it could be a day or more.  So I don't think this solution is going to work.

**Comment by ke-d** [comment]
> Have you tried increasing your "Delay before cleaning" setting? 

This is only used for useful for short counters, unless you never close your browser.

As for this issue, I don't think it's worth maintaining and testing for a extra whitelist that 99% of websites won't be on. Keeping things simple would reduce the risk of things breaking. ;) Also, you could just greylist those websites as a nice compromise.

**Comment by DiagonalArg** [comment]
@mrdokenny - I sympathize with the practical issues, and yes, as I said above:

    ... as it stands to even log in, I have to greylist the firefox domain ...

I'm not sure greylisting is a "nice compromise."  It keeps cookies until I close my browser, which could be basically forever, if I keep my machine on and the browser open - which I do.
