### ISSUE TITLE
Can't install in Firefox

### ISSUE THREAD

**Issue by bittorrenter** [mrdokenny/Cookie-AutoDelete#446]
Hi,
I've got a few Firefox addons (eg. NoScript, UBlock ) but Firefox does not provide any way to install this add-on
Weird

Over.

### Your settings 

- OS/version: Windows 8.1
- Browser/version: Firefox 62.0.2
- Cookie AutoDelete version: n/a

**Comment by ghost** [comment]
>but Firefox does not provide any way to install this add-on

Steps to reproduce will be helpful. You go to https://addons.mozilla.org/firefox/addon/cookie-autodelete/ and...?

**Comment by sebasped** [comment]
Same here. I go to https://addons.mozilla.org/firefox/addon/cookie-autodelete/ and says I'm using firefox 45, but actually I'm using Firefox 62.0.3
![2018-10-15-130222_1373x874_scrot](https://user-images.githubusercontent.com/24229351/46962914-b9682d80-d07a-11e8-8b70-9be90e3fe038.png)

**Comment by ke-d** [comment]
https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/FAQ:-Common-Questions-and-Issues#cant-install-this-extension-on-firefox
