### ISSUE TITLE
REQUEST: Support for other tracking data (cache, ...)?

### ISSUE THREAD

**Issue by Salomon-MH** [mrdokenny/Cookie-AutoDelete#449]
Hello,

is it possible to also include support for other data such as the browser cache for websites? It would be nice to see such an option as I currently have to remove Cache etc. manually.

Thanks!

**Comment by sm4rk0** [comment]
Did you search existing issues for "Cache"?
There are at least these: #44, #150, #356.

**Comment by Salomon-MH** [comment]
Kind of, but I cant see anyone mentioning things like "filesystems", "database storage" and "service workers" which also appear in my cache management page for chrome.

**Comment by ghost** [comment]
https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/FAQ:-Common-Questions-and-Issues#what-is-the-state-of-the-webextension-api-to-clean-x-data

**Comment by ke-d** [comment]
Can't be done on a per website basis at this moment, but check the FAQ that @gwarser for latest updates
