### ISSUE TITLE
[REQUEST] Add "Blacklist" option beside Greylist and Whitelist

### ISSUE THREAD

**Issue by Existencielle** [mrdokenny/Cookie-AutoDelete#450]
I would find it very helpful if you could add domains to a Blacklist the same way that you currently can add them to a Greylist or Whitelist. (upon clicking on the Cookie-AutoDelete icon)

The effect of that Blacklist should be that cookies will be deleted (after the set delay) even if the tab is still open.

**Comment by ke-d** [comment]
Duplicate of #134
