### ISSUE TITLE
Can't install in Firefox

### ISSUE THREAD

**Issue by sebasped** [mrdokenny/Cookie-AutoDelete#451]
I go to https://addons.mozilla.org/firefox/addon/cookie-autodelete/ and says I'm using firefox 45, but actually I'm using Firefox 62.0.3

![2018-10-15-130222_1373x874_scrot](https://user-images.githubusercontent.com/24229351/46962914-b9682d80-d07a-11e8-8b70-9be90e3fe038.png)

_Originally posted by @sebasped in https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/446#issuecomment-429913889_

**Comment by ke-d** [comment]
https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/FAQ:-Common-Questions-and-Issues#cant-install-this-extension-on-firefox
