### ISSUE TITLE
Whitelisting no longer work

### ISSUE THREAD

**Issue by Speciesx** [mrdokenny/Cookie-AutoDelete#452]
whitelisting no longer work in Firefox nightly.

Windows 10
Firefox nigthly
Cookie AutoDelete 2.2.0

**Comment by ticotexas** [comment]
whitelisting also not working for me in Firefox 63.0, Ubuntu 18.10, CAD 2.2.0

**Comment by skjerns** [comment]
Same in Opera #458

**Comment by gecoool** [comment]
I can also confirm that whitelist not working on MacOS HighSiera 10.13.6, Firefox 62.0 64bit

**Comment by ke-d** [comment]
What do you mean it doesn't work?

1. Adding a site to the whitelist doesn't work
2. Cleanup is deleting cookies even from whitelisted sites.

**Comment by skjerns** [comment]
- I can add lists successfully to the whitelist, both subdoman and normally
- The cookies are deleted at the next cleanup cycle nevertheless

**Comment by gecoool** [comment]
Thx for replies !
By whitelist I and likely the others would understand a list of sites which are excepted from cookies deletion. If this is not the functionality you tried to implement via whitelist, I don't understand which one is. I assume this answers "doesn't work part". I could really use such a feature. I am sure it is not too difficult to implement an exceptions list.

**Comment by skjerns** [comment]
@gecoool The whitelist is supposed to do exactly this

suspicious that this ceases to work across enginges (firefox as well as chromium engine). But maybe it just never worked on Opera.

**Comment by ke-d** [comment]
> By whitelist I and likely the others would understand a list of sites which are excepted from cookies deletion. 

Yes this is the intended function. It still works as intended for me even in the latest nightly (2018-11-11). 

Try a new profile:
https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles

@skjerns I don't officially support Opera, but I remember someone one trying to get it to work.

**Comment by skjerns** [comment]
By _"trying to get"_ it work you imply it did not work, I assume? :(

**Comment by skjerns** [comment]
I can happily announce that the newest version of Opera is working again!

**Comment by kennethtran93** [comment]
Closing stale issue.
