### ISSUE TITLE
FEATURE REQUEST: Add option to auto-delete all cookies older than a specified age

### ISSUE THREAD

**Issue by fyrstormer** [mrdokenny/Cookie-AutoDelete#453]
I've been looking for a while for a cookie manager that can periodically (e.g. once a day) delete all cookies older than a certain age. My rationale is, if I haven't used a cookie in longer than 2 weeks (for example), then I don't want the website that owns that cookie to automatically recognize me if/when I return to their site in the future. Basically I want websites to have a more human-like memory, slowly forgetting who I am over time. I can't find a cookie manager that offers this feature, but this one seems to be the best cookie manager available, so I'd like to see this feature added to it.

**Comment by fyrstormer** [comment]
Before someone asks: Clearing cookies on startup doesn't address my issue, because I have my browser set to re-open all previously-open tabs on startup. Besides, if I need to restart my browser multiple times in quick succession for some reason, I don't want to have to temporarily disable cookie deletion on startup before doing so.

**Comment by ke-d** [comment]
So I don't have access to `Last accessed on` for cookies according to the [documentation](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/Cookie#Type), but I do have access on when the cookie's expiration date. So the next version will be able to auto clean expired cookies cause sometimes the browser doesn't clean them for some reason.

**Comment by ke-d** [comment]
Closing in favor of #426 actually.
