### ISSUE TITLE
FEATURE REQUEST: Make the toolbar icon grayscale when auto-clean is disabled

### ISSUE THREAD

**Issue by JavaVanilla** [mrdokenny/Cookie-AutoDelete#454]
That way the user doesn't have to remember if they set the option and more importantly, they don't forget the option on.

**Comment by kennethtran93** [comment]
If you're up for testing, head over to PR #713 and download the latest build / last comment.

**Comment by JavaVanilla** [comment]
Thanks. Just installed it, will report if something unusual happens.
