### ISSUE TITLE
naming conventions

### ISSUE THREAD

**Issue by fourquarts** [mrdokenny/Cookie-AutoDelete#455]
### Describe the Bug/Feature
The name "greylist" doesn't convey what it does, so I would like it to be renamed. I regularly forget and have to look it up. Something that clearly conveys what it does would be good, like "Keep until quit".

If you want the names of the two lists to be consistent, you could rename the whitelist to something like "Keep forever".

Thanks!

### Your settings 

- OS/version: 
- Browser/version: 
- Cookie AutoDelete version:

**Comment by ke-d** [comment]
It might cause some different translations to be longer than necessary even with those three words `Keep until quit`. Also when you hover over the buttons, it tells you what they do as well.

![image](https://user-images.githubusercontent.com/17077613/48172487-df1cd700-e2b4-11e8-9f00-f60c54d0bff7.png)
