### ISSUE TITLE
Does not clean when I press the home button

### ISSUE THREAD

**Issue by nadieenespecial** [mrdokenny/Cookie-AutoDelete#459]
### Describe the Bug/Feature

When I am on a page (example google.com) and press the home button to **Firefox Home (default)** the extension does not clean the cookies.

It only deletes the cookies if I close the tab.

### Screenshot in which the bug can be seen

![screenshot from 2018-10-30 03-12-45](https://user-images.githubusercontent.com/43034851/47699481-ceec6400-dbf1-11e8-81d8-ab8a52800ac9.png)

### Steps for anyone to reproduce the bug
1: Go to google.com.
2: Press the home button on Firefox.

### Your settings 
![screenshot from 2018-10-30 03-18-00](https://user-images.githubusercontent.com/43034851/47699697-77022d00-dbf2-11e8-8599-71ac54a498c6.png)
![screenshot from 2018-10-30 03-22-57](https://user-images.githubusercontent.com/43034851/47699891-263f0400-dbf3-11e8-896e-95a7aa38e503.png)

- OS/version: Ubuntu 18.04.1 LTS
- Browser/version: 63.0 (64-bit)
- Cookie AutoDelete version: 2.2.0

**Comment by ke-d** [comment]
I believe that there's no trigger for a page load to home yet.

**Comment by kennethtran93** [comment]
If you would like to give it a try, head on over to PR #713 and download the latest build (in comments) and let me know if there's any tweaks that need to be looked into.
