### ISSUE TITLE
Can't install in Firefox 63 Manjaro i3 Linux x64

### ISSUE THREAD

**Issue by sebasped** [mrdokenny/Cookie-AutoDelete#461]
When I go to https://addons.mozilla.org/en-US/firefox/addon/cookie-autodelete/ it says I'm using Firefox 45

![2018-11-08-111857_977x608_scrot](https://user-images.githubusercontent.com/24229351/48204257-4728f700-e361-11e8-9e77-558332777de8.png)

I try this FAQ:

https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/FAQ:-Common-Questions-and-Issues#cant-install-this-extension-on-firefox

with no luck. I do indeed have privacy.resistFingerprinting disabled in about:config

![2018-11-08-112128_1098x376_scrot](https://user-images.githubusercontent.com/24229351/48204447-c0c0e500-e361-11e8-8d6a-43426ee050f1.png)

I'm using Manjaro i3 Linux, Firefox 63.0.1 (64-bit).

**Comment by ghost** [comment]
Can you check your UA on other page? For example here https://www.whatsmyua.info/

**Comment by sebasped** [comment]
> Can you check your UA on other page? For example here https://www.whatsmyua.info/

In https://www.whatsmyua.info/ give this:


What's my user agent?

See what your user-agent detection library really thinks!
Enter a user-agent string:Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0
According to useragent v2.1.9:
ua

    rawUa: Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0
    string:
    family: Firefox
    major: 45
    minor: 0
    patch: 0
    device: Other 0.0.0

os

    string: Linux 0.0.0
    family: Linux
    major: 0
    minor: 0
    patch: 0

According to ua-parser-js v0.7.11:
ua

    ua: Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0

browser

    name: Firefox
    version: 45.0
    major: 45

engine

    name: Gecko
    version: 45.0

os

    name: Linux
    version: x86_64

device

    model: undefined
    vendor: undefined
    type: undefined

cpu

    architecture: amd64

According to platform.js v1.3.3:
ua

    name: Firefox
    version: 45.0
    layout: Gecko

os

    os: Linux 64-bit

device

    product:
    manufacturer:
    description: Firefox 45.0 on Linux 64-bit

API

GET /api/v1?ua=<ua-string>&version=<ua-parser-version>

Parameters:

    ua-string: Be sure to url-encode it. Defaults to your request's user agent string.
    ua-parser-version: Coming soon. Defaults to "latest".

**Comment by ghost** [comment]
Your Firefox presents itself as v45.0

Any other extension? Modified `about:config` pref `general.useragent.override`?

**Comment by sebasped** [comment]
That was it! Thanks! Indeed `general.useragent.override` was modified, I think, by an old legacy extension `Random Agent Spoofer` that I was installed in the past.
