### ISSUE TITLE
Is it possible to disable automatic cleaning on browser restart only?

### ISSUE THREAD

**Issue by Xuob** [mrdokenny/Cookie-AutoDelete#463]
I need automatic cleaning to work only after tab close, but not after browser restart.

**Comment by ke-d** [comment]
Hi, Can you explain why you might use it so I can understand the use cases?

**Comment by p-groarke** [comment]
I personally want the inverse option. Only cleanup on browser restart. This to minimize the amount of re-logins I have to do all the time. Thanks.

**Comment by ke-d** [comment]
@p-groarke make a greylist rule with `*`

**Comment by p-groarke** [comment]
@mrdokenny A bit convoluted, but that'll work. ty

**Comment by ke-d** [comment]
@p-groarke It's a side effect of having expressions and wildcards. I mean you can even do git*b.com to match both `github.com` and `gitlab.com`. Also, I don't have to maintain a setting that does the same thing. :)

**Comment by Xuob** [comment]
> 
> 
> Hi, Can you explain why you might use it so I can understand the use cases?

I need cookies to survive browser closing manually or crashing, in order to continue my work in the next browsing session, but I want them to be deleted automatically after I finish my work with some site and manually close its tabs.

**Comment by ke-d** [comment]
> I need cookies to survive browser closing manually or crashing, in order to continue my work in the next browsing session, but I want them to be deleted automatically after I finish my work with some site and manually close its tabs.

CAD should protect cookies from open tabs even after restart if you don't enable `Clean Cookies from Open Tabs on Startup`

**Comment by Xuob** [comment]
> 
> 
> > I need cookies to survive browser closing manually or crashing, in order to continue my work in the next browsing session, but I want them to be deleted automatically after I finish my work with some site and manually close its tabs.
> 
> CAD should protect cookies from open tabs even after restart if you don't enable `Clean Cookies from Open Tabs on Startup`

This works only if FF is able to restore the tabs automatically after restart/crash.
If FF for some reason fails to restore the tabs, then cookies will get deleted by CAD.
It is possible to restore the tabs later manually (by pressing the "restore tabs" button), but all cookies are gone already...
So, I would like to see "Do NOT clean on startup" option in CAD.
Thanks.

**Comment by kennethtran93** [comment]
If this is a Firefox-specific feature to implement only, then we could check the tab url to see if `about:sessionrestore` is opened upon startup.  If so then we could not do the startup removal until that tab is closed.  Would that be perhaps what you want?

I am unsure how Chrome handles sessions crashing at this time.

**Comment by Xuob** [comment]
This is excellent idea! I think checking for about:sessionrestore on startup should work.

**Comment by kennethtran93** [comment]
Alpha build of this is available in #713 comments.  Please let me know what you think.
