### ISSUE TITLE
Clearer Icon

### ISSUE THREAD

**Issue by ainola** [mrdokenny/Cookie-AutoDelete#47]
The current icon is a great indication of what the project does; I am not proposing to replace that. However, the icon to be used in the browser toolbar shrinks enough that it's difficult to tell what it is.

Here is a proposal that hopefully may interest you:

![cookie_mockup](https://user-images.githubusercontent.com/5383525/27147846-83afd53a-50fb-11e7-8aaa-cb15b1d0127f.png)

My rationale for keeping a neutral color until a site is whitelisted is that, more often than not, a site will not be whitelisted.

Perhaps the green isn't the best color? Maybe the blue from firefox's download icon would be better? In any case, I just mocked this up with a creative commons cookie icon located here:

https://thenounproject.com/term/cookie/8917/

Here are the SVGs that I used:
[cookie_svgs.zip](https://github.com/mrdokenny/Cookie-AutoDelete/files/1075538/cookie_svgs.zip)

**Comment by mrdokenny** [comment]
Well the icon is red when a site is not protected and blue when it is protected by the whitelist. Later on, I'll add a yellow icon for sites that are protected until browser restart #20

**Comment by ainola** [comment]
My comment was that the icon is much too small to be able to tell what it is: It looks like a blob of red and a blob of blue. Contrast to ublock origin, which has a pretty distinctive shield.

**Comment by ainola** [comment]
Feel free to close this as WONTFIX if you feel any differently.

**Comment by mrdokenny** [comment]
IMO, I think its fine and it's too late to change it now since people are already associating Cookie AutoDelete with that custom icon.
