### ISSUE TITLE
Opera full support needed. The extension clears cookies even on WhiteListed sites. Opera 57.0.3098.91

### ISSUE THREAD

**Issue by Musoki** [mrdokenny/Cookie-AutoDelete#470]
### Your settings 

- OS/version: 
- Browser/version: 
- Cookie AutoDelete version:

**Comment by ke-d** [comment]
Unofficial Opera support is through the Chrome extension (if it works there, then it should work on any chromium derived browsers), but I don't want to test it on each chromium derived browser there as it slows down development for me.
