### ISSUE TITLE
Indexed DB not cleared

### ISSUE THREAD

**Issue by quthla** [mrdokenny/Cookie-AutoDelete#471]
### Describe the Bug/Feature

Indexed DB does not get cleared. Is this due to lack of an api to clear that storage?

### Steps for anyone to reproduce the bug

Navigate to WhatsApp Web, close the tab, wait for auto clear to kick in, open WhatsApp Web again, check Indexed DB in Developer Tools.

### Your settings 

- OS/version: 
- Browser/version: 
- Cookie AutoDelete version:

**Comment by ghost** [comment]
https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/FAQ:-Common-Questions-and-Issues#what-is-the-state-of-the-webextension-api-to-clean-x-data

**Comment by quthla** [comment]
Search for "indexed" brought no results but then this can be closed.
