### ISSUE TITLE
Log times are not in local time zone

### ISSUE THREAD

**Issue by fmyhr** [mrdokenny/Cookie-AutoDelete#474]
### Describe the Bug/Feature
Hardware clock is set to UTC as usual for Linux.
OS time zone is set to EST.
CAD log times are incorrectly shown in UTC, without clear indication of time zone.

### Steps for anyone to reproduce the bug
Set OS time zone != hardware clock time zone.

### Your settings 
- OS/version: Debian 9 AMD64
- Browser/version: Firefox 63.0.3
- Cookie AutoDelete version: 2.2.0

**Comment by ke-d** [comment]
I'll look into it.

**Comment by ke-d** [comment]
https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/blob/3.X.X-Branch/src/ui/common_components/ActivityTable.tsx#L218

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString

So that's the API I called to autoformat the dateTime into the correct timezone automatically. So it should work unless maybe fingerprinting protection is on?

**Comment by kennethtran93** [comment]
@mrdokenny toLocaleString is only to format the data given into it to the system's locale (e.g. January 12 could be 12/1/2019, 1/12/2019, or 2019/1/12 depending on locale) - it doesn't convert timezones.

Approach: either show UTC/GMT after the string, or make your own format, disregarding the locale if you intended to show local time zone, or reuse my code for appending timestamp to export file as shown in these lines:  https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/blob/4faa7dba5eda8863a567d9492c41a378a516372a/src/ui/settings/components/Expressions.tsx#L118-L121

Apologies for not directly contributing code to this issue - my laptop is currently being refreshed/updated so it'll take me some time to get the development stuff set up again.

**Comment by ke-d** [comment]
I'll accept a PR for this. :)

**Comment by kennethtran93** [comment]
What I did as (hopefully) append the short time zone name, since the timestamp being parsed (may) already contain the timezone offset.  Hopefully that will satisfy this issue for now. Screenshot is in PR.
