### ISSUE TITLE
Feature request: remove cookies+local data for died sites

### ISSUE THREAD

**Issue by VladV2** [mrdokenny/Cookie-AutoDelete#477]
Hi!
Please add a feature to automatically remove data for died sites.
For example: 1 time per N days, after start, look some cookies which are not used for NN days, and check if their sites have always DNS records. If not - suggest to remove them.
Or you may add an especial button to call this function to force checking all unused cookies.
Thanx!

**Comment by ke-d** [comment]
Seems like a duplicate of #426
