### ISSUE TITLE
Feature request: data exchange with other plugins (if possible)

### ISSUE THREAD

**Issue by VladV2** [mrdokenny/Cookie-AutoDelete#478]
Hi !

Is it possible to get data from other plugins?
It would be nice to drop all data for sites blacklisted in AdBlock, uBlock, NoScript, etc.

**Comment by ke-d** [comment]
They would have to expose an API for CAD to call, which I believe that none of those you listed have done so.

**Comment by kennethtran93** [comment]
Would this feature request be similar to having an exported text file from those extensions and importing it into CAD?

**Comment by kennethtran93** [comment]
Closing as I don't think its feasible at this time.  You'll just need to get the URL's and format it to work with our Import Expression Option.
