### ISSUE TITLE
[Feature] Support Pale Moon

### ISSUE THREAD

**Issue by gjhklfdsa** [mrdokenny/Cookie-AutoDelete#479]
**Description**: Add Official Extension for [Pale Moon](https://addons.palemoon.org/)

**Comment by ke-d** [comment]
They don't support WebExtensions according to [this](https://forum.palemoon.org/viewtopic.php?f=1&t=19727).

> As an extra reminder: Pale Moon's supported extension technologies are XUL based (either overlay, bootstrapped or using the deprecated jetpack libraries), and WebExtensions are not and will not be supported by Pale Moon in any way, shape or form.

So basically this is a non starter.
