### ISSUE TITLE
Contextual identities: removing contextual identities doesn't remove 'tab' in addon.

### ISSUE THREAD

**Issue by businessBoris** [mrdokenny/Cookie-AutoDelete#48]
### Describe the Bug

I'm quite happily using the containers feature of FF53.0.x (now 54 today) with your add-on with the context identity option on.

BUG: removing a container does not remove the context identity tab and associated domain specifications - even after close and reopen browser.

[ There may be a related bug: the context identity list doesn't track the containers list closely. Adding a container doesn't allow addition of a domain specification until there is a tab within that container. Don't want to add it separately. ] 

### Steps for anyone to reproduce the bug

1. Delete a container using the FF containers addon.
2. Close Firefox and reopen if you wish.
3. Observe that the tab for the deleted container is still visible within your addon preferences page.

### Your settings 

- OS/version: Linux Exherbo [Think Gentoo with discrete source trees!] / Gnome latest / Wayland mostly.
- Browser/version: FF53.0.x and today, FF54.0.
- Cookie AutoDelete version: 1.3.1

### Gotchas
- I have an excessive number of tabs (~500) and an excessive number of addons installed.  There are no problems - I am in the process of sorting out the mess after removing the FF tab folders feature. I stress I am not experiencing any problems whatsoever as a result of my maltreatment.

I am very pleased with the addon - I suggest that this is a minor bug to the experimental version.

**Comment by mrdokenny** [comment]
Thanks for reporting. It's a known issue for #41 . I am waiting for this [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1344519) to land which would make it easier to track additions and removal events a lot easier.

The workaround for now is this.
1. Export your whitelist
2. Restore Default Settings (this deletes the cache and the extension settings)
3. Redo your settings 
4. Reimport the whitelist.

**Comment by businessBoris** [comment]
Thank you. I only looked at the open issues list before posting; my bad.
