### ISSUE TITLE
Cookies are deleted from Firefox but remain on computer.

### ISSUE THREAD

**Issue by ghost** [mrdokenny/Cookie-AutoDelete#480]
### Describe the Bug/Feature
Extension works correctly in Firefox but doesn't delete cookies completely and can be viewed with a cookie viewer outside of firefox. I've tried mixing and matching tons of settings and googling the issue but can't find anything about it, thank you.

### Screenshot in which the bug can be seen
https://a.uguu.se/mIKUg2Yl2KdE.png

### Your settings 

- OS/version: w7
- Browser/version: ff 64.0
- Cookie AutoDelete version: 2.20

**Comment by ke-d** [comment]
https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/FAQ:-Common-Questions-and-Issues#what-is-the-state-of-the-webextension-api-to-clean-x-data
```
HTTP Strict Transport Security (HSTS) Pinning (No API, but can set SiteSecurityServiceState.txt to read-only in Firefox)

    This is also what CCleaner refers as "cookies".
```

**Comment by ghost** [comment]
Sorry, I didn't see that on the FAQ, it's 100% my fault, so they have no actual data in them? Is there any way to have them deleted by CAD when normal cleaning happens?

**Comment by ke-d** [comment]
There's no API for it but you can set clear the file `SiteSecurityServiceState.txt` in your profile and then set that file to read only if you are worried.

**Comment by ghost** [comment]
Thanks I did that! Is it a security risk to do that? Is there any negative to doing it?

https://a.uguu.se/G0wxJSqqGXJP.png

I went to a couple popular sites to test if it was working and it seems to but now it keeps the sites and reverses FirstPartyDomain in their cookie name, not sure why.

**Comment by ke-d** [comment]
I'm probably not the right person to ask but I think when a site goes from http to an https site, it saves the "signature" so that the next time you visit that site, it automatically goes into https. However, if HSTS is disabled then the site has to do this conversion from http -> https every time you use http, which could be spoofed by an attacker.

If anyone has a better explanation, then feel free to clarify.
