### ISSUE TITLE
IPv6 Cookies aren't deleted

### ISSUE THREAD

**Issue by tsia** [mrdokenny/Cookie-AutoDelete#485]
### Describe the Bug/Feature

Every time the Extension clears cookies it claims to be removing cookies of the same 2 sites.
Even when i hit the clean button manually. It seems to be an issue with IPv6 Addresses.
according to Firefox those cookies haven't been used for a long time

### Screenshot in which the bug can be seen
![selection_412](https://user-images.githubusercontent.com/1386595/51111243-c6242b00-17fb-11e9-9093-04832de57253.png)

![selection_413](https://user-images.githubusercontent.com/1386595/51111307-f966ba00-17fb-11e9-892c-e5daf22ac62e.png)

### Steps for anyone to reproduce the bug
* open a site via its ipv6 address (e. g. https://[2a03:4000:6:310e:216:3eff:fe53:99b3]/ (yes, the cert is invalid))
* hit the clean button or wait for Cookie-AutoDelete to delete the cookies

### Your settings 

- [x] Enable Automatic Cleaning? Delay Before Cleaning: `60` Second(s)
- [x] Enable Cleanup on Domain Change
- [x] Enable Cleanup Log and Counter
- [x] Show Number of Cookies for that Domain
- [x] Show Notification After Cookie Cleanup 3 Second(s)
- [ ] Clean Cookies from Open Tabs on Startup?
- [ ] Enable Support for Firefox's Container Tabs?
- [x] Localstorage Cleanup (Firefox 58+)?

- OS/version: Debian Linux 9.6
- Browser/version: Firefox 64.0.2
- Cookie AutoDelete version: 3.0.0

**Comment by ke-d** [comment]
This looks like a bug in Firefox. I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1520058

As a workaround, you can whitelisting `*:*:*:*:*:*:*:*` for now so the activity log doesn't get flooded. 

Whitelisting the site doesn't work cause in regular expression `[.*]` means something completely different than `\[.*\]`. So what I will do is patch it so it will allow you to whitelist the site normally and even do `[*]`.

**Comment by kennethtran93** [comment]
Per the bugzilla link from ke-d as resolved, I'm going to close this for now.
