### ISSUE TITLE
read all existing cookie and imporve export function

### ISSUE THREAD

**Issue by heforfree** [mrdokenny/Cookie-AutoDelete#49]
hello
please add way the addon show existing cookie then we white list them.
and export function not good as other addon
currently it just only export white list domain name
i need export cookie with its other value so can import to chrome or another profile
can you do that?
also upload file should named "import".
thanks best regards

**Comment by mrdokenny** [comment]
I think what you are looking for is a Cookie Manager something like [this](https://addons.mozilla.org/en-US/firefox/addon/a-cookie-manager/?src=search) or [editthiscookie](https://chrome.google.com/webstore/detail/editthiscookie/fngmhnnpilhplaeedifhccceomclgfbg).

Basically what your asking is out of scope for Cookie "AutoDelete", which its main purpose is to manage deleting cookies not an general purpose cookie manager.
