### ISSUE TITLE
Enabling support for localStorage and containers in Firefox with privacy.firstparty.isolate causes cookies not to be deleted

### ISSUE THREAD

**Issue by anon88391** [mrdokenny/Cookie-AutoDelete#495]
### Describe the Bug/Feature

In the newest Firefox, if you enable a privacy.firstparty.isolate in about:config and also containter and localStorage support, the addon never deletes any cookies. Both the log and cookie deletion counter remain unchanged.

### Steps for anyone to reproduce the bug

Use the newest Firefox with containers.
Go to about:config and set privacy.firstparty.isolate to true.
In the addon, enable support for localStorage and containters.
Go to any site and watch the log stay empty and cookies not get deleted.

### Your settings 

- OS/version: Windows 10 x64
- Browser/version: Firefox 65.0
- Cookie AutoDelete version: 3.0.1

**Comment by kennethtran93** [comment]
Key questions raised while reading this:

- Auto-Clean on or off?
- What happens if you manually clicked the clean button?
- What's your CAD settings?
- Was tab in a container?

**Comment by ke-d** [comment]
Whenever you flip the `privacy.firstparty.isolate` setting you should restart the browser (and clear cookies if the browser hasn't done so), so CAD can enable some internal settings.

**Comment by kennethtran93** [comment]
Presuming this issue is resolved per solution above as no other response is given.
