### ISSUE TITLE
Firefox Abort Message with cookie-autodelete enabled

### ISSUE THREAD

**Issue by ReinoutDeWinter** [mrdokenny/Cookie-AutoDelete#497]
When firefox is closed an abort message is displayed: 
AbortMessage: ###!!! ABORT: file resource:///modules/Sanitizer.jsm, line 141
When the Cookie-AutoDelete addon is disabled, this abort message does not appear.

Entire output from the Abort Message:
AbortMessage: ###!!! ABORT: file resource:///modules/Sanitizer.jsm, line 141
Accessibility: Active
AccessibilityInProcClient: 0x400
AdapterDeviceID: 0x0a16
AdapterDriverVersion: 20.19.15.4531
AdapterSubsysID: 05fa1028
AdapterVendorID: 0x8086
Add-ons: adguardadblocker%40adguard.com:2.10.17,support%40lastpass.com:4.24.0.5,firefox%40ghostery.com:8.3.1,CookieAutoDelete%40kennydo.com:3.0.1,belgiumeid%40eid.belgium.be:1.0.29,formautofill%40mozilla.org:1.0,screenshots%40mozilla.org:35.0.0,webcompat-reporter%40mozilla.org:1.1.0,webcompat%40mozilla.org:3.0.0,web2pdfextension.17%40acrobat.adobe.com:18.0.9
AsyncShutdownTimeout: {"phase":"Places Clients shutdown","conditions":[{"name":"sanitize.js: Sanitize on shutdown","state":{"progress":{"isShutdown":true}},"filename":"resource:///modules/Sanitizer.jsm","lineNumber":141,"stack":["resource:///modules/Sanitizer.jsm:onStartup:141","jar:file:///C:/Program%20Files/Mozilla%20Firefox/browser/omni.ja!/components/nsBrowserGlue.js:BG__onWindowsRestored:1557","jar:file:///C:/Program%20Files/Mozilla%20Firefox/browser/omni.ja!/components/nsBrowserGlue.js:BG_observe:743","resource:///modules/sessionstore/SessionStore.jsm:initializeWindow:1177","resource:///modules/sessionstore/SessionStore.jsm:onBeforeBrowserWindowShown/<:1329"]}]}
AvailablePageFile: 12022902784
AvailablePhysicalMemory: 9009807360
AvailableVirtualMemory: 140731009744896
BIOS_Manufacturer: Dell Inc.         
BlockedDllList: 
BreakpadReserveAddress: 2451866386432
BreakpadReserveSize: 83886080
BuildID: 20190211233335
CPUMicrocodeVersion: 0x23
ContentSandboxCapable: 1
ContentSandboxLevel: 5
CrashTime: 1550041316
DOMIPCEnabled: 1
FramePoisonBase: 9223372036600889344
FramePoisonSize: 65536
GPUProcessLaunchCount: 1
GPUProcessStatus: Running
InstallTime: 1550007415
MemoryErrorCorrection: None
ModuleSignatureInfo: {"Fedict":["beid_ff_pkcs11_64.dll","beidpkcs11.dll","beid_ff_pkcs11.dll"],"Microsoft Corporation":["api-ms-win-crt-runtime-l1-1-0.dll","api-ms-win-crt-string-l1-1-0.dll","api-ms-win-crt-heap-l1-1-0.dll","api-ms-win-crt-stdio-l1-1-0.dll","api-ms-win-crt-convert-l1-1-0.dll","api-ms-win-crt-locale-l1-1-0.dll","api-ms-win-crt-math-l1-1-0.dll","api-ms-win-crt-time-l1-1-0.dll","api-ms-win-crt-filesystem-l1-1-0.dll","api-ms-win-crt-environment-l1-1-0.dll","api-ms-win-crt-utility-l1-1-0.dll","api-ms-win-crt-multibyte-l1-1-0.dll","msvcp140.dll","VCRUNTIME140.dll"],"Microsoft Windows":["msmpeg2vdec.dll","mfperfhelper.dll","wscapi.dll","MSAudDecMFT.dll","evr.dll","OneCoreCommonProxyStub.dll","explorerframe.dll","NapiNSP.dll","pnrpnsp.dll","DWrite.dll","linkinfo.dll","mf.dll","mfplat.dll","wshbth.dll","winrnr.dll","ntshrui.dll","cscapi.dll","dbghelp.dll","dbgcore.dll","srvcli.dll","dataexchange.dll","rasadhlp.dll","FWPUCLNT.DLL","twinapi.dll","oleacc.dll","edputil.dll","dxva2.dll","urlmon.dll","RTWorkQ.dll","iertutil.dll","mscms.dll","OneCoreUAPCommonProxyStub.dll","TextInputFramework.dll","CoreUIComponents.dll","version.dll","dhcpcsvc.dll","dhcpcsvc6.DLL","policymanager.dll","MMDevAPI.dll","avrt.dll","AudioSes.dll","usp10.dll","WinTypes.dll","nlaapi.dll","ColorAdapterClient.dll","credui.dll","wsock32.dll","WinSCard.dll","wtsapi32.dll","msvcp110_win.dll","d3d11.dll","WINMMBASE.dll","winmm.dll","CoreMessaging.dll","dcomp.dll","rmclient.dll","twinapi.appcore.dll","uxtheme.dll","dwmapi.dll","propsys.dll","dxgi.dll","ntmarta.dll","winsta.dll","rsaenh.dll","IPHLPAPI.DLL","dnsapi.dll","mswsock.dll","CRYPTBASE.DLL","devobj.dll","userenv.dll","sspicli.dll","powrprof.dll","kernel.appcore.dll","msasn1.dll","profapi.dll","msvcp_win.dll","KERNELBASE.dll","bcryptPrimitives.dll","crypt32.dll","bcrypt.dll","cryptsp.dll","windows.storage.dll","win32u.dll","gdi32full.dll","ucrtbase.dll","cfgmgr32.dll","wintrust.dll","rpcrt4.dll","shell32.dll","clbcatq.dll","shlwapi.dll","nsi.dll","psapi.dll","advapi32.dll","setupapi.dll","user32.dll","SHCore.dll","kernel32.dll","msvcrt.dll","sechost.dll","combase.dll","ole32.dll","ws2_32.dll","msctf.dll","imm32.dll","gdi32.dll","oleaut32.dll","ntdll.dll"],"Mozilla Corporation":["firefox.exe","xul.dll","mozavcodec.dll","nss3.dll","nssckbi.dll","freebl3.dll","mozavutil.dll","softokn3.dll","mozglue.dll","AccessibleHandler.dll","ia2marshal.dll","lgpllibs.dll"]}
MozCrashReason: MOZ_CRASH()
Notes: 
Has dual GPUs. GPU #2: AdapterVendorID2: 0x10de, AdapterDeviceID2: 0x0fe4, AdapterSubsysID2: 05fa1028, AdapterDriverVersion2: 25.21.14.1881FP(D00-L1000-W00001000-T000) DWrite? DWrite+ WR? WR- OMTP? OMTP+3 xpcom_runtime_abort(###!!! ABORT: file resource:///modules/Sanitizer.jsm, line 141)
ProductID: {ec8030f7-c20a-464f-9b0e-13a3a9e97384}
ProductName: Firefox
ProxyStreamSize: 136
ProxyStreamSizeFrom: IStream::Stat
ProxyStreamUnmarshalStatus: !aInitBufSize
ReleaseChannel: release
SafeMode: 0
SecondsSinceLastCrash: 2020
ShutdownProgress: profile-change-teardown
StartupCrash: 0
StartupTime: 1550039868
SystemMemoryUsePercentage: 47
TelemetryEnvironment: {"build":{"applicationId":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","applicationName":"Firefox","architecture":"x86-64","buildId":"20190211233335","version":"65.0.1","vendor":"Mozilla","displayVersion":"65.0.1","platformVersion":"65.0.1","xpcomAbi":"x86_64-msvc","updaterAvailable":true},"partner":{"distributionId":null,"distributionVersion":null,"partnerId":null,"distributor":null,"distributorChannel":null,"partnerNames":[]},"system":{"memoryMB":16283,"virtualMaxMB":134217728,"cpu":{"count":4,"cores":2,"vendor":"GenuineIntel","family":6,"model":69,"stepping":1,"l2cacheKB":256,"l3cacheKB":4096,"speedMHz":1995,"extensions":["hasMMX","hasSSE","hasSSE2","hasSSE3","hasSSSE3","hasSSE4_1","hasSSE4_2","hasAVX","hasAVX2","hasAES"]},"os":{"name":"Windows_NT","version":"10.0","locale":"en-GB","servicePackMajor":0,"servicePackMinor":0,"windowsBuildNumber":17763,"windowsUBR":253,"installYear":2018},"hdd":{"profile":{"model":"ST1000LM014-1EJ164","revision":"DEMA"},"binary":{"model":"ST1000LM014-1EJ164","revision":"DEMA"},"system":{"model":"ST1000LM014-1EJ164","revision":"DEMA"}},"gfx":{"D2DEnabled":false,"DWriteEnabled":true,"ContentBackend":"Skia","adapters":[{"description":"Intel(R) HD Graphics Family","vendorID":"0x8086","deviceID":"0x0a16","subsysID":"05fa1028","RAM":null,"driver":"igdumdim64 igd10iumd64 igd10iumd64 igd12umd64 igdumdim32 igd10iumd32 igd10iumd32 igd12umd32","driverVersion":"20.19.15.4531","driverDate":"9-29-2016","GPUActive":true},{"description":"NVIDIA GeForce GT 750M","vendorID":"0x10de","deviceID":"0x0fe4","subsysID":"05fa1028","RAM":2048,"driver":"C:\\WINDOWS\\System32\\DriverStore\\FileRepository\\nvdmi.inf_amd64_c191b94cf3786e11\\nvldumdx.dll,C:\\WINDOWS\\System32\\DriverStore\\FileRepository\\nvdmi.inf_amd64_c191b94cf3786e11\\nvldumdx.dll,C:\\WINDOWS\\System32\\DriverStore\\FileRepository\\nvdmi.inf_amd64_c191b94cf3786e11\\nvldumdx.dll,C:\\WINDOWS\\System32\\DriverStore\\FileRepository\\nvdmi.inf_amd64_c191b94cf3786e11\\nvldumdx.dll C:\\WINDOWS\\System32\\DriverStore\\FileRepository\\nvdmi.inf_amd64_c191b94cf3786e11\\nvldumd.dll,C:\\WINDOWS\\System32\\DriverStore\\FileRepository\\nvdmi.inf_amd64_c191b94cf3786e11\\nvldumd.dll,C:\\WINDOWS\\System32\\DriverStore\\FileRepository\\nvdmi.inf_amd64_c191b94cf3786e11\\nvldumd.dll,C:\\WINDOWS\\System32\\DriverStore\\FileRepository\\nvdmi.inf_amd64_c191b94cf3786e11\\nvldumd.dll","driverVersion":"25.21.14.1881","driverDate":"1-30-2019","GPUActive":false}],"monitors":[{"screenWidth":1920,"screenHeight":1080,"refreshRate":60,"pseudoDisplay":false}],"features":{"compositor":"d3d11","gpuProcess":{"status":"available"},"wrQualified":{"status":"blocked"},"webrender":{"status":"opt-in"},"advancedLayers":{"status":"available"},"d3d11":{"status":"available","version":45312,"warp":false,"textureSharing":true,"blacklisted":false},"d2d":{"status":"available","version":"1.1"}}},"appleModelId":null,"isWow64":false,"sec":{"antivirus":["Norton Security"],"antispyware":null,"firewall":["Norton Security"]}},"settings":{"blocklistEnabled":true,"e10sEnabled":true,"e10sMultiProcesses":4,"telemetryEnabled":false,"locale":"nl","update":{"channel":"release","enabled":true,"autoDownload":true},"userPrefs":{"app.shield.optoutstudies.enabled":false,"browser.cache.disk.capacity":460800,"browser.search.region":"BE","browser.search.widget.inNavBar":false,"browser.urlbar.userMadeSearchSuggestionsChoice":true,"network.proxy.http":"<user-set>","privacy.trackingprotection.enabled":true,"privacy.donottrackheader.enabled":true},"sandbox":{"effectiveContentProcessLevel":5},"addonCompatibilityCheckEnabled":true,"isDefaultBrowser":true,"defaultSearchEngine":"google-b-d","defaultSearchEngineData":{"name":"Google","loadPath":"jar:[app]/omni.ja!/google-b-d.xml","origin":"default","submissionURL":"https://www.google.com/search?client=firefox-b-d&q="}},"profile":{"creationDate":16385,"resetDate":16631},"addons":{"activeAddons":{"belgiumeid@eid.belgium.be":{"version":"1.0.29","scope":1,"type":"extension","updateDay":17843,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Gebruik de Belgische elektronische identiteitskaart (eID) in Firefox","name":"eID België","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":17811,"signedState":2},"web2pdfextension.17@acrobat.adobe.com":{"version":"18.0.9","scope":8,"type":"extension","updateDay":17869,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"De huidige webpagina converteren naar een Adobe PDF-bestand ","name":"Adobe Acrobat","userDisabled":false,"appDisabled":false,"foreignInstall":true,"hasBinaryComponents":false,"installDay":17471,"signedState":2},"CookieAutoDelete@kennydo.com":{"version":"3.0.1","scope":1,"type":"extension","updateDay":17912,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Krijg controle over uw cookies! Automatisch verwijderen van ongebruikte cookies van gesloten tabblad","name":"Cookie AutoDelete","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":17782,"signedState":2},"adguardadblocker@adguard.com":{"version":"2.10.17","scope":1,"type":"extension","updateDay":17921,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Unmatched adblock extension against advertising and pop-ups. Blocks ads on Facebook, Youtube and all","name":"AdGuard-advertentieblokkeerder","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":17179,"signedState":2},"firefox@ghostery.com":{"version":"8.3.1","scope":1,"type":"extension","updateDay":17928,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Ghostery is een krachtige privacy extensie. Blokkeer ads, stop trackers en maak websites sneller,","name":"Ghostery – Privacy Ad Blocker","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":17782,"signedState":2},"support@lastpass.com":{"version":"4.24.0.5","scope":1,"type":"extension","updateDay":17928,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Last Password you will ever need","name":"LastPass: Free Password Manager","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":17782,"signedState":2},"formautofill@mozilla.org":{"version":"1.0","scope":1,"type":"extension","updateDay":17926,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":null,"name":"Form Autofill","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":17773},"screenshots@mozilla.org":{"version":"35.0.0","scope":1,"type":"extension","updateDay":17926,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Maak clips en schermafbeeldingen van het web en sla deze tijdelijk of permanent op.","name":"Firefox Screenshots","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":17773},"webcompat-reporter@mozilla.org":{"version":"1.1.0","scope":1,"type":"extension","updateDay":17926,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Report site compatibility issues on webcompat.com","name":"WebCompat Reporter","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":17773},"webcompat@mozilla.org":{"version":"3.0.0","scope":1,"type":"extension","updateDay":17881,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Urgent post-release fixes for web compatibility.","name":"Web Compat","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":17773}},"theme":{"id":"385629@personas.mozilla.org","blocklisted":false,"description":null,"name":"Black Gray White / desktop, mobile","userDisabled":false,"appDisabled":false,"version":"0","scope":1,"foreignInstall":false,"hasBinaryComponents":false,"installDay":17782,"updateDay":17783},"activePlugins":[{"name":"Shockwave Flash","version":"32.0.0.114","description":"Shockwave Flash 32.0 r0","blocklisted":false,"disabled":false,"clicktoplay":true,"mimeTypes":["application/x-shockwave-flash","application/futuresplash"],"updateDay":17905}],"activeGMPlugins":{"gmp-gmpopenh264":{"version":"1.7.1","userDisabled":false,"applyBackgroundUpdates":1},"gmp-widevinecdm":{"version":"4.10.1146.0","userDisabled":false,"applyBackgroundUpdates":1}},"persona":"385629"},"experiments":{"rollout-monitor-v2-1505837":{"branch":"active","type":"normandy-prefrollout"}}}
ThreadIdNameMapping: 18380:"Gecko_IOThread",7696:"JS Watchdog",1852:"JS Helper",4268:"JS Helper",17772:"JS Helper",10628:"JS Helper",3004:"Timer",19844:"Link Monitor",17288:"Cache2 I/O",16112:"Cookie",9464:"GMPThread",5204:"Worker Launcher",20392:"VsyncIOThread",8452:"WindowsVsyncThread",17076:"Compositor",18020:"ImgDecoder #1",11004:"ImageIO",14000:"IPDL Background",21276:"DOM Worker",16364:"HTML5 Parser",10996:"StyleThread#1",4300:"StyleThread#2",15100:"StyleThread#0",21128:"ImageBridgeChild",21212:"ProcessHangMon",3276:"DataStorage",11512:"ProxyResolution",15628:"Cache I/O",18624:"mozStorage #1",9752:"mozStorage #2",19336:"ImgDecoder #2",12252:"ImgDecoder #3",16100:"DOM Worker",10376:"localStorage DB",20432:"QuotaManager IO",3344:"DOM Worker",10028:"URL Classifier",11416:"Classifier Update",19500:"COM MTA",11392:"SaveScripts",11752:"DOM Worker",2676:"DNS Resolver #4",8432:"mozStorage #4",6072:"ToastBgThread",4480:"mozStorage #5",16952:"IdentityCrypto",16644:"mozStorage #6",14464:"mozStorage #7",14800:"mozStorage #8",19752:"PlayEventSound",11892:"DNS Resolver #11",13080:"Shutdown Hang Terminator",12984:"Lazy Idle",
Throttleable: 1
TotalPageFile: 21783281664
TotalPhysicalMemory: 17073516544
TotalVirtualMemory: 140737488224256
UptimeTS: 14475.47
Vendor: Mozilla
Version: 65.0.1
Winsock_LSP: Hyper-V RAW : 2 : 34 : 1 : 1 : 0x20026 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : 1234191b-4bf7-4ca7-86e0-dfd7c32b5445 
 AF_UNIX : 2 : 1 : 1 : 0 : 0x20026 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : a00943d9-9c2e-4633-9b59-0057a3160994 
 MSAFD Tcpip [TCP/IP] : 2 : 2 : 1 : 6 : 0x20066 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : e70f1aa0-ab8b-11cf-8ca3-00805f48a192 
 MSAFD Tcpip [UDP/IP] : 2 : 2 : 2 : 17 : 0x20609 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : e70f1aa0-ab8b-11cf-8ca3-00805f48a192 
 MSAFD Tcpip [RAW/IP] : 2 : 2 : 3 : 0 : 0x20609 : 0xc : %SystemRoot%\system32\mswsock.dll :  : e70f1aa0-ab8b-11cf-8ca3-00805f48a192 
 MSAFD Tcpip [TCP/IPv6] : 2 : 23 : 1 : 6 : 0x20066 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : f9eab0c0-26d4-11d0-bbbf-00aa006c34e4 
 MSAFD Tcpip [UDP/IPv6] : 2 : 23 : 2 : 17 : 0x20609 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : f9eab0c0-26d4-11d0-bbbf-00aa006c34e4 
 MSAFD Tcpip [RAW/IPv6] : 2 : 23 : 3 : 0 : 0x20609 : 0xc : %SystemRoot%\system32\mswsock.dll :  : f9eab0c0-26d4-11d0-bbbf-00aa006c34e4 
 RSVP TCPv6 Service Provider : 2 : 23 : 1 : 6 : 0x22066 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : 9d60a9e0-337a-11d0-bd88-0000c082e69a 
 RSVP TCP Service Provider : 2 : 2 : 1 : 6 : 0x22066 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : 9d60a9e0-337a-11d0-bd88-0000c082e69a 
 RSVP UDPv6 Service Provider : 2 : 23 : 2 : 17 : 0x22609 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : 9d60a9e0-337a-11d0-bd88-0000c082e69a 
 RSVP UDP Service Provider : 2 : 2 : 2 : 17 : 0x22609 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : 9d60a9e0-337a-11d0-bd88-0000c082e69a 
 MSAFD Irda [IrDA] : 2 : 26 : 1 : 1 : 0x20006 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : 3972523d-2af1-11d1-b655-00805f3642cc 
 MSAFD L2CAP [Bluetooth] : 2 : 32 : 1 : 256 : 0x20006 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : 9fc48064-7298-43e4-b7bd-181f2089792a 
 MSAFD RfComm [Bluetooth] : 2 : 32 : 1 : 3 : 0x20026 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : 9fc48064-7298-43e4-b7bd-181f2089792a
useragent_locale: nl

My configuration:
- OS/version:  Win10 Home 10.0.17763
- Browser/version: Firefox 65.0.1 64bit
- Cookie AutoDelete version:  3.0.1

Settings are attached in screenshot
![cookie_autodelete_settings](https://user-images.githubusercontent.com/47592107/52699194-7c06a480-2f75-11e9-86d7-151a189ac6d9.png)

**Comment by kennethtran93** [comment]
Did you try using this addon/extension by itself first?  Possibly some other addon/extension is conflicting with this one.

**Comment by chiraag-nataraj** [comment]
At least on Debian with Firefox 67.0.2 and CAD 3.0.2 in a completely fresh profile, I get the following output:
```
ಜೂನ್ 18 09:44:53 chiraag systemd[1802]: Started firefox-tmp.kYMyMxUCOW.
ಜೂನ್ 18 09:44:53 chiraag firejail[20145]: Reading profile /home/chiraag/.config/firejail/firefox.profile
ಜೂನ್ 18 09:44:53 chiraag firejail[20145]: Reading profile /home/chiraag/.config/firejail/common.inc
ಜೂನ್ 18 09:44:53 chiraag firejail[20145]: Parent pid 20145, child pid 20147
ಜೂನ್ 18 09:44:53 chiraag firejail[20145]: Private /etc installed in 17.92 ms
ಜೂನ್ 18 09:44:53 chiraag firejail[20145]: Warning: skipping emp for private /opt
ಜೂನ್ 18 09:44:53 chiraag firejail[20145]: Private /opt installed in 0.02 ms
ಜೂನ್ 18 09:44:53 chiraag firejail[20145]: Warning: skipping emp for private /srv
ಜೂನ್ 18 09:44:53 chiraag firejail[20145]: Private /srv installed in 0.02 ms
ಜೂನ್ 18 09:44:53 chiraag firejail[20145]: 6 programs installed in 5.22 ms
ಜೂನ್ 18 09:44:53 chiraag firejail[20145]: Child process initialized in 64.54 ms
ಜೂನ್ 18 09:45:59 chiraag firejail[20145]: [Parent 22, Gecko_IOThread] WARNING: pipe error (79): Connection reset by peer: file /build/firefox-3fHcM7/firefox-67.0.2/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 357
ಜೂನ್ 18 09:45:59 chiraag firejail[20145]: [Parent 22, Gecko_IOThread] WARNING: pipe error (80): Connection reset by peer: file /build/firefox-3fHcM7/firefox-67.0.2/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 357
ಜೂನ್ 18 09:46:01 chiraag firejail[20145]: Parent is shutting down, bye...
ಜೂನ್ 18 09:46:01 chiraag systemd[1802]: firefox-tmp.kYMyMxUCOW.service: Succeeded.
```
But I get those warnings no matter what (possibly as a result of sandboxing firefox?). I don't seem to get any CAD-related warnings/errors.

**Comment by kennethtran93** [comment]
@ReinoutDeWinter @chiraag-nataraj Is this still an issue with the latest version of CAD and Firefox?  If not I'll close this soon.

**Comment by ReinoutDeWinter** [comment]
Hi Kenneth T,
This issue seems to be resolved.

kr

**Comment by kennethtran93** [comment]
Closing as per above.
