### ISSUE TITLE
Icon in Toolbar not showing anything in Firefox Nightly 67.0a1 (2019-02-15)

### ISSUE THREAD

**Issue by pboe** [mrdokenny/Cookie-AutoDelete#498]
Since a few nightlies clicking on the icon in the toolbar isn't showing anything.
Firefox 67.0a1 (2019-02-15)
Cookie-AutoDelete 3.0.1
macOS 10.13.6
![screenshot](https://user-images.githubusercontent.com/7489057/52862493-b323b400-3135-11e9-8f34-7de2f1052641.png)

**Comment by ke-d** [comment]
You could try:
https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/FAQ:-Common-Questions-and-Issues#how-do-i-reset-the-extension-settings

**Comment by pboe** [comment]
The preferences menu wasn't showing as well, so i had to reinstall.
