### ISSUE TITLE
Option to hide badge text in toolbar icon

### ISSUE THREAD

**Issue by fsp22** [mrdokenny/Cookie-AutoDelete#50]
Can you add a preference to hide the badge text with the number of cookies on the red/blue toolbar icon?

On site with cookies the icon like this 
![prev](https://user-images.githubusercontent.com/13574518/27218650-2c5eedfe-527f-11e7-853e-7b3896994c7e.png) 

becomes 
![next](https://user-images.githubusercontent.com/13574518/27218666-3eb86318-527f-11e7-97ef-49af29845dcb.png)

**Comment by mrdokenny** [comment]
That's this setting.

![capture1](https://user-images.githubusercontent.com/17077613/27246320-ac2dca02-52a5-11e7-9f49-0d3b2c774528.PNG)

**Comment by fsp22** [comment]
thanks
