### ISSUE TITLE
all cookies always deleted from private container, by Cookie-AutoDelete user has no control over it

### ISSUE THREAD

**Issue by AggravatingSignUpExperience** [mrdokenny/Cookie-AutoDelete#500]
### Describe the Bug
all cookies always deleted from private container

Cookie-AutoDelete deletes all cookies from the private container (private browsing), nothing shows up in the log. (notification does show)
Nothing seems relevant in the browser's console.
I can't make any rules for this container because it doesn't show.

### Steps for anyone to reproduce the bug
Enter and leave a site (with cookies) in private mode. I had several windows open and I searched google for wikipedia, visited wikipedia, then closed those windows (leaving other windows open so firefox is still open).

### Your settings 
Enable Automatic Cleaning? yes
Delay Before Cleaning Seconds: 0
Enable Cleanup on Domain Change? no
Enable Cleanup Log and Counter? yes
Show Number of Cookies for that Domain? yes
Show Notification After Cookie Cleanup Second(s)? 5
Clean Cookies from Open Tabs on Startup? no
Enable Support for Firefox's Container Tabs? yes
Localstorage Cleanup (Firefox 58+)? yes

- OS/version: Win 7
- Browser/version: Firefox 65 
- Cookie AutoDelete version: 3.0.1 

(signing up for github was not fun, after making an account it said my account was flagged and no one would see anything I submitted. This was after 10 minutes with a capcha that said "rotate that thing" and no matter which button I clicked it rotated counterclockwise -- after 20 attempts I had to give up and do the audio one, and make a new account)

**Comment by ke-d** [comment]
> Cookie-AutoDelete deletes all cookies from the private container (private browsing), nothing shows up in the log. (notification does show)

That is expected since it would be a privacy leak if CAD saved logs for private mode browsing. 

> I can't make any rules for this container because it doesn't show.
Same reasoning as above.

**Comment by AggravatingSignUpExperience** [comment]
But I don't **WANT** it to delete **ALL** the cookies from the private container **every time I leave a site** (while keeping the browser open -- obviously if I close the WHOLE browser session they will be cleared, because the private container is emptied on browser exit, which is fine).

I mentioned the logs purely for diagnostic purposes, I don't usually even have the logs turned on.

I can't add rules for it not to mess with the private container because it would be a "privacy leak"? How is deleting all the cookies from private container **whether I want it to or not** (even if it isn't logged) a privacy leak?

Without Cookie-AutoDelete all cookies (+misc) stays until Firefox is exited (or at least all instances of private mode windows close).

With Cookie-AutoDelete all cookies (+misc) in the private container are deleted right away, the user has no option to change or control this behavior.

**Comment by AggravatingSignUpExperience** [comment]
I was able to work around this by adding a rule (outside the rule page) to whitelist all for "private container".

Not logging the "private container" makes sense (although a debugging option is always nice).

Not allowing the user to **see**/**configure** OR **remove** rules already set for the "private container" not so good.
