### ISSUE TITLE
Feature request, rule ordering OR default/last rules

### ISSUE THREAD

**Issue by AggravatingSignUpExperience** [mrdokenny/Cookie-AutoDelete#501]
I have facebook set to it's own container and a rule for that container to delete all cookies (also localstorage) that are not from "✱.facebook.com"(whitelist) "✱"(greylist -not needed due to default last rule?) I run into a problem if I want to delete "✱.facebook.com" cookies from other containers.

For the container "default" if I have no rules then the (hidden) last rule applies: delete all unmatched cookies (I don't want to delete all non-whitelisted cookies all the time!).

If I add the rule "✱"(whitelist), and  "✱.facebook.com"(greylist) then the whitelist overrides the greylist and my greylist entry doesn't apply.

If I could order the rules this wouldn't be a problem (put this greylist first). If I could edit the "last" rule this wouldn't be a problem (set the "last" rule to whitelist all "✱" and leave the greylist -- then no other rules are needed)

Right now the "last" rule is invisible and stuck as "all unmatched = greylist".

**Comment by ke-d** [comment]
The default sorting ruleset is whitelist -> greylist
https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/blob/3.X.X-Branch/src/redux/Reducers.ts#L36

> I run into a problem if I want to delete "*.facebook.com" cookies from other containers.

Do you have open tabs of facebook? In that case, #262 is not implemented yet.

Also are you entering the rules correctly?
https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/Documentation#enter-expression

**Comment by AggravatingSignUpExperience** [comment]
I understand the default sorting, it's the cause of the problem -- not that that rule order is _always_ problematic/wrong.

Perhaps I am overlooking some rule logic, help me define a simple set of rule that accomplishes these goals:

"default" container:
- 1 Any and all cookies for the domain "facebook.com" and all subdomains ("www.facebook.com", "connect.facebook.com", "helpustrackyouforourbenifit.facebook.com", etc..) are deleted as soon as possible if they appear in the "default" container.
- 2 No other cookies are deleted from "default" container

"facebook" container:
- 3 Any and all cookies **NOT** for the domain  "facebook.com" and all subdomains  are deleted as soon as possible if they appear in the "facebook" container.
- 4 Cookies for the domain "facebook.com" and all subdomains are left alone in the "facebook" container.

For 1/2#  I create a greylist rule in the "default" container "✱.facebook.com" (without the quotes of course). If that's the only rule I make then **ALL** cookies in the "default" container are deleted. If I add the whitelist rule "✱" then **NO** cookies are deleted, even "✱.facebook.com". The whitelist rule applies first, matches **EVERYTHING**, and nothing makes it past that rule.

For 3/4# I create a whitelist rule in the "facebook" container for "✱.facebook.com", and a greylist rule for "✱". But since the _hidden_ **last** rule seems to be a greylist of "✱", I can omit the previous greylist rule in the "facebook" container and not change what happens.


I read the bug about not deleting from container A if that domain is open in ANY(other) container, and while that is not ideal it isn't a huge problem. It also doesn't seem to apply to my example.

(Sorry about the weird unicode asterisks "✱", it turned things italic and hid my ascii asterisks when I used normal ones -- even though that's not the markdown for italic... weird.. -- this may have made my first post unclear)

**Comment by AggravatingSignUpExperience** [comment]
1a seems to be the simplest fix, just give the user control of what happens when there is no rule match.

current setup:
whitelist: if matched don't delete and stop evaluating rules (whitelist evaluated first)
greylist: lazy delete later (always evaluated after whitelist)
no match: aggressive auto delete (more aggressive than greylist)

preferred setup 1a:
whitelist: if matched don't delete and stop evaluating rules (whitelist evaluated first)
greylist: lazy delete later (always evaluated after whitelist)
no match: user has choice of **"do nothing"**(whitelist-like), **greylist**, or "aggressive auto delete"(default option to match current behavior) 

preferred setup 1b (**rules evaluated in configured order**):
whitelist: if matched don't delete and stop evaluating rules
greylist: lazy delete later and stop evaluating rules
no match: aggressive auto delete (as currently)

**Comment by kennethtran93** [comment]
I'm going to crunch it up to a feature request for blacklist since you're primarily asking to remove data from a specific domain.

**Comment by kennethtran93** [comment]
Your primary reason appears to request for another list which would apply the action of removing cookies and site data almost immediately after its creation, which has been requested already.
