### ISSUE TITLE
Remnants after cookies deletion by CAD

### ISSUE THREAD

**Issue by Heri0n** [mrdokenny/Cookie-AutoDelete#506]
### Describe the Bug/Feature
With CAD automatic deletion enabled, after browsing on some sites, then progressively closing tabs, and finally closing the browser, Ccleaner still find a bunch of 0KB cookies related to the browsed sites

### Screenshot in which the bug can be seen
https://anonfiles.com/c0j7Q5v1bb/Cookies_set_jpg
Cookie set after browsing on several sites

https://anonfiles.com/k0j3Q0vab6/Cookie_remaining_30_s_after_closing_tabs_jpg
Cookie 30s after I closed all non empty tabs

https://anonfiles.com/z5jeQ8v5b4/What_found_Ccleaner_after_closing_the_browser_jpg
Bunch of 0KB cookies (related to the sites I browsed)  found by Ccleaner after I close my browser.

### Your settings 

Enable Automatic Cleaning?  Yes  Delay Before Cleaning:Second(s)? 10
Enable Cleanup on Domain Change? No
Enable Cleanup Log and Counter? Yes
Show Number of Cookies for that Domain? Yes
Show Notification After Cookie CleanupSecond(s)? 4s
Clean Cookies from Open Tabs on Startup? Yes
Enable Support for Firefox's Container Tabs? No
Localstorage Cleanup (Firefox 58+)? Yes

- OS/version:  Windows 7
- Browser/version: FF 65
- Cookie AutoDelete version: v3.0.1 set to automatically clear cookies and local storage after 10s

**Comment by ke-d** [comment]
https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/FAQ:-Common-Questions-and-Issues#what-is-the-state-of-the-webextension-api-to-clean-x-data
