### ISSUE TITLE
Cookies, Site Data & Cache Keep Increasing.. What is this??

### ISSUE THREAD

**Issue by koolx** [mrdokenny/Cookie-AutoDelete#507]
I had 1GB of stored cookies, site data and cache while using CAD. How the heck is that possible?? I managed to delete them in ff options. I have auto-clean enabled. But when I visit sites then check the amount of stored cookies, site data and cache in ff options, they keep increasing. Are CAD settings configured correctly?

When I click clean, the amount of cookies and cache hasn't changed. How can I get CAD to delete all unwanted cookies and cache except for cookies I want to keep?

Btw, I read the FAQ and its not helpful. Below are images showing my settings. 

![1](https://user-images.githubusercontent.com/8130105/53864773-5d675c80-3fbb-11e9-8a4a-e34873ca2f47.png)

![2](https://user-images.githubusercontent.com/8130105/53864779-60fae380-3fbb-11e9-854e-e6015f365652.png)

**Comment by kennethtran93** [comment]
Browser version and CAD version?

**Comment by koolx** [comment]
ff version 66.0.1. And CAD version 3.0.1.

- David

**Comment by kennethtran93** [comment]
> When I click clean, the amount of cookies and cache hasn't changed. 

How did you know that it wasn't cleaned/cleared?  Also I believe this webextension doesn't touch the cache.  localstorage is NOT the same as cache.  Cache is the browser saving a snapshot of the webpage/site, which includes images, scripts, pages, etc.  Localstorage may be data that the website is storing similar to a cookie, thus falls under 'site data' I believe (unconfirmed).


> How can I get CAD to delete all unwanted cookies and cache except for cookies I want to keep?

As said above, this webextension should already clear cookies after X seconds.  Cache may require a separate extension if available or just manually do it in settings/preferences.  Perhaps enabling notifications and the log counter would help, but the log counter may take up more space as cleaning happens, in which its history can be deleted within the webextension itself.  As per your second screenshot, you are saying you're keeping cookes from github.com and its subdomains.

**Comment by kennethtran93** [comment]
@koolx is this still an issue with the more recent versions (3.2.0)?

**Comment by kennethtran93** [comment]
Closing due to stale.
