### ISSUE TITLE
Import previous cookie settings through external script

### ISSUE THREAD

**Issue by daniel-barrows** [mrdokenny/Cookie-AutoDelete#508]
Ideally, Cookie-AutoDelete would use the existing cookie preservation settings stored in the browser. I understand that [there's not an API for that right now](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/FAQ:-Common-Questions-and-Issues#why-is-there-no-import-from-sdcwhy-cookie-autodelete-doesnt-use-the-native-cookie-whitelist-in-firefox-or-chrome), so it isn't possible for Cookie-AutoDelete to import them directly. However, it's [fairly trivial for a user to access the prior cookie settings](https://gist.github.com/daniel-barrows/ec3a59339b16f418020c2f9b6a94e766), and it would be nice if Cookie-AutoDelete could make this as easy as possible.

Here's what I suggest:
 1. Upon installation, prompt the user to ask if they want to import old cookie settings
 2. If they say yes, offer them a link to a script which they can run on their local machine and produce a JSON suitable for importing into Cookie-AutoDelete.
 3. On the same page as the script link, also include the <kbd>Import Expressions</kbd> button from [`src/ui/settings/components/Expressions.tsx`](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/blob/3.X.X-Branch/src/ui/settings/components/Expressions.tsx) (accessed at `moz-extension://e38f9d03-8992-4e12-a98d-52deeae06a2c/settings/settings.html#tabExpressionList`)

I can adapt my [firefox cookie settings export](https://gist.github.com/daniel-barrows/ec3a59339b16f418020c2f9b6a94e766) script for you to produce a Cookie-AutoDelete's JSON format to be used in step 2 above.

The main challenge I see here is platform compatibility. My script is a POSIX shell script. It's not complicated and can easily be ported, but I don't know if there's a cross-platform way to do it or if sqlite is available on all machines. Firefox itself is using sqlite, so it's on all computers Firefox is on somewhere.

**Comment by chiraag-nataraj** [comment]
> Firefox itself is using sqlite, so it's on all computers Firefox is on somewhere.

Pretty sure they're just using the sqlite shared library to access their databases. That doesn't mean the sqlite program is available, unfortunately.

**Comment by kennethtran93** [comment]
I'll welcome a documentation page for this, but it won't be anywhere in the extension (except maybe a message and a link to that documentation).
