### ISSUE TITLE
No full list of expressions

### ISSUE THREAD

**Issue by Zerwin** [mrdokenny/Cookie-AutoDelete#509]
### Describe the Bug/Feature

If I go to the List of Expressions, not all currently set Expressions are shown. I have multiple sites that, if being visited are shown to being on the grey/whitelist, yet they aren't in listed under Settings -> List of Expressions. I noticed this bug when I tried to export the list and import in a new browser profile, and multiple websites were being deleted that were whitelisted earlier.

### Your settings 
Default + Enable Automatic Cleaning + Localstorage Cleanup

- OS/version: Windows 10 1803, freshly setup
- Browser/version: Firefox 65.0.2
- Cookie AutoDelete version: 3.0.1

**Comment by kennethtran93** [comment]
is the website cookie in question being deleted after import into new profile?  Is there a sample website/screenshot that you could provide to help?

**Comment by Zerwin** [comment]
The problem was quite a while ago, and after the firefox addon debacle, I lost the list of what wasn't on the exported list. I can't seem to duplicate the problem anymore, so I close this issue for now.
