### ISSUE TITLE
Issues with domain whitelisting from icon

### ISSUE THREAD

**Issue by collectorgeneral** [mrdokenny/Cookie-AutoDelete#51]
### Describe the Bug/Feature

It appears to me that certain websites have issues with whitelisting the domain.

For instance, if one goes to account.google.com and whitelists from there, it does not whitelist google.com (which we want) but rather it whitelists account.google.com which has the undesirable effect of deleting cookies.

What would be expected is that google.com gets whitelisted instead. 

Another related issue with some websites that have urls such as: www1.somewebsite.com or www2.somewebsite.com: if visited and whitelisted, the extension appears to capture the wwwx part of the url. What would be expected is that it ignores those parts. 

### Screenshot in which the bug can be seen
![screenshot from 2017-06-17 00-48-42_2](https://user-images.githubusercontent.com/15972594/27249963-684566bc-52f8-11e7-9b37-516febb4c2e1.png)
![screenshot from 2017-06-17 00-58-00](https://user-images.githubusercontent.com/15972594/27249962-684549b6-52f8-11e7-820f-c7cd1b63581c.png)

As you can see, I whitelisted google.com from the accounts page but on gmail, it does not detect the whitelist and essentially deletes the cookie.

### Steps for anyone to reproduce the bug

As an example, go to accounts.google.com and whitelist using the extension icon. it appears fine but when you go to other services such as gmail, they are not identified. 

### Your settings 

ALL tickboxes checked.

- OS/version: 
Manjaro 17.0.1
- Browser/version: 
Firefox 53.0.3
- Cookie AutoDelete version: 
1.3.0

**Comment by collectorgeneral** [comment]
It is important to note that manually inputting google.com in the settings page appears to help circumvent the issue of adding by clicking the extension.
However, there is another issue with doing this, which is that the extension itself appears blue but the checkbox for the "Add to whitelist" is not checked. As an example, refer to the screenshot below:

![screenshot from 2017-06-17 01-08-19_3](https://user-images.githubusercontent.com/15972594/27249996-ee6e1d32-52f9-11e7-8a80-e7505964ce36.png)

And I picked google.com as an example, but it appears to be the case with other websites too. 

This is AFTER I manually input google.com in the whitelist urls. Notice that the icon is blue, which indicates okay, but the checkbox is not checked? This could cause confusion.

**Comment by mrdokenny** [comment]
> For instance, if one goes to account.google.com and whitelists from there, it does not whitelist google.com (which we want) but rather it whitelists account.google.com which has the undesirable effect of deleting cookies.

That's the expected behavior cause you are on that exact domain (mail.google.com). If you wanted to whitelist the main domain such as google.com, you would go into the options UI and enter it from there manually. Or actually go to google.com and "Add to Whitelist" from there.

Also I didn't want to overload the popup and confuse people.

> Another related issue with some websites that have urls such as: www1.somewebsite.com or www2.somewebsite.com: if visited and whitelisted, the extension appears to capture the wwwx part of the url. What would be expected is that it ignores those parts.

I haven't seen any url like that before, do you have an example?

**Comment by mrdokenny** [comment]
> This is AFTER I manually input google.com in the whitelist urls. Notice that the icon is blue, which indicates okay, but the checkbox is not checked? This could cause confusion.

Yeah that is the expected behavior because its showing that mail.google.com is protected because there's an entry for google.com

**Comment by mrdokenny** [comment]
See issue #3 for implementation details.

**Comment by collectorgeneral** [comment]
> Yeah that is the expected behavior because its showing that mail.google.com is protected because there's an entry for google.com

Yes, I understand that after inputting google.com you see the icon turn blue. Which is what we would expect. What I am saying is that simultaneously the checkbox should be ticked too. 

> If you wanted to whitelist the main domain such as google.com, you would go into the options UI and enter it from there manually. Or actually go to google.com and "Add to Whitelist" from there.

The problem with sites like google is that they redirect you to geographic site, like google.ca in my instance, but all their accounts are handled by *.google.com and thus renders this route useless.

> See issue #3 for implementation details.
Hm, while I understand the reasoning behind the idea, and I agree with it, many cases (such as mine), you have issues where you can have your page as google.ca you yahoo.ca where as the credentials and other stuff are managed by their *.com counterparts. This makes it quite annoying to deal with. This is the case for me with almost any major website: amazon, google, yahoo you name it. We are always redirected to our geographic page while the credentials are managed by the *.com website. 

Ideally, I would like to have two options: whitelist subdomain OR whitelist Top Level Domain. However, I will leave it up to you to decide. 

> I haven't seen any url like that before, do you have an example?
Sure 😃. Several websites I visit have this quirk, notably bank websites: If you go try going to www.scotiaonline.scotiabank.com, you will be automatically redirected to www1.* or www2.*

Again, same issue here, if you whitelist from the login page, it will whitelist subdomain, not TLD which breaks some of the functionality HARD. I had to disable the extension to circumvent this problem. You might understand why it would not help an average user, especially if it breaks functionality on a really important website like the banks. So I go back to suggesting having a 2 tier option: 

- Add to whitelist? When this is checked, expose another option that says:
- Also add Top Level Domain?

**Comment by mrdokenny** [comment]
@collectorgeneral 
> Yes, I understand that after inputting google.com you see the icon turn blue. Which is what we would expect. What I am saying is that simultaneously the checkbox should be ticked too.

It's unchecked because you would be adding mail.google.com and that domain is not in the whitelist yet.

> The problem with sites like google is that they redirect you to geographic site, like google.ca in my instance, but all their accounts are handled by *.google.com and thus renders this route useless.

I think the solution here is to manually add those *.com sites since it would be impossible to do detection for different top level domains (.ca, .uk,, .cz) for each locale.

> Several websites I visit have this quirk, notably bank websites: If you go try going to www.scotiaonline.scotiabank.com, you will be automatically redirected to www1.* or www2.*

> Again, same issue here, if you whitelist from the login page, it will whitelist subdomain, not TLD which breaks some of the functionality HARD. I had to disable the extension to circumvent this problem. 

That is definitely a bug. I can see that when you add that example website it adds `www1.scotiaonline.scotiabank.com` which should be instead be `scotiaonline.scotiabank.com`

I also see that it's creating these cookies.

![capture2](https://user-images.githubusercontent.com/17077613/27250254-bff25baa-52de-11e7-96e4-f27bc4fd893d.PNG)

How the cleanup works is it takes a "domain" part in that picture of the cookies (deletes the leading dot if there is any) and does a strict comparison with the whitelist. 

So while you can't add it from the popup, you can manually add `scotiabank.com` and it should protect cookies `scotiabank.com` and `www1.scotiaonline.scotiabank.com`. Can you confirm?

**Comment by collectorgeneral** [comment]
Yes. That is correct. 
Also, you are right, it is impossible to add all the localisations. Maybe it is better to leave it as it is and input domains manually.

**Comment by mrdokenny** [comment]
Yeah sorry it didn't work out in the popup but hey at least there's an option to input them manually 😉.

I'll see what I can do about the www1 bug.

Also, just curious does Self Destructing Cookies have this problem?

**Comment by collectorgeneral** [comment]
Good question. I am not sure. It's been a while since I used SDC and I remember having to mess with it in order to get it working, so maybe it did.

**Comment by mrdokenny** [comment]
I see. Ok then.
![capture2](https://user-images.githubusercontent.com/17077613/27250360-6326d122-52e2-11e7-8212-f6718bd9b676.PNG)

For future reference, look at the domain part and add that manually (without the leading dot) for the sites you want to protect cause the cleanup is going to be comparing that domain attribute for every cookie.

Adding the site from the popup is probably working fine for the majority of people (including me), it's just those random sites (mostly international) that give it an issue so any example sites should be reported. 😄

**Comment by collectorgeneral** [comment]
Yep, I guess that is true. On the note of adding sites to whitelist, can you make an option to edit existing entries in the whitelist? I could at least manually edit subdomains I want/correct mistakes easily 😺 . Currently you need to delete it and readd it. Possibly just make it so that you can click the entry to edit? Is this doable?

**Comment by mrdokenny** [comment]
> Possibly just make it so that you can click the entry to edit? Is this doable?

I think it is possible but it won't be a high priority for me cause there's other features that I have to implement to close the gap with SDC.

Also if you export it, you can manually edit the file in a text editor, then do a "Remove all" and "Upload File".

**Comment by collectorgeneral** [comment]
Sure! I would rather have you focus on closing the gap with SDC too 😺 
I will close this issue since you have clarified it. Thank you!
