### ISSUE TITLE
Путь хранения настроек

### ISSUE THREAD

**Issue by sv19com** [mrdokenny/Cookie-AutoDelete#510]
Очень нужно добавить путь хранения настроек: в случае переустановки Windows достаточно будет указать путь

**Comment by kennethtran93** [comment]
English via Google Translation:

> Title: **Storage path settings**
> 
> It is very necessary to add the path to store the settings: in case of reinstalling Windows, it will be enough to specify the path

**Comment by kennethtran93** [comment]
Most likely duplicate of #429, I'm presuming the export of all settings related to the webextension, including core and grey/white lists.

**Comment by ke-d** [comment]
Duplicate of #429
