### ISSUE TITLE
Firefox 66 Notification window/popup broken

### ISSUE THREAD

**Issue by MaxXor** [mrdokenny/Cookie-AutoDelete#511]
### Describe the Bug/Feature
In Firefox 66 the notification window/popup is broken. It just shows an error.

### Screenshot in which the bug can be seen
![error](https://user-images.githubusercontent.com/7271470/54598403-ba8df400-4a38-11e9-8a4a-8afec6815fc4.png)

### Steps for anyone to reproduce the bug
Update to Firefox 66 and click on the extension icon.

### Your settings 

- OS/version: Arch Linux
- Browser/version:  Firefox 66
- Cookie AutoDelete version: 3.0.1

**Comment by kennethtran93** [comment]
weird. It's working for me in Windows 10.

Firefox Browser 66.0.1 64-bit
CAD v3.0.1

**Comment by kennethtran93** [comment]
Does exporting the expressions, then resetting the webextension and re-importing those expressions help?

**Comment by MaxXor** [comment]
Yes, that fixed it thanks. Couldn't reproduce it on another PC. No idea what caused this.
