### ISSUE TITLE
Some sites remember me although I use Cookie-AutoDelete

### ISSUE THREAD

**Issue by ghost** [mrdokenny/Cookie-AutoDelete#514]
### Describe the Bug/Feature

Sites like www.immobilienscout24.de and others seem to remember me, although Cookie-Auto-Delete is active. When I enter site, the information I recently filled into the form, are there again.

### Your settings 

- OS/version: Kubuntu 18.04
- Browser/version: Firefox 66.0.2 (64bit)
- Cookie AutoDelete version: 3.0.1

**Comment by ke-d** [comment]
They use localstorage, do you have the enable localstorage setting enabled?

**Comment by gwarser** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1522188 "storage.local IndexedDB database gets corrupted for some users"

**Comment by ghost** [comment]
That was the right clue. Now it works. Thank you. So it may be my fault - not a bug.

**Comment by kennethtran93** [comment]
Could somebody please mark this as closed?
