### ISSUE TITLE
No longer cleaning anything in FF nightly.

### ISSUE THREAD

**Issue by Betsy25** [mrdokenny/Cookie-AutoDelete#515]
### Describe the Bug/Feature
When using Firefox Nightly v68, CAD no longer cleans anything, also no Cleaning popups. It's been a full month since it last cleaned anything according to the log.

### Steps for anyone to reproduce the bug
Try in Firefox Nightly v68

### Your settings 
[Screenshot](http://imgbox.com/GZDv3o2r)

- OS/version: Win7 x64
- Browser/version: Firefox Nightly v68
- Cookie AutoDelete version: 3.0.1

**Comment by ke-d** [comment]
Looks FF changed something with the localstorage API recently, I think it stills cleans stuff but it doesn't provide logs cause the cookie cleanup happens before localstorage.

Anyway can you try this patch and see if it resolves your issue? @Betsy25 

[Cookie-AutoDelete_Firefox_Dev_190413_0820.zip](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/files/3076371/Cookie-AutoDelete_Firefox_Dev_190413_0820.zip)

**Comment by Betsy25** [comment]
All seems to work fine again with the patched version, @mrdokenny
