### ISSUE TITLE
Can a save settings button be added?

### ISSUE THREAD

**Issue by techspecx** [mrdokenny/Cookie-AutoDelete#516]
### Describe the Bug/Feature
Settings not saving after I close the Firefox Quantum browser. Latest release 66.0.3

### Screenshot in which the bug can be seen
No screenshot

### Steps for anyone to reproduce the bug
Open browser - pick my settings and the cookies are deleted. But when I close the browser and reopen it all my settings revert back to default. Also when I close the browser and then reopen it the Auto Clean-enabled button needs to be activated again. Is there a way to have these enabled all the time also because if it isn't enabled Firefox collects cookies until I realize that it wasn't enabled.

Can't we add a save button so the settings are always enabled so I don't have to go back in and change my settings to what I like to use. Thank you.

### Your settings 

- OS/version: Windows 10 64bit
- Browser/version: Firefox Quantum 66.0.3
- Cookie AutoDelete version: 3.0.1

**Comment by ke-d** [comment]
Settings are automatically saved when you change a setting (no need for a save button), so something else is deleting your extension settings.

**Comment by ghost** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1522188 "storage.local IndexedDB database gets corrupted for some users"

**Comment by kennethtran93** [comment]
Is this still an active issue after updating both Firefox and CAD to their latest respective versions?  If not I'll be closing this issue in a few days.

**Comment by kennethtran93** [comment]
Closing for staleness.  Most likely it was storage.local corruption as mentioned above to it is a firefox thing.
