### ISSUE TITLE
www not deleting

### ISSUE THREAD

**Issue by digil12** [mrdokenny/Cookie-AutoDelete#517]
If I visit some sites, for example  www.independent.co.uk   or  www.menshealth.com  cookies get set as  independent.co.uk and menshealth.com  along with www.independent.co.uk   and  www.menshealth.com

But Cookie-AutoDelete doesn't remove the www. cookies, although it does delete independent.co.uk and menshealth.com  cookies.

I'm using Opera browser.  Am I doing anything wrong ?  

![image](https://user-images.githubusercontent.com/49650314/56157357-3a1ace80-5fb7-11e9-8f23-8da5f25bc171.png)

**Comment by kennethtran93** [comment]
Since you have the log checked off, provide a screenshot of that log in particular and where you see the www cookies as well.

Presuming your white/grey list has none of those urls mentioned.

**Comment by digil12** [comment]
So your app deletes  menshealth.com  even though it wasn't there, and leaves behind  www.menshealth.com    Doesn't happen for all sites, but does for this and a few others at random.  I've now checked the 'Enable Cleanup on Domain Change?' but makes no difference...

![image](https://user-images.githubusercontent.com/49650314/56376458-d7684380-61ff-11e9-94a3-b11e1ac6f344.png)

![image](https://user-images.githubusercontent.com/49650314/56376529-02529780-6200-11e9-829a-3ae406e7c3b5.png)

**Comment by ke-d** [comment]
What might get confusing is that CAD acknowledge domains with `www` and without it the same. So `www.google.com` = `google.com`. Mostly done so less whitelisting is needed since many sites use `www` for their default domains.

As for your problem, it could be how Opera handles the APIs since CAD does not officially support Opera.

**Comment by kennethtran93** [comment]
Closing this issue due to unofficially supported browser.
