### ISSUE TITLE
Session vs Persistent cookies

### ISSUE THREAD

**Issue by Pete879739** [mrdokenny/Cookie-AutoDelete#518]
This is a suggestion to add a comment to the FAQs that CAD doesn't preserve Session cookies.  While that's probably obvious to you, it took me a long time to realize why CAD wasn't saving FastMail.com's cookies.  It turned out that the website uses only session cookies unless I tell it to remember my login credentials.

I'm thinking that some of the bug reports or at least bad user reviews might be caused by such misunderstandings.

**Comment by kennethtran93** [comment]
session cookies are essentially cookies, so they get removed if not whitelisted?

If you want to keep certain cookies you should be able to whitelist the url and only check off that specific cookie id/name (probably has the 'session' word in it) to be kept once you uncheck 'keep all cookies'.

I do agree that a FAQ entry should be added for this nonetheless.

**Comment by ke-d** [comment]
CAD doesn't modify any cookies so it won't upgrade session cookies to persistent.

**Comment by Pete879739** [comment]
I think there's been a misunderstanding.  My point was that I thought CAD had a bug cuz it wasn't saving the cookie for a white-listed domain.  Then I realized it wasn't CAD's fault cuz it was only a session cookie.

So I thought if there had been a FAQ entry about it, I might have realized my mistake sooner.  Other people might also make the same mistake and unfairly blame CAD.

Anyway it's only a suggestion.

**Comment by kennethtran93** [comment]
Apologies for the rather large delay in editing FAQs.  The note for Session Cookies has been added.

**Comment by Pete879739** [comment]
> Apologies for the rather large delay in editing FAQs. The note for Session Cookies has been added.

Thanks!
