### ISSUE TITLE
Add option to change toolbar icon

### ISSUE THREAD

**Issue by mueller-ma** [mrdokenny/Cookie-AutoDelete#519]
### Describe the Feature

Add option to change the toolbar icon to an icon which is similar to the icons by Mozilla (reload, download, back, forward, etc.).
Suggestion: https://materialdesignicons.com/icon/delete-outline or a crossed out cookie.

**Comment by kennethtran93** [comment]
Perhaps a reason/use case why this would be helpful/useful?

**Comment by mueller-ma** [comment]
IMO the toolbar looks better if all icons have the same style.

**Comment by kennethtran93** [comment]
Just remember that there are many webextensions out there, in various browsers, so each addon needs to somehow be distinguished from one another.  I don't think there are too many webextensions that allow users to change the toolbar icon as most icons are done as logo/branding for their extensions.

Not to mention that there's actually 4 icons (albeit different colored) for this extension, to distinguish whitelist, greylist, no rules, and unavailable on each tab.

**Comment by kennethtran93** [comment]
Closing for now - Kenny can reopen this should this feature feels needed for this extension
