### ISSUE TITLE
Add an option to hide toolbar icon

### ISSUE THREAD

**Issue by lypwig** [mrdokenny/Cookie-AutoDelete#520]
A such option (disabled by default) could be useful do silently delete cookies, while keeping the toolbar clean.

**Comment by kennethtran93** [comment]
Unless I'm mistaken, that is technically a browser feature request, and in both Chrome and Firefox they have already been implemented.  Simply right-click the extension and choose the action accordingly.

In Google Chrome:
![Add an option to hide toolbar icon · Issue #520 · Cookie-AutoDeleteCookie-AutoDelete - Google Chrome](https://user-images.githubusercontent.com/6724477/56340059-8ad02a00-6165-11e9-94d7-bf102775c54c.png)

In Firefox:
![Firefox Developer Edition](https://user-images.githubusercontent.com/6724477/56340060-8b68c080-6165-11e9-8ca3-ea3d168002e6.png)
