### ISSUE TITLE
Add option to whitelist/graylist domain from logs

### ISSUE THREAD

**Issue by saurabh-mhaisekar** [mrdokenny/Cookie-AutoDelete#521]
It would be really great if I am able to add a domain to whitelist or gray list directly from the logs. This is particularly useful when using extensions such as evernote or lastpass.

**Comment by ScoobyDone** [comment]
omg, yes.  very helpful on your first day of usage and all your existing cookies are getting whacked since SDC's whitelist worked a bit differently...  :(

**Comment by polygonie** [comment]
I agree this would be extremely useful! 
It would make managing the white/grey lists a lot easier than manual editing.

**Comment by cj8686** [comment]
I came here just to log the same suggestion. Inline whitelisting from the log would streamline the whitelisting workflow significantly. This extension is fantastic, thanks to all those who contribute to its success.

**Comment by kennethtran93** [comment]
Update:  I'm working on right-click context menus, which would include adding domain/subdomains by right-clicking on either the link, page, or selected text.

This issue would be resolved by selecting the domain from the logs and right-clicking the selection to bring up the (4) options (domain only -> greylist/whitelist) (domain w/ all subdomains -> greylist/whitelist)

**Comment by kennethtran93** [comment]
For those who know how to test this please give it a shot in the linked PR #753
