### ISSUE TITLE
I've selected "Localstorage Cleanup (Firefox 58+)". But just checked Firefox 66.0.3 (64-bit) and it is storing data from about 24 sites. 

### ISSUE THREAD

**Issue by jj123** [mrdokenny/Cookie-AutoDelete#524]
### Your settings 

- OS/version: 
- Browser/version: 
- Cookie AutoDelete version:

**Comment by jj123** [comment]
That is what I see in "FF/Tools/Options/Privacy & Security/Cookies and Site Data / Manage Data.
Everything stored has zero Cookies and does show a Storage size.

Under FF Cookies and Site Data I did NOT check "Delete cookies and site data when Firefox is closed" because I assumed Cookie AutoDelete is taking care of it.

The only way that stored site data deletes is when I manually click in FF Manage Data/Clear All.

Am I then misunderstanding Cookie AutoDelete when I've checked "Localstorage Cleanup (Firefox 58+)"?

(Great app btw - thank you).

**Comment by kennethtran93** [comment]
Duplicate issue - see #512 comments for details, notably this one:  https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/512#issuecomment-482820132

Also next time don't put everything in the title - just a quick info title and the rest can go in to the description please.

**Comment by kennethtran93** [comment]
Closing due to duplicate issue #512
