### ISSUE TITLE
Compatibility with FF 66.0.3[SOLVED]

### ISSUE THREAD

**Issue by v-k-** [mrdokenny/Cookie-AutoDelete#526]
Hello. The extension have been disabled in FF 66.0.3.

- OS/version: mac os 10.14.4
- Browser/version: FireFox 66.0.3
- Cookie AutoDelete version: 3.0.2
<img width="761" alt="Screen Shot 2019-05-05 at 10 35 33" src="https://user-images.githubusercontent.com/2482677/57194805-835c9f00-6f21-11e9-9e27-c2005f388c7a.png">

**Comment by alln4tural** [comment]
Same for 66.0.2 android

Thanks for this addon!

**Comment by ghost** [comment]
https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/525

**Comment by v-k-** [comment]
Updating FireFox to just released 66.0.4 just solved the problem with all add-ons.
The issue can be closed, I think.

thanks for the app and your time.
