### ISSUE TITLE
Deleted Cookies in Whitelist

### ISSUE THREAD

**Issue by ghost** [mrdokenny/Cookie-AutoDelete#536]
### Bug

I had just the Default Settings enabled and no cookies were being deleted, so I enabled the first option, "Automatic Cleaning" and closed the browser. 
I have two Expressions whitelisted and it cleaned those cookies as well, though the two Expressions remain whitelisted in the "List of Expressions".
I have now reset it back to Default but no cookies are being cleaned.
Why doesn't it clean cookies on the default settings?

### My Settings 

Enable Automatic Cleaning? Delay Before Cleaning:Second(s)? - 15 yes
Enable Cleanup on Domain Change? - no
Enable Cleanup Log and Counter? - yes
Show Number of Cookies for that Domain? - yes
Show Notification After Cookie CleanupSecond(s)? - yes, 3
Clean Cookies from Open Tabs on Startup? - no
Enable Support for Firefox's Container Tabs? - yes
Localstorage Cleanup (Firefox 58+)? - no

- OS/version: Windows 7
- Browser/version: Firefox 67.0.1
- Cookie AutoDelete version: 3.0.2

**Comment by kennethtran93** [comment]
What are the expressions?

**Comment by kennethtran93** [comment]
Default gives you a chance to make sure that you have properly grey or white list the URLs if need be first, then you need to enable cleaning (first option).  Otherwise, if the Default is to delete everything upon installation, then people would complain about their existing cookies being deleted without allowing them time to create their grey and/or white lists.

**Comment by mireksochor** [comment]
I have the same issue. With auto-clean enabled and site whilelisted the cookies are still deleted when closing the tab. What am I doing wrong?

Enable Automatic Cleaning: YES
Delay Before Cleaning:Second(s)? : 15s
Enable Cleanup on Domain Change: NO
Enable Cleanup Log and Counter? YES
Show Number of Cookies for that Domain? YES
Show Notification After Cookie CleanupSecond(s)? YES, 3s
Clean Cookies from Open Tabs on Startup? NO
Enable Support for Firefox's Container Tabs? NO
Localstorage Cleanup (Firefox 58+)? NO


OS: macOS 10.14.5
Browser: 67.0.1 (64-bit)
CAD version 3.0.2

**Comment by kennethtran93** [comment]
@DavidManning @mireksochor 
To help you out and to narrow any possible bugs down further, please answer/provide the following additional details:
- What are the expressions you used?
- What does your cleanup log details say - click on the timestamp of that specific cleanup to see its details (screenshot is fine)?

**Comment by ghost** [comment]
I installed a different addon.

**Comment by mireksochor** [comment]
Thanks @kennethtran93 for getting back to me so quickly.
Here are expressions I am using: denikn.cz and *.denikn.cz, keep local storage and Keep all cookies.
Cleanup log says: No Cleanups log found
But notification after closing the website says:15 cookies deleted from denikn.cz

Any idea?

**Comment by kennethtran93** [comment]
@mireksochor Open a new issue with the above including your settings.  This is out of my basic knowledge so it may be some unheard of bug...
