### ISSUE TITLE
IP Regex bug (work-12345678.workplace.com) is being treated as an IP

### ISSUE THREAD

**Issue by hethhhhh** [mrdokenny/Cookie-AutoDelete#539]
On some websites, e.g. workplace.com (facebook's office spinoff) the presence of Cookie Autodelete addon logs out the user almoust every minute, even though it's whitelisted. When I disable the addon it works fine.

This and some others problems can be solved if there was disable on this website option, or maybe it's a whitelist bug?

- OS/version: 8.1
- Browser/version: FF 67.0.2
- Cookie AutoDelete version: 3.0.2

**Comment by kennethtran93** [comment]
Are there any logs that this web extension performed anything on that site as well as your expressions if any?

**Comment by hethhhhh** [comment]
workplace.com (datr, sb, c_user, xs, spin, pnl_data2, presence, wd): Clean because workplace.com is not in the White/Grey lists
https://i.imgur.com/plhIPgI.png

Maybe Cookie-AutoDelete doesn't detect there are cookies from *.workplace?

**Comment by kennethtran93** [comment]
Weird - that definitely looks like a bug.
All sites should usually show a *.example.com just below its subdomain.example.com.


A workaround for now is to go into settings -> List of Expressions, find your workplace.com entry, and change it to *.workplace.com manually.

I'll try to look into this further later on.

**Comment by kennethtran93** [comment]
I've found the culprit - this line (  `const reIP = new RegExp('[0-9]+.[0-9]+.[0-9]+.[0-9]+');` ) is catching the https://work-12345678.workplace.com as an IP address (as IP addresses don't have subdomains).

I'll patch it up shortly with a PR (only for IPv4 for now).  

@mrdokenny Probably better to use the npm package `ip-regex` that is download over 5 million times than try to reinvent the wheel here.

**Comment by kennethtran93** [comment]
While it is fixed, it will be held for one or two more fixes before another patch release will be made, FYI.
