### ISSUE TITLE
Make CAD compatible with Edge Chromium. 

### ISSUE THREAD

**Issue by saurabh-mhaisekar** [mrdokenny/Cookie-AutoDelete#542]

**Comment by kennethtran93** [comment]
Edge Chromium isn't fully released to the public yet.  In the meantime, have you tried this to see if it works?  https://microsoftedgesupport.microsoft.com/hc/en-us/articles/360017581013-Install-a-Chrome-Web-Store-extension-on-Microsoft-Edge-for-Windows-and-MacOS

**Comment by ghost** [comment]
me i have tested, it work well, i upvote this demand BUT after i have contacted them it seems theyre upload system it's not released yet (i will warn you when it's opened for upload if you want)

**Comment by ghost** [comment]
the complete response it : 
"We are in the process of putting together the new publishing pipeline for Chromium based extensions which should be ready later part of this year. We should be making an announcement closer towards availability."

**Comment by ghost** [comment]
the chrome web store acceptation seem's to be temporary for let the user have their favorite extensions

**Comment by ktnjared** [comment]
The process is now documented over on Microsoft Docs: [Publish An Extension](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/publish-extension).

Would love to see CAD in the Edge Addons catalog, especially with extension syncing being [slated for release this month](https://techcommunity.microsoft.com/t5/discussions/top-feedback-summary-for-march-11/m-p/1222906).

**Comment by kennethtran93** [comment]
Work in Progress.  The downside is the amount of copy-paste that I have to do for each locale I have...stupid.

This will just be the same as the Chrome version for now.  I'm sure there will be some bugs that will surface and when that happens please open an issue.

**Comment by m-i-k-e-y** [comment]
I've installed CAD from the Chrome Web Store in Edge Chromium and it is working (for me) as advertised.

**Comment by kennethtran93** [comment]
The Backend of the Edge Extension Page is very tedious...making me wonder if it is really worth it...

For each locale (I think there's at least 15 in this one, they require their own description (to which I'm just copy-pasting the English one), as well as uploading the extension icon as the minimum.  Then for optional things I'm adding 3 screenshots and adding in keyword search terms...  Each screenshot and logo takes a minute or so for the file picker to load, then another minute to actually upload...

I've done just over 10 locales at this point...not even halfway yet...

**Comment by ktnjared** [comment]
Looks like you need to provide store listing languages for each language you support, so since CAD has a number of translations in its build, it’ll need one for each. Looks like there’s 30 languages in the repo, so it’s probably prompting for 30 locales to be setup.
 
That might be something to consider adding into the translation effort: store page text localized, along with screenshots of the localized version.
 
e: I’ll be honest, I didn’t expect it to be so involved, but I do appreciate you doing this.

**Comment by ktnjared** [comment]
I was going through the [Microsoft Edge Addons Catalog Developer Policies](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/store-policies/developer-policies) so I can better understand it and to see if there was something I could do to offer as help, and came across section [1.7 Localization](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/store-policies/developer-policies?branch=user%2Fv-jomar7%2Fdocs%2Fextensions-chromium%2Fstore-policies%2F2019DEC09#17-localization) where it says: 

> You should localize your Extension for all languages that the Extension claims to support. The text of the description of your Extension should be localized in each language that you declare.
> If your Extension is localized such that some features are not available in a localized version, you must clearly state or display the limits of localization in the Extension description. The experience provided by an Extension must be reasonably similar in all languages that it supports.

@kennethtran93 , you mentioned earlier that you were copying the English in for all of the localized descriptions. This might get the extension flagged. 

Might be easier for now to built the extension without localizations until localization contributors can contribute the text fields necessary for submission?

**Comment by kennethtran93** [comment]
The Title and Short description is already localized if it was translated through Crowdin (those were apparently already taken through manifest.json).  The Long Description wasn't.  I wasn't planning on having the long description translated as it could change at anytime and some meaning may be lost in context, especially as the description varies between browser stores.

It's actually easier to build everything at once as the locales are already in the extension folder.  The only things that need to be compiled into the folder are the source files and some of the global files (e.g. bootstrap, jquery, etc).

> > If your Extension is localized such that some features are not available in a localized version, you must clearly state or display the limits of localization in the Extension description. The experience provided by an Extension must be reasonably similar in all languages that it supports.

All features are available in all languages (browser-dependent of course), so I don't think this applies.  It should show the default English version for the locales strings that weren't translated yet.

**Comment by kennethtran93** [comment]
If you're curious, here's what one locale of its storefront page fields are.
![FireShot_Capture_001_partner microsoft com_20200329-1402](https://user-images.githubusercontent.com/6724477/77860973-11d7b000-71c7-11ea-9a62-91ee1f35b8cb.png)

The search terms are preliminary.  I'm sure there would be better terms to include.

**Comment by kennethtran93** [comment]
As 3.2.0 is not complete at this time, 3.1.1 has been published onto the Edge Chromium Extension store here:  https://microsoftedge.microsoft.com/addons/detail/djkjpnciiommncecmdefpdllknjdmmmo
