### ISSUE TITLE
Vivaldi browser - extension unusable

### ISSUE THREAD

**Issue by vjuhasz2** [mrdokenny/Cookie-AutoDelete#544]
After the first auto-cleanup the user interface becomes unusable. Clicking on the icon will result in a small white box with no content. No white- or greylisting is possible anymore, so the extension becomes unusable.

![image](https://user-images.githubusercontent.com/52224774/60144444-43e05f80-97ba-11e9-986e-960d5f289485.png)

Vivaldi | 2.6.1566.40 (Stable channel) (32-bit)
-- | --
Revision | 8688bc465077a16ed6f840ab566085fee1f32d4b
OS | Windows 10 OS Version 1903 (Build 18362.175)
JavaScript | V8 7.5.288.23
Flash | 32.0.0.207 C:\WINDOWS\SysWOW64\Macromed\Flash\pepflashplayer32_32_0_0_207.dll
User Agent | Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.94 Safari/537.36 Vivaldi/2.6.1566.40
Command Line | "D:\Program Files\Vivaldi 25\Application\vivaldi.exe" --vivaldi-standalone --flag-switches-begin --flag-switches-end --ppapi-flash-path="C:\WINDOWS\SysWOW64\Macromed\Flash\pepflashplayer32_32_0_0_207.dll" --save-page-as-mhtml
Executable Path | D:\Program Files\Vivaldi 25\Application\vivaldi.exe
Profile Path | D:\Program Files\Vivaldi 25\User Data\Default

**Comment by kennethtran93** [comment]
FYI - Vivaldi is not officially supported.  Only Mozilla Firefox and Google Chrome are.  Derivatives of those, including Waterfox and other Chromium-based browsers are not supported at this time.
