### ISSUE TITLE
Whitelist doesnt work in Firefox 67.0.1 with Permanent Private Browsing

### ISSUE THREAD

**Issue by mireksochor** [mrdokenny/Cookie-AutoDelete#546]
Whitelisted sites still does not keep cookies. "No cleanup logs found" message appearing. 
Cleanup log in settings is stating "No Cleanup Logs Found" message.

- OS/version: 10.14.5
- Browser/version: 67.0.1
- Cookie AutoDelete version: CAD version 3.0.2

[X] Enable Automatic Cleaning? Delay Before Cleaning: 15Second(s)?
Enable Cleanup on Domain Change?
[X] Enable Cleanup Log and Counter?
[X] Show Number of Cookies for that Domain?
Show Notification After Cookie CleanupSecond(s)?
Clean Cookies from Open Tabs on Startup?
Enable Support for Firefox's Container Tabs?
Localstorage Cleanup (Firefox 58+)?

**Comment by kennethtran93** [comment]
Please let us know the URL what wasn't working as well as the expression you have on your whitelist.  Also your cookie settings in Firefox Preferences.

**Comment by mireksochor** [comment]
Hi!
its multiple urls: i.e. denikn.cz
The expressions related to that site is: 
*.denikn.cz, keep localstorage, keep all cookies, whitelisted
denikn.cz, keep localstorage, keep all cookies, whitelisted
predplatne.denikn.cz, keep localstorage, keep all cookies, whitelisted

**Firefox settings:**
Content blocking: Custom
 - Block trackers
 - DNT always
 
**Cookies and Site Data**
In permanent private browsing mode, cookies and site data will always be cleared when Firefox is closed. 

What baffles me that notification is saying how many cookies has been deleted but there are no Cleanup logs.

**Comment by kennethtran93** [comment]
~~@mrdokenny Does this addon fully work in private browsing mode?~~

**Comment by kennethtran93** [comment]
@mireksochor A search from old issues lead me to a previous issue to which the answer there as well:  https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/500#issuecomment-464291315 which is pasted below (the answer is from the creator).

> Cookie-AutoDelete deletes all cookies from the private container (private browsing), nothing shows up in the log. (notification does show)

That is expected since it would be a privacy leak if CAD saved logs for private mode browsing.

> I can't make any rules for this container because it doesn't show.

Same reasoning as above.

As of result I will now close this issue as a duplicate of #500.
