### ISSUE TITLE
"Options" button links to the Release Notes page instead of the Options page.

### ISSUE THREAD

**Issue by addHarry** [mrdokenny/Cookie-AutoDelete#548]
"Options" button links to the Release Notes page instead of Options;  Note: this is for the current CAD version 3.0.2  used with the current stable version of Firefox (v.67.04) within Win10 Pro 64bit. I have already tried rebooting Firefox with only CAD enabled (with my 5 other extensions disabled). Any remedy suggestions? Thanks much...BTW, CAD is great!

**Comment by kennethtran93** [comment]
~~Where is this options button you are clicking from?~~
EDIT:  nevermind - I rarely use the options button from the addons page, hence that question..

**Comment by kennethtran93** [comment]
In accordance with the manifest file, 
https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/blob/7563c02f07ecc7741fd58bad9f5a14d1a0be7b69/extension/manifest.json#L33-L36 
it is supposed to be that page first.  You can access the settings tab through the navigation, or use the popup settings to go directly there.  At this point it isn't really a bug.

@mrdokenny Is this truly a 'works as intended' situation?

**Comment by addHarry** [comment]
Thanks KT93 for your reply...  I now realize that I overlooked the unidentified /// 3 line "hamburger" icon in the upper left corner of the Release Notes page that your Options button took me to. Bear in mind though, that normally, a selection button such as yours called "Options" button is for accessing the options page immediately--as you know, your options button  links to your Release Notes page with the unidentified somewhat obscure, easy 3 line /// hamburger button in the upper left corner of your otherwise all-text Release Note page--yes, the "hamburger button is used by Mozilla Firefox as one if its toolbar icons but your use of it is too obscure since it is by itself (not on a toolbar). Still I did eventually find it after contacting you.

**Comment by addHarry** [comment]
Thanks KT93 for your reply... I now realize that I overlooked the unidentified /// 3 line "hamburger" icon in the upper left corner of the Release Notes page that your Options button took me to. Bear in mind though, that normally, a selection button such as yours called "Options" button is for accessing the options page immediately--as you know, your options button links to your Release Notes page with the unidentified somewhat obscure, simple 3 line /// hamburger button in the upper left corner of your otherwise all-text Release Note page--yes, the "hamburger button is used by Mozilla Firefox as one if its toolbar icons but your use of it is too obscure since it is by itself (not on a toolbar). Still I did eventually find it after contacting you.

**Comment by addHarry** [comment]
Thanks KT93 for your reply... I now realize that I overlooked the unidentified /// 3 line icon/button in the upper left corner of the Release Notes page that your Options button took me to. Bear in mind though, that normally, a selection button such as yours called "Options" button is for accessing the options page immediately--as you know, your options button links to your Release Notes page with the unidentified somewhat obscure, simple 3 line button in the upper left corner of your otherwise all-text Release Note page--yes, the /// 3 line button button is used by Mozilla Firefox as one if its toolbar icons but your use of it is too obscure since it is by itself indentified in a corner (not on a toolbar). Still I did eventually find it after contacting you.

**Comment by addHarry** [comment]
Thanks KT93 for your reply... I now realize that I overlooked the unidentified /// 3 line icon/button in the upper left corner of the Release Notes page that your Options button took me to ...BUT bear in mind that, normally, a selection button such as yours labeled "Options" and placed in an outlined button-box, is for accessing the "Options page" immediately. Yet your clearly labeled & outlined "Options" button actually takes your user to the Release Notes page where you've placed in a corner a non-labeled non-outlined somewhat obscure/abstract 3 line /// button somehow meant to indicate that the Options page is linked to it? Please reconsider that design.

**Comment by kennethtran93** [comment]
The 'Options' button text cannot be changed as it is set by the browser itself. 

I agree that the menu design needs some update.  I'll think about that for a bit, but if you want you can also propose a design change as well.

**Comment by ke-d** [comment]
You could change it in the manifest to something like `settings/settings.html#tabSettings`, which would switch to that tab in the options menu. The button in the popup uses that link but not in the options button in the browser UI.

**Comment by addHarry** [comment]
KT93...sincere thanks for your email...here's the "Options" button I initially commented on and that you asked via email as to "where" it is that I was accessing/using it (see attached jpg file-link below)...specifically, this button is located on the current (version 67) Firefox Browser addons page ...I should maybe kick myself for always using the Firefox addons page to access my extensions and their options (settings), but the addons page has all my browser's extensions in one place and so it's easiest just to set them up right there when I first install them (Note: I generally download addons as XPI files and then manually install them within the addon page--using its "manual installation" link--this method enables me to keep a back-up copy of the addon). BTW, I have now (today) used your toolbar button to access your addon's options/settings menu. It's quite  a nice menu set-up ...sorry I didn't use it in the first place ...Thanks much for your extension ...it's definitely a very good one!

![Options button](https://user-images.githubusercontent.com/52419038/60748956-d02c1880-9f58-11e9-9dbf-1a4bfbf2426e.JPG)
