### ISSUE TITLE
Option to clean cache

### ISSUE THREAD

**Issue by 5im-0n** [mrdokenny/Cookie-AutoDelete#551]
I just read this http://lucb1e.com/rp/cookielesscookies/ and thought it would be nice if Cookie AutoDelete would delete the cache for the site as well as cookies and localstorage, so this tracking method would stop to work.

**Comment by kennethtran93** [comment]
While looking up the relevant API that would do this, this page (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browsingData/removeCache) does not filter per site, so at this time it will not be implemented.  As per (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browsingData/RemovalOptions) Only cookies and local storage items are able to be removed by hostnames.

**Comment by kennethtran93** [comment]
That article is also from 2013 (at the very least the github source that was linked was from then), when Firefox Addon still existed/worked.  Firefox overhauled the WebExtension / Addon so some of the things that used to work in a Firefox Addon will not work at this time after porting it to a WebExtension

**Comment by samuel8941** [comment]
Since to my knowledge there isn't a single chrome extension that automatically clears cache, I think it would be awesome if you add an option to just clear everything automatically every x minutes.

**Comment by kennethtran93** [comment]
Once it contains something to filter by hostname then we would consider that in the future.

**Comment by sdht0** [comment]
This feature will also be available soon: https://bugzilla.mozilla.org/show_bug.cgi?id=1636784

**Comment by kennethtran93** [comment]
Awesome.  This will be implemented same time as indexedDB, but not until I can fix some outstanding bugs/regression.

**Comment by kennethtran93** [comment]
Need some testers over at #798.  To download the zip file, follow the latest instructions given through github-actions bot
