### ISSUE TITLE
[bug] grey/white list button not working for ipv6 sub domains

### ISSUE THREAD

**Issue by ghost** [mrdokenny/Cookie-AutoDelete#555]
### Describe the Bug/Feature

whilst pressing + grey|white from the pop out menu works as expected for ipv6 addresses it does not however for subdomains, e.g. *.[ipv6]. The pop out menu just stays put without extending/revealing the additional settings.

### Steps for anyone to reproduce the

 bug

- navigate to an ipv6 address
- open CAD pop out
- press + grey/white on the top row -> works as expected
- press + grey/white on the bottom row -> extended options do not show

### Your settings 

- OS/version: W10 Pro x_64 v1903 b18362.239
- Browser/version: FF N 70.0a1 (2019-07-19) (64-bit)
- Cookie AutoDelete version: 3.0.2

**Comment by kennethtran93** [comment]
I assume this wasn't an issue in the first place?  IPv4 doesn't have subdomains, so I am not sure if IPv6 would have subdomains available.  In the first place if IPv6 doesn't have subdomains then the second/bottom row shouldn't really show up at all...
