### ISSUE TITLE
Container cookies are deleted when restarting browser

### ISSUE THREAD

**Issue by Standeman73** [mrdokenny/Cookie-AutoDelete#557]
Hi there,

I'm a beginner in keeping my firefox more private and installed CAD. Now I do want my Youtube accounts and FB to stay logged in. To resolve this I use special containers for these sites and whitelisted them in their containers. The problem is CAD also deletes these cookies when resstarting even though they're containered.

Steps for anyone to reproduce the bug:
Firefox settings:
- A bunch of config adjustments (let me know if necessary)
	- network.cookie.lifetimePolicy = 0 (standard)
	- network.cookie.cookieBehavior = 4 (standard)

CAD settings: 
- Everything checked except notification and local storage cleanup. Container support is checked.

SS:
![SS expression list](https://user-images.githubusercontent.com/53143379/61591853-c7c81480-abcb-11e9-8d0d-0a50dcd36924.png)

Versions:
OS/version: Win 10 Home, ver 1803, build 17134.829
Browser/version: FF Version 68.0.1 (64-bits)
Cookie AutoDelete version: CAD version: 3.0.2

Thanks in advance. Please let me know if further info is required!

**Comment by kennethtran93** [comment]
In accordance with your screenshot, the cookies were deleted from the main default container, not the youtube one.  Were you still logged in to Youtube through the Youtube Container?

**Comment by Standeman73** [comment]
Oh sorry for the wrong ss. Issue remains that when logged in in container and closing FF on next login all cookies are gone even within container

**Comment by ghost** [comment]
Same issue as above. I log into (say) Youtube, then later on I close the browser. When I reopen it, the cookie(s) are gone and I have to log in again despite Youtube being whitelisted. The log shows "No Cleanup Logs Found".

- OS/version: Windows 10 Enterprise LTSC 1809
- Browser/version: Firefox 68.0.1
- Cookie AutoDelete version: 3.0.2

**Comment by kennethtran93** [comment]
@ntov are you using private browsing?  How are you whitelisting youtube?

**Comment by LinuxOnTheDesktop** [comment]
If I may chime in: it seems to be that cookies for containerised sites are being deleted while the browser and indeed the relevant page is open. For, I log into Reddit, in a Reddit tab, and the AddOn is set to greylist - actually, I changed it to whitelist - Reddit; but soon I get logged out. This happens on Windows 10 with CAD 3.0.2. I have a Linux computer and I am unsure whether it happens there - I could check. EDIT: And I'm not using private browsing for Reddit.

**Comment by ghost** [comment]
> 
> 
> @ntov are you using private browsing? How are you whitelisting youtube?

Sorry, I just noticed this message. I am not using private browsing mode. I am whitelisting through the CAD popup. Here is a screenshot of the CAD settings: https://imgur.com/FMqUcBD

**Comment by kennethtran93** [comment]
@Standeman73 Query:  Youtube may be using Google for logging in, thus you will probably need to whitelist some of *.google.com's cookies, unsure which at this time though.

@LinuxOnTheDesktop I wonder if, similar to Youtube, Reddit has a third-party login cookie...

Ensure cleanup log is enabled, then try manual `clean` and/or `clean including open tabs` (greylist and whitelist takes precedence) depending on whether you have enabled `Clean open tabs on startup`.  Then check if you are still logged in or not.  If not, you'll need to look into the cleanup log history and see what domains and cookies from each domain was removed.  You can also undo the cookie removal, but only do that after you copied down the domains and cookies that you are looking into.

**Comment by kennethtran93** [comment]
With debug mode available with the latest release 3.3.1, is this still an issue?  If so those logs would really help me out here.

**Comment by kennethtran93** [comment]
Closing due to stale.   If this still persists, please open a new issue with relevant logs and reproducible details.
