### ISSUE TITLE
Bug: compatibility with Facebook Container addon (firefox)

### ISSUE THREAD

**Issue by blueport8** [mrdokenny/Cookie-AutoDelete#560]
Hi,

I've noticed a bug in Cookie-AutoDelete. When used in parallel with Facebook Container (https://addons.mozilla.org/pl/firefox/addon/facebook-container) it stops to automatically delete cookies for facebook page. I've tested it on clean profile with only this two extensions installed. 

Steps to reproduce:
- Create new profile (or use current)
- Install Cookie-AutoDelete,
- Install Facebook Container,
- Go to Cookie-AutoDelete settings and enable automatic cookie and localstorage cleaning when tab is closed,
- Open facebook page and login,
- Close the tab
- If auto-delete delay > 0s - wait
- Go to browser settings and check saved cookies

Result:
- Facebook cookies are not deleted,
- Account still logged in

Expected behaviour:
- Cookies deleted

Environment:
- OS/version: Windows 10
- Browser/version: 69.0b10
- Cookie AutoDelete version: 3.0.2

**Comment by kennethtran93** [comment]
Other users have found that using CAD won't work properly when using the separate Facebook Container webextension (#378 and #388).

I'll keep it on my list to check up on this to see what's wrong.

**Comment by kyounger** [comment]
Found a workaround.

I just added `facebook.com` to the Facebook Container whitelist, alongside a generic whitelist. So far my testing seems to indicate that allows CAD to not delete the facebook cookies from the Facebook container.

![image](https://user-images.githubusercontent.com/197920/73876512-bb7c6f80-481c-11ea-9170-7d99566118d0.png)

**Comment by kennethtran93** [comment]
@kyounger I think the original post was saying that the cookies **_aren't_** deleted when using the Facebook container and CAD.

**Comment by kyounger** [comment]
Oh I did read the original report incorrectly. Maybe that seems to indicate that maybe this is working as intended?

**Comment by kennethtran93** [comment]
>   * Go to Cookie-AutoDelete settings and enable automatic cookie and localstorage cleaning when tab is closed,

Did you also check `Enable Support for Firefox's Container Tabs`?

**Comment by kennethtran93** [comment]
Is this still an issue with the latest versions of CAD 3.3.1?

**Comment by kennethtran93** [comment]
Closing as stale as the original author didn't reply at all since creating the issue.
