### ISSUE TITLE
add option to have 'keep localstorage' deselected as default

### ISSUE THREAD

**Issue by bitpixl** [mrdokenny/Cookie-AutoDelete#561]
Hi,

I'm wondering if it's possible to add an option to the settings that will by default deselect the option "keep localstorage" when I'm whitelisting a domain. For 99% of the domains I'm whitelisting I never need localstorage to be enabled.

os: win10
browser: Firefox (latest)
extention version: latest

thanks for reading and keep up the great work!

**Comment by xss** [comment]
I just noticed this, as well, and searched CAD for a setting for this, which eventually lead me here. :)

The pre-selection of "Leep Localstorage" must be a rather recent change (or possibly the ability itself to delete Localstorage in the first place). All my "older" whitelist items did not have "Keep Localstorage" checked, and I certainly didn't uncheck it on purpose before.

**Comment by SvenBent** [comment]
all my whitelistening is cookies only (autologin) as well
This would be beneficial

**Comment by kennethtran93** [comment]
work in progress.
