### ISSUE TITLE
C-A Seems to do Nothing.

### ISSUE THREAD

**Issue by Zapperjohn** [mrdokenny/Cookie-AutoDelete#564]
C-A goes through the motions. Popups appear that say a cookie has been deleted in Firefox. Going to "Options - Manage data" and cookies are gone. But when I close Firefox and then open a new CCleaner window they are ALL back. I have tried this in every order making sure CCleaner doesn't have any past history. I've tried all kinds of combinations of websites that I don't generally visit. There should be no way for Cleaner to be aware of the specific specific cookies that were in Firefox before closing.  I would expect that Cookie-Autodelete would not leave a trail for another program to retrieve the deleted cookies.

**Comment by kennethtran93** [comment]
Do you have the cleanup log and counter enabled - that allows CAD to be able to restore cookies based on the timestamp that it was removed from Firefox's cookie area.  How that is stored is out of my knowledge at this time.

Edit:  CAD was only meant to clear cookies or alter them in a way that original (and other 3rd party) sites would not be able to detect them while using the browser, not to prevent external applications on your computer from detecting them at all.

**Comment by kennethtran93** [comment]
Closing this issue as CAD cannot control how CCleaner and other external programs find cookies.  That is irrelevant to this webextension.  This program only controls how cookies within firefox browser is handled (namely accessing through browser tabs) as this program has the feature to allow 'undoing' its cookie removal via timestamp should that feature be enabled.
