### ISSUE TITLE
how to auto clean the cookies without the login status

### ISSUE THREAD

**Issue by gh279760559** [mrdokenny/Cookie-AutoDelete#565]
### Describe the Bug/Feature
Hi before it works well. Since I update the autodelete version, it seems the auto-delete includes the login status. So just curious how to use this to auto-delete cookies without the login status? It is annoying that every time I need to login in when opening the website such Gmail Linkedin etc. 

### Your settings 

- OS/version: macOS Mojave
- Browser/version: chrome 76.0.3809.132
- Cookie AutoDelete version: 3.0.2

**Comment by kennethtran93** [comment]
What was your previous version?  There hasn't been a release of CAD for ~4 months now.  I am not sure what login status you are talking about at this time.  Could you please elaborate on it?

I'd suggest turning on the cleanup log and counter if you haven't already, manually clean first, then access and login to said site, then clean again.  That timestamped cleanup log should show which cookies were deleted (gmail may utilize more than one domain for keeping it logged in, I'm not sure).  From there you can restore the deleted cookies and may need to manually add the sites to be whitelisted into the Expression Table in settings.

**Comment by bsd-source** [comment]
You need to whitelist specific website cookies.

Select Cookie AutoDelete --> Settings --> List of Expressions

For gmail I use the following Whitelist:

*.google.com

Same for LinkedIn:

*.linkedin.com

I attempted to narrow down the exact google cookie to keep me logged in but it was too time consuming so I ended up using *.google.com.

**Comment by kennethtran93** [comment]
At this point we don't have a way to decipher which cookies are used for login because each site handles it differently.  

I'm going to close this in a few days, unless there is something else to add, as there hasn't been a response from the original author of this request.

**Comment by kennethtran93** [comment]
Closed due to stale issue.
