### ISSUE TITLE
Whitelisted cookies cleaned (more than one in expression)

### ISSUE THREAD

**Issue by kdmcguire** [mrdokenny/Cookie-AutoDelete#567]
### Describe the Bug/Feature

Cookies in container whitelist are erased on clean. Could be because a single expression contains multiple cookies. I was hoping to use a single expression with multiple domains to whitelist some basic ones that I'd like whitelisted in every container.

### Screenshot in which the bug can be seen

Not a screenshot, but relevant export and clean log:

```
"firefox-container-1": [
    {
      "expression": "*.addons.mozilla.org, *.app.getpocket.com, *.bitwarden.com, *.bitwarden.net, *.duckduckgo.com, *.firefox.com, *.getpocket.com, *.mozilla.org, addons.mozilla.org",
      "listType": "WHITE",
      "storeId": "firefox-container-1",
      "cookieNames": [],
      "id": "QgfOagBfA"
    },
... (etc)
```

```
firefox-container-1
bitwarden.com (__cfduid): Clean because bitwarden.com is not in the White/Grey lists
getpocket.com (G_ENABLED_IDPS, a95b4b6, d4a79ec, 159e76e, sess_nonce, sess_guid, ps, ftv1, fsv1, a_widget_t): Clean because getpocket.com is not in the White/Grey lists
addons.mozilla.org (frontend_auth_token, sessionid, taarId): Clean because addons.mozilla.org is not in the White/Grey lists
duckduckgo.com (ae, 1, aq, ap, l, n, ak, ad, ax, ay, ao, am, ah, au, c, p, aj, objectKey): Clean because duckduckgo.com is not in the White/Grey lists
```

### Steps for anyone to reproduce the bug

1. Use the 'List of Expressions' page widget to add a list of multiple domains to the whitelist (e.g. *.duckduckgo.com, *.mozilla.com)
2. Visit those pages
3. Run manual clean
4. See those cookies cleaned, despite being whitelisted

### Your settings 

- OS/version: Windows 10 / 18362.239
- Browser/version: Firefox / 68.0.2
- Cookie AutoDelete version: 3.0.2

**Comment by kdmcguire** [comment]
I'm guessing that entering multiple domains into a single expression isn't possible, but that isn't necessarily clear.

1. The placeholder text in the expression input field shows three examples separated by commas
2. The input field does not reject a comma-separated string of multiple values
3. The saved expression accepts and shows a comma-separated string of multiple values, as if ordinary.

I guess you could:
* Alter the expression input field placeholder text to make it clear that the three examples are of three separate inputs, not one (e.g. add "or" before the last example)
* Make the expression input field reject submissions with commas and spaces

Or:
* Allow multiple comma-separated values in expressions.

**Comment by kennethtran93** [comment]
Hmmm... I had never tried that in the first place.  Thanks for the info.  I'll see what I can do.

**Comment by kennethtran93** [comment]
Update:  Multiple comma-separated expressions should now be parsed separately from the text field as well as from Import Expressions, once the new version gets pushed through.
