### ISSUE TITLE
Yandex Android Browser Erases Settings

### ISSUE THREAD

**Issue by rjm831** [mrdokenny/Cookie-AutoDelete#571]
I'm using Yandex browser on a Motorola Droid with C-AD installed as an extension.  For some reason the extension seems to get reset to default almost every time I exit the browser & come back - my settings & white/greylists completely erased.
I've got the same browser & setup on an Amazon Fire HD-10 & everything works fine, so I'm assuming this is a problem specific to the Droid (or Nougat?).  Has anyone else encountered a problem like this?
Thanks in advance, everyone.

**Comment by kennethtran93** [comment]
As the browser you are using isn't officially supported by us (i.e. not Firefox or Chrome), I cannot resolve your problem (nor do I use those devices/browsers either).

**Comment by kennethtran93** [comment]
closing due to unofficially supported browser (and no response to your issue from others)
