### ISSUE TITLE
facebook cookie not being deleted

### ISSUE THREAD

**Issue by kolmex** [mrdokenny/Cookie-AutoDelete#572]
### Your settings 

- OS/version:  Windows 10
- Browser/version:  firefox  69.0.1(64-bit)
- Cookie AutoDelete version:  CAD version: 3.0.2

Auto clean is enabled and  do not whitelist facebook,
but when I view firefox>opions>privacy & security>cookie and site data>managing data 
keep seeing facebook have cookies stored in my pc.
Am I setting wrong or how to auto clean it

**Comment by chiraag-nataraj** [comment]
Can you show us a screenshot of that page? Do you see this with any other sites?

**Comment by kolmex** [comment]
[https://cdn1.imggmi.com/uploads/2019/9/30/f9f63518bea00287580284d64e724ac4-full.png](url)

Those cookies being kept more than a day that were whitelist sites.

**Comment by kennethtran93** [comment]
What are your firefox cookie settings as well as CAD settings?

**Comment by kennethtran93** [comment]
Could I get an update for this issue please?

**Comment by kennethtran93** [comment]
Closing as stale
- Screenshot link is invalid/no picture shows up.
- no CAD settings shown.
