### ISSUE TITLE
Firefox recommend extensions program

### ISSUE THREAD

**Issue by erotavlasme** [mrdokenny/Cookie-AutoDelete#573]
Hi,
your add on is one of the best in term of privacy for cookies management. Why is it not approved by Mozilla as [recommended extension](https://support.mozilla.org/en-US/kb/recommended-extensions-program)?
Thank you

**Comment by parcelcat** [comment]
The [Recommended Extensions program](https://support.mozilla.org/en-US/kb/recommended-extensions-program#w_may-i-suggest-extensions-to-become-recommended) page says:

> **May I suggest extensions to become Recommended?**
> 
> Yes. If there’s extension you feel should be Recommended, please email amo-featured [at] mozilla [dot] org with a link to its AMO listing page. 

If you email Mozilla, they might consider making Cookie AutoDelete a Recommended extension.

**Comment by kennethtran93** [comment]
It used to be a recommended addon back when it was the transition from the old extensions.  Probably due to the fact that only very few people are available to contribute codes and bug fixes that we're a bit behind.

Closing this as the solution would be to do the steps mentioned above.

**Comment by kennethtran93** [comment]
And for those still following along this, we have just gotten on the recommended web extension program in Firefox.
