### ISSUE TITLE
Can't install on unsigned versions of Chromium

### ISSUE THREAD

**Issue by embamba** [mrdokenny/Cookie-AutoDelete#575]
I can't install Cookie AutoDelete on unsigned Chromium browsers like Iridium and Ungoogled Chromium. I tried installing the /extensions folder from this repo. But I get an error message stating that a necessary file isn't present. I don't think I'm set up to compile the code available here. Is there a downloadable version available that I can use in these situations for Developer Mode on the browser's Manage Extensions page?

- OS/version: OS X 10.14.6
- Browser/version: Ungoogled Chromium 77.0.3865.90

**Comment by kennethtran93** [comment]
While we don't support those browsers, you can try to download the compiled and signed extensions through the releases tab on this repo (https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/releases)

The extension folder isn't a proper working extension on its own.  It only holds a few base files, and everything else gets compiled through bash, grunt and other processes.
