### ISSUE TITLE
Concerns related to Ambiguity of Privacy Policy

### ISSUE THREAD

**Issue by frankclaassens** [mrdokenny/Cookie-AutoDelete#577]
### **NOTE: I have read the FAQ and consulted the documentation without remedy**

Hi,

Firstly, thank you for developing this very useful Firefox addon and for maintaining support.

### **Interpretation**

For the purpose of this discussion:

- **Cookie-AutoDelete:** software source code as held within the following github repository: [Cookie-AutoDelete / Cookie-AutoDelete](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete)

- **installation:** an action performed by a person by means of downloading **Auto-CookieDelete** from the [release page](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/releases) or [Firefox Add-ons page](https://addons.mozilla.org/en-US/firefox/addon/cookie-autodelete/?src=search)

- **modifiable:** anything which, upon an act, changes from on thing to another.

- **personal information:** ANY information, irrespective of it being identifiable or not, that results from the usage by a person of **Cookie-AutoDelete** after **installation**.

- **Privacy policy page:** a github.com wiki page that allows anyone with authority to perform an act on the modifiable content as presented on the landing page of this link: [Privacy Policy](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/Privacy-Policy)

- **Privacy policy** refers to all **modifiable** content, including but **not limited to** text, images and all content contained on a landing webpage should a 3rd party url/link be included in the **modifiable** content on the **Privacy policy page**. Unless otherwise corrected, the **Privacy policy page** contains all content relative to the subject matter of privacy and protection of personal data. Any content or 3rd party policies not included on the **Privacy policy page** that has an interest or seeks access to the **personal information** of a person protected by the **Privacy policy** will be in violation of the **Privacy policy** and subjected to legal action.

### **Issue: Ambiguity in Privacy Policy**

I wish to highlight the ambiguous nature of the Privacy policy on the Privacy policy page. 

The Privacy policy 09 October 2019 19:21 (BST) states the following modifiable content:

> Cookie AutoDelete does not collect or send data out to any "home" server.

The GDPR states the following on privacy policies: (comprises of best-practices in general)

> "provide people with a privacy notice that is: In a concise, transparent, intelligible, and easily accessible form. Written in clear and plain language, particularly for any information addressed specifically to a child."

The use of words in quotes on a privacy policy is discouraged. Do not use them unless you are fully aware of their meaning, and if you are, then it should be removed from the Privacy policy for it to be concise. Should you continue to refer to "home" then you need to clearly define by means of interpretation what "home" means and what is covered by "home".

**Consider the following:**

**"home:"** a place or premise of residence 

You install Cookie-AutoDelete on your computer at "home". The current Privacy policy may be interpreted as not sending data to **any "home"** **server**, but you may be sending data to a dodgy 3rd party. Also, data and personal information are not the same thing. If you don't have the time to look up the legal definition of these words, then consider keeping the privacy policy as concise as possible. The less words you use, the better. But if you opt for this route, make sure it is concise, clear and unambiguous.

### **Suggested Remedy: Keep it short, concise, clear and easy for anyone to understand**

If **Cookie-AutoDelete** does not collect or send data, then the following can be used instead:

> 1. Cookie-AutoDelete does not collect the personal information of the person using Cookie-AutoDelete. All other data and information not considered as personal information are hereby bind.

> 2. Cookie-AutoDelete does not collect the personal information of the individual using Cookie-AutoDelete. All other data and information not considered as personal information are hereby bind.

> 3. Cookie-AutoDelete does not collect data on the device it is installed. All other personal information and information not considered as data are hereby bind.

You get the picture 😄 The first sentence should be clear, and concise. Avoid using and/or in the first statement. If you wish to add additional information to a statement (as I did above) when the use or and/or is _fine_ but should be limited.

**Comment by kennethtran93** [comment]
Hmmm...

Depending on the settings used in CAD, it technically collects information (cookies, possibly localstorage) if you desire to undo that this web extension performed.  However, there is no outside communication from the web extension itself.  That's where the "home" portion comes in as it is localized to the computer it is installed in, and external applications (e.g. CCleaner) may be able to pick up the cookies labelled as browser cookies even though firefox itself doesn't see it.

I can change it to reflect what you suggested if you so desired.

**Comment by kennethtran93** [comment]
Updated Privacy Policy a bit.  Hopefully made it less ambiguous.  May need better wording on some parts.
In the meantime, I will close this issue.  Feel free to comment on this for revisions.

**Comment by frankclaassens** [comment]
>Updated Privacy Policy a bit.  Hopefully made it less ambiguous.  May need better wording on some parts. ...

@kennethtran93 will check it out. Apologies for only getting back to you now. Had a bunch of personal issues that took up months of my time but that’s mostly resolved now. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by frankclaassens** [comment]
Privacy policy looks much better! Thanks for picking this up @kennethtran93 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ghost** [comment]
> Updated Privacy Policy a bit. Hopefully made it less ambiguous. May need better wording on some parts.
> In the meantime, I will close this issue. Feel free to comment on this for revisions.

Hello!
I know this is an old thread, but I'm curious about one thing. The privacy policy on the Firefox add-on site is different from the Chrome store description. Is there a reason for this? On the firefox site and the github it claims nothing is collected/sent, yet the following is on the chrome page. (Attached) Is there a reason for this?
![CAD](https://user-images.githubusercontent.com/71984294/134743055-fc50cd60-2dbd-4e50-b184-34433ccd1947.png)

**Comment by kennethtran93** [comment]
As you can tell, Chrome requires a more visual approach to privacy items.

Even if it is behind the 'enable log and counter' setting, the information is still being collected (just not stored if the above is not enabled).

It is still true that the data that we do collect is not sent anywhere. (The sync function has yet to be implemented so this part is still very true.)

Personally Identifiable Information: Some people could classify their web history /cleanup log history could be personal information. This is more true if the cleanup log and counter is enabled as we store a copy of the cookies, which may contain personally identifiable information, that would be removed by our extension in the event that one needs to undo the cleanup. 

Web history: primarily applies to notifications and cleanup log and counter as it lists the sites that we cleaned up. 

User activity: primarily applies when you change domains in a tab or close a tab, or restart browser. We run checks to see if any cleanup is required, when enabled.

The examples given from Chrome we can not adjust.

Hope this clarifies it for you.

**Comment by ghost** [comment]
Thank you for the clarification!
