### ISSUE TITLE
All cookies are not deleted.

### ISSUE THREAD

**Issue by techhifi** [mrdokenny/Cookie-AutoDelete#590]
### Steps for anyone to reproduce the bug
Open a web page that stores cookies.    Open new blank tab. Close the tab where a website was loaded.  Cookie Auto delete deletes cookies.   Open CCleaner utility.  OPtions --> Cookies. 
There are still cookies that were not deleted..

### Your settings 
All setting enabled.  Autoclean after 3 secs

- OS/version: Win 10 
- Browser/version:  Firefox/70.0.1
- Cookie AutoDelete version:  3.02

**Comment by kennethtran93** [comment]
Please refer to the FAQ on that per what you had written above, with [a link to the FAQ mentioning CCleaner.](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/FAQ:-Common-Questions-and-Issues#why-are-cookies-still-being-shown-through-ccleaner-if-it-was-deleted-through-cookie-autodelete)
