### ISSUE TITLE
Suggestion: Use FF built in whitelist

### ISSUE THREAD

**Issue by SvenBent** [mrdokenny/Cookie-AutoDelete#591]
Before CAD my standard Firefoxx cookies settings was
- Block all third party cookies ( i only know one site where this gives any issues)
- Accept all first party cookies but only keep for sessoopn
- Whitelist specific sites for autologin cookies I want to keep

This whitelist is pretty long now.  Its rather annoying having to do those again in CAD
Is it possible to have it CAD used the built in whitelist instead of its own ?
 if not would it be possible to import the whitelist at least?

- Thank you

**Comment by kennethtran93** [comment]
Sorry, but there isn't any Firefox WebExtension API available to see that whitelist.  I believe that was mentioned before when WebExtension started to become mainstream.

There's also no WebExtension API to import/export the built-in whitelist as far as I remember, unless they created something recently.
