### ISSUE TITLE
UX Dropdown Zoom 

### ISSUE THREAD

**Issue by wiredrunner** [mrdokenny/Cookie-AutoDelete#593]
In the past I could change the zoom level on the drop down by changing the zoom on the options page now it follows the default zoom level with no way to change it other than changing the default zoom level.  Even that wouldn't be so bad if it was easier to slide to the right but the bar is hidden and is difficult to 'grab' with the mouse which is frustrating.

uBlocko's dropdown zoom can be changed by changing the zoom on its option page so its not a browser issue as far as I can tell. uMatrix has an option to change 'text' size which accomplishes the same thing.
![Screenshot 2019-11-29 at 1 56 41 PM](https://user-images.githubusercontent.com/25047709/69886539-6b2ee180-12b0-11ea-869d-edf923837934.png)
![Screenshot 2019-11-29 at 1 56 54 PM](https://user-images.githubusercontent.com/25047709/69886545-6e29d200-12b0-11ea-88ae-2d87aa0f41e0.png)

- OS/version: ChromeOS 78.0.3904.106
- Browser/version: Chrome 78.0.3904.106
- Cookie AutoDelete version: 3.02

**Comment by kennethtran93** [comment]
Hmmm...  I don't have ChromeOS so I cannot test that system out.  On my linux/Windows via Firefox and Chrome, it shows up fine.  Mind you this extension hasn't been updated in some time so it could be the latest updates to browser/system that is causing it.

**Comment by kennethtran93** [comment]
I'm adding in a font size selectable option for popup and setting in the next version 3.4.0

Chrome, however, requires setting minWidth otherwise the layout breaks...
Also the overflow for popup is set to auto already.

**Comment by kennethtran93** [comment]
Try this alpha - https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/releases/tag/v3.3.1-alpha in a fresh/blank profile
