### ISSUE TITLE
New "notify"setting not yet visisble on settings page

### ISSUE THREAD

**Issue by dutspark** [mrdokenny/Cookie-AutoDelete#594]
"Starting with version 3.0.2, the extension notifies websites about which cookies the visitor allows them to install (this can be switched off in extension's settings it needed)."
This setting is not on the settings page yet.

- OS/version: win10 pro
- Browser/version: chrome 78.0.3904.108 (Officiële build) (64-bits)
- Cookie AutoDelete version: 3.0.2

**Comment by ghost** [comment]
This is not "I don't care about cookies" issue tracker.

![image](https://user-images.githubusercontent.com/886325/69964282-5c476980-1512-11ea-87af-ddfde6196099.png)

**Comment by kennethtran93** [comment]
Closing due to invalid issue, per above note about wrong extension issue.
