### ISSUE TITLE
There is an error in FAQ

### ISSUE THREAD

**Issue by LaurentGrenet** [mrdokenny/Cookie-AutoDelete#596]
In FAQ, under question "How do I set all cookies to be deleted on browser restart rather than on tab close?", there is a mistake : 

It is suggested to create a GreyList on domain * and to "**Uncheck** Keep All Cookies (and Keep Localstorage if desired/available)"

Obviously, if the check boxes are **unchecked**, it means that CAD do not keep any cookie (nor local storage).... and it is what we experience with such a rule : cookies are deleted on tab close, and do wait for browser restart...

The correct wording should be : "pay attention to **let** Keep all cookies **checked** (and Keep local storage is desired/available"

**Comment by kennethtran93** [comment]
If the keep cookies checkbox is checked for the greylist, then the cookies are NOT deleted after browser restart.

**Comment by LaurentGrenet** [comment]
Yes, I agree... but the FAQ writes to **un**check, ie **DO NOT check** the cookies checkbox... Here is the mistake.

**Comment by kennethtran93** [comment]
By NOT checking the cookies box, then the cookies WILL be deleted on browser restart instead of tab close.

~~Sorry I just edited my previous post to reflect this.~~
I almost confused myself there.  Late night posts.

**Comment by kennethtran93** [comment]
...Nevermind...Let me look into my logical thinking/codebase. You may be on to something there.

**Comment by kennethtran93** [comment]
My apologies there.  After testing it out, you're right.

Greylist with Keep cookie checked will remove cookies after browser restart
Greylist with no cookies checked will be removed per tab close.

Updated FAQ.  Thank you very much for raising the issue.
