### ISSUE TITLE
Suggestion: Groups for Whitelisting/Greylisting

### ISSUE THREAD

**Issue by motiv8d** [mrdokenny/Cookie-AutoDelete#597]
After also experiencing the same issues in Cookie-AutoDelete#567 "Multiple Expression in one line / reject comma-separated values", I see a way not only to resolve this, but to enhance overall functionality, especially as functionality of granularity of kept cookies increase.

The suggestion is to use groups of settings that one can set once, but then apply the group to a new container rather than manually adding all the individual components.

Eg: Simplistically, keeping cookies for google/gmail/youtube login. Currently it seems that this requires presently:
1. accounts.google.com
2. google.com
3. youtube.com 

Google could change this in future of course.

If these 3 items were able to be incorporated into a group the user can call say: "Google Accounts Auth", then that one group could be added to a new container for a new google account.

Furthermore, if the entries in that group required modification, eg: adding 4. newserver.google.com in the future, then it could change all of the containers where that group rule had been added.

And as functionality increases within CAD, then there could be a way to make this more granular within the group, and then that would seamlessly for the user apply to all the containers it had been added to retrospectively, and of course apply to any new containers the user needs to.

Additionally, there could be a section created whereby users can add their own groups to a public resource for other users to incorporate on their own systems.
This would make it much easier, for example if a user did all the work to make the most succinct and specific group of allowances possible for "Google Accounts Auth", then other users could download that and use it.

Otherwise I take the opportunity to thank you dev Kenneth for a very handy addon I have just started using.

**Comment by kennethtran93** [comment]
I can see the use in this.  However, this would probably come into play with an updated import that allows groupings and/or partial imports / overriding imports.

By the way I'm not the one who created this addon.  Just helping to maintain it as much as time allows.

**Comment by kennethtran93** [comment]
For now multiple expressions has been implemented.  You could create an import file whereas the domain line contains multiple comma-separated values (the id will get regenerated so you may be able to use that as a temporary comment that won't get imported into the extension).

**Comment by kennethtran93** [comment]
Closing as the above note would do the trick.  I'll add into the documentation soon.
