### ISSUE TITLE
UI is too big under chromium

### ISSUE THREAD

**Issue by jstkdng** [mrdokenny/Cookie-AutoDelete#598]
### Describe the Bug/Feature
The UI is way to big compared to other browser content and other extension tooltips. This doesn't happen under firefox.
### Screenshot in which the bug can be seen
![image](https://user-images.githubusercontent.com/52050345/70865635-acb8c100-1f2d-11ea-916e-d71732d5007a.png)

### Steps for anyone to reproduce the bug
1. Open the CAD tooltip

### Your settings 

- OS/version: Arch Linux
- Browser/version: Chromium / 79.0.3945.79
- Cookie AutoDelete version: 3.0.2

**Comment by kennethtran93** [comment]
I'd have to inquire about the UI looks with Kenny as to why it is what it is, but he's currently on hiatus.  

If I had to guess it helps for touchscreens and mobile devices.

**Comment by kennethtran93** [comment]
Try this alpha - https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/releases/tag/v3.3.1-alpha in a fresh/blank profile
