### ISSUE TITLE
Chrome cookie settings with multiple profiles 

### ISSUE THREAD

**Issue by lordgordon** [mrdokenny/Cookie-AutoDelete#6]
Hi,

I'm using Google Chrome Version 57.0.2987.133 (64-bit) with two profiles. I have installed this extension in both profiles, then removed in one. The extension seems working fine, yet on ```chrome://settings``` I have the cookie settings wrong:

* profile 1 with the extension: cookie setting is  "free";
* profile 2 **without** the extension: cookie setting is locked as it is controlled by an extension.

I attach the screenshots of the two ```chrome://settings```.
![image](https://cloud.githubusercontent.com/assets/7745293/25316399/08b178b4-2867-11e7-8ecf-d07c2f8c4744.png)
![image](https://cloud.githubusercontent.com/assets/7745293/25316400/0bf78da6-2867-11e7-90ee-67dafa4770f5.png)

Thank you very much for your support. This extension looks really promising.

Regards,

Nicholas

**Comment by mrdokenny** [comment]
Hey Nicholas,

Thanks for trying my extension. Unfortunately, I cannot reproduce your problem in your second profile. I think it might be another extension?

**Comment by lordgordon** [comment]
True. After some extensive testing I figured out the root cause, and it was another extension.

Sorry for the wrong alarm.

Thanks for your prompt support.

**Comment by mrdokenny** [comment]
No problem.
