### ISSUE TITLE
Expression Import JSON Format

### ISSUE THREAD

**Issue by jsrath** [mrdokenny/Cookie-AutoDelete#602]
### Describe the Bug/Feature

Hi @kennethtran93, the JSON format described [here](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/Documentation#importing-expressions-courtesy-of-electricfeet) for importing expressions:

```json
 {
   "default": [
     {
       "expression": "github.com",
       "listType": "GREY"
     },
     {
       "expression": "example.com",
       "listType": "WHITE"
     }
   ]
 }
```
Failed to import correctly for me - it just failed silently with no sites added. 

However, when adding a site manually, I noticed that the payload of the dispatched `ADD_EXPRESSION` action also included a `storeId` property:

```js
payload: {expression: "github.com", listType: "GREY", storeId: "default"}
```
Adding this `storeId` property to my JSON resulted in a successful import. 

Looking at the `Expression` type, I see that `storeId` is not optional, so not having it in the uploaded JSON could be the source of the issue:

```typescript
type Expression = Readonly<{
  expression: string;
  cleanLocalStorage?: boolean;
  cleanAllCookies?: boolean;
  listType: ListType;
  storeId: string;
  id?: string;
  cookieNames?: string[];
}>;
```

I'm not sure if this is a universal issue, but it might be good to update the JSON format described in the wiki to: 

```json
{
  "default": [
    {
      "expression": "github.com",
      "listType": "GREY",
      "storeId": "default"
    },
    {
      "expression": "example.com",
      "listType": "WHITE",
      "storeId": "default"
    }
  ]
}
```

### Your settings 

- OS/version: Windows 10 Pro (64 bit)
- Browser/version: Chrome V79
- Cookie AutoDelete version: 3.0.2

**Comment by kennethtran93** [comment]
Exported Expressions from Firefox also has the storeId.  Revised FAQ documentation per above.

Thanks @jsrath!

**Comment by Urbs3w** [comment]
> 
> 
> Exported Expressions from Firefox also has the storeId. Revised FAQ documentation per above.
> 
> Thanks @jsrath!

Hello @kennethtran93 ,

Thanks for updating the FAQ. I [suggested](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/396#issuecomment-517380780) this fix back in August in [bug 396](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/396) but it somehow got missed. I think you can close bug 396 too with this change.  I am wondering if you can give credit to me too in the documentation since I also suggested this fix back in August (before this latest report)?

Regards,
Urbs

**Comment by kennethtran93** [comment]
Done and done.
