### ISSUE TITLE
Please add support for WaterFox

### ISSUE THREAD

**Issue by pcunite** [mrdokenny/Cookie-AutoDelete#606]
Please add support for WaterFox.

Thank you.

**Comment by kennethtran93** [comment]
As Waterfox is using the legacy addons, I suggest you to use Self-Destructing Cookies as this webextension was created based on that.

**Comment by kennethtran93** [comment]
Closing as Waterfox has yet to support webextensions fully at this time.  Do correct me if I'm wrong.
