### ISSUE TITLE
Don't set cookies for blocked websites

### ISSUE THREAD

**Issue by ElhemEnohpi** [mrdokenny/Cookie-AutoDelete#607]
### Describe the Bug/Feature
I've just started using Firefox and Cookie AutoDelete, after some time away.

I've blocked several websites such as Google and Facebook from setting cookies and storage, using Firefox's native preferences/permissions settings. But with Cookie AutoDelete installed, cookies get set for these websites anyway, and I receive notifications that cookies have been cleaned when closing the tab, which I did not expect. I spent a lot of time troubleshooting before realizing it was caused by CAD.

I understand now that the cookie is set by CAD for cleanup purposes, and not by the website, and isn't used for tracking etc. However, it makes things confusing - if I block a website, I should not see cookies for it. As far as I understand, a blocked website can't use localstorage, so I suggest that CAD shouldn't set cleanup cookies for blocked websites.

I'm surprised it's even possible for an extension to override the permission settings, and it wasn't obvious to me why I was seeing Google cookies, despite having them blocked. In Firefox's current UI for cookie and storage management (Preferences > Privacy & Security > Cookies and Site Data > Manage Data)  it's no longer possible to see the name and content of the cookies. Users must now figure out how access the Web Developer tools "Storage Inspector" to view them, which I eventually did.

### Screenshot in which the bug can be seen
![screenshot_329](https://user-images.githubusercontent.com/23618559/72470476-3388e400-37e1-11ea-8f68-b5b270800323.png)
![screenshot_330](https://user-images.githubusercontent.com/23618559/72470484-35eb3e00-37e1-11ea-90a5-830d7a131210.png)
I tried every combination to block the damned cookie!
![screenshot_331](https://user-images.githubusercontent.com/23618559/72470497-397ec500-37e1-11ea-97ce-ebe07c48f16b.png)
But it was still there!
![screenshot_332](https://user-images.githubusercontent.com/23618559/72470513-3c79b580-37e1-11ea-9979-f8ddfde499c7.png)
![Screen Shot 2020-01-15 at 9 58 34 PM](https://user-images.githubusercontent.com/23618559/72471419-ea399400-37e2-11ea-8bcc-46b42706f636.png)

### Steps for anyone to reproduce the bug
1. Block cookies for a website using Firefox's permissions or preferences.
2. Install Cookie Auto Delete and enable local storage cleanup.
3. Visit a site for which cookies are blocked.

Expected result: no cookie is set, and I do not receive any notifications from CAD about cleaning them up.
Actual result: a cookie is set, and visible in the Firefox UI, but it is not obvious why. Notifications are received from CAD that cookies for the blocked website have been cleaned on closing the tab.

### Your settings 

- OS/version: macOS 10.14.6
- Browser/version: Firefox 72.0.1
- Cookie AutoDelete version: 3.0.2

**Comment by kennethtran93** [comment]
At this time there is no function within Firefox WebExtension API to access Firefox Preferences so we cannot see any website settings you have set into Firefox.  

This may be a Firefox bug itself so perhaps try creating an issue with them.

The only step I can see is a global privacy setting  https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/privacy/websites which is all or nothing it look like.  That has no relative impact to the current process other than adding in an informative note if firefox is already blocking ALL cookies or whatnot.

**Comment by kennethtran93** [comment]
As a context, CAD only sets a cookie if there's no cookies set, purely for localstorage cleanup as the way it is currently set up is that it requires at least one cookie.
For the time being I believe I made it to now show up on the icon, but there will still be a notification about that cookie being erased.

I still can't see a way to see if a site has been blocked from setting cookies yet.  Also, localstorage and cookies aren't the same thing if I recall correctly.

**Comment by kennethtran93** [comment]
Closing due to browser limitations.  It's not something that can be checked with the limited amount of exposed api.  I'll keep it under a project of browser limitations to see if anything could be done in the future.
