### ISSUE TITLE
"Unexpected error" messages

### ISSUE THREAD

**Issue by ax487** [mrdokenny/Cookie-AutoDelete#609]
### Describe the Bug/Feature

I keep getting  `Error! An unexpected error occured` messages whenever cookies are to be deleted, either by triggering the process manually via "Clean" -> "Clean, include open tabs".

Unfortunately, the console does not seem to show any output. Let me know if I can get you any better backtraces. I realize that I am not giving you a lot of information...

### Screenshot in which the bug can be seen

![error](https://user-images.githubusercontent.com/22445828/72663233-9e5c3a00-39f0-11ea-9af5-d79b8bb72b05.png)

### Steps for anyone to reproduce the bug

Clean cookies (manually or automatically).

### Your settings 

![settings](https://user-images.githubusercontent.com/22445828/72663279-0448c180-39f1-11ea-89d6-725b5716208e.png)

- OS/version: Arch Linux, 64 bit
- Browser/version: Firefox 72.0.1
- Cookie AutoDelete version: 3.0.2

**Comment by kennethtran93** [comment]
if you go to `about:debugging` > This Firefox > CAD > Inspect, then click on the console tab.   Open the CAD popup again and try clicking the button.  Hopefully errors/warning will populate the console lines.  Please include them if there are.  Note that other webextension console logs may appear there.

**Comment by ax487** [comment]
Ok, thanks for the help. I get the following backtrace:

    Error: "An unexpected error occurred" 
    (1) […]
    ​
    0: Object { cached: false, cleanCookie: true, openTabStatus: "reasonTabsWereNotIgnored", … }
    ​
    length: 1
    ​
    <prototype>: Array []
    common-background-popup-setting.bundle.js:30:22213
        cleanCookiesOperation moz-extension://a7851d55-24bb-4f2a-8615-1fd285c4b5ef/bundles/common-background-popup-setting.bundle.js:30
        c moz-extension://a7851d55-24bb-4f2a-8615-1fd285c4b5ef/bundles/common-background-popup-setting.bundle.js:30

The object is (slightly redacted)

    [
      {
        "cached": false,
        "cleanCookie": true,
        "cookie": {
          "name": "__cfduid",
          "value": "***",
          "domain": ".js.org",
          "hostOnly": false,
          "path": "/",
          "secure": false,
          "httpOnly": true,
          "sameSite": "no_restriction",
          "session": false,
          "firstPartyDomain": "",
          "expirationDate": 1543008790,
          "storeId": "firefox-default",
          "hostname": "js.org",
          "mainDomain": "js.org",
          "preparedCookieDomain": "http://js.org/"
        },
        "openTabStatus": "reasonTabsWereNotIgnored",
        "reason": "reasonCleanNoList"
      }
    ]

If you have some debug version available, I could maybe get a better (less webpacked) backtrace...

**Comment by kennethtran93** [comment]
I wish I had something better of a debug version.  I've only recently been given collaboration status so it will take some time.

I kinda wish that [1] line had what I needed.

What's your Firefox preferences like (i.e. cookie and maybe privacy-related) as well as any active webextensions?

**Comment by kennethtran93** [comment]
Is this still an issue @ax487?

The only thing I can think of at this time is a cookie or a domain with some invalid characters or malformed cookie names/domain names before CAD was installed and used.  Maybe you'll need to manually clear those domains using Firefox's internal cookie manager.

**Comment by ax487** [comment]
Well, I just reenabled the extension and it-seems fine. Maybe we can close this for now.

**Comment by kennethtran93** [comment]
Closing for now.
