### ISSUE TITLE
Exclude CAD's own cookie from badge icon count

### ISSUE THREAD

**Issue by relikd** [mrdokenny/Cookie-AutoDelete#611]
### Describe the Bug/Feature

Hi there, I was just confused that CAD showed me a badge count of 1 on my own site where I know that I don't use any cookies. Turns out, the count shows the CAD auto-delete cookie that is automatically created for each site. 
Can this single cookie be excluded from the icon badge count? It gives a false impression that there are cookies where actually there aren't any.

### Your settings 

- Cookie AutoDelete version: 3.0.2

**EDIT:** The site uses LocalStorage and I have the "Localstorage Cleanup" setting enabled

**Comment by kennethtran93** [comment]
Great Idea.  I'll keep it in mind for future releases.

**Comment by kennethtran93** [comment]
This was a quickfix.  Hopefully when the new version comes out you won't see CAD cookie anymore.  Let me know once 3.0.4 comes out if you still see it.

**Comment by relikd** [comment]
The 1 count does no longer show up 👍
For another future version you could also hide the message log `1 Deleted Cookies from: XXX`
(of course only if the single cookie is indeed the CAD cookie)
