### ISSUE TITLE
Compatible with Edge Chrome

### ISSUE THREAD

**Issue by Bamajon1974** [mrdokenny/Cookie-AutoDelete#612]
Are there any compatibility issues or other issues with Cookie Auto-Delete and Edge Chromium? 

Thanks in Advance! 

### Your settings 

- OS/version: 
- Browser/version: 
- Cookie AutoDelete version:

**Comment by kennethtran93** [comment]
I have yet to even look at Edge Chrome yet.  If there are any compatibility issues at this time we don't offer official support for that browser at this time.

**Comment by Bamajon1974** [comment]
Does that mean you are going to evaluate compatibility with Chrome in the
near future?

**Comment by kennethtran93** [comment]
Google Chrome is supported.  As Edge Chrome is based on Chromium, some features may work off the bat but if there's any discrepancies between browsers then there's currently no support for fixing them at this time.

Probably not in the near future, but it could be looked upon.

**Comment by Bamajon1974** [comment]
Got it. From what I understand, Edge Chrome largely resembles Google Chrome
but there are differences in security and privacy features, among other
things (such as Internet Explorer support). For security/ad
blocking/privacy related apps, like this cookie autodelte or ublock origin,
etc. there may be some compatibility issues, which is why I asked. I will
ask on Reddit forums.

Thank you for your help.
