### ISSUE TITLE
Brave - Does not delete cookies automatically when installed with multiple profiles on domain change or tab close.  

### ISSUE THREAD

**Issue by jonathanflack** [mrdokenny/Cookie-AutoDelete#618]
Brave Version 1.2.43 Chromium: 79.0.3945.130 (Official Build) 
(64-bit) MacOS Catalina 10.15.3.  

Create multiple profiles in Brave, install plugin for both profiles, configure and test autodelete with 0 sec delay.

**Comment by kennethtran93** [comment]
Please use the post itself to describe the info and shorten the title.

**Comment by kennethtran93** [comment]
Just letting you know that you're using a chromium variant to which we don't offer official support to at this time.  Only official Google Chrome and Mozilla Firefox are officially supported.

**Comment by jonathanflack** [comment]
It's understood that Brave is not currently supported, but you might just consider your reply posture here.  Bug reports are precious in my work (cybersecurity), and I never reply in a way that might alienate those sending them.

**Comment by kennethtran93** [comment]
My apologies there - it's been a long day at work for me.  My only other comment would be to try searching elsewhere like stackexchange, reddit, stackoverflow, and other communities to see if there is a workaround or proposed solution.

Although CAD may work with Chromium variants as Google Chrome is Chromium with additional closed-source enhancements, the variants may have modified how the webextension APIs work, and thus we cannot offer support in that sense.

I have mentioned that if people are using variants of Mozilla Firefox or Google Chrome at this time that support is not guaranteed/available.  Bugs from those browsers will probably not be resolved as easily unless it is also found in the main counterparts.
