### ISSUE TITLE
Ability to copy text in popup

### ISSUE THREAD

**Issue by SpaceClicker** [mrdokenny/Cookie-AutoDelete#622]
I had a problem when trying to add support for my credit unions (CU) website.  When you log in, it checks cookies to make sure your device is authorized, if not, it sends a text message or makes a phone call to give you a security code that you must enter, which validates the device for future logins.  However, the cookies that are stored are for a third party domain, not the domain of my CU.  So, if I log out and close the tab for the credit union website, the third party cookies are deleted (even though I whitelisted the CU domain itself) and if I then go to the CU domain and log in again, it again asks for the security code.

I was able to add the third party domain (*.digitalinsight.com) to the whitelist, and all is good, however, to do so I needed to look at the CAD log to see what cookies were deleted after I closed the tab with the CU domain, and then manually go to the "List of expressions" tab in the CAD settings, and type in the domain manually.

There is no way to copy the domain from the CAD log since the text is not copyable, so it makes it a bit tedious to have to type it all in manually, making sure you do it correctly (this is particularly painful for long and/or hard to type domains which may just be seemingly "random" text since they are generally not visible domains and may only be used behind the scenes).

I would like to see a change to CAD so that either the text in the log is copyable (this is the minimal fix), or better yet, you can click on the domain and it will give you the option to add it to the whitelist/greylist similar to how you can add a domain that is in the URL bar.

EDIT:  I just realized that the text is copyable in the Settnigs->Cleanup log, just not in the drop down menu log.  So it's possible to copy and paste it from there, but I would still like the ability to just click on the domain in the drop down menu to add it more easily.

**Comment by kennethtran93** [comment]
I haven't had too much of a chance to research into detail how the popup works at this time.  I'll see what I can do but it may take some time.

**Comment by kennethtran93** [comment]
I'll leave it as copying text in popup for now as I think there was an existing issue/request that had adding domains to list via cleanup entries.

**Comment by kennethtran93** [comment]
If you would like to give it a try, head on over to PR #713 and download the latest build (in comments) and let me know if there's any tweaks that need to be looked into.

I'd manually link the PR that closes this issue but it seems it is full. At least the commit mentions this.
