### ISSUE TITLE
Greylisting as default?

### ISSUE THREAD

**Issue by Retriev3r** [mrdokenny/Cookie-AutoDelete#629]
Hello there,
currently the cookies get auto deleted after the tab or window gets closed - which means every few seconds.
I would like to make greylisting as default so that all (not whitelisted) cookies get auto deleted with browser exit/start.

Is that possible?
Could you implement this as an option?

Thank you,
Ben

**Comment by kennethtran93** [comment]
There should have been an FAQ for this type of setup already. 
Go into settings -> List of Expressions, then put `*` as greylist.

**Comment by kennethtran93** [comment]
https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/FAQ:-Common-Questions-and-Issues#how-do-i-set-all-cookies-to-be-deleted-on-browser-restart-rather-than-on-tab-close

Please read the FAQ next time.

**Comment by Retriev3r** [comment]
> https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/FAQ:-Common-Questions-and-Issues#how-do-i-set-all-cookies-to-be-deleted-on-browser-restart-rather-than-on-tab-close
> 
> Please read the FAQ next time.

Oh 😮
You are right! My apologies. I did read, but I somehow overlook this.
THANK YOU @kennethtran93

**Comment by kennethtran93** [comment]
You're welcome.
