### ISSUE TITLE
[BUG] Cookies won't be deleted when all tabs closed

### ISSUE THREAD

**Issue by timehaschanged** [mrdokenny/Cookie-AutoDelete#630]
**Bug description**

Cookies won't be deleted if all tabs are closed (not quit) together (Command + W).
I assume that because no auto-notification pops up.

**System Info:**

 - OS: macOS Catalina 10.15.3 (19D76)
 - Browser Info: Firefox 73.0.1 (64-bit)
 - CookieAutoDelete Version: 3.0.4

**Comment by kennethtran93** [comment]
What's your firefox settings in relation to closing the last tab action?

**Comment by kennethtran93** [comment]
This isn't a bug on Firefox Dev 77.0b2 on Linux, when I have `browser.tabs.closeWindowWithLastTab` set to **false** in `about:config`.  When the last tab closes a new blank tab opens for me.  Then after the delay the notification appears.

Closing as stale.
