### ISSUE TITLE
[SUPPORT] Localstorage auto cleaning

### ISSUE THREAD

**Issue by ghost** [mrdokenny/Cookie-AutoDelete#632]
ETA for automatic localstorage cleaning support in Chrome extension like on Firefox 58+?

**Comment by kennethtran93** [comment]
There's an active issue for this.  #523 
Please don't open a new issue, but instead comment on that one.

There is no ETA for it right now as I haven't started comparing functions between Chrome and Firefox.  I suppose this should be my next task after I get Crowdin translations integrated as well as some other status checks with GitHub Actions.

**Comment by kennethtran93** [comment]
3.2.0 has been compiled and ready for use in GitHub Releases.  Official release platforms are all under review at this time and will auto update when approved.

This is the one with Chrome localstorage.
