### ISSUE TITLE
Firefox "settings for clearing history" compatibility

### ISSUE THREAD

**Issue by 07416** [mrdokenny/Cookie-AutoDelete#64]
The setting is found in options > "privacy" (`about:preferences#privacy`) > "Clear history when Firefox closes".

![capture63](https://user-images.githubusercontent.com/14923168/27507668-57ed4f48-58dc-11e7-8df8-9b27b5b7b580.PNG)

Is there a setting I can't check to use Cookie-AutoDelete's full functionality? "Cookies" most likely can't be selected, unless addons can preserve cookies.

I have some issues with disappearing cookies and I decided to ask for advice before filing a (potentially faulty) bug report. [Self-Destructing Cookies](https://addons.mozilla.org/en-US/firefox/addon/self-destructing-cookies/)' whitelist is cleared if "Site Preferences" is selected.

**Comment by mrdokenny** [comment]
> Is there a setting I can't check to use Cookie-AutoDelete's full functionality? "Cookies" most likely can't be selected, unless addons can preserve cookies.

Those settings should be fine, just don't select Cookies.

> I have some issues with disappearing cookies and I decided to ask for advice before filing a (potentially faulty) bug report. 

Sounds like SDC might have corrupted your profile somehow. Try a Firefox refresh.

**Comment by 07416** [comment]
> Sounds like SDC might have corrupted your profile somehow. 

I don't think there's a reason to believe that Self-Destructing Cookies may have caused issues. I only mentioned how the best-known Firefox cookie manager stores data.

**Comment by mrdokenny** [comment]
Well someone has some problems with their profile with SDC leftovers so I thought maybe you had some problems. 😉 See #54 

> Self-Destructing Cookies' whitelist is cleared if "Site Preferences" is selected.

Also, this doesn't affect me because I store data separate from "Site Preferences"
