### ISSUE TITLE
[BUG] Automatic cleaning does not work on YouTube.com and Google.com

### ISSUE THREAD

**Issue by TheFuzzStone** [mrdokenny/Cookie-AutoDelete#640]
**Describe the bug**

Automatic cleaning does not work on (they are **not** in my White/Grey lists):

* https://www.google.com/
* https://www.youtube.com/

---

**To Reproduce**

1. First, turn on Automatic cleaning in the settings of the extension:

![](https://i.imgur.com/4rUUp8O.png)

---

2. Go to https://www.youtube.com/
3. Close the tab with https://www.youtube.com/
4. Click on the extension and you won't see that the cookies from YouTube was removed:

---

![](https://i.imgur.com/GgbyGAg.png)

---

5. To ensure that YouTube/Google cookies are present, go to Firefox's cookie settings:

---

![](https://i.imgur.com/DpNr1pL.png)

![](https://i.imgur.com/LGbOcb8.png)

**Expected behavior**

I expect the complete removal of cookies, as it works with other sites.

**Your System Info (please complete the following information):**

System: Manjaro Linux
Kernel: 5.4.23-1-MANJARO
DE: KDE Plasma 5.17.5
Browser Info: Firefox 73.0.1 (64-bit)
CookieAutoDelete Version: 3.0.4
Other Plugins: [uBlock Origin](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/); [Privacy Badger](https://addons.mozilla.org/en-US/firefox/addon/privacy-badger17/), [HTTPS Everywhere](https://addons.mozilla.org/en-US/firefox/addon/https-everywhere/), [Decentral Eyes](https://addons.mozilla.org/en-US/firefox/addon/decentraleyes/), [ClearURLs Add-on](https://addons.mozilla.org/en-US/firefox/addon/clearurls/), [Dark Reader](https://addons.mozilla.org/en-US/firefox/addon/darkreader/)

**Comment by kennethtran93** [comment]
If you know how to get into your Storage Inspector via Development Tools(F12), could you post a screenshot of the cookies shown there?

**Comment by TheFuzzStone** [comment]
@kennethtran93 

![](https://i.imgur.com/JxP1Mpu.png)

---

![](https://i.imgur.com/si94mQS.png)

**Comment by kennethtran93** [comment]
Is this before or after CAD was run?  If you can manually run the clean, include open tabs is there any difference?  This function respects the white/grey list so it's essentially the same as closing the tab and waiting for the auto cleanup.

I'm also assuming that the most recent cleanup log you should expanded before taking the screenshot doesn't have either google or youtube listed on it?

**Comment by kennethtran93** [comment]
While still waiting for a response to the above questions, I just want to make sure that you have no other tabs or windows open that are using Youtube or Google as you didn't have that option enabled in settings.

**Comment by kennethtran93** [comment]
Closing due to staleness.

**Comment by TheFuzzStone** [comment]
I'm sorry for the late response.

---

> I just want to make sure that you have no other tabs or windows open that are using Youtube or Google as you didn't have that option enabled in settings.

I also apologize for creating this issue 😬.
It's not a bug. It was just that another tab YouTube.com was opened (and pinned), that's why the automatic cleaning didn't work.

---

Thank you to all contributors for such a cool extension!
