### ISSUE TITLE
[SUPPORT] Keep certain cookies

### ISSUE THREAD

**Issue by thegeek1977** [mrdokenny/Cookie-AutoDelete#645]
Hi.

I have a feature request.

It would be cool to be able to keep certain cookies from a domain while the others are deleted the normal way
.
For example: for youtube.com: it would be cool to be able to keep the PREFS-cookie and discard the rest and that should be define by the user.

That way one can keep the cookies with the preferences for a site while not giving his/her private life away to google.

Is this possible to do?

Thank you in advance

**Comment by kennethtran93** [comment]
you can whitelist the domain, then uncheck the 'keep all cookies' checkbox, which will then show the cookies currently for that domain.  Then check which one you want to keep.

**Comment by kennethtran93** [comment]
![CAD Popup - YouTube - Mozilla Firefox](https://user-images.githubusercontent.com/6724477/76176859-7b880f80-616f-11ea-937e-6ec979fba26e.png)

This is probably what you want then.

**Comment by kennethtran93** [comment]
Then upon cleaning, your whitelist may look something like this:
![Issues · Cookie-AutoDeleteCookie-AutoDelete - Mozilla Firefox](https://user-images.githubusercontent.com/6724477/76176950-d15cb780-616f-11ea-8665-579cefe81e7e.png)

**Comment by kennethtran93** [comment]
If you're looking for a way to manually define the cookies kept, that may not be feasible as it's up to each site how they name and use their cookies.

Let me know if this helped you.  If this support issue's been quiet for about a week then I'll close it.

**Comment by thegeek1977** [comment]
Sorry for not getting back to you. I tried to reply by email but appearently that did not work out well.
Here is what I was trying to wrote.

"Thank you very much. That was exactly what I was looking for. Works like a charm now. Sorry to waste your time with this.
I did not know that I was able to do this out of the box. You can go on and close this whenever you like as this solved it for me."

I will close this ticket by myself. Again, thank you for your support.
