### ISSUE TITLE
[FEATURE REQUEST] Using C-AD as anti-distraction extension

### ISSUE THREAD

**Issue by maltsev** [mrdokenny/Cookie-AutoDelete#646]
I guess, the primary use-case of this extension is to prevent being tracked. But it also seems that this extension would work pretty well for a totally different issue: preventing from visiting Facebook, Twitter, Reddit, and other distraction websites too often. Since all these websites require you to be signed in to get any meaningful experience letting C-AD automatically sign you out after you close the tab would, in my opinion, significantly reduce impulse visits of this websites since each time you'll have to enter your credentials (so it isn't a quick dopamine hit anymore).

The only thing that prevents me from using C-AD for that purpose is that I don't want to be signed out of all other websites that I visit from time to time. Sure, I can add them to the white list but it'd require adding each of these websites separately, and I have probably a hundred of them.

A possible solution would be to implement some sort of black-list, so C-AD deletes only cookies from that list and keeps other cookies present (discussed in #134 and #549). 

Another solution is to add regexp support so it'd be possible to white list all websites except Facebook, Twitter, etc (discussed in #169). 

I'm a developer myself so I can implement that. But first I'd like to have a discussion if you see this use-case fit for C-AD at all and if you eventually ready to accept my PR.

**Comment by kennethtran93** [comment]
A blacklist on top of the existing whitelist/greylist is fine.  It would be implemented as always delete then.   Another option on the settings will need to be added such that one can set a delay on the blacklist itself.  This may be related to #631 .

Regex support could be possible too.  I was going to implement the ability to use comma-separate site value sometime soon.

With an additional button in the popup, we will need to make it a dropdown selection, maybe even need to adjust the list of expressions page too.

**Comment by maltsev** [comment]
Thanks for the clarification! I'll check this weekend which one is better to implement.

**Comment by kennethtran93** [comment]
Is this a closable feature request or will additional items be implemented?

**Comment by maltsev** [comment]
The solution implemented in #649 works well for me, but maybe it will be too complex for other people to use. On the other hand, I don't plan to work on this issue anymore, so I guess, we could close it for now. 

I'll send you updated docs about this feature this evening.

**Comment by kennethtran93** [comment]
Thanks!  Version 3.1.0 is uploaded for review to both extension stores, but if you want to try you can download it from GitHub Releases.

**Comment by maltsev** [comment]
> I'll send you updated docs about this feature this evening.

It seems you already took care of that :-)
