### ISSUE TITLE
Setting "delay before cleaning" to 0 in active mode 

### ISSUE THREAD

**Issue by 07416** [mrdokenny/Cookie-AutoDelete#65]
Is `0` is a valid setting for "delay before cleaning" (options > "cookie settings")? If it is, values below `1` have to be set manually by typing, UI can't be used.

**Comment by mrdokenny** [comment]
I put this in the extension page:

> - The delay is in minutes because timers in Chrome are allowed to fire once per minute. This limitation doesn't exist with Firefox, so theoretically you could set a lower delay value by typing in .1 (which is 6 seconds) or even 0 for instant cleanup after tab close. You use the dot (0.1) or comma (0,1) depending on which locale you have uses. Remember to save afterward! Be warned that a lower value will cause merchant sites that use PayPal to break. One workaround is to have another tab of that merchant site before the site redirects you to PayPal. 

So `0` is valid in Firefox.

> If it is, values below 1 have to be set manually by typing, UI can't be used. 

Trying to make it somewhat consistent across browsers.

**Comment by 07416** [comment]
I apologize for not properly reading the addon description.

**Comment by grenzor** [comment]
@mrdokenny 

I noticed using the latest beta on Nightly, any delay under 0.10 can't be typed in manually (it auto changes to 0). Only way I could set it below that is to copy-paste the delay.

**Comment by ke-d** [comment]
@grenzor https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number#Controlling_step_size

Maybe just needs some tweaks to the HTML 5 input tag.
