### ISSUE TITLE
[BUG]  Automatic cleaning stopped working since 3.1.0 (Chrome only)

### ISSUE THREAD

**Issue by antoinelibert** [mrdokenny/Cookie-AutoDelete#658]
**Describe the bug**

Since updating to 3.1.0, cleaning is no more triggered automatically. This is happening on my Chrome but not Firefox. Manual cleaning (click on the button) still works.

**To Reproduce**

1. Enable automatic cleaning
2. Set interval to 60 secs (example)
3. Open website (not white listed)
4. Close website tab.
5. Wait 60 secs
6. Cleaning is not triggered. (No new line appears in the list inside the extension popup)

**Expected behavior**

Cookies of [insert_website] are removed and listed in the extension popup.

**Your System Info (please complete the following information):**

 - OS: Windows 10 Pro 1909
 - Browser Info: Chrome 80.0.3987.149
 - CookieAutoDelete Version 3.1.0

**Comment by bluzeman7** [comment]
Same exact issue on chromebook, latest OS, with the updated CAD 3.1.0  
Was working perfectly through late last night under previous version.

**Comment by kennethtran93** [comment]
Whoops.  I'll need to dig deeper into webextension-polyfill to see what happened between v0.1.1. and v0.6.0.

**Comment by drb-germany** [comment]
I can confirm the behavior, I have removed and reinstalled the extension (Chrome), cookies are not deleted after closing tabs even though they are supposed to be removed after 5 seconds. Last cleaning actions in log file are listed from yesterday, 2020/03/17

**Comment by NooNameR** [comment]
confirmed. it is just cleaning a cookies when browser has been restarted.

**Comment by kennethtran93** [comment]
Just want to make sure here so I can narrow it down:  Automatic cleaning is not working after domain change or tab close, but is working on browser restart?

**Comment by NooNameR** [comment]
yeap, correct. browser restart helps (I have disabled default browser cleanup)

**Comment by antoinelibert** [comment]
I can confirm that restarting the browser triggers a cleaning.

**Comment by pacopepepipo** [comment]
Same here

It doesn't work when I hit clean manually
It doesn't work automatically
but it seems to work after restart

**Comment by drb-germany** [comment]
> It doesn't work when I hit clean manually
> It doesn't work automatically
> but it seems to work after restart

For me it does work when I hit clean manually!

**Comment by kennethtran93** [comment]
When released, this should hopefully fix the auto cleaning in Google Chrome.  Please let me know.  

Seems like the alarm output changed from a way older version of Chrome WebExtension API until now...(or at least when webextension-polyfill 0.1.1 was out) to match Firefox Output

**Comment by wavesurf432** [comment]
Hello, I noticed the 3.1.1 update is only available for Firefox at the moment, not Chrome/Chromium/Brave.

I've been having the same issues with cookies not being deleted with Brave. Everything was working fine till a few days ago. 

Edit: Just noticed too that cleanup logs aren't been logged with Firefox. Cookies are being deleted when checking Firefox's settings, but the cleanup logs in 3.1.1 aren't showing up.

Hope this helps.

**Comment by Telhub** [comment]
Additional remark:
cpu load jumps immediately to 100% when the program icon is clicked and remains there until the  Google Chrome Helper (Renderer) process is killed manually. 
Chrome Version 80.0.3987.149 macOS High Sierra 10.13.2

add-on worked perfectly prior to the update to 3.1.0
looking forward to the fix, thanks a lot for you work!

**Comment by kennethtran93** [comment]
@wavesurf432 
> Hello, I noticed the 3.1.1 update is only available for Firefox at the moment, not Chrome/Chromium/Brave.

I did push out the update the same time as Firefox. It appears that Google Chrome still has the update under review. Once it passed their review then it will be published to the public. If you want to temporarily install the updated version then has over to the GitHub Releases section. 

> 
> I've been having the same issues with cookies not being deleted with Brave. Everything was working fine till a few days ago.

While we don't officially support variant browsers, 3.1.0 did break the auto cleanup in Chrome. 3.1.1 should fix it... Whenever it has been reviewed. 

> Edit: Just noticed too that cleanup logs aren't been logged with Firefox. Cookies are being deleted when checking Firefox's settings, but the cleanup logs in 3.1.1 aren't showing up.

Please open another issue for this with further details. 

Thanks.

**Comment by kennethtran93** [comment]
@Telhub 
> Additional remark:
> cpu load jumps immediately to 100% when the program icon is clicked and remains there until the Google Chrome Helper (Renderer) process is killed manually.
> Chrome Version 80.0.3987.149 macOS High Sierra 10.13.2

Please open a new issue for this with further details. 

> 
> add-on worked perfectly prior to the update to 3.1.0
> looking forward to the fix, thanks a lot for you work!

Thanks!

**Comment by wavesurf432** [comment]
> @wavesurf432
> 
> > Hello, I noticed the 3.1.1 update is only available for Firefox at the moment, not Chrome/Chromium/Brave.
> 
> I did push out the update the same time as Firefox. It appears that Google Chrome still has the update under review. Once it passed their review then it will be published to the public. If you want to temporarily install the updated version then has over to the GitHub Releases section.
> 
> > I've been having the same issues with cookies not being deleted with Brave. Everything was working fine till a few days ago.
> 
> While we don't officially support variant browsers, 3.1.0 did break the auto cleanup in Chrome. 3.1.1 should fix it... Whenever it has been reviewed.
> 
> > Edit: Just noticed too that cleanup logs aren't been logged with Firefox. Cookies are being deleted when checking Firefox's settings, but the cleanup logs in 3.1.1 aren't showing up.
> 
> Please open another issue for this with further details.
> 
> Thanks.

That's great to hear, thanks for the great extension.

**Comment by wavesurf432** [comment]
Update: everything looks to working now with the 3.1.1 update with Brave.

Thanks again.
