### ISSUE TITLE
[BUG]  Cookie (LocalStorage) NOT AutoDelete - online.vtb.ru site

### ISSUE THREAD

**Issue by led9** [mrdokenny/Cookie-AutoDelete#664]
error report

**Comment by led9** [comment]
error report 2

**Comment by kennethtran93** [comment]
Because it is a banking site, I cannot perform the task of logging in and out of that site.

Could you please attach screenshots of Firefox Storage Inspector (Menu -> Web Developer -> Storage Inspector) and screenshot each of the sections, their host and its cookies (please redact the values of the cookies but keep the cookie name and everything else intact) of that page in question (the ones that shows you still partially logged in).

**Comment by led9** [comment]
image screenshot

**Comment by kennethtran93** [comment]
Thanks - could I ask you to also translate/insert the English headers for the section headers (Cookies, Cache Storage, Local Storage, Session Storage).

**Comment by kennethtran93** [comment]
Also please fill in the bug report properly.  I also need the CAD version (extension version).

**Comment by led9** [comment]
In the screenshot, everything is in the same places as in your browser version, the translation is not justified.

**Comment by kennethtran93** [comment]
My apologies if you think I'm not trying to narrow down the issue.  There's a difference in whether the bank decided to store it in a cookie, localstorage, or indexedDB.

Per my English screenshot, there's a difference in section headers is if you look at the English version:
![Screenshot_20200321_233706](https://user-images.githubusercontent.com/6724477/77243967-42b75400-6bcd-11ea-819b-3ab348e9438b.png)

If it is a cookie or localStorage, I will continue to look deeper into this as to why that specific site isn't getting its data cleaned.  However, indexedDB is only a 'clear all' at this time (not by individual site) so I'm holding off on implementing that at this time.

**Comment by led9** [comment]
Problem site: https://online.vtb.ru/content/v/ru/login.html
Extension's version = 3.1.1
i set interface of my Firefox to English, there screen: 
![1](https://user-images.githubusercontent.com/7848312/77244680-92cc0000-6c39-11ea-8d8f-d4c927650911.jpg)

I also have StoragErazor https://addons.mozilla.org/en-US/firefox/addon/storagerazor/
but it also no delete cookies/data from this site (all other's = delete)

**Comment by kennethtran93** [comment]
Looks like it's a local storage issue. That will help me narrow down what I need to look into.

**Comment by kennethtran93** [comment]
Just to confirm - do you have the 'enable localstorage cleanup' enabled in the CAD settings?

**Comment by led9** [comment]
silly me :) This setting was disabled.
BUT - I enabled this option, restart browser, re-enter on online.vtb.ru, close it - cookies of this site still not delete. (!)
list of rules - 
white list = one site(nothing like online.vtb.ru)
Grey list
"*" - Leave local storage contents and Leave all cookies
" " - Leave local storage contents and Leave all cookies

page settings
enabled only top box and bottom box
try enabled Container Tabs в Firefox - no effect

**Comment by led9** [comment]
Deleted Grey list setting totally = no effect, online.vtb.ru still live :)

**Comment by led9** [comment]
I can test the experimental version of your extension to defeat these cookies

**Comment by kennethtran93** [comment]
Normally enabling settings do not necessitate a restart, unless you are testing the greylist action.

Question 1:  Does your bank utilize some sort of webextension as part of a 'hosted app'?

Question 2:  Do you know how to `inspect` the webextension on the background page through `about:debugging`?

**Comment by kennethtran93** [comment]
Apologies for the delayed response.  I was working on other older issues/feature requests including localstorage for Chrome.  I had this issue on the back of my mind, and I cannot figure out why it cannot be deleted, unless it was a 'hosted app' web extension/app installed by your banking site...which seems highly unlikely.

On another note, Question 3 relates to what you initially put into the first post:
> If you manually click "delete cookies and site data" in the address bar(on tab with log in), it is deleted. 

How was this done?  Through Firefox itself or CAD WebExtension?

**Comment by kennethtran93** [comment]
Got a temp version here.  This outputs the hostnames being sent to localstorage via background page's console tab.  Send a screenshot over when you have a chance to run it through autocleanup / manual cleanup.
~Cookie-AutoDelete_Firefox_Dev_200326_0326.zip~

**Comment by led9** [comment]
Hello
1 = No, no install site extension - the login is the same as on this site - only login / password and number from sms
2 = I read and found out

>How was this done? Through Firefox itself or CAD WebExtension?
Through Firefox - clicked on the lock icon in the address bar and chose "delete cookies and site data"

>Cookie-AutoDelete_Firefox_Dev_200326_0326.zip
see screenshot
![1](https://user-images.githubusercontent.com/7848312/77667193-b24d8a80-6fa3-11ea-9d28-9368a5d1ab25.jpg)

**Comment by kennethtran93** [comment]
Found the bug while troubleshooting the one for Chome #523 

Seems firefox requires the exact domain, not just the main domain.  I'll update the code and let you know.

I'm unsure if firefox uses the webextension API or its own internal API to clear storage.  Most likely the former.

On a separate note, I'm curious as to why browser.privacy.websites is undefined in your case.

**Comment by kennethtran93** [comment]
Ok this update should fix it...at least for those cookies whose domain matches with the localstorage one.  As long as the cookie isn't set for a generic domain that is.

[Cookie-AutoDelete_Firefox_Dev_200326_1616.zip](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/files/4390509/Cookie-AutoDelete_Firefox_Dev_200326_1616.zip)

Please give this a shot and let me know.  Thanks.

**Comment by led9** [comment]
https://online.vtb.ru/content/v/ru/login.html
When you login to it, close a tab and reopen it, you can see that the data has not been deleted.
BUT! - if I manually choose to delete data for this site in your extension, then the data is deleted.
I think this is a step towards victory - your extension can remove these strong cookies. It just doesn’t delete automatically yet.
See screenshot - 
First, I closed the tab and the extension tried to delete cookies, could not, then I manually selected the delete local storage button for this site in your extension and the extension deleted it.
![1](https://user-images.githubusercontent.com/7848312/77771002-eee2ba00-7067-11ea-9307-69cf911f9ec3.jpg)

**Comment by kennethtran93** [comment]
Once again I remind you that your bank is most likely storing your saved info in LocalStorage, not cookies.  They're completely different.

Unfortunately those errors don't help very well as it doesn't tell me anything.  Some of those errors are from FIrefox itself, and maybe from other extensions.

**Comment by kennethtran93** [comment]
I'd assume that you closed the tab and waited for the auto clean to be executed.  As long as there was a cookie from the online.vtb.ru domain then the localstorage should be cleared for that specific domain unless the settings weren't setup accordingly when you tested that version.

**Comment by led9** [comment]
Yes, im closed the tab, time auto clean = 0, im assume that - auto clean to be executed. But no clean.
kennethtran93, your extension work fine - deleted local storage for this site when manually click - "clear" button in _your extension_ - 

that is, the extension knows what and how to remove data for this site, the only question is if this happens automatically - only this, and not how to do it at all.
So this is only one site, im can manually delete it, I do not insist on fixing your extension, it is already good - it deletes the other.

**Comment by kennethtran93** [comment]
Technically it is still a bug in your case until it is resolved.

Could you try a one second autoclean delay?  I might need to change the backend to make it minimum 1 second or set it internally to 500 milliseconds due to the following note https://developer.mozilla.org/en-US/docs/Web/JavaScript/EventLoop#Zero_delays

> Zero delays
> 
> Zero delay doesn't actually mean the call back will fire-off after zero milliseconds. Calling setTimeout with a delay of 0 (zero) milliseconds doesn't execute the callback function after the given interval.
> 
> The execution depends on the number of waiting tasks in the queue. In the example below, the message ''this is just a message'' will be written to the console before the message in the callback gets processed, because the delay is the minimum time required for the runtime to process the request (not a guaranteed time).
> 
> Basically, the setTimeout needs to wait for all the code for queued messages to complete even though you specified a particular time limit for your setTimeout.

I'm not sure what other queued items are still in the backend that delays the autocleanup, but I do want to make sure that the autocleanup is working for your site.

**Comment by led9** [comment]
Autodelete work!
I set 1 sec, try login and logout, close tab, open after five second = no autodelete,
Then i delete gray list totally in settings, try one more time - Autodelete work! 
(try another = work again)
:)

**Comment by led9** [comment]
yes = gray list if exist then NO work, even with 1 sec lag settings
0 sec lag in settings = NO work -it doesn’t matter if the gray list settings exists or not

1 sec and not gray list = all work!

**Comment by kennethtran93** [comment]
Greylist is browser restart.  That is what it is supposed to do - clean on restart of browser itself.  (Try that if you can as well, it should work as well.)

Sweet.  Then the PR mentioned will fix that...perhaps I'll change it to a 250-500 millisecond delay instead of 0.

**Comment by led9** [comment]
3.2.0 version = NO work on online.vtb.ru, again!

**Comment by led9** [comment]
I don’t understand - you fixed it and I even tried the new version - everything worked, why doesn’t it work in the release?
In the description of the changes in the new version of the extension, you did not even mention this problem and its solution! What, decided not to fix it? Well, I don’t know - it doesn’t work in short and this is unpleasant.

**Comment by kennethtran93** [comment]
The minimum 1 second is implemented.  However I didn't validate existing settings

**Comment by kennethtran93** [comment]
My apologies on the change log - I'm still pretty new at this.

**Comment by kennethtran93** [comment]
Try 1 second for autoclean delay first.

**Comment by kennethtran93** [comment]
I'll keep this open for now to make sure that it works as long as the autodelay is not zero seconds.

**Comment by led9** [comment]
You have updated everything, apparently the matter is different. (Sorry to suggest such)
1 sec, 2 sec = same. Not work. beta-version from this thread - not work too.
I assume that the browser Firefox Nightly is so updated that it stopped working.
I am using the latest version.
how it started - strong, stubborn cookies :)

**Comment by kennethtran93** [comment]
Thanks for the update.  That takes a bit off my plate, being the only developer at this time and all.

Unfortunately I won't have time to check what broke in the beta, but hopefully it would get fixed before it reaches developer edition as that's what I'm using to enhance/debug the extensions.

There is another recent issue most likely relating to localstorage that needs fixing, notably cookies and localstorage set by `file://` (local html files with inline javascript) and cookies that for some reason or another have empty domains.  Because I cannot iterate through the localStorage area, I would need to blindly try and remove it based on the cookies that gets retrieved.

**Comment by kennethtran93** [comment]
If you do have the chance could you try using Firefox (stable/public), Beta, or Developer edition and see if this issue persists?
