### ISSUE TITLE
[SUPPORT]  After update Vivaldi Browser to 2.11.1811.49 cookies auto delete does not work anymore.

### ISSUE THREAD

**Issue by ghost** [mrdokenny/Cookie-AutoDelete#667]
**Please describe what you need support with.**

A clear and concise description of what you need support with.

**Describe the solution you'd like**

**Additional context**

**Comment by ghost** [comment]
now this extinsion taking 50% of my cpu usage (Vivaldi)

**Comment by kennethtran93** [comment]
While we don't officially support Chrome variants, we do understand that the current published version on the Chrome website is 3.1.0. Which contains a bug for auto cleanup. #658 

3.1.1 fixes the auto cleanup issue. You can get it under GitHub Releases.

Please keep the title short and use the description post for the details. The details are required to help narrow down where the issue may be.

**Comment by kennethtran93** [comment]
Closing due to unofficially supported browser.

If this could be duplicated in Google Chrome then feel free to update this issue or create a new one with details.
