### ISSUE TITLE
[BUG] No Cleanup Logs Being Generated with CAD 3.1.1 on Firefox

### ISSUE THREAD

**Issue by wavesurf432** [mrdokenny/Cookie-AutoDelete#668]
**Describe the bug**
No cleanup logs are being generated with CAD 3.1.1 on Firefox with auto cleaning on domain changes and manual deletions of cookies. 

All three clean options (Clean, include open tabs e.t.c), from what I can gather, are working; but no cleanup logs are being generated. The same is happening with auto cleaning on domain switches.

**To Reproduce**
1. Manually delete cookies with clean options from drop down GUI.

2. Set CAD to auto-delete cookies on domain switch; then test with a couple websites.

**Expected behavior**

1.Manually clean cookies from drop down GUI - cleanup log immediately generated within GUI.

2. Switch from one domain to another - upon opening CAD, the GUI shows the cleanup log related to that domain switch. 

**System Info**

 - OS: Linux Mint 19.3
 - Browser Info: Firefox 74.0
 - CookieAutoDelete Version 3.1.1

**Comment by kennethtran93** [comment]
Do you have 'Enable Cleanup Log and Counter' enabled?

**Comment by wavesurf432** [comment]
> Do you have 'Enable Cleanup Log and Counter' enabled?

Yes.

All options ticked in cookie settings except Show Notification After Cookie Cleanup and Enable Support For Firefox's Container Tabs.

**Comment by kennethtran93** [comment]
Hmmm...for some reason I cannot reproduce this.  I'm using Kubuntu LTS 18.04 and Windows 10 Pro, Firefox 74 and CAD 3.1.1.  

Both `Clean` and `Clean, include open tabs` (and the autocleaning) generated logs for me, when using my existing profile to test and unchecking the two options mentioned above.

The `Clean cookies for this domain` and `Clean localstorage for this domain` do NOT add any log entries at this time as they simply disregard any greylist or whitelist cookie exceptions and will remove ALL cookies with NO ability to undo them, similar to localstorage (though no logs exist for those at this time either way).

Are you on permanent private browsing by chance?  If I recall correctly this extension doesn't play well with private browsing.

**Comment by kennethtran93** [comment]
What was your cleanup delay set to? You would need to wait until the delay has passed before the cleanup would commence.

**Comment by wavesurf432** [comment]
Hey, sorry for the long delay before replying!

I am using permanent private browsing, and my cleanup delay is set to 0 seconds.

**Comment by kennethtran93** [comment]
With the way Kenny had it set up in previous versions before I assisted, it is expected that only notifications would work and cleanup logs would not be generated in private browsing mode due to privacy concerns as mentioned in #500 and other issues.

**Comment by wavesurf432** [comment]
> With the way Kenny had it set up in previous versions before I assisted, it is expected that only notifications would work and cleanup logs would not be generated in private browsing mode due to privacy concerns as mentioned in #500 and other issues.

Ah, I didn't catch that issue when I searched for duplicates before posting this issue - sorry about that! Looks like that's everything sorted now. 

Thanks again for your help and the great extension!
