### ISSUE TITLE
[SUPPORT]  QUESTION

### ISSUE THREAD

**Issue by psytkm** [mrdokenny/Cookie-AutoDelete#673]
Hi,

Sorry to disturb - I was looking over your project and was wondering if you could help me on how you were able to know when the browser tab was closed or restarted, in order to remove all cookies from that particular tab?

I wasn't able to find a space on here where I would be able to post questions about the extension.

Kind regards,
T

**Comment by kennethtran93** [comment]
This should have been submitted as a 'support' issue.

A) Browser Tab close listener is here: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/onRemoved

B) Browser Restart is essentially when the webextension gets loaded here (another listener): https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onStartup 

C) It is not just cookies and site data for that tab.  Anytime the tab closes, we query ALL existing cookies and filter out the greylist, whitelist, and open tabs from it depending on configuration.  That leaves us with the items to remove.

**Comment by kennethtran93** [comment]
If there's no further questions then this can be closed, or I'll close it in a few days.

**Comment by psytkm** [comment]
Apologies Kenneth, I will ensure that I raise it as a support issue next time.

I have no further questions.

Thank you for the help.
