### ISSUE TITLE
[SUPPORT]  Non stop Refresh after Clean Cookies in Chrome

### ISSUE THREAD

**Issue by ssilva-d** [mrdokenny/Cookie-AutoDelete#675]
I apologize for lack of details, but
I had the extension installed on Chrome and one time hit something without meaning to on the extension menu - I was going for  "Clear cookies for this domain" - and suddenly a message came up showing a long list of Cookies that had been cleared, including many domains from my history that weren't necessarily open at the time.

After that - some sites that I visit go into non-stop Refresh and I can do nothing to stop them.
The two I have noticed so far are twitter (which shows no content and only "Something went wrong") and fonts.adobe.com, both of which I am logged into as a user.

I don't know if the issue is or isn't related to the extension, any ideas?

Thank you

**Comment by kennethtran93** [comment]
Just as a side note seeing that you have it resolved on your own already.

You may have clicked 'clean' or 'clean including open tabs'.  Those are the only two manual options that will give any cleaning log indications.  

Clear cookies for this domain will clear all cookies for that domain regardless of grey or whitelist.

If I had to guess, the site that had its cookies cleared wasn't part of any list, but the cookie stored was an authenticated response that came from another site that has its domain grey or white listed.

**Comment by ssilva-d** [comment]
Yep I resolved just resetting my Chrome settings, but I think you're right
I most likely hit clean.

Thanks for the extra info.
