### ISSUE TITLE
Same website - different whitelist outcomes between Firefox/Win10 and Firefox/Android

### ISSUE THREAD

**Issue by ReLHUB** [mrdokenny/Cookie-AutoDelete#676]
Hello
Wildcard issue on Android I think. Can't figure it out, have tried but with no success. Solved issue, so more of a heads up for devs. 

1. CAD 3.1.1 on both platforms.

2. Whitelist entry on both platforms is *.guitargear.net.au

3. On Windows10/Firefox 74.0 (64 bit), the whitelisted entry '*.guitargear.net.au' functions as expected for;
   www.guitargear.net.au
   backstage.guitargear.net.au

4. On Android 9/Firefox 68.6.0, the whitelist entry above '*.guitargear.net.au' ,does not work for    "backstage.guitargear.net.au". I have to add another whitelist entry with the fully qualified name for it to function as expected.

Thanks

**Comment by kennethtran93** [comment]
is this still happening on the latest version 3.2.0?
