### ISSUE TITLE
[BUG]  Unable to delete specific cookie

### ISSUE THREAD

**Issue by snowbound** [mrdokenny/Cookie-AutoDelete#679]
**Describe the bug**
I am using the Brave browser.  It is a chromium based browser.  In Google Chrome or MS Edge one can enter "google.com" in the browser's clear on exit area and that specific cookie is deleted. However, in Brave it does not function properly since deletion of the google.com cookie should result in logging me out of my Gmail accounts automatically WITHOUT removing Authenticator 2FA cookie or YouTube configuration cookie.

I installed Cookie-AutoDelete and tried setting up a filter on using "google.com" and putting it on greylist. I tried using with and without Keep Cookies and the result was the same I remained logged into my Gmail account.  

I believe the specific cookie that is sub cookie of google.com that I need it to delete sid@*.google.com on browser restart. So I greylist that in the expression. Yet when I restart the browser I am still logged into my Gmail accounts. Does not seem to be deleting that cookie
![Cookie Filter](https://user-images.githubusercontent.com/596147/78715301-d59d0180-78e2-11ea-8183-ae95b4fe9f2b.jpg)

**Your System Info (please complete the following information):**

 - Windows10 Pro 1909
 - Version 1.8.66 Chromium: 81.0.4044.83 (Official Build) beta (64-bit)
 - CAD version: 3.1.1

the attached is the screen shot of the filter in place. When close the browser and start it up the cookie is still there.

**Comment by kennethtran93** [comment]
Greylist works a little differently - check it off to delete that specific cookie on browser restart.

**Comment by kennethtran93** [comment]
Also if you have session restore, then CAD may not be able to remove it before the tab loads.

Also there's an option, if you do have that tab opened on startup, to remove cookies on open tabs at startup that needs to be checked.

**Comment by snowbound** [comment]
I had it checked on initially. I exited Brave. I start Brave back up the
cookie still shows up in Expression as well as all of its sub cookies. I
was also still logged into Gmail. I use Session Buddy which requires manual
intervention to load the tabs up after the browser starts up. No automatic
loading of the tabs occurs when the browser starts up.

**Comment by kennethtran93** [comment]
The cookie name will ALWAYS show up in the CAD Expression as it is something you had specifically set to remove upon restart.  You'll need to check elsewhere (for Chrome: `F12 -> Application tab -> Storage` sidemenu for the cookies on that domain/tab).  Also, check if `gmail.com` domain stores any login-related cookies.  Per for screenshot, also try `*.google.com` to pick up other cookies (e.g. accounts.google.com)

Unfortunately I do not know the specific login cookie to erase.

**Comment by snowbound** [comment]
Its not just the cookie name google.com that is showing up after browser
restart its all of its sub cookies such as the SID one still shows in the
list. I go to "All cookies and site data" and look for google.com cookie it
still shows up even after Brave is closed and started back up. It is as if
the extension is not deleting the cookie,  Even when I click on SID sub
cookie on the google.com cookie in that screenshot close down Brave start
it back up and I am still logged into Gmail.

In Google Chrome if I enter Google.com in its browser Clear On Exit then
Chrome will delete the cookies properly Brave for whatever reason will not.

If I use *.google.com it deletes all of the google cookies including the
YouTube configuration and the 2FA cookies for Gmail. That is something I
would not like to happen.

In Firefox I am using "Forget Me Not" extension and have it clear out the
sid@*.google.com cookie upon browser restart. That forces a Gmail logout.

Thanks for the tip re F12 I found that indeed it is the SID cookie as
highlighted in the attached screenshot that I edited down to show the
relevant area. If I right mouse click on the SID entry and select Delete
then reload the Gmail tab I am indeed logged out of Gmail.  I removed
google.com from the expression list and put SID@mail.google.com and ensured
it was checked on and greylisted. I closed Brave. I started Brave up again
and I was still logged in to Gmail. Thanks for the help anyways.

**Comment by kennethtran93** [comment]
Unfortunately there is no blacklist to remove a specific cookie while keeping the rest yet.

**Comment by kennethtran93** [comment]
One more question:  What was your delay time set to?

**Comment by kennethtran93** [comment]
_I probably should have read the title first_

This currently isn't a bug per se - you're asking for a blacklist feature in this case.

**Comment by kennethtran93** [comment]
Tagging relevant request/issues #95 #549 and maybe others.

**Comment by snowbound** [comment]
I had it a 15 default. Turned it down to 10. With sid@mail.google.com set
for greylist and checked on it deleted all the cookies for YouTube
configuration plus the 2FA authorization cookie. If I specified google.com
and placed the check mark only in the SID subcookie the same thing
happened. Is there no way to fine tune what specific cookie is deleted and
tell it hands off all others?

**Comment by kennethtran93** [comment]
a blacklist has yet to be implemented - thus this isn't a bug but a feature request now.

**Comment by kennethtran93** [comment]
As there is already a request for blacklist, I will close this support issue now.
