### ISSUE TITLE
[SUPPORT]  Pushing settings and whitelist to multiple users

### ISSUE THREAD

**Issue by phillipge** [mrdokenny/Cookie-AutoDelete#683]
Is there a way to push out the whitelist and settings to multiple users?

Can it be done via GPO?  If not, are these settings stored in the windows registry or in a txt file on the local machine?  I could make any of these work for what I am needing to do.

**Comment by kennethtran93** [comment]
Sorry.  There's no remote setup for this webextension yet.  It doesn't have sync either.  Only manual import and export of the expressions (no base settings export at this time).

**Comment by kennethtran93** [comment]
A near future update will have base settings included.

**Comment by kennethtran93** [comment]
Closing this support issue.  It will be a while before this gets implemented.
