### ISSUE TITLE
Feature: Suppress cookie warning / popups from websites

### ISSUE THREAD

**Issue by driebe** [mrdokenny/Cookie-AutoDelete#684]
Hi,

similar to the "I don't care about cookies"-extension, I would love to see Cookies-Autodelete adopt this feature and suppression any kind of cookie popup or warning on all websites which are not grey- or whitelisted.

This way there's no need for installing more than one cookie-related Firefox extension in the future.
Thanks for your consideration.

Regards
Daniel

**Comment by kennethtran93** [comment]
Hi Daniel,

I appreciate your suggestion, though I still think having separate cookie extensions would still be ideal at this time.

If they really want to suppress the warnings, then just whitelist that specific cookie that holds the 'agreed' flag in that domain.  All other unchecked cookies will be removed.

**Comment by BenceSzalai** [comment]
How such cookies can be individually whitelisted? Can we add a specific cookie to the whitelist from the GUI or do we need to manually add an expression for each? In expressions, can we use wildcard domains, to say allow the most common cookie control cookies on all domains (can be abused in fact, but still most likely it won't be)?

**Comment by kennethtran93** [comment]
> How such cookies can be individually whitelisted? Can we add a specific cookie to the whitelist from the GUI or do we need to manually add an expression for each? 

You can whitelist it for individual domains via the popup or in the Expression area of Settings.  Ensure that the domain is whitelisted, then uncheck 'Keep all cookies' and check the cookie name that stores the cookie warning suppression.

> In expressions, can we use wildcard domains, to say allow the most common cookie control cookies on all domains (can be abused in fact, but still most likely it won't be)?

Yes.  The recent releases allow regex expressions/wildcard domains.  e.g. `git*.com` will match _gitlab.com_ and _github.com_.  If there is a common cookie name for many websites, you can either try to find a common wildcard hostname/regex or just use `*` in whitelist and check the cookie to keep.

In both cases, the cookie must already exist.  At this time there's no wildcard / manual input for cookie names unless it is through the custom expression import (though the imported expression  must NOT exist already).

**Comment by kennethtran93** [comment]
If this support is resolved then you or I can close it.  However if I don't here a response from you after the weekend then I'll close it.

**Comment by driebe** [comment]
Hi Kenneth,
as it was not a support but a feature request. I still believe that it would be cool if cookiesAutodelete would make away with all the annoying "I agree to your cookie" popups - indifferent on whether or not the cookies are allowed for a given website or not.

As you have a differing opinion whether this feature would be worthwhile to be added to this extension, I guess I will have to rely on "I don't care about cookies" for this afterall. No hard feelings ;-)

Regards
Dan
