### ISSUE TITLE
French Translation bug

### ISSUE THREAD

**Issue by tomapi69** [mrdokenny/Cookie-AutoDelete#69]
Hello,

Whitelist translation to "Liste blance" is incorrect and should be "Liste Blanche". I'll be happy to help and review the other words.

Regards

Thomas

**Comment by mrdokenny** [comment]
I'm going to ping @Primokorn for this. 

You can look at this messages.json file.

https://github.com/mrdokenny/Cookie-AutoDelete/blob/master/extension/_locales/fr/messages.json

**Comment by Primokorn** [comment]
Sorry for this tipo. I didn't have time to check all the strings.
I don't find this translation in the json file though.

**Comment by mrdokenny** [comment]
@Primokorn I looked at the history and it's a typo in 1.3.0

https://github.com/mrdokenny/Cookie-AutoDelete/blob/56eac2b4947dd06ccb4ddbba9b2447d6a514c6ad/extension/_locales/fr/messages.json#L58

So it should be fixed in 1.4.0 that I already pushed out on AMO and Chrome WebStore.

**Comment by tomapi69** [comment]
OK So no need for me to review further. Thanks for the quick reaction.
