### ISSUE TITLE
[FEATURE REQUEST]  persistent storage - delete when 0 cookies

### ISSUE THREAD

**Issue by AtomicRobotMan0101** [mrdokenny/Cookie-AutoDelete#694]
**Is your feature request related to a problem? Please describe.**

Firefox seems to store Persistant Storage data even when cookies are deleted by CAD.

PS is obviously used for tracking. If a site cannot set, or has cookies destroyed, it will simply store them (or even more data) in PS.

This is obviously very bad.

**Describe the solution you'd like**

When the CAD script runs, kill off any remaining PS containers.

**Describe alternatives you've considered**

None. Ive only just noticed this behaviour. Ive not seen it mentioned in any other addons, nor a quick web search seems to raise this as an "issue", even though its an obvious vector for tracking.

**Additional context**

Nil. Just enjoying CAD and wish to enhance it without feature creep.

**Comment by kennethtran93** [comment]
This was mentioned in previous issues as:
- 'cookie/storage' still shows in Firefox Manage Cookie and Site Data panel or not deleted on clean, etc.
  - namely LocalStorage and Persistent Storage counts as one.  Deleting one will not remove the other so the size would still show for persistent storage.

The same response is given for those:
- IndexedDB can NOT clean by host yet.  Webextensions can not delete indexedDB by host yet.  (This may be a relevant bug: https://bugzilla.mozilla.org/show_bug.cgi?id=934640)
- At this time we are holding off on implementing cleanups that cannot clean by hostname.

**Comment by kennethtran93** [comment]
In an attempt to do some housekeeping on issues, I will close this as a browserbug limitation for now that cannot be worked upon at this time.  If and when cleaning certain items by hostname has been implemented, feel free to open a new issue and/or comment/reference on older closed issues.

**Comment by kennethtran93** [comment]
A near future release of 3.5.0 will have cache, indexedDB, pluginData, and serviceworkers removed by domain.
