### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by SW1FT** [mrdokenny/Cookie-AutoDelete#7]
Localization should be considered in a near future in my opinion.

Also, I can provide a pt_PT translation.

**Comment by mrdokenny** [comment]
I would have to set it up since everything is hardcoded right now, but thanks for the offer.

I'll let you know when its ready.

**Comment by mrdokenny** [comment]
@SW1FT I added localization support. Please check the instructions on the main GitHub page.

**Comment by SW1FT** [comment]
@mrdokenny Done, check #10.

**Comment by mrdokenny** [comment]
![screenshot 2017-05-05 11 24 23](https://cloud.githubusercontent.com/assets/17077613/25758988/8577018a-3185-11e7-982c-9da9308d5bbf.png)

Thanks for your contribution!
