### ISSUE TITLE
[BUG]  Does not delete cookie from websites ending in a dot

### ISSUE THREAD

**Issue by crazyyzarc** [mrdokenny/Cookie-AutoDelete#701]
**DESCRIPTION**

I get a popup every minute indicating that the cookies have been deleted. But they are not deleted.

**HOW DO YOU RE-PRODUCE IT?**
1. Visit a page (i.e. faz.net)
2. Add a dot at the end of the URL like "faz.net."
3. Accept possible certificate errors and accept cookies (not in addon, but in Firefox)
4. Activate auto cookie deletion 
5. They are not deleted by the Addon

**Expected behavior**
The cookies will be deleted

**Screenshots**

[Picture - overview](https://framapic.org/0kW86bLdzBiU/ZbkauoLdbHqV.png)
[Picture - auto cookie delete](https://framapic.org/ryGPiGw46VGl/Lytio27yv88e.png)
[Picture - auto cookie delete #2](https://framapic.org/LASLc9MT7G28/3FB3wEoPebt9.png)
[Picture - Firefox Cookie database entry](https://framapic.org/TBAlwz1uoWWo/LMW9tVJ0Nyuu.png)
[Picture - Firefox Cookie database entry #2](https://framapic.org/ej5W2dojmkDa/CWabmtxrgphd.png)

**Your System Info (please complete the following information):**

OS: Win10 x64 rb 1903
Browser: Firefox 75
CookieAutoDelete Version: 3.20

**Comment by kennethtran93** [comment]
Seems like Kenny removed the trailing dot from all domain names when clearing cookies and localstorage. As we don't see them used too often. 

I'll try to get that resolved in the next patch update.

Thanks!

**Comment by kennethtran93** [comment]
So the next patch will differentiate between the domains with a dot and without a dot (at least on the popup).  This also means that expressions must have a dot at the end in order for it to be kept if you are accessing sites through the end dot.

**Comment by kennethtran93** [comment]
Please try the zip patch in #713 and let me know if it fixes your problem.

This should remove cookies from websites ending in a dot now (including localstorage).
There's also debug mode if you're savvy enough to comb through the browser extension console logs that it spits out through there.
