### ISSUE TITLE
[BUG]  does not delete coockie automaticaly, only when i click on clear coockies from this domain

### ISSUE THREAD

**Issue by natanh** [mrdokenny/Cookie-AutoDelete#703]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

Add screenshots to help explain your problem, notably the settings and any related errors.  For showing cookie counts, it would be helpful to also include a screenshot of the Storage Inspector that you can access through Development Tools (F12) WHILE on that tab/site.

**Your System Info (please complete the following information):**

 - OS: [e.g. iOS, Windows 10 Pro, Android/Samsung]
 - Browser Info: [e.g. Chrome 77.0.1234.111, Firefox 77.0.2]
 - CookieAutoDelete Version [e.g. 3.0.3] 

**Additional context**

**Comment by kennethtran93** [comment]
Please fill in the bug Report Detail body.

**Comment by kennethtran93** [comment]
If the detail report is not filled in I will close this shortly.
