### ISSUE TITLE
[FEATURE REQUEST]  Option to disable translations

### ISSUE THREAD

**Issue by azumukupoe** [mrdokenny/Cookie-AutoDelete#708]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kennethtran93** [comment]
Please fill in the request body.

**Comment by kennethtran93** [comment]
There's currently no way to disable translations through webextension as it is using browser.i18n.getMessage() function.  You'll need to go through your browser configuration to override what language it should be using.

I'll keep this open for a bit, but if the request body is not filled in properly this will be closed.

**Comment by kennethtran93** [comment]
Closing this as incomplete and per the reasons listed above.
