### ISSUE TITLE
Line ending format for whitelist text file

### ISSUE THREAD

**Issue by hermes3por3** [mrdokenny/Cookie-AutoDelete#71]
I have noticed that whitelist import does not work (and fails silently) if lines end with `\r\n` (Carrier Return and Line Feed) instead of just `\n` as the exported file. I think having the flexibility to accept both would be great. This happened because I manually edited the whitelist file, and my text editor happens to be configured to create new lines with `\r\n` by default, which I suspect many people will have.

- OS/version: Windows 10
- Browser/version: 56.a01
- Cookie AutoDelete version: 1.3.1

**Comment by mrdokenny** [comment]
Are you talking about these?

![screenshot 2017-06-27 07 57 32](https://user-images.githubusercontent.com/17077613/27594343-5bfc56fe-5b0e-11e7-8ded-515745cc3d84.png)

**Comment by mrdokenny** [comment]
So I fixed this by normalizing the CRLF and CR EOL to LF EOL.

**Comment by hermes3por3** [comment]
Hi Kenny,

that's right! Your addon only reads unix line end (LF). I believe 
accepting the three of them should be desirable.

Best regards,

Hermes

**Comment by woctezuma** [comment]
So is this fixed already? Because I think I encountered this problem today.

I copy-pasted the content of my whitelist in a chat window, got it on another computer this way, pasted in with notepad.exe and got the addon to bug out. I had to copy & paste each website individually instead of importing the whitelist. It looks like this bug.

**Comment by mrdokenny** [comment]
@woctezuma It's fixed but I haven't pushed it out yet.

**Comment by mrdokenny** [comment]
@woctezuma Can you test 1.4.1 out and do the exact thing you did to confirm that its fixed.

https://github.com/mrdokenny/Cookie-AutoDelete/releases/tag/1.4.1

**Comment by woctezuma** [comment]
I would if I knew how to install an unsigned addon. Right now, I have set `xpinstall.signatures.required` to `False` but Firefox 54.0.1 still does not allow me to install the pre-release addon.

**Comment by mrdokenny** [comment]
@woctezuma Go into `about:debugging` and load the xpi temporary.

**Comment by woctezuma** [comment]
Yep. It is fixed. I have just tried with two fresh profiles on Firefox:

- with the signed addon 1.4.0, the bug is there,
- with the unsigned addon 1.4.1, the import works as expected.

**Comment by mrdokenny** [comment]
@woctezuma Thanks I''ll push 1.4.1 out.
