### ISSUE TITLE
Sync List of Expressions Between Devices or Add "Delete All" Expressions?

### ISSUE THREAD

**Issue by elprice7345** [mrdokenny/Cookie-AutoDelete#712]
**Is your feature request related to a problem? Please describe.**

I like to keep my CAD List of Expressions synced between my devices.

Currently, I save a list of expressions from my "Master" device and upload them to my other devices.

This works, but doesn't delete an expression I've deleted from my master device on "synced" devices.

I can manually delete each expression, but that is a PIA.

**Describe the solution you'd like**

Ideally, CAD could automatically sync expression lists between selected browsers and/or devices.

**Describe alternatives you've considered**

In lieu of adding syncing functionality (maybe more work than you want to undertake), could you add a "Delete All" expressions function? Users could then manually "sync" (export/delete/import) between devices.

**Additional context**

N/A

**Comment by kennethtran93** [comment]
I get where your stance is, but please follow the feature request report template when submitting feature requests.  This includes keeping the headers noted.  I'd hate to start implementing auto-close for those who don't follow the template.  It is there for a reason.

It is easier at this time to add a Delete All expressions and can do that in the next version or so.
Syncing is later on.  Only between same-browsers of course!

**Comment by elprice7345** [comment]
My bad! :-(

Would you like me to resubmit using the proper template?

**Comment by kennethtran93** [comment]
If you can - just copy the template over to this one and merge it with your responses.

**Comment by elprice7345** [comment]
I've updated my original post to the feature request template.

Please let me know if there's anything else I can do!

**Comment by kennethtran93** [comment]
PR #713 (build in comments) added a 'Delete All Expressions' Button that will remove all expressions for All lists.  The removal of all expressions per list is not implemented yet.

Could you please test it on a fresh profile and see if it works for you?

**Comment by elprice7345** [comment]
Sorry, @kennethtran93, I'm not a developer and I have no idea how to test an extension.

If you can provide a link with simple instructions, I'll give it a go.

**Comment by kennethtran93** [comment]
I don't have a link for you... If you do want to test, you can try the following:
- on Firefox: download and install Firefox developer edition. Then goto about:config and search for 'xpi' and set the signature one to false. Then you can go to about:add-ons and click on the gear cog and install the addon from the zip build I have provided in 713.
- Chrome: use a new profile, unzip the chrome build version and goto chrome://extensions. Then enable development mode on the top-right and then you can 'load unpacked extension' by navigating to the unzipped folder and selecting the manifest.json file.

**Comment by kennethtran93** [comment]
Or just wait until it gets published...sometime next week pending validations.

**Comment by elprice7345** [comment]
I tested my request and all is good! Thanks!
