### ISSUE TITLE
[Bug]  Remove menubar at the top.

### ISSUE THREAD

**Issue by BoboSims** [mrdokenny/Cookie-AutoDelete#714]
Suddenly a new menu bar appears at the top, holding only one button, to activate the sidebar.
What in heaven's name is THAT for? Not only does that bar take more screen real-estate away, but it also forces users to press more buttons to get to the functions they want...

Truth be told, I had rather see that bar gone ASAP, because I don't consider it an improvement. Or maybe make it configurable?

**Comment by kennethtran93** [comment]
That was originally for Firefox Android.  I'll update the CSS so that the sidemenu shows up after the window's width grows past a certain point.

**Comment by BoboSims** [comment]
Ah, so I *should* have reported it as a bug, huh?
Anyway, thank you for the quick response. I'm confident that it will be gone soon :)

**Comment by kennethtran93** [comment]
For your information, if your browser width was greater than 1300 px then it would be hidden.  I'm going to lower the min browser width to 1024 px so anything below 1024 will show the menu on top.

**Comment by BoboSims** [comment]
So you mean that if I use my browser full-screen at 1920x1080 resolution, the menu bar should not have been visible in the first place? If that is the case, then something else must have been changed that messed up your code.

**Comment by kennethtran93** [comment]
Hmmm...it appears to work fine on my Firefox stable and Developer edition...

If you're saying 1920x1080 like this, it works.
![Screenshot_20200507_193938](https://user-images.githubusercontent.com/6724477/81364477-935e1000-909a-11ea-9c4d-6948b223f31d.png)

Otherwise if your screen is rotated so that 1080px wide is the width then the menu will show at the top.  This was done for tablets, touchscreens, mobile, etc.

**Comment by kennethtran93** [comment]
Nonetheless I did put in the patch to lower the min/max width to 1024px.  With this even if the screen is rotated to portrait mode then it should always show the sidebar.

**Comment by BoboSims** [comment]
![Screen Shot 2020-08-05 08 55 19](https://user-images.githubusercontent.com/10255508/81379820-136f8e80-910a-11ea-827a-0eb6a6be9a01.PNG)

My TV is **always** in landscape mode, 1920 width, 1080 height. I don't know how to rotate that. Until a few days ago, I always had the sidebar. I immediately opened this issue the moment I saw the top menu for the first time. So I **think** it was an update which did it.

**Comment by kennethtran93** [comment]
Funny thing was that I don't think I've touched the CSS portion of that code in the last update...

**Comment by BoboSims** [comment]
Well, I have no idea what to say to that. Maybe that code relies on something else that *did* get changed? Not necessarily by you, but perhaps by someone else? You never know.

**Comment by kennethtran93** [comment]
I just found out that by zooming in 150% you will see it...That's probably why.  To that fact there's nothing much I can do on my end but to lower the width limit for sidebar/top menu.  If there's smaller screens that will complain later on I will bump the limit higher.

**Comment by kennethtran93** [comment]
Most likely your window version may have scaling set differently per monitor?

**Comment by BoboSims** [comment]
150%?  Make that 120%. My TV is at such a distance from me, that for better readability, I have my browser scaling set to 120%. When I reduced it to 110%, the bar was gone!

Problem solved. Not happy about the smaller setting, but I'll live with it.

**Comment by kennethtran93** [comment]
You may be able to zoom in again after the next update.

**Comment by BoboSims** [comment]
That would be great, but I won't complain if it doesn't work. Thanks, bro!
