### ISSUE TITLE
[FEATURE REQUEST] edit a single cookie

### ISSUE THREAD

**Issue by gabri25ele** [mrdokenny/Cookie-AutoDelete#715]
Possibile to add an option to edit the single cookie? save it, export it?

**Comment by kennethtran93** [comment]
There's no plan to support cookie modifications from this extension anytime soon.  That brings it away from the main purpose of this extension.

I'd suggest you use Cookie Manager if you're on Firefox: https://addons.mozilla.org/en-CA/firefox/addon/a-cookie-manager/
