### ISSUE TITLE
Right Click support

### ISSUE THREAD

**Issue by glholman** [mrdokenny/Cookie-AutoDelete#717]
**NEED:** I am frustrated when I sign-on to certain browser extensions (e.g., Evernote that provide a check box to stay logged in for 30-days that opens a window) but for which, inside the sign-in pop-up window, I cannot whitelist the URL that is shown in the popup.  

I have tried going to the apparent URL that it looks like it is going to inside the pop-up window and white listed that page, but then when I go to use the app again after shutting down the browser, it has lost its cookie so presume it is not the correct page.

**WISH:** What I would like to be able to do is Right Click mouse and see a place to whitelist the URL with Cookie Autodelete, as this would allow me to whitelist insight these types of popup windows.

     I cannot envision an alternative solution, but am open to anything that would relieve the overhead of having to sign-on so often for apps I use all day everyday.  Thanks for listening.

**Comment by kennethtran93** [comment]
I'd appreciate it if you had followed the feature request template, keeping the headers intact.
Nonetheless I see where you are getting at.

**Comment by kennethtran93** [comment]
Update:  Work In Progress.

Here's my current draft of menu items:
- Manual Clean Options [ browser_action and page only] 
  - The (4) cleaning options found in popup.
- Expression Menu [ link, page, selection only] 
  - for each type, show options for domain only or all subdomains with domain
    - for each option, add to greylist or whitelist.
- Enable Automatic Cleaning option
- Open CAD Settings

**Comment by kennethtran93** [comment]
If you know how and would like to test this unsigned dev version, head on over to the linked PR #753
