### ISSUE TITLE
[SUPPORT] How exactly are Container-Tabs handled

### ISSUE THREAD

**Issue by JustMyGithub** [mrdokenny/Cookie-AutoDelete#718]
**Please describe what you need support with.**

I think the description about container-tabs is confusing. What happens with or without active support? 
Will inactive support act as if there was no container, meaning keep cookies in all containers until the website is closed in the last container? (container agnostic) 
Will inactive support only delete for the "major" containers tabs and not for any container?
Can container-specific white/greylist be set? (e.g. delete in major but whitelist in container A and greylist in container B) ?

I understand that because of API limitations localstorage will be cleaned for all (container and major)

**Describe the solution you'd like**

Understand the exact functionality of the extension.

**Additional context**

I'd like to use two containers, each of these being logged in to a webmail (different accounts) and both containers shall whitelist the websites' cookies. However in the major container cookies from these domain shall be deleted after closing the last tab of it.

**Comment by kennethtran93** [comment]
> I think the description about container-tabs is confusing. What happens with or without active support?

I'll answer your more specific questions below first.  If you still need details let me know.

> Will inactive support act as if there was no container, meaning keep cookies in all containers until the website is closed in the last container? (container agnostic)
> Will inactive support only delete for the "major" containers tabs and not for any container?

I think these two questions are one and the same...
Without active support - only clean default / non-container items (at least that would be the purpose).    It is slightly buggy per recent bug reports. 

> Can container-specific white/greylist be set? (e.g. delete in major but whitelist in container A and greylist in container B) ?

Yes.  However the current buggy implementation is that the domain must not be opened in any containers in order for the cleanup to work properly.

> I'd like to use two containers, each of these being logged in to a webmail (different accounts) and both containers shall whitelist the websites' cookies. However in the major container cookies from these domain shall be deleted after closing the last tab of it.

It is doable...only when the webmail stores their credentials as a cookie and not localstorage.

**Comment by JustMyGithub** [comment]
Thanks for responding so quickly. 

The 4th part of your answer says its doable, but the 3rd part of your answer contradicts that, doesn't it? Or do you mean "properly" because the local storage will not being deleted (but cookies will be)?

PS: At least the German description for local storage clean up may be interpreted as "local storage for all websites will be deleted". I'm pretty sure you mean "all items of the website and if activated in all containers will be deleted - be it authentication, tracking, state data or anything else, because of API limitations"

(btw: what you call default / non-container is what I called major - just to make sure we do not misunderstand each other)

**Comment by kennethtran93** [comment]
> The 4th part of your answer says its doable, but the 3rd part of your answer contradicts that, doesn't it? Or do you mean "properly" because the local storage will not being deleted (but cookies will be)?

Properly as in a slight bug in the extension currently whereas if the domain is meant for cleaning on one container because all its related tabs are closed but is still open as a tab in another container, those cookies won't get cleared from the container that needs it cleared.

Localstorage is a one-hit kill for ALL containers.  I don't believe the API allows cleaning localstorage by containers at this time, so if domains store items in localstorage (like the credentials), and if the domain you want to keep cookies and localstorage for in one container but remove localstorage in another container, then the localstorage will be cleared provided other criterias are met (openTabs, etc).
> 
> PS: At least the German description for local storage clean up may be interpreted as "local storage for all websites will be deleted". I'm pretty sure you mean "all items of the website and if activated in all containers will be deleted - be it authentication, tracking, state data or anything else, because of API limitations"
LocalStorage API limitations per above response

Localstorage is only PART of the items of the website.  There's cookies, indexedDB, serviceworkers, cache, etc.


> (btw: what you call default / non-container is what I called major - just to make sure we do not misunderstand each other)

OK.

**Comment by kennethtran93** [comment]
Anything else that I need to clarify upon before this support issue is closed?

**Comment by JustMyGithub** [comment]
Thanks, I think this can be closed.
