### ISSUE TITLE
[FEATURE REQUEST]  clean cookies for discarded tabs

### ISSUE THREAD

**Issue by Grumph** [mrdokenny/Cookie-AutoDelete#720]
**Is your feature request related to a problem? Please describe.**

I use extensions that discard/unload tabs from memory (AutoTabDiscard to name one).
When a tab is discarded, it's unloaded from memory, and reloaded later.
I expect that cookies are removed for discarded tabs, as in my workflow it's the same if I clos the tab and reopen it later.

**Describe the solution you'd like**

Launch the clean timer when the tab is discarded.

**Describe alternatives you've considered**

I tried to build a solution by myself, but it's the first time I read TypeScript and do WebExtension developpement, and I don't understand how the cookies are deleted.

**Additional context**

See attached draft. #721

**Comment by kennethtran93** [comment]
I've implemented it based on your initial contribution from #721 to #753.

Thanks!
