### ISSUE TITLE
[SUPPORT]  Doesn't delete cookies at all

### ISSUE THREAD

**Issue by pacopepepipo** [mrdokenny/Cookie-AutoDelete#726]
**Describe the bug**

When I hit the clean button, the cookies that are not greylisted or whitelisted and should be delete, persists and are not deleted.

**To Reproduce**

1. click delete
2. cookies are not deleted

for example, I go to https://watch.lolesports.com/ cookies are set, I leave the page, I click on delete, and the cookies are still there and wont be deleted. Same for hundreds of other sites. Even the log says that they are deleted, but no, they are on chrome.

I tried to reinstall the extension but nothing was solved, thousands of cookies are on my browser.

**Expected behavior**

cookies should be deleted

**Your System Info (please complete the following information):**

 - OS: win 10 x64
 - Browser Info: Chrome Version 81.0.4044.138 (Official Build) (64-bit)
 - CookieAutoDelete 3.2.0

**Comment by kennethtran93** [comment]
Where do you still see cookies remaining?

I need your settings screenshot.

**Comment by kennethtran93** [comment]
I've tested the current 3.2.0 version against the domain mentioned above and on a fresh profile.  I'm presuming that you have enabled localstorage cleanup as well.

If this is what you are seeing under Chrome's site data after you have closed all tabs of that domain.
![Screenshot_20200513_131101](https://user-images.githubusercontent.com/6724477/81860494-af8b0280-951b-11ea-82d3-1a5ac516e401.png)

Then it is not cookies or localstorage, but rather everything else, per next screenshot below (this was taken when the tab was open, so the size seems to have shrank a bit after I closed the tab and ran cleanup again to get the screenshot above).
![Screenshot_20200513_130946](https://user-images.githubusercontent.com/6724477/81860635-dea17400-951b-11ea-8462-3fd0a35e0dd6.png)

We do not clean the cache at this time as it is not implemented yet.  While it may be able to clean cache/cache storage by hostname in Chrome, Firefox does not have that capability yet.  A request to have cache cleaned in intervals was put through.

We also do not clean service workers as it is not implemented yet, nor have I checked/tested if it can be cleaned by hostnames.

This extension was based off of Firefox's legacy extension, thus I mainly base it off of what Firefox's WebExtension API has to offer.

**Comment by pacopepepipo** [comment]
I'm sorry for making you lose your time, you are right and I was completely wrong as the files are inside cookies zone on chrome, but they are not, they are local databases and service workers that I thought were cookie from a lot of sites.

And I straight thought it, because after deleting the cookies, some pages like that one, were still maintaining preferences that usually are deleted with the cookies, and I didn't knew that could be made without them.

I don't know why google put them there so we cannot delete them without deleting the cookies, but it is what it is, time to move to firefox.

![](https://i.imgur.com/emM6z2k.png)

thanks

**Comment by kennethtran93** [comment]
You are mistaken when you said we cannot delete them - Browsers can (when you use their internal cleaning features but some things are a 'clear everything of that type' sort of thing), but it has yet to be implemented into this extension yet.  This extension was based off of Firefox's legacy extension Self-Destructing Cookies.  

I cannot say when as I'm the only one working on the extension at this time.  Ideally when each type of data can be cleared by hostname, it will be implemented sooner.

For autocleaning, my stance is currently to implement those that can clear by hostnames.

**Comment by pacopepepipo** [comment]
> You are mistaken when you said we cannot delete them - Browsers can (when you use their internal cleaning features but some things are a 'clear everything of that type' sort of thing), but it has yet to be implemented into this extension yet. This extension was based off of Firefox's legacy extension Self-Destructing Cookies.

No, I mean I cannot go into 

chrome://settings/siteData?search=cookies 

and batch delete everything but cookies.

We have a "remove all" button that will delete every cookie, cache storage, service workers and database storage, but we cannot choose what to batch delete, so I could maintain the cookies but delete everything else in just a click.

It's not your extension, it's chrome in this case that doesn't have that workaround.

**Comment by kennethtran93** [comment]
Firefox doesn't have that either.

**Comment by kennethtran93** [comment]
Don't forget that some sites use localstorage instead of cookies for storing information.  If you only keep those site cookies then expect your data to not load properly at times or is missing.
