### ISSUE TITLE
[FEATURE REQUEST]  shortcut key 

### ISSUE THREAD

**Issue by Ckcut2020** [mrdokenny/Cookie-AutoDelete#727]
**Is your feature request related to a problem? Please describe.**

When used manually to clear a single website it would be much easier and faster to to so from the keyboard instead of opening menu, select etc.

**Describe the solution you'd like**
enable keyboard shortcut for each of the clean actions, preferably shortcuts that can be chosen by user.

**Comment by kennethtran93** [comment]
Duplicate of #46
