### ISSUE TITLE
[Question] Delay/Grace Period

### ISSUE THREAD

**Issue by RandomGOTI** [mrdokenny/Cookie-AutoDelete#73]
Hi , I am using firefox 54 x64
Any plans on taking full advantage on firefox and allow delay values in secounds ?
instant cleanup may break some sites and 6s is quite long compared to 2s ( ͡° ͜ʖ ͡°)
Thanks

**Comment by mrdokenny** [comment]
2/60=0.03 minutes

I know it probably not the most user friendly option but as long as Chrome has a minimum timer of 1 minute, I have to make it constant across browsers. At least, FF doesn't have this limitation.

**Comment by RandomGOTI** [comment]
Tbh didn't thought of using 2 decimal digits... now i feel stupid xD
Works and well made , great successor for sdc 
thanks again , should've tried before asking but it seems you guys already thought about everything : )

**Comment by mrdokenny** [comment]
>you **guys** already thought about everything

Mostly it's just me doing all the code and a couple of volunteer translators, but thanks, and enjoy 1.4.0 which gets pretty close to SDC now. The only thing left is localstorage support. Everything else is basically bonus.

**Comment by RandomGOTI** [comment]
@mrdokenny 
For some reason i tried to make CAD 1.4.0 to work with 2s (0.03)  on chrome 59.0.3071.115 (Official Build) (64-bit) and it seems that its working just fine ... google may had removed the limit
Awesome news ( ͡° ͜ʖ ͡°)
