### ISSUE TITLE
[BUG] Icon not changing color

### ISSUE THREAD

**Issue by mondocane80** [mrdokenny/Cookie-AutoDelete#733]
Since I updated to 3.3.0...

The toolbar icon used to change from blue to orange to red depending up what settings you use for each site.  Now the icon stays blue all the time and doesn't change color.

I miss that because I can take a quick glance at what settings I have set for each site rather than open the menu all the time to check.

Please restore this feature.  Thanks

Using Firefox 68.8.0 ESR on Windows 7

**Comment by kennethtran93** [comment]
Check your settings - there's a new option called 'Keep Default Icon'.  Make sure that is unchecked.

**Comment by kennethtran93** [comment]
Also, people had asked for the icon to not change when there is no cookies on that site as well.  I may need to make an option for that as well if there is no expression set and no cookies to either be red or default.  Perhaps next version.

**Comment by kennethtran93** [comment]
I'll look into it further - seems like a logical order of getting the icon to change properly.

Thanks.

**Comment by mondocane80** [comment]
> Check your settings - there's a new option called 'Keep Default Icon'. Make sure that is unchecked.

Hello,

Under the CAD settings, there is no 'Keep Default Icon' tickbox to uncheck.  Is it located somewhere else?

**Comment by ghost** [comment]
> 
> 
> Check your settings - there's a new option called 'Keep Default Icon'. Make sure that is unchecked.

This setting doesn't work for me. The icon always stays blue, only the badge with the Number of Cookies for that Domain changes color.

**Comment by kennethtran93** [comment]
I've already confirmed it as a bug and is working on a fix for it.  I wonder why testing it on a fresh profile didn't pick that up...I must have been tired and missed something.

My apologies for the regression.

**Comment by kennethtran93** [comment]
GitHub is having some issues at this time, so until I can rerun GitHub Actions to generate another alpha build prerelease, I've manually compiled it for prerelease testing at https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/releases/tag/v3.3.1-alpha2  Please let me know if it works for you as it worked for me again as well.

**Comment by quazgar** [comment]
The icon still is blue for me even for sites which are not in any list, with 3.3.1. The setting "Keep Default Icons on all list types" is unchecked.

**Comment by kennethtran93** [comment]
If there are no cookies for that site, or the only cookie is the one we created for localstorage cleaning, it stays blue.

**Comment by kennethtran93** [comment]
So while I can see the icon changing even if it is not in any list, I think a regression has occurred in the sense the sites with no cookies (aside from our CAD Localstorage one) are seeing red icon instead of blue if no list...

**Comment by kennethtran93** [comment]
Fixed bug in PR #774 where icon changes color when cookie count is 0.  This was a previous feature request that was implemented.
