### ISSUE TITLE
[SUPPORT] How to do less trial and error during configuration

### ISSUE THREAD

**Issue by stdedos** [mrdokenny/Cookie-AutoDelete#734]
**Please describe what you need support with.**

I would like very much to activate the full power of the extension, but it can be so painful to figure out which cookies are required for it to function "configured" and which are just crust. I have the extension installed maybe even more than a year, but never got around to configure it.

**Describe the solution you'd like**

* Are there some "sane" templates to use?
  e.g. Being able to stay logged in in Gmail/Facebook, save your language settings in Google Search, but nothing more?
* Is there some kind of demo mode?
  Select which cookies to "pretend" they don't exist, and see what a webpage load looks like?

**Comment by kennethtran93** [comment]
> * Are there some "sane" templates to use?
>   e.g. Being able to stay logged in in Gmail/Facebook, save your language settings in Google Search, but nothing more?


No, but other users that may have already configured it properly may have exported it and shared it.    Those you'll need to hunt around and import from.
I believe Gmail requires some cookies from google.com domain, but that's all I know.  Specific cookies will be trial and error unless other people chime in.


> * Is there some kind of demo mode?
>   Select which cookies to "pretend" they don't exist, and see what a webpage load looks like?

No demo mode, but if you enable `cleanup log and counter`, then cookies removed by the extension through `autoclean` and the `clean` button in popup will usually generate a log at which point that specific cleanup entry (of cookies) can be restored.  Keep in mind that domains handle how the cookies are used, and as such restored cookies may not work again if it wasn't there beforehand.

**Comment by kennethtran93** [comment]
Any other questions at this time?

**Comment by stdedos** [comment]
Not really, no. I guess "I need to get out of my confort zone" and just do it.
Thank you for your quick reply and full response 😃

I might have further questions when I'll actually go for it - I'll try to re-use this thread, if it will still be able.

If it somehow helps your backlog, you may close. I'd prefer if you didn't lock it though.

**Comment by kennethtran93** [comment]
I don't usually lock any issues unless it is really necessary, so if you comment on this again I'll still receive emails about them.
