### ISSUE TITLE
[SUPPORT]  Should security issues be posted publicly? What's the protocol?

### ISSUE THREAD

**Issue by gggirlgeek** [mrdokenny/Cookie-AutoDelete#737]
Hello @kennethtran93: and @ke-d:

Sorry to post here but I am not experienced with Github. I need to discuss a security vulnerabilty I see in Cookie-AutoDelete with the developers but don't know if it should be posted publicly. What is the protocol in this situation? I'm sure you all are aware of it because it's obvious. I just want to make sure. I also want to see how you suggest we work around it.

Thanks

**Comment by kennethtran93** [comment]
Because the extension doesn't make any network requests, security concern would most likely limited to individual machines.

Sometimes the obvious thing is overlooked, so I appreciate any feedback.

Having said that you can GPG sign your message with my public key here and post it as a reply.  I don't use it too often though.

EDIT:  GPG key upload.

**Comment by gggirlgeek** [comment]
Never done this before. I've imported the key, and created my own in  Kleopatra for Windows. I've created a notepad document and encrypted it with our keys. Do I send it to your email?

**Comment by kennethtran93** [comment]
Just paste the code here.  In reality only I have the decoding key so nobody else should be able to decode it.

That or upload to Firefox Send and paste link here. Feel free to add a one-time password to it as well and limit download to one download/one day.

**Comment by kennethtran93** [comment]
that or send the file over via Firefox Send and paste link here.

**Comment by kennethtran93** [comment]
Still waiting for the security issue...

**Comment by kennethtran93** [comment]
Closing as no response.  When you have the upload ready, just paste the link here for download.
