### ISSUE TITLE
button is red when subdomain matches whitelisted domain, should be blue

### ISSUE THREAD

**Issue by snarfed** [mrdokenny/Cookie-AutoDelete#74]
first, thanks for the whitelist subdomain support! (https://github.com/mrdokenny/Cookie-AutoDelete/issues/3#issuecomment-304912809) i love it.

minor bug report: when i'm on a subdomain that matches a whitelisted domain, the button is red, but it should be blue.

thanks in advance!

### Screenshot in which the bug can be seen

<img width="1211" alt="screen shot 2017-06-28 at 7 40 13 am" src="https://user-images.githubusercontent.com/778068/27643227-4f1511ac-5bd5-11e7-8249-f84de5c3e132.png">

### Steps for anyone to reproduce the bug

* Whitelist google.com
* Open mail.google.com
* See that the plugin button is red, not blue

### Your settings

- OS/version: Mac OS X 10.11.6
- Browser/version: Firefox 54.0
- Cookie AutoDelete version: 1.4.0

**Comment by mrdokenny** [comment]
What are your C-AD settings because `Enable Check for Subdomains` might not be enabled?

**Comment by snarfed** [comment]
thanks for the reply! it is enabled.

<img width="326" alt="screen shot 2017-06-28 at 7 53 18 am" src="https://user-images.githubusercontent.com/778068/27643787-e10621e0-5bd6-11e7-9e07-0a2dd95e7ecc.png">

**Comment by snarfed** [comment]
...and the button correctly turns blue on exact whitelisted domains, just not on subdomains.

**Comment by mrdokenny** [comment]
I am unable to reproduce this. How are you adding it through the whitelist (popup or settings page)? If you add it through the settings page, the icon state won't update until you refresh the page.

**Comment by snarfed** [comment]
argh, sorry it doesn't repro for you.

pretty much all of my whitelisted domains were added on the settings page, via import. i've both restarted firefox and reloaded page(s) since that, but this still happens.

here are my complete settings:

<img width="599" alt="screen shot 2017-06-28 at 8 06 53 am" src="https://user-images.githubusercontent.com/778068/27644597-d2959576-5bd8-11e7-9bca-7012fd0c7a33.png">

**Comment by mrdokenny** [comment]
Can you do a `Restore Default Settings` (this deletes the extension data) and add just google.com in the settings menu or the popup?

**Comment by Taurean75** [comment]
I can't reproduce it, either.

Thanks for this feature by the way. :)

**Comment by snarfed** [comment]
> Can you do a Restore Default Settings (this deletes the extension data) and add just google.com in the settings menu or the popup?

sure! done. i tried adding it both ways and reloading the subdomain pages. same thing happens.

**Comment by mrdokenny** [comment]
>Thanks for this feature by the way. :)

Your welcome. :)

@snarfed Could you check the console and see if there's any errors on page load relating to `background-webpack.js`?

**Comment by snarfed** [comment]
huh. it fixed itself. no idea what happened, but whitelisted subdomains now get the blue icon. sorry for the false alarm.

i guess i now have a related bug report or feature request, though: consider selecting the whitelisted radio button when on a whitelisted subdomain? or you could add a new radio button or UI element if you want. example:

<img width="460" alt="screen shot 2017-06-28 at 5 34 18 pm" src="https://user-images.githubusercontent.com/778068/27666392-3ae62ff6-5c28-11e7-95e7-a1761f30129e.png">

let me know if you want me to file a new issue.

**Comment by mrdokenny** [comment]
@snarfed That's the expected behavior. Since you whitelisted github.com, help.github.com will be protected (via the blue icon), BUT help.github.com is not *strictly* in the whitelist so the radio menu would default to `Clean After Tab Close`.

[Related Comment](https://github.com/mrdokenny/Cookie-AutoDelete/issues/51#issuecomment-309193764)

**Comment by mrdokenny** [comment]
This is also how it would work if you had disabled Subdomain Checking as well.

**Comment by snarfed** [comment]
@mrdokenny understood! it just seems confusing to show `Clean After Tab Close` selected when subdomain checking is on, since cookies won't actually be cleaned after the tab closed.

**Comment by mrdokenny** [comment]
That's probably because the wording before 1.4.0 was just a checkbox labeled `Add to WhiteList?` which made more sense back then.

Anyways thanks for using it and remember to close once you feel good with this issue. 😄

**Comment by snarfed** [comment]
thanks again for the responses!

it looks like i was premature in declaring the original bug fixed. i'm seeing the blue icon for some subdomains, e.g. whi.color.com when i have color.com whitelisted:

<img width="1204" alt="screen shot 2017-06-29 at 8 03 35 am" src="https://user-images.githubusercontent.com/778068/27694691-a79ae0be-5ca1-11e7-9d7c-c2290792e861.png">

...but not others, e.g console.cloud.google.com is red even though i have google.com whitelisted:

<img width="1203" alt="screen shot 2017-06-29 at 8 01 36 am" src="https://user-images.githubusercontent.com/778068/27694715-b5a85a88-5ca1-11e7-83ab-f7d5f9b6076a.png">

definitely confusing. same thing happens after shift-refresh and browser restart. let me know if you'd like me to reopen the issue, or do anything else to help debug.

**Comment by mrdokenny** [comment]
@snarfed That's how it's implemented currently. Whitelisting google.com will protect google.com, *.google.com, but not *.*.google.com. I don't think it's necessary to go further as you could whitelist cloud.google.com to get *.cloud.google.com.

**Comment by snarfed** [comment]
@mrdokenny got it, thanks for the explanation.

i definitely get that i can whitelist cloud.google.com etc, but fwiw, the current behavior definitely surprised me as a user. i expected subdomains at all levels would be whitelisted, not just first level. just fyi.

**Comment by mrdokenny** [comment]
It's a mix between of different levels of granular control. As for me, I have it turned Subdomains turned off because I like to keep the minimum amount of cookies to stay logged in. Even if I end up with a big whitelist, I know that I can export it for later.
