### ISSUE TITLE
[SUPPORT]  Can't view individual cookies? for RES/reddit

### ISSUE THREAD

**Issue by doobersn** [mrdokenny/Cookie-AutoDelete#747]
I would like to view individual cookies so I can block/allow certain things. I can view how many cookies there are on a page but cant actually see the cookies. Is there a way to do this? Thanks!

**Comment by kennethtran93** [comment]
Add the domain to either a whitelist or greylist, then uncheck 'keep all cookies' to see individual cookie names (not value - just cookie names).

**Comment by kennethtran93** [comment]
Note that you won't see 3rd party cookies for that page.

If you really need to see 3rd party cookies, consider opening Developer Tools and go to Storage tab (in Firefox) or application tab (in Chrome) to see the full list of cookies for that page.

**Comment by doobersn** [comment]
Thank you! I'm trying to figure out why Reddit Enhancment Suite doesn't work even though I've whitelisted .reddit.com. It seems like cookie auto delete has completely messed up all features for Reddit Enhancement Suite. I think it must be a third party cookie, right?

**Comment by kennethtran93** [comment]
I don't use that so I don't know. Are you using reddit.com or *.reddit.com?

**Comment by doobersn** [comment]
*.reddit.com. Reddit Enhancement Suite is a third party extension for Firefox.

**Comment by kennethtran93** [comment]
Depending on your browser, try seeing what cookies/third-party cookies are used on that page by going into Developer Tools > Storage tab  (in Firefox) or Application tab (in Chrome) to see the cookies on that page (and its relevant domain it is coming from).

Perhaps also check your localstorage setting and make sure you are keeping it as well as some sites are using that as well.

I don't think cookies originating from webextensions (not domains) (if that is allowed) are cleared at all, but I could be wrong.

**Comment by doobersn** [comment]
Thanks. Yeah, it looks like the only cookie I can see in the firefox storage tab is the one im whitelisting, so it must be some other cookie I just cant find. Ah well. Thanks for the assistance!

**Comment by kennethtran93** [comment]
If you enable cleanup log and counter, you can undo the majority of cookies that this extension removes (though before you undo take a look at each domain and cookies it removed).  Maybe that will help.

This may help - https://www.reddit.com/r/Enhancement/comments/m4udf/where_does_res_store_its_local_data/.
I am inclined to believe RES uses localstorage, so you'll need to check the 'keep localstorage' box on whitelist or uncheck 'clean localstorage' in CAD settings.
We still have yet to implement the other storage cleanups (indexedDB, cache, etc) so those aren't cleaned by this extension yet.

Alternately this? https://www.reddit.com/r/RESissues/comments/gnsqfb/res_no_longer_showing_up_after_firefox_7601_update/

**Comment by doobersn** [comment]
Thank you so much for looking into this more! I do in fact have 'keep localstorage' checked. I see 'localstorage cleanup' but that is not enabled. So i'm not sure if it's a different option I might be missing. I have all the default settings enabled. 
![1](https://user-images.githubusercontent.com/28417880/82980009-6aa0aa80-9fb6-11ea-92c1-8aec06778dda.JPG)
![2](https://user-images.githubusercontent.com/28417880/82980011-6b394100-9fb6-11ea-9615-e301c3b229f3.JPG)

**Comment by kennethtran93** [comment]
I'm unsure on how to assist in your case, unless you feel like sending over a debug mode log that you'll need to copy-paste into a file and send it over, starting from when the webpage worked fine until the cookie cleanup - whether manual or tab closed/domain changed.  As I don't use RES, it is hard for me to say which cookies are required to stay.  Maybe other RES users can help if you post on their subreddit?

Since you have cleanup logs enabled, you can see what cookies are removed through the Cleanup Log section - just expand the entries as needed and see what cookies (and its names) are being removed.  Note down which site/cookie you think may have an impact, then through trial and error whitelist them accordingly.

**Comment by kennethtran93** [comment]
Some final support through Reddit:  https://www.reddit.com/r/Enhancement/comments/gv9uwt/firefox_770_update_appears_to_have_removed_many/

For future support, see if the nice community over at their subreddit (r/Enhancement / r/RESissues) will be more helpful.  It'll be the collaborative thought of many vs the one lone person :D
