### ISSUE TITLE
Local storage still present in Firefox [SUPPORT]  

### ISSUE THREAD

**Issue by CaptainFrosty** [mrdokenny/Cookie-AutoDelete#751]
**Please describe what you need support with.**

Local storage does not appear to be cleaned for me in Firefox Beta 77.0. The site data table in Firefox settings shows 0 cookies for a website, but still shows a size in the Storage column, and the data is still present in the `\Users\*\AppData\Roaming\Mozilla\Firefox\Profiles\*\storage\default` folder of the Firefox profile. This is for sites that are not whitelisted at all. The Local Storage cleanup option is enabled.

**Describe the solution you'd like**

Figure out why I'm not automatically cleaning local storage and only the cookies themselves.

**Additional context**

**Comment by kennethtran93** [comment]
I'd link a relevant issue but it seems to be deleted...so now referencing it through an archive. 

https://web.archive.org/web/20200124135657/https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/512#issuecomment-477875623

**Comment by kennethtran93** [comment]
In short, that column is not just localstorage data but indexedDB at the very least.

**Comment by CaptainFrosty** [comment]
So then these databases are yet another separate web dumping site and can't be cleared by CAD?

**Comment by kennethtran93** [comment]
Per https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/171#issuecomment-621023828, indexedDB cleaning by domain will be implemented starting Firefox 77.

For this webextension, we only clean data that is clearable by hostname, otherwise if we clean other types of data, it is usually an all or nothing scenario, which may affect other sites.

**Comment by CaptainFrosty** [comment]
OK, thanks for the information.
