### ISSUE TITLE
[FEATURE REQUEST]  Make the new context menus optional, if it's easy.

### ISSUE THREAD

**Issue by wrkq** [mrdokenny/Cookie-AutoDelete#766]
**Is your feature request related to a problem? Please describe.**

Hello. You asked - over a week ago, admittedly - to take a look at the dev build including the new grand feature set that was merged as #753 .
It solved my issue regarding per-container cleanup, as far as I can see, thanks once agian.

But it also includes multiple other brand new features, the biggest of which is a CAD's own right click submenu to offer access to CAD features in popup windows lacking the toolbar.

This is a very valid need, but I personally don't need it (I identify the domains to gray/white via the cleanup log after an action such as popup-driven log-in fails) and the additional menu entry just gets in the way - it's a largeish multi-level submenu with a bright icon calling out for attention in a black-themed menu.
I generally do all I can to cut the right click menu to minimum, disable it for all other extensions (like uBO) and hide some Firefox's standard entries with userChrome.css.

**Describe the solution you'd like**

if it's as easy as one more settings panel checkbox and a a condition check in the place where the menu's registered with FIrefox today, I would very much appreciate if you'd make the menu toggleable (most probably on by default?).

**Describe alternatives you've considered**

It's very much a "if it's super easy and if you have time" kind of request.

If it's more complex, or would cause problems, I'll try to find a way to hide it with userChrome.css (hopefully the menu elements ID is tied to some static or semi-static extension ID) or worst case just clench teeth and live with it.

**Additional context**

I apologize for stirring a fuss about such an objectively small problem.
Best regards...

**Comment by kennethtran93** [comment]
Good idea. I haven't thought of that to be an option at all.

Will see what I can do. Better to get this one done first before it is even officially released.

**Comment by kennethtran93** [comment]
Build is in #767 if you are interesting in testing it again.

**Comment by wrkq** [comment]
... wow.
Thanks a ton, that was super quick.

The toggle seems to work with no issues. the checkbox for autoclean stays in sync and the actions still work after adding/removing the menu a few times.
(Really good idea with these small popups like "Added to greylist for container 3" to reassure the user the action has been executed, btw.)

I think it would be a good idea to make the menu on by default on new installations for ease of discoverability and for the "it is there if you need it" factor.
Weirdos like me will find the disable switch quickly. :)

Finally - as I'll be honest I didn't really pay attention to all the features in the menu before - might I suggest a bit of a rephrasing for the entries in "Add Domain/Expression" submenu?

Maybe something like
"Add current page's domain (example.com) \>"
"Add current page's domain and all subdomains (*.example.com) \>"
instead of the current "of selected page" phrasing?

If I understand correctly the menu text must be static, but using example.com literally should be obvious enough.

Thanks again!

**Comment by kennethtran93** [comment]
> (Really good idea with these small popups like "Added to greylist for container 3" to reassure the user the action has been executed, btw.)

Thanks.  This was in line with having notifications shown when doing manual cleaning of cookies and localstorage.

> I think it would be a good idea to make the menu on by default on new installations for ease of discoverability and for the "it is there if you need it" factor.
> Weirdos like me will find the disable switch quickly. :)

Done.

> Finally - as I'll be honest I didn't really pay attention to all the features in the menu before - might I suggest a bit of a rephrasing for the entries in "Add Domain/Expression" submenu?
> 
> Maybe something like
> "Add current page's domain (example.com) >"
> "Add current page's domain and all subdomains (*.example.com) >"
> instead of the current "of selected page" phrasing?
> 
> If I understand correctly the menu text must be static, but using example.com literally should be obvious enough.

That might help. Probably next version.
