### ISSUE TITLE
Problem Deleting cookies of the Synchronizing with account Chrome

### ISSUE THREAD

**Issue by ajalalex** [mrdokenny/Cookie-AutoDelete#770]
- OS/version: Win 10 Pro
- Browser/version: Latest Chrome
- Cookie AutoDelete version: New version 06.15.2020

Hi there!
When enable the option "Auto Clean Cookies" it delete the major cookies of the synchronizing on chrome with account on Google during the open browser.

So its a problem!!
![sync problem](https://user-images.githubusercontent.com/20431476/84672943-7a4d4800-aeff-11ea-8bd5-9bbe84a16ae3.JPG)

**Comment by kennethtran93** [comment]
I'm not quite getting the meaning there as the English is slightly broken up. 

Sounds like you'll need to disable autocleaning, then sync up your cookies first, then re-enable it. 

You may also need to whitelist google (either `google.com` or `*.google.com`) if it is happening after sync. 

Ultimately the control is in your hands to configure the lists properly.

**Comment by kennethtran93** [comment]
>     * Cookie AutoDelete version: New version 06.15.2020

Also note that the main branch on the GitHub Repo may be broken at times.  The most stable versions are usually what we push out to GitHub releases (in this case 20200614 / 3.4.0-alpha).  If you're building it yourself you'll always have the date and time that you build it yourself in the zip file.

**Comment by kennethtran93** [comment]
Let me know if there's any other support you require.
