### ISSUE TITLE
Undo cookies fails to set a cookie starting with __Secure-

### ISSUE THREAD

**Issue by kennethtran93** [mrdokenny/Cookie-AutoDelete#772]
Some cookies which I **get back** , does have this error: **Failed to parse or set a cookie named:  __Secure-3PSID**, even on the latest version, and dev build as well. 

_Originally posted by @Marek33 in https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/768#issuecomment-644317666_

Additional Background
Has to do with this:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#Cookie_prefixes

And for some reason the code didn't include `domain` or `secure` attributes when restoring cookies.
Because we didn't set the `secure` parameter to `true`, by MDN's doc, it is set to `false` by default.

quick bugfix will be patched shortly.

**Comment by kennethtran93** [comment]
Try build in #773.  As long as you can find one domain that uses the cookie prefix __Secure-.

**Comment by Marek33** [comment]
I did, tried the latest version, but it seems, that I can't reproduce it anymore, though, I will try to do it later today.

However, when I want to reverse the cookies, which were deleted, in the previous session, it doesn't show anything, and cookies are still there (they can be still deleted) or I just get this error: **Failed to parse or set a cookie named __Secure-valid-with-secure**.

Only the Clear Logs work for deleting them, but then I lose the statistics, which I like.

BTW: In older version 3.0.2, I have these two errors, which I have no idea, what exactly they mean, and I have no idea, if it's still in the newer ones, since I was not able to reproduce them: **Invalid cookie store id “1”** _and_ **Failed to parse or set a cookie named Secure-OSID.**

**Comment by kennethtran93** [comment]
> However, when I want to reverse the cookies, which were deleted, in the previous session, it doesn't show anything, and cookies are still there (they can be still deleted)

We don't have any notification in regards to restored cookies at this time.

>  or I just get this error: **Failed to parse or set a cookie named __Secure-valid-with-secure**.

In versions up to current 3.3.1, we forgot to include 'secure' attributes with re-creating the cookie, thus those cookies may fail because that attribute was missing / set to false by default.


> Only the Clear Logs work for deleting them, but then I lose the statistics, which I like.

~~I'm not sure I understand the current context here... If you don't want to restore it then just keep it in the logs as is?~~
EDIT:  If for some reason the restore failed at one point, the cookies processed up to that point have been restored, and the cookie with error and the rest haven't been restored.  Rather than clearing the entry (in which the already deleted cookies have yet to be restored), we opted to keep the entire entry for now.  This means that multiple clicks of it may restore duplicate cookies and fail at that same cookie.  What we do in cookie restore is we set the promise via `browser.cookies.set` (but not execute it yet) for all cookie stores/clean reasons, then execute all the promises at the same time with `Promise.all` which will quit upon the first error caught.

> BTW: In older version 3.0.2, I have these two errors, which I have no idea, what exactly they mean, and I have no idea, if it's still in the newer ones, since I was not able to reproduce them: **Invalid cookie store id “1”**

This may have happened if CAD doesn't have permission for Private Browsing/Incognito in Chrome, but `browser.cookies.getAllCookieStores` returned `1` (Which is generally Chrome's Private Browsing cookie store if you had recently used Incognito mode and there were recently active cookies in there).  Based on the code in 3.0.2 (and may still be the case today), it looks like we may have forgotten to scrub cookies from Incognito mode in Chrome so that they cannot be restored or viewed through the logs.

>  _and_ **Failed to parse or set a cookie named Secure-OSID.**

This falls in line with the current bug, most likely it included underscores in the cookie name and we forgot to include `secure` attribute when restoring cookie.

**Comment by kennethtran93** [comment]
I've added a commit to scrub cookieStoreId 1 from cleanup logs as we most likely cannot restore them anyway.

**Comment by Marek33** [comment]
I mean, that if some cookies, can't be reversed, it should show some kind of error message, but it doesn't. For example, of the Firefox platform, it always reverses every cookie, but not for the Chromium.

I understand, and since the issue is closed, it's fixed then?

Is it possible to have the logs cleared, without clearing the statistics?

Unfortunately, I don't remember, if I had CAD enabled there, but I probably don't have it enabled in the incognito mode.

I see and thanks for all the info!

BTW: Before you release the 3.4.0, please check the **close notifications from this tab**, which is on Chromium platforms, and it permanently disables, all notifications from the CAD. I tested it, on the Brave with the 3.3.1 version.

**Comment by kennethtran93** [comment]
> I mean, that if some cookies, can't be reversed, it should show some kind of error message, but it doesn't. For example, of the Firefox platform, it always reverses every cookie, but not for the Chromium.

It does, as long as `browser.cookies.set` throws an error / rejects a Promise, then we show a notification.  This part of the code was already part of 3.0.2, unsure how far back it goes.

> 
> I understand, and since the issue is closed, it's fixed then?

Please include reply quotes otherwise I won't fully understand this question as it appeared in its own paragraph.  Presuming you meant this issue of secure cookies - the code has been added in and will be included in 3.4.0.  As far as testing...I haven't encountered any myself.  Then again I rarely need to undo any cookie removal on my profile.

> Is it possible to have the logs cleared, without clearing the statistics?

You'll need to clarify - what statistics are you talking about here?


> Unfortunately, I don't remember, if I had CAD enabled there, but I probably don't have it enabled in the incognito mode.

Most likely the problem when trying to restore cookies with cookieStoreId 1 then...I've added a patch to scrub those from the cleanup logs.


> BTW: Before you release the 3.4.0, please check the **close notifications from this tab**, which is on Chromium platforms, and it permanently disables, all notifications from the CAD. I tested it, on the Brave with the 3.3.1 version.

Can you post a screenshot of what you are referring to here?  I use firefox for the most part and chrome occasionally for testing and whatnot.

We call `browser.notifications.create`, so it is up to the browser to display it.  Outside of that we have no control of whether or not it is displayed.

**Comment by Marek33** [comment]
> It does, as long as `browser.cookies.set` throws an error / rejects a Promise, then we show a notification. This part of the code was already part of 3.0.2, unsure how far back it goes.

For me, it sometimes, doesn't show it.

> Please include reply quotes otherwise I won't fully understand this question as it appeared in its own paragraph. Presuming you meant this issue of secure cookies - the code has been added in and will be included in 3.4.0. As far as testing...I haven't encountered any myself. Then again I rarely need to undo any cookie removal on my profile.

Alright, I will.

> You'll need to clarify - what statistics are you talking about here?

The number of all deleted cookies.

> Most likely the problem when trying to restore cookies with cookieStoreId 1 then...I've added a patch to scrub those from the cleanup logs.

I understand, and that is fixed then?

> Can you post a screenshot of what you are referring to here? I use firefox for the most part and chrome occasionally for testing and whatnot.

Yes, here is it: ![Chromium](https://user-images.githubusercontent.com/19204886/84833725-3dcd3980-b030-11ea-8fc7-80794735d208.jpg)

> We call `browser.notifications.create`, so it is up to the browser to display it. Outside of that we have no control of whether or not it is displayed.

I see, so it's a Chromium problem.

**Comment by kennethtran93** [comment]
> > It does, as long as `browser.cookies.set` throws an error / rejects a Promise, then we show a notification. This part of the code was already part of 3.0.2, unsure how far back it goes.
> 
> For me, it sometimes, doesn't show it.

Then it should've been fine unless the entry wasn't cleared for unknown reasons - at least now there's logging involved so you can see.

> > You'll need to clarify - what statistics are you talking about here?
> 
> The number of all deleted cookies.

If you head to the welcome page, you may be able to see the total cookies removed overall.  I don't think we decrement those count at this time but I could be wrong.

> > Most likely the problem when trying to restore cookies with cookieStoreId 1 then...I've added a patch to scrub those from the cleanup logs.
> 
> I understand, and that is fixed then?

Should be when I release the next version.

> > Can you post a screenshot of what you are referring to here? I use firefox for the most part and chrome occasionally for testing and whatnot.
> 
> Yes, here is it: ![Chromium](https://user-images.githubusercontent.com/19204886/84833725-3dcd3980-b030-11ea-8fc7-80794735d208.jpg)
> 
> > We call `browser.notifications.create`, so it is up to the browser to display it. Outside of that we have no control of whether or not it is displayed.
> 
> I see, so it's a Chromium problem.

Yeah this is a Chromium browser feature to which we have no control over.  If you block our notifications, so be it.  It's not a bug on either end.  I think they lump the website notifications and extension notification design into one, such that the setting cog will show to allow you to disable notification for that site, app, or extension depending on what was shown at that time.

**Comment by Marek33** [comment]
> > > It does, as long as `browser.cookies.set` throws an error / rejects a Promise, then we show a notification. This part of the code was already part of 3.0.2, unsure how far back it goes.
> > 
> > 
> > For me, it sometimes, doesn't show it.
> 
> Then it should've been fine unless the entry wasn't cleared for unknown reasons - at least now there's logging involved so you can see.

I understand, and thanks!

> > > You'll need to clarify - what statistics are you talking about here?
> > 
> > 
> > The number of all deleted cookies.
> 
> If you head to the welcome page, you may be able to see the total cookies removed overall. I don't think we decrement those count at this time but I could be wrong.

When I click on clearing the cookie entries, in the Cleanup Log, then it gets reset to 0, which I think shouldn't be.

> > > Most likely the problem when trying to restore cookies with cookieStoreId 1 then...I've added a patch to scrub those from the cleanup logs.
> > 
> > 
> > I understand, and that is fixed then?
> 
> Should be when I release the next version.

Thanks!

> > > Can you post a screenshot of what you are referring to here? I use firefox for the most part and chrome occasionally for testing and whatnot.
> > 
> > 
> > Yes, here is it: ![Chromium](https://user-images.githubusercontent.com/19204886/84833725-3dcd3980-b030-11ea-8fc7-80794735d208.jpg)
> > > We call `browser.notifications.create`, so it is up to the browser to display it. Outside of that we have no control of whether or not it is displayed.
> > 
> > 
> > I see, so it's a Chromium problem.
> 
> Yeah this is a Chromium browser feature to which we have no control over. If you block our notifications, so be it. It's not a bug on either end. I think they lump the website notifications and extension notification design into one, such that the setting cog will show to allow you to disable notification for that site, app, or extension depending on what was shown at that time.

I see, and I did it by mistake, on the Iridium, but when I use the new version, I don't have that problem, since I'm using the unpacked version.

**Comment by kennethtran93** [comment]
> > > The number of all deleted cookies.
> > 
> > 
> > If you head to the welcome page, you may be able to see the total cookies removed overall. I don't think we decrement those count at this time but I could be wrong.
> 
> When I click on clearing the cookie entries, in the Cleanup Log, then it gets reset to 0, which I think shouldn't be.

Open a new issue/feature request for this.  Currently does seem that way when I look at the backend.

> 
> I see, and I did it by mistake, on the Iridium, but when I use the new version, I don't have that problem, since I'm using the unpacked version.

From what I can understand, the official version is assigned its extension ID through chrome webstore, while the unpacked version uses a locally randomized extension ID, thus why you would be able to do that I think...Probably the unpacked version follows a separate logic when it comes down to these things...maybe.

**Comment by Marek33** [comment]
> > > > The number of all deleted cookies.
> > > 
> > > 
> > > If you head to the welcome page, you may be able to see the total cookies removed overall. I don't think we decrement those count at this time but I could be wrong.
> > 
> > 
> > When I click on clearing the cookie entries, in the Cleanup Log, then it gets reset to 0, which I think shouldn't be.
> 
> Open a new issue/feature request for this. Currently does seem that way when I look at the backend.

Yes, I will since I just did that, in Sandboxie on the Firefox.

> > I see, and I did it by mistake, on the Iridium, but when I use the new version, I don't have that problem, since I'm using the unpacked version.
> 
> From what I can understand, the official version is assigned its extension ID through chrome webstore, while the unpacked version uses a locally randomized extension ID, thus why you would be able to do that I think...Probably the unpacked version follows a separate logic when it comes down to these things...maybe.

No, it's because I can't update the extension since Iridium/Ungoogled block that connection, so there is nothing ported from the older versions. I will copy the data (for statistics), but I will not change any settings, so I wouldn't break it again.
