### ISSUE TITLE
Clearing Logs delete a number of all deleted cookies.

### ISSUE THREAD

**Issue by Marek33** [mrdokenny/Cookie-AutoDelete#777]
**Describe the bug**

Clearing Logs, shouldn't delete the number of cookies, which the Cookie AutoDelete has deleted.

**To Reproduce**

1. Go to 'Open settings'
2. Click on 'Cleanup Log'
3. Click on 'Clearing Logs'
4. See that the total amount of deleted cookies is 0, instead of the number, of deleted cookies, which you had before.

**Expected behavior**

Clicking on Cleanup Log, and then on Clearing Logs, should remove the logs, not the total amount of deleted cookies.

**Screenshots**

 - OS: [Windows 7 Pro]
 - Browser Info: [Firefox 77.0.1]
 - CookieAutoDelete Version [3.3.1]

**Additional context**

I don't know why there is the **untested bug/issue**, since it's a very easily reproducible bug.

**Comment by kennethtran93** [comment]
Probably because not too many people visit the welcome page as it is mostly release notes and whatnot.

I'll fix the reset of cookie count, and add in a button or something to reset it from that page if users decide so.

**Comment by Marek33** [comment]
I think that most people, just have a mindset where they just install it, and then don't much care for it.

That's good to hear, and I hope that it will give some kind of dialog, so it wouldn't be deleted by a mistake.
