### ISSUE TITLE
[BUG]  Notifications showing from manual cleaning, despite being disabled. 

### ISSUE THREAD

**Issue by jtheletter** [mrdokenny/Cookie-AutoDelete#779]
This just began today. Haven't seen these notifications for years. 

Notifications are shown as being disabled when I click on the extension button in my app window (big red "notifications disabled") and under the extension settings ("show notification after cookie cleanup" is unticked). 

However, as of today, if I click the extension button in my app window and then click either "clear cookies" or "clear storage", I get a MacOS notification from this extension reporting the outcome. 

Please make it stop, thank you. 

* Cookie AutoDelete version 3.4.0
* Brave version 1.10.93
* MacOS version 10.15.5

**Comment by kennethtran93** [comment]
The manual clean notifications was previously requested as it previously didn't have one at all. 

The current notification option was meant only for automatic cleaning notifications.

I'll have to make another option to toggle manual notifications

**Comment by kennethtran93** [comment]
I've updated the doc to reflect this https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/Documentation#show-notification-after-cookie-cleanup

**Comment by kennethtran93** [comment]
And the Request in question was #386

**Comment by jtheletter** [comment]
Thank you for explaining how this came to be. I'd still call it a bug, as the interface doesn't indicate anywhere that the disabling of notifications is now limited to automatic actions. Most users likely don't take the time to look at issue reports to find explanations. Please reverse this change or add a means to opt out, thanks.

**Comment by ghost** [comment]
I also feel like this change either needs to be reversed or a means to opt-out needs to be added ASAP. It's been driving me crazy for the past week trying to figure out how I can turn off this notification and avoid the dreaded *ding* chime that accompanies it.

**Comment by kennethtran93** [comment]
I wonder why you guys are doing manual clean instead of either changing the domain or on tab close.  Curious.  Kinda bypasses the whole 'Cookie **Auto**Delete'

**Comment by Cromemco** [comment]
If there's no reason to manually clean, then there would be no reason to have such a function at all. It's a little easier to manually clean than to change domains. Sometimes, people may even have multiple tabs to the same domain open, in which case, changing domain or closing one tab accomplishes nothing. It would be even easier if there were keyboard shortcuts to activate manual cleaning for cookies and localstorage. Having to click through the dropdown menu is a bit of a bother.

**Comment by kennethtran93** [comment]
I'd thought that manual clean would only be done *occasionally* as that bypasses the keep list completely.

I think you're asking for a list implementation that would remove cookies if it was created on a certain domain.

There's already a request for keyboard shortcuts if you want to vote that up.  Alternatively there's the Right-Click menu as well.

**Comment by ghost** [comment]
I'm not really sure what you're getting at. Speaking for myself, I'm not "asking for a list implementation that would remove cookies if it was created on a certain domain." I'm just requesting that notifications don't show up when I've actively disabled notifications. I honestly can't imagine why anyone would have ever requested that you "show the notification when manually clearing cookies via the toolbar icon, even if the notification is disabled in the settings" or why that would be considered an enhancement rather than a bug.

**Comment by jtheletter** [comment]
Here's how I use this extension: 

* I want it automatically to remove all cookies/storage (I don't see why these are separated) when I leave any site (when I close the last for any domain) by default. This, as I understand it, protects me from tracking and browser bloat from whatever random sites I might visit. 
* For sites where I log in and expect to stay logged in, I greylist them. If greylisting fails, I whitelist them. That way, I don't need continually to re-authenticate on my regular-usage sites.
* When sites where I log in produce bugs, I manually clear their storage/cookies (the separation of cookies and storage here is annoying, I wish I could do it in one step, not two). 
* Or when I developing a website, I commonly will manually clear storage/cookies.

My manual-clearing due to bugs happens most often on Twitter. Several times a week I visit Twitter and instead of my feed, it shows a "something went wrong, please try again" warning. I clear cookies/storage, re-auth, and it's fixed. 

I don't need or want my web browser to generate a macOS notification for this manual action, because I can see already in the extension tool icon in the browser toolbar and in the extension tool's dropdown that the number of cookies changes from X number to zero. You already show me this in two places. Why add it to a third place, a place that's not even specific to this extension?

**Comment by kennethtran93** [comment]
> I'm not really sure what you're getting at. Speaking for myself, I'm not "asking for a list implementation that would remove cookies if it was created on a certain domain." I'm just requesting that notifications don't show up when I've actively disabled notifications. I honestly can't imagine why anyone would have ever requested that you "show the notification when manually clearing cookies via the toolbar icon, even if the notification is disabled in the settings" or why that would be considered an enhancement rather than a bug.

Because sometimes (in the popup) even if the green transition was showing, it wasn't working properly (especially in the case of localstorage where it always turned green without checking if it was actually cleared).  Also the cookie count in popup wasn't there when this request was made.

Note that within the popup and right-click, I did add a warning that says that those manual actions will bypass the settings.

**Comment by kennethtran93** [comment]
> * I want it automatically to remove all cookies/storage (I don't see why these are separated) when I leave any site (when I close the last for any domain) by default. This, as I understand it, protects me from tracking and browser bloat from whatever random sites I might visit.

Because some people may want to keep certain data while removing the rest.

>     * When sites where I log in produce bugs, I manually clear their storage/cookies (the separation of cookies and storage here is annoying, I wish I could do it in one step, not two).

Those will stay separate for now.  If the site you're logged into isn't part of any lists, you can use `clean, include open tabs`, as long as all the other domains are already in a list.

>     * Or when I developing a website, I commonly will manually clear storage/cookies.

As above, you can use `clean, include open tabs`, as long as all the other domains are already in a list.

> My manual-clearing due to bugs happens most often on Twitter. Several times a week I visit Twitter and instead of my feed, it shows a "something went wrong, please try again" warning. I clear cookies/storage, re-auth, and it's fixed.



> 
> I don't need or want my web browser to generate a macOS notification for this manual action, because I can see already in the extension tool icon in the browser toolbar and in the extension tool's dropdown that the number of cookies changes from X number to zero. You already show me this in two places. Why add it to a third place, a place that's not even specific to this extension?

As mentioned previously the cookie count within the popup wasn't there when the request was made.  Also the badge count could be disabled in settings.

**Comment by kennethtran93** [comment]
I'll look into it later on but not a big priority at this time. This will involve rewriting the function again due to the fact that manual clean from the right-click also calls that function which has the notification afterwards.

My main priority is the new cleanup by host data that was recently (or will be) released on Firefox.

**Comment by Cromemco** [comment]
If somebody chooses to manually clean, it's pretty clear that it overrides the whitelist, so a warning isn't necessary. We wouldn't be manually cleaning if we didn't want to clean that particular domain.

A keyboard shortcut like cmd-shift-c to clean would be so much more convenient and far faster to use. Nested menus always require reading and precise mouse pointer positioning to open the main menu, open the submenu then select the option, especially as the current options are not discrete buttons. Good human interface practice is to avoid such menus whenever possible.

**Comment by jtheletter** [comment]
> If the site you're logged into isn't part of any lists, you can use clean, include open tabs, as long as all the other domains are already in a list.

I thought I said this, but to be clear, this use-case is to clear cookies/storage on sites that go buggy where I log in (all of which I greylist or whitelist). 

> As above, you can use clean, include open tabs, as long as all the other domains are already in a list.

I never use "clean, include open tabs". When I'm manually cleaning, I only want it to affect the current tab.

**Comment by ghost** [comment]
Would it be possible for us to revert to the previous version of Cookie-AutoDelete? I genuinely hate the current iteration and I was 100% happy with the former version?

**Comment by kennethtran93** [comment]
> Would it be possible for us to revert to the previous version of Cookie-AutoDelete? I genuinely hate the current iteration and I was 100% happy with the former version?

The older releases are available through GitHub Releases, but no support will be given for those at this point.  You'll also miss out on future updates including cleaning cache, indexedDB, plugin data, and service workers, as well as committed code for purging expired cookies.

**Comment by kennethtran93** [comment]
PR #798 now has an option for manual notifications.  Only issue is if it was toggled from right-click context menus and this was disabled then there's nothing that shows if anything was done, but that's up to the user I guess.
