### ISSUE TITLE
[SUPPORT]  Youtube cookies not deleted

### ISSUE THREAD

**Issue by Mordicus** [mrdokenny/Cookie-AutoDelete#786]
**Please describe what you need support with.**

I am using Cookie Autodelete 3.4.0 with Yandex Browser (Chrome) v20.6.
Autodelete seems to work properly, excepted it does not delete Youtube.com cookies even when all related tabs are closed.

**Describe the solution you'd like**

I did not set any special permission for Youtube, why cookies are not deleted? How to deleted them?
Next, Yandex Browser often shows me that there are not only cookie but also "service workers" from Youtube AND other sites which are not deleted. Why and how to clean them all?

Thank you!

**Additional context**

**Comment by kennethtran93** [comment]
> **Please describe what you need support with.**
> 
> I am using Cookie Autodelete 3.4.0 with Yandex Browser (Chrome) v20.6.
> Autodelete seems to work properly, excepted it does not delete Youtube.com cookies even when all related tabs are closed.
> 
> **Describe the solution you'd like**
> 
> I did not set any special permission for Youtube, why cookies are not deleted? How to deleted them?
> Next, Yandex Browser often shows me that there are not only cookie but also "service workers" from Youtube AND other sites which are not deleted. Why and how to clean them all?
> 
> Thank you!

As that browser isn't officially supported, only basic support will be given.
1. What cookies from youtube.com remains and where/how did you locate them?
2. Youtube.com, in addition to cookies, does use other site data including localstorage, sessionstorage, indexedDB, cache, service workers.  Note that localstorage cleaning must be enabled in CAD Settings.
   - CAD can only clean cookies, localstorage and sessionstorage at this time.  There are plans later on to include indexedDB, cache, and service workers to clean by host.  Cleaning other site data can only be implemented once the WebExtension API for cleaning those site data by host is implemented.
   - To clean other site data that we haven't implemented yet, you'll need to do it manually for now.  If you're not picky on keeping any site data, you can use Chrome's Clean data function to remove site data based on time/days.
3. Login information is kept through `accounts.google.com`, so if you had whitelisted google but not youtube, you'll most likely be re-logged in again upon future visits.  Of course if you do remove cookies from accounts.google.com then you'll most likely also lose login status from Gmail and whatnot.

**Comment by Mordicus** [comment]
Hi! Thanks for the reply and sorry for my late reaction.

_What cookies from youtube.com remains and where/how did you locate them?_
In Yandex Browser, cookies seem to be located in browser://settings/siteData

AutoDelete does delete many cookies, but some are not, like Youtube cookied, always present.
www.youtube.com database, service workers are there
Cookies from Youtube.com are: PREF, VISITOR INFO1 LIVE, YSC.  

_Note that local storage cleaning must be enabled in CAD Settings:_ 
it's done, but several cookies are not deleted, not only Youtube, but cookies from google.com as well (I did not set any exception for Google/Youtube services).
Login information is kept through accounts.google.com: ok I will check this too, but I do not remember having set any permission for Youtube & Google.

**Comment by kennethtran93** [comment]
Did you refresh the sitedata page after CAD performed its cleanups?  It works for me.

Have a look at a brief gif showcasing the removal of cookies and localstorage from Google Chrome Dev.
![Peek 2020-07-02 17-33](https://user-images.githubusercontent.com/6724477/86420156-8e789f80-bc8a-11ea-8d33-3cb0f76324fe.gif)



>  [www.youtube.com](http://www.youtube.com) database, service workers are there

At this point CAD does not clean those yet as we were waiting for Firefox's api to allow cleaning by host/domain.  Those cleanups will be implemented in the near future.

I'm not sure about your browser at this time - you'll have to do some digging around yourself to see why it may/may not be removed.  This is primarily because the maintainers of your browser may have tweaked the WebExtensions API, thus the primary reason why we only give official support to Google Chrome browser and not its variants excluding Microsoft Edge Chromium.

**Comment by Mordicus** [comment]
Ok, I've done some more testing, I found that the issue was not AutoDelete extension but my Yandex Profile (Chrome) was corrupted. I created a new profile, re-sync and reinstalled the extensions including Autodelete cookie, and now Youtube & Google cookies are properly deleted, cleaned!
Sorry for giving you some hard work and thank you for the kind support!
Best regards.

**Comment by kennethtran93** [comment]
Awesome.  As the extension was working fine that would've been one of my next recommendations.
