### ISSUE TITLE
[SUPPORT]  RESILIENT/RESISTANT Cookies

### ISSUE THREAD

**Issue by rastamanf1** [mrdokenny/Cookie-AutoDelete#787]
**Please describe what you need support with.**

_Hello,_

I would just like to ask, how **Cookie AutoDelete** copes with the **(virtually) 'immortal' _Cookie SPIES_**, such as [Zombie cookies](https://en.wikipedia.org/wiki/Zombie_cookie), [Supercookies](https://en.wikipedia.org/wiki/HTTP_cookie#Supercookie), [Evercookies](https://en.wikipedia.org/wiki/Evercookie)...

_THANKS._

**Describe the solution you'd like**

An answer.

**Additional context**

Just curious.

**Comment by kennethtran93** [comment]
Long story short...we don't.  We can only rely on the [WebExtension APIs that are available to us](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API).  We rely on the browser returning the cookies to us through [`browser.cookies.getAll`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/getAll) and match it with the lists that users customize to determine whether or not we keep that cookie or not based on its domain/url and cookie name.
  - For auto cleanups, we query for all cookies from given cookie store id (Firefox container).  Chrome uses '0' for regular browsing and '1' for incognito.
---
To shed a deeper light from the list given from wiki of zombie cookies:
 -  Standard HTTP cookies
    - as mentioned above.
 -  Storing cookies in and reading out web history
    - we don't deal with any history
 -  Storing cookies in HTTP ETags
    - This is working with the cache, and since cleaning by host was recently implemented through WebExtension API (at least on Firefox (Chrome supposedly had it long before)), getting this implemented through CAD is in progress.
 -  Internet Explorer userData storage (starting IE9, userData is no longer supported)
    - Don't think this extension installs in IE, so this is irrelevant.
 -  HTML5 Session Storage
    - We only clean this if it was manually triggered while that domain/tab is still open as the browser is supposed to clear this after the session.
 -  HTML5 Local Storage
    - If setting in CAD is enabled for localstorage, then we'll clean it by hostname unless it was configured to be kept for that domain.
 -  HTML5 Global Storage
    - Initial research says this is just localstorage and sessionstorage grouped together.
    - With that said, we simply rely on [`browser.browsingData.removeLocalStorage`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browsingData/removeLocalStorage) through our automatic cleaning.
 -  HTML5 Database Storage via SQLite
    - I believe this is indexedDB through the browser.  This was also implemented to be able to clean by host though WebExtensio API recently, so implementation through CAD is in progress.
 -  Storing cookies in RGB values of auto-generated, force-cached PNGs using HTML5 Canvas tag to read pixels (cookies) back out
    - Going to group this with the HTTP ETags response above as it seems to relate to cache.
 -  Local shared objects (Flash cookies)
 -  Silverlight Isolated Storage
    - Don't think we can do anything about it as it isn't exposed through WebExtension API for cleaning, unless it is secretly grouped into [`browser.browsingData.removePluginData`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browsingData/removePluginData), and I'm not sure at this point if it is cleanable by host or not.
 -  Cookie syncing scripts that function as a cache cookie and respawn the MUID cookie[5]
    - This is split into two parts - cookies and cache.  Both have been responded to above respectively.
 -  TCP Fast Open
 -  TLS's Session ID
    - I think these two are diving into OS-related functions as well as browser functions that haven't been exposed through WebExtension API yet for cleaning.
---
From the wiki of SuperCookies:

> A supercookie is a cookie with an origin of a top-level domain (such as .com) or a public suffix (such as .co.uk). Ordinary cookies, by contrast, have an origin of a specific domain name, such as example.com.
> 
> Supercookies can be a potential security concern and are therefore often blocked by web browsers. If unblocked by the browser, an attacker in control of a malicious website could set a supercookie and potentially disrupt or impersonate legitimate user requests to another website that shares the same top-level domain or public suffix as the malicious website. For example, a supercookie with an origin of .com, could maliciously affect a request made to example.com, even if the cookie did not originate from example.com. This can be used to fake logins or change user information. 

To that effect we just rely on the browser returning the cookies based on the parameters given, either by hostname or cookie store id.  If those cookies are returned, they will most likely not match any of the expressions customized by the user (unless they did manually set `.com` as an expression on browser restart or keep forever...)

---
As for EverCookie, I believe the answer was already given through the list of zombie cookies above.

**Comment by rastamanf1** [comment]
_**@kennethtran93**_ 

**THANK YOU very much** for your elaborative and comprehensive explanation!

Well, so even after **CAD's intervention** there may still reside some **harmful content** in the PC? Right? Actually, is there a way how to get rid of all of it? (It would probably need to be done/prevented on the browser['s core] level, right?)

_THANKS, again._

**Comment by kennethtran93** [comment]
I would think it would be a combination of browser settings, OS configuration, and OS programs that deal with removing cookies and other files outside the browser (e.g. CCleaner).  At this point it may be question that can be thrown into StackOverflow or related tech sites for further QA and whatnot.
