### ISSUE TITLE
Please change the name of whitelist and grey-list to Keep-list and clean-list or something fits[FEATURE REQUEST]  

### ISSUE THREAD

**Issue by rammanokar** [mrdokenny/Cookie-AutoDelete#789]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kennethtran93** [comment]
Dupliate of #754 .  Show your support by voting or contributing there.

Next time please search up the issues/requests before opening up a new one.
