### ISSUE TITLE
[SUPPORT]  Delete All Cookie Content within a container

### ISSUE THREAD

**Issue by RamonAbudAlcala** [mrdokenny/Cookie-AutoDelete#790]
**Is your feature request related to a problem? Please describe.**

No. It is a featuer that I thought that the extension was being advertised with. Since I can't find how to do it, I think it would be a really nice thing to add. 

**Describe the solution you'd like**

It would be really nice to be able to clean the cookies only of the browsing done from a specific container. Without affecting any of the other containers.

**Comment by kennethtran93** [comment]
FYI - This falls under the support category.

What you do is in **Settings -> List of Expressions**, just under the buttons there are tabs for each container.  In each container that you don't need cleaning for, simply enter `*` in the textbox and click `whitelist`.  It should look similar to this for each container you don't want cleaned.

![Cookie AutoDelete Settings - Mozilla Firefox](https://user-images.githubusercontent.com/6724477/86145854-5156b680-baac-11ea-80f2-60f3f6fb1555.png)

In the container tab that you want cleaning for, leave it empty, or add expressions/domains/urls that you would like to either keep or clean on browser restart.

Don't forget to check `Enable Support for Firefox's Container Tabs` in **CAD Settings**

![Cookie AutoDelete Settings - Mozilla Firefox_2](https://user-images.githubusercontent.com/6724477/86145988-7b0fdd80-baac-11ea-99f3-35bf4c0fc0b1.png)

**Comment by RamonAbudAlcala** [comment]
Thanks! it seems that the feature is there. Thanks for describing how to delete the cookies from a specific container.

I still have the feeling that this can be something that could be improved. I mean, it seems that one could incorporate it into a button or something else. Especially because adding and removing the `*` from various containers seems like something that could be automated.

**Comment by kennethtran93** [comment]
> Thanks! it seems that the feature is there. Thanks for describing how to delete the cookies from a specific container.
> 
> I still have the feeling that this can be something that could be improved. I mean, it seems that one could incorporate it into a button or something else. Especially because adding and removing the `*` from various containers seems like something that could be automated.

Not necessarily as those are generally one-time things to setup.
