### ISSUE TITLE
FireFox 78 allows WebExtensions to Clear by Domain: IndexedDB, ServiceWorkers, cache and pluginData

### ISSUE THREAD

**Issue by rugabunda** [mrdokenny/Cookie-AutoDelete#792]
Firefox 77 supported clearing IndexDB by hostname if that helps: https://bugzilla.mozilla.org/show_bug.cgi?id=1551301.

Firefox 77 also supported clearing ServiceWorkers by hostname: https://bugzilla.mozilla.org/show_bug.cgi?id=1632990.

After that, Firefox 78, coming to an update today or tomorrow, will support clearing cache and pluginData by hostname: https://bugzilla.mozilla.org/show_bug.cgi?id=1636784.

Will consider looking at your addon once it implements these feautures

**Comment by kennethtran93** [comment]
IndexedDB request is duplicate of #171.

ServiceWorkers request is duplicate of #287.

Cache request is duplicate of #551 and maybe #283.

I am already working on these whenever I have some spare time.

Plugin Data...will now be added to the list of things to add for cleanup.

Note that it will take some time as I need to overhaul the localstorage cleaning function and make it work with the other cleaning items, not to mention the Addition options in the Expressions that I need to add.

**Comment by rugabunda** [comment]
Sounds great! Keep up the great work ken!

**Comment by kennethtran93** [comment]
Need some testers over at #798.  To download the zip file, follow the latest instructions given through github-actions bot
