### ISSUE TITLE
[SUPPORT] Doesn't remove greylist data on startup 

### ISSUE THREAD

**Issue by avidseeker** [mrdokenny/Cookie-AutoDelete#794]
**Please describe what you need support with.**

The extension was working fine a couple of days ago. I checked the FAQS and did everything instructed there. The problem is:
1. CAD does not automatically erase cookies in the greylist.
2. "clean" button does not work at all.

**Describe the solution you'd like**

Clear the cookies that are assigned in the greylist.

**Additional context**

**Comment by kennethtran93** [comment]
Could I get your browser and CAD version?  Can I also get your CAD settings?

The auto/manual cookie cleanup button will not remove greylist - only browser restart for those.

Last release was about two week ago, so it may be a browser update?

**Comment by avidseeker** [comment]
Here's what I did:
1. Cleared all cookies (fresh start)
2. Uninstalled CAD, reinstalled it.
3. With fresh untouched settings, I only added the wild card * to the greylist.
4. Logged in a random website.
5. Restarted the browser.

The expected result: the cookies of the websites should be deleted.
The actual result: I stayed logged in.

**Comment by avidseeker** [comment]
My browser and CAD are updated to the latest versions:
Firefox: 78.0.1
CAD: 3.4.0

**Comment by kennethtran93** [comment]
Do you have Clean Cookes from open tabs at startup enabled?  See this doc for additional info: https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/Documentation#clean-cookies-from-open-tabs-on-startup.

Long story short the page may have loaded before this extension was able to initialize and perform startup cleanup.
