### ISSUE TITLE
[FEATURE REQUEST]  Sync white/grey/black lists to an account

### ISSUE THREAD

**Issue by JessicaMulein** [mrdokenny/Cookie-AutoDelete#795]
**Is your feature request related to a problem? Please describe.**

Not a problem, but an enhancement. Ability to not have to retrain the various lists on each system I go to would be nice. I run parallels and it can be easy to forget which browser has which whitelists.

**Describe the solution you'd like**

Creation of an account/login/registration system and sync the settings to the account.

Pro level: Option to sync all the cookies too.... share sessions across browsers in your account....

**Describe alternatives you've considered**

I've not considered any alternatives to Cookie-AutoDelete.

**Additional context**

**Comment by kennethtran93** [comment]
Pretty much a duplicate of #30, in terms of browser sync.

Although if this was implemented, it won't be cross-browser sync.  That would require additional resources that we won't have the time or resource to manage.  That would also require a whole other set of privacy policy and whatnot, especially with 3rd-party providers if we were to consider that.

I also think the pro level is over the top for what this is supposed to do which is clean cookies and other site data.  Same with sessions.  There may be another extension that does this already...I'm not sure.

**Comment by JessicaMulein** [comment]
Sorry! Missed that one!

**Comment by JessicaMulein** [comment]
FWIW- I was looking to reduce # of extensions that each have to process events and take up bar space. Figured cookies/sessions was at least a domain area. Appreciate pointing me at #30. Tried to look through the issues and missed it.

**Comment by kennethtran93** [comment]
> FWIW- I was looking to reduce # of extensions that each have to process events and take up bar space. Figured cookies/sessions was at least a domain area. 

You can pin extra app icons in the overflow area so it is not on the bar.  Perfect for those that you don't need to click anything for.  
While extensions do process events, it is up to each extension to setup listeners for it, so extensions don't process unneeded events.
For example, in the tabs API, the follow events are available:
```
    onActivated
    onActiveChanged
    onAttached
    onCreated
    onDetached
    onHighlightChanged
    onHighlighted
    onMoved
    onRemoved
    onReplaced
    onSelectionChanged
    onUpdated
    onZoomChange
```

but CAD only adds listeners to `onRemoved` and `onUpdated`


> Appreciate pointing me at #30. Tried to look through the issues and missed it.

No problem.  I know it is an old issue that still isn't resolved, but it will get looked into once we get the backend data structure more unified.
