### ISSUE TITLE
Expressions missed when importing a JSON file via the Import Expressions button.

### ISSUE THREAD

**Issue by BigFriendlyGit** [mrdokenny/Cookie-AutoDelete#796]
### Describe the Bug/Feature

I exported my Expressions via the 'Export Expressions' button on the 'List of Expressions; page under the add-on settings. When I import these expressions in to another machine via the 'Import Expressions' button on the 'List of Expressions' page then one of my containers (called 'Google') does not import anything.

The 'Default' container list gets populated correctly but there are no entries under the 'Google' container tab on the 'List of Expressions' page on the destination machine.  They are present on the source machine.

If I review the json file created when I exported the settings I can see them listed under 'firefox-container-6' and the container where I would expect to find them is in position 6 if you like, however they do not import.

I cannot see the expressions (i.e. *.google.com') listed under any other container shown on the 'List of Expressions' page so it is not as if they have been imported in the wrong place - it looks like they have just not been imported.

I can manually add them as a workaround but thought it was worth flagging in case it is a bug.

Thanks  

### Your settings 

- Source OS/version: MacOS Catalina 10.15.5
- Destination OS/version: Win 10 v1909 OS Build 18363.900 
- Source and Destination Browser/version: Firefox 78.0.1
- Source and Destination Cookie AutoDelete version: 3.4.0

**Comment by kennethtran93** [comment]
Dupliate of #579 and #529. 

 Main culprit of this is the way container IDs are used.  In Firefox, they don't seem to be reused I believe (at least not for the same profile).  So if you had created a container and removed it, the next container you create will have a different ID incremented from the last container created.

At this point CAD relies on the container ID only.  There have been discussions through the issues above as well.
