### ISSUE TITLE
Not working with Nightly (Linux)

### ISSUE THREAD

**Issue by Radagast** [mrdokenny/Cookie-AutoDelete#8]
I can't seem to get the addon working with Nightly. In 'Active mode' It shows the number of cookies on the toolbar button but It doesn't clear cookies and doesn't, for obvious reasons, show notifications. I've tried the addon in a new Nightly profile. To check, I also tested firefox 53, where it works correctly.

**Comment by mrdokenny** [comment]
Are you using Containers mode? I notice that it breaks if you use it in Containers mode on Nightly, but using it without Containers mode works fine.

**Comment by Radagast** [comment]
Thanks for the feedback, I'll have to look again, as I did try with a new profile. 

I did have Test-Pilot with containers, in my main profile, but I removed those a few days ago. However, I did originally test this addon in that profile with containers enabled.

I'll report back.

**Comment by Radagast** [comment]
So, after testing in a new profile, It does work but the notifications inconsistent, it does, however, appear to be deleting the cookie. 

On my main profile, even with the Test-Pilot/Containers stuff removed, it still fails to work at all. The question then, which is more likely, a conflict with another addon, I have quite a few or is it simply some crud remaining from the containers extension.

**Comment by mrdokenny** [comment]
Sorry what I meant if you enabled in Cookie AutoDelete's settings "Enable Support for Firefox's Contextual Identities (EXPERIMENTAL Firefox 53+)" Turning that on will break Cookie Cleanup on Nightly but not Firefox 53-54.

**Comment by Radagast** [comment]
Ah, ok. I misunderstood. I didn't enable that option, so it it must be something else. I'll rebuild a profile with my addons and see what happens

**Comment by Radagast** [comment]
Ok. Perhaps I'm just not understanding how this is supposed to work. In preferences I set 'Enable Active Mode' to on with a delay of one minute. Opened a site, checked the cookie was set the closed the tab. Nothing happened even though the toolbar button showed the number of cookies for the site (reddit.com)

I then manually deleted the cookie, went back to reddit and this time, on the toolbar button ticked the box for Active Mode. This time the cookie was deleted when the tab was closed.

Is this the expected behaviour?

**Comment by mrdokenny** [comment]
Did you remember to save when you "Enabled Active Mode" in the preferences? Once you made your changes, press save and a green confirmation will show up and will store those settings. If you enable it in the popup toolbar, the setting is autosaved when you check/uncheck Active Mode.

**Comment by Radagast** [comment]
I did save and it was confirmed.

Another issue. When 'browser.sessionstore.restore_on_demand' is true, which I believe is now the default, selecting a tab in a restored session, with the addon is installed, causes the page not to load until the toolbar button is selected. Doesn't seem to matter whether the site is whitelisted in the addon prefs or not.

**Comment by mrdokenny** [comment]
I can't reproduce that so I'm not sure what the deal is with that. Perhaps another (legacy) extension conflict?

**Comment by Radagast** [comment]
The clash appears to be something to do with uMatrix when using default deny. Still looking.

**Comment by mrdokenny** [comment]
I'll close this since there was no response. Please reopen or make a new issue if you still need help.
