### ISSUE TITLE
Whitelist not remembered in Firefox nightly.

### ISSUE THREAD

**Issue by Betsy25** [mrdokenny/Cookie-AutoDelete#80]
EDIT: Actually a normal browser restart also gets them lost. (In the case "Enable Support for Firefox's Contextual Identities" is enabled.)

If the browser is closed, all whitelisted sites added during that session are lost into oblivion. (In the case "Enable Support for Firefox's Contextual Identities" is enabled.)

- OS/version: Win7 x64
- Browser/version: Firefox Nightly v56a1
- Cookie AutoDelete version: 1.4.0

**Comment by ala0796678357** [comment]
alaa
