### ISSUE TITLE
[BUG] Cookie counter on subdomains always zero

### ISSUE THREAD

**Issue by Tibladar** [mrdokenny/Cookie-AutoDelete#801]
**Describe the bug**

The cookie counter on websites with a subdomain like `https://en.wikipedia.org/` is always zero, even when there are cookies clearly set and also deleted when leaving the sites.
Manual delete doesn't work as it shows 'No cookies found'.

On sites without a subdomain like `https://github.com/` it works fine.

**To Reproduce**

1. Go to `https://en.wikipedia.org/`
2. Open the addon menu
3. See '0 cookies'
4. Open browser console and go to Storage Inspector

**Expected behavior**

The cookies should get counted properly

**Screenshots**

![image](https://user-images.githubusercontent.com/52620063/87453968-dab0d180-c5f2-11ea-8e54-928f00e04a05.png)

**Your System Info (please complete the following information):**

 - OS: Ubuntu 20.04
 - Browser Info: Firefox 78.0.1
 - CookieAutoDelete Version: latest™ 3.4.0

**Comment by kennethtran93** [comment]
Hmmm...It seems to be working in mine (at least the cookie counter in subdomains).
![Screenshot_20200714_130158](https://user-images.githubusercontent.com/6724477/87470977-73832500-c5d2-11ea-8a7f-d70baaf4d8c2.png)
Ubuntu 18.04 with Firefox 78.0.2.

At the moment we only count the cookies created in the subdomains.  This is the same with manual cleaning.  Otherwise cleaning the main domains may affect cookies stored through other subdomains and may brake other sites (e.g. authentications from subdomains passed through the main domain).

Not to mention that some subdomains aren't affiliated with the main domain (e.g. free hosting providers).

As a sidenote, do you have firstpartyisolate enabled?

**Comment by kennethtran93** [comment]
Not to mention that some subdomains aren't affiliated with the main domain (e.g. free hosting providers).

**Comment by Tibladar** [comment]
> At the moment we only count the cookies created in the subdomains. This is the same with manual cleaning.

That sounds good

> As a sidenote, do you have firstpartyisolate enabled?

Yes, disabling makes the counter work.
Maybe related to `privacy.firstparty.isolate.use_site`

**Comment by kennethtran93** [comment]
> > As a sidenote, do you have firstpartyisolate enabled?
> 
> Yes, disabling makes the counter work.

Surprisingly in my tests, testing `privacy.firstparty.isolate` for both true/false still shows same result that I had before.

> Maybe related to `privacy.firstparty.isolate.use_site`

That was only freshly added in 78.0.1 and I don't have a clue what that is about.  Currently defaults to false.  I won't consider it a bug at this point until I understand exactly what that does.

**Comment by Tibladar** [comment]
> Surprisingly in my tests, testing privacy.firstparty.isolate for both true/false still shows same result that I had before.

It seems to be `privacy.firstparty.isolate.use_site` with `privacy.firstparty.isolate` enabled.
You may need to clear the site's cookies in order to see a different result.

> until I understand exactly what that does.

Looking at the changeset https://hg.mozilla.org/integration/autoland/rev/a77c31684931#l2.12 and its ticket https://bugzilla.mozilla.org/show_bug.cgi?id=1637516 it seems to change the use from the old `GetBaseDomain (eTLD+1)` to a specific `site` which doesn't ignore the used scheme like the old one.
Because there's a new string I suspect the old domain matching doesn't work anymore.

**Comment by kennethtran93** [comment]
From the changeset given, it looks like it does the following if `use_site` is adding round brackets with schemes and ports...
```
+  site.AssignLiteral("(");
+  site.Append(aScheme);
+  site.Append(",");
+  site.Append(aHost);
+  if (aPort != -1) {
+    site.Append(",");
+    site.AppendInt(aPort);
+  }
+  site.AppendLiteral(")");
```

So here's my findings:
---

| `privacy.firstparty.isolate.use_site` setting | `firstPartyDomain` cookie property value |
|  :---:  |  :---:  |
| Enabled | `(https,wikipedia.org)` |
| Disabled | `wikipedia.org`|

Which means I now not only need to detect if firstPartyDomain (via the workaround so I don't need to request privacy permission), I also need to check the firstPartyDomain given for a cookie...
