### ISSUE TITLE
[BUG]  flashing/shaking when "clean" drop down menu opened from overflow menu.

### ISSUE THREAD

**Issue by Benjie56** [mrdokenny/Cookie-AutoDelete#803]
**Describe the bug**

When the menu is opened from the overflow menu in Firefox, opening the drop-down menu titled "clean" causes everything to shake back and forth quickly.

I assume this is caused by the drop-down being to large, or maybe the scrollbar changing the width of the menu.

**To Reproduce**

Steps to reproduce the behaviour:
Using Firefox for desktop:
1. Move the "Cookie AutoDelete" icon into the "overflow" menu
![Image](https://benjiefiftysix.github.io/issue-images/Screenshot-2020.07.16:13-10-25.png)
2. Click on the icon in the overflow menu to open the menu
3. Click on the arrow at the right of the button labelled "Clean"
4. The menu should start flashing quickly

**Expected behaviour**

The drop-down should be displayed without any shaking

**Screenshots**

[Recording](https://benjiefiftysix.github.io/issue-images/Screenrecording-2020-07-16_13.31.39.mp4)

**Your System Info:**

 - OS: Manjaro KDE
 - GTK theme: Breath-Dark (controls scrollbars)
 - Browser Info: Firefox 78.0.2
 - CookieAutoDelete Version 3.4.0

**Comment by kennethtran93** [comment]
Considering the Overflow menu doesn't expand horizontally that is a given.  I find it a lot easier to not have it pinned in overflow but I guess that's a personal choice (easier to see icon with cookie and color).  

I had left it to bootstrap, jquery, and popper.js to handle the popup.

As a workaround for the time being, use a different popup size font.

**Comment by kennethtran93** [comment]
I have yet to find a good way to fix this, other than to make the popup font size default smaller, though that would only affect new installations.

**Comment by kennethtran93** [comment]
Can you confirm if this is still happening on the latest Firefox +CAD version?  I just tried putting it into overflow and checking the dropdown from there and it seems to load properly, no flashing or adjustments of any kind.

Used Kubuntu + Firefox.

**Comment by Benjie56** [comment]
I have tested this in firefox 83.0 and 78.4.0 esr, CAD 3.5.1, with the size-of-popup setting set to 16.
I still experience the issue, I still looks exactly the same for me.

**Comment by kennethtran93** [comment]
Not sure if it is a specific problem or not, as on Windows 10, FF 84, I do not see the issue at this time
![image](https://user-images.githubusercontent.com/6724477/102843992-4a579380-43bf-11eb-9fc4-6f6c9fe0dbd9.png)

What I think I will try and do is to have the clean button move to the next line if on a smaller size.  That may help resolve this, but we'll see.  I'll send you an alpha build here when I have it sorted out.

**Comment by Benjie56** [comment]
I have 2 monitors connected. I just realised it only happens when firefox in on my 1920x1080 monitor, and not on the 1360x768 monitor. Resizing the firefox window does not seem to affect it. On the larger monitor, where the issue occurs, the clean button is the first button on the second row (there are 2 rows, with 2 buttons each), and on the smaller monitor, where I don't have the issue, the buttons are arranged the same as your screenshot.

**Comment by kennethtran93** [comment]
That's good to know. Yeah I don't think the overflow menu can be resized at all.

Perhaps with this new info I'll try to make each button go into its own line. That may help.

**Comment by kennethtran93** [comment]
Here's some work in progress screenshots.  One not from overflow and one from overflow.  Essentially removes the popup menu and pushes the items below it as a collapsible area.  Now that I think about it, why did we have a popup within a popup... 🤔 

![Debugging - Runtime  this-firefox — Firefox Developer Edition](https://user-images.githubusercontent.com/6724477/102959830-6af21d00-4495-11eb-8edc-8bc29edbdfc3.png)

![Debugging - Runtime  this-firefox — Firefox Developer Edition_2](https://user-images.githubusercontent.com/6724477/102959834-6ded0d80-4495-11eb-8c84-c8990dc5e9a4.png)

**Comment by kennethtran93** [comment]
PR #1009 should have your fix, if you would like to give that a shot.

**Comment by kennethtran93** [comment]
A 3.6.0 alpha2 build is available for testing from the release/pre-release section, if you want to try it out.

**Comment by Benjie56** [comment]
Hi, sorry for not getting back to you. I tested the full release 3.6.0 and it is working perfectly now!
