### ISSUE TITLE
I have a problem with a site that goes from one to another and then back  

### ISSUE THREAD

**Issue by pratomorone** [mrdokenny/Cookie-AutoDelete#804]
I really like the add-on.

I am using the latest version of Firefox.

When I log into E"Trade and go to do some research, the site takes me to etrade.wallstreet.com.  When I did not have the add-on, it would come back to E*Trade when I had completed my research.  With it on, E*Trade is logged off when I return to it.  I have added all the E*Trade links to the whitelist to no avail.

Guidance is needed, please.

Thanx!

**Please describe what you need support with.**

A clear and concise description of what you need support with.

**Describe the solution you'd like**

**Additional context**

**Comment by kennethtran93** [comment]
Next time, please use the format given.

Best to enable `Cookie Log and Counter`, then you can see what cookie(s) and domains the extension has cleaned up during your session through the Cleanup Log.  From there you can narrow down what you need for whitelisting domains.
