### ISSUE TITLE
[SUPPORT] Whitelisting individual cookies

### ISSUE THREAD

**Issue by lonix1** [mrdokenny/Cookie-AutoDelete#805]
**Please describe what you need support with.**

I want to whitelist a particular cookie. I followed the instructions [here](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/Documentation#whitelisting-individual-cookies).

**Describe the solution you'd like**

To see the individual cookies.

**Additional context**

After unchecking "Keep All Cookies", the site's individual cookies are not shown. The popup does not change at all (except that the checkbox is now unchecked).

The popup shows that there are multiple cookies (`Cookie(s): 7`), and I can see them in the devtools. But they are not shown in the popup.

I'm using the latest version of firefox and the extension.

**Comment by kennethtran93** [comment]
Do you have first party isolation turned on?

You may need to change the domain expression one level up (e.g. subdomain.domain.com -> *.domain.com or domain.com).

From the devtools, what other domains are shown?

To better assist you, please provide the domain expression used as well as a screenshot of the devtools panel with the storage tab

**Comment by Chaython** [comment]
Individual cookies is too complicated for lazy people like me.
I was just hoping for an alternative to EditThisCookie, that is alive, and auto deletes expired...
https://github.com/ETCExtensions/Edit-This-Cookie
Edit this cookie is better for inspection and individually whitelisting cookies, some sites create endless telemetry/tracker cookies, I really just want to save session[login/two step], dark mode and widescreen cookies - block everything else...

**Comment by kennethtran93** [comment]
For inspecting cookies I'd suggest https://addons.mozilla.org/en-US/firefox/addon/a-cookie-manager/, but i do not know the equivalent in Chrome.

To keep individual cookies, you just need to check the one you want to keep, as long as you know the name for it.  I do not have plans to add in cookie inspection at this time,
