### ISSUE TITLE
[BUG]  CAD Conflicts with Google Voice

### ISSUE THREAD

**Issue by koolx** [mrdokenny/Cookie-AutoDelete#808]
I'm unable to access voicemail in google voice. When I go to google voice I see an endless loading spiral but I never see any of my voicemail. 

At one point I did clear all cookies for everything related to google and I was able to access voice. But the next day I wasnt able to. Its likely a cookies issue. How should I configure CAD to allow access to google voice?

.

**Comment by kennethtran93** [comment]
Please use the support issue template next time.  Not sure why I didn't receive any emails from GitHub relating to new issues, so apologies in the not-as-quick response.

From the cleanup logs, you'll need to decipher which cookie/domain that was cleaned, then whitelist that cookie/domain, undo the cleanup logs if you want, and try again.  As I don't use google voice, there is only so much support I can provide.

**Comment by koolx** [comment]
Hi Kenneth. Excuse the late reply. Your suggestion fixed my issue. Thanks man!
