### ISSUE TITLE
[FEATURE REQUEST] Allow CIDR in Expression

### ISSUE THREAD

**Issue by polyproline** [mrdokenny/Cookie-AutoDelete#814]
### Is your feature request related to a problem? Please describe.
For the websites visited by IP address, whether it is the choice of IPv4 or IPv6, they are not well supported
### Describe the solution you'd like
Add CIDR support
### Describe alternatives you've considered
> Regular Expressions  

#### ipv4 private address  
/^(?:(?:1[0-9][0-9]\.)|(?:2[0-4][0-9]\.)|(?:25[0-5]\.)|(?:[1-9][0-9]\.)|(?:[0-9]\.)){3}(?:(?:1[0-9][0-9])|(?:2[0-4][0-9])|(?:25[0-5])|(?:[1-9][0-9])|(?:[0-9]))$/

#### ipv6 private address  
I con`t find

### Additional context

**Comment by kennethtran93** [comment]
I'm not sure why you had removed the auto assigned labels and whatnot if you had followed the template.

Please update the title accordingly as well.

**Comment by kennethtran93** [comment]
The only issue, as with other expressions using wildcards and whatnot, is in regards to the cookie list in the expression options.   If there are different domains with the same cookie name, it will be treated one and the same. If you want a cookie 'myCookie' removed from site A but kept in site B, using this CIDR notation or wildcards to capture both sites will keep them both if checked in whitelist, or removed on browser restart if checked in greylist.

**Comment by polyproline** [comment]
> The only issue, as with other expressions using wildcards and whatnot, is in regards to the cookie list in the expression options. If there are different domains with the same cookie name, it will be treated one and the same. If you want a cookie 'myCookie' removed from site A but kept in site B, using this CIDR notation or wildcards to capture both sites will keep them both if checked in whitelist, or removed on browser restart if checked in greylist.

About this question, I use this extension with uMatrix , control the cookies privilege in different host.

**Comment by kennethtran93** [comment]
> About this question, I use this extension with uMatrix , control the cookies privilege in different host.


That most likely doesn't affect our extension. We query through the Cookie API itself. Thus if 192.168.1.1 and 192.168.1.2 both have a cookie with the same same, our extension will treat it all the same if you use cidr notation. If you create separate expressions, i.e. One IP address per entry with no cidr, then you can control each cookie that has the same name on each IP address.

Of course if uMatrix alters the cookie itself through the API (the domain name and/or the cookie name that is) then we won't be able to keep any of those cookies unless there's an Expression to cover them all, provided you know how uMatrix alters the cookie data.
