### ISSUE TITLE
Not deleting cookies windows Chrome [SUPPORT]  

### ISSUE THREAD

**Issue by Keystonecop** [mrdokenny/Cookie-AutoDelete#817]
![three](https://user-images.githubusercontent.com/69061234/89088345-9b9db280-d34c-11ea-87fd-ed75f94835aa.png)
![two](https://user-images.githubusercontent.com/69061234/89088346-9c364900-d34c-11ea-9db2-1ad79628f096.png)
![one](https://user-images.githubusercontent.com/69061234/89088347-9c364900-d34c-11ea-8ad2-19550c766298.png)

Google Chrome is up to date
Version 84.0.4147.105 (Official Build) (64-bit) 

I have 3 Greylist for this site..  https://www.sacbee.com/  It says the cookies 3) get cleaned.. but when I check  chrome://settings/siteData  they are still there.  

Thank YOU for your time..

**Comment by kennethtran93** [comment]
Here's my initial questions for you:

1. Seeing that you have autoclean disabled, which action did you click on for cleaning?

2. Somewhat relates to 1: Was that domain open in any other tabs?

As a side note, because auto clean is disabled, greylist acts pretty much like whitelist.

**Comment by Keystonecop** [comment]
Same results.. I for got to change it back having run every possible way I could think of..  domain was NOT open in another tab.
 clean goes to zero and back to 1..

**Comment by kennethtran93** [comment]
So to clarify, there were No tabs with that domain remaining?

Did you have any cookies checked?

I'm not sure if that site has any service workers that are doing any cookie work.

Also assuming the delay is at least one second?

**Comment by Keystonecop** [comment]
Only the one tab open
Delay is 15
No cookies checked
![pic](https://user-images.githubusercontent.com/69061234/89089635-22ee2480-d353-11ea-9e36-6a6ad9698cf9.jpg)

**Comment by Keystonecop** [comment]
![image20](https://user-images.githubusercontent.com/69061234/89090192-1d460e00-d356-11ea-9035-29533004d547.png)

**Comment by kennethtran93** [comment]
The default clean button doesn't touch open tabs. Did you click on the dropdown and then 'clean, include open tabs'?

**Comment by Keystonecop** [comment]
It says it cleans when I reopen the browser.. but  the cookies are all there.. Picture above was after it said it was cleaned..

can you recreate it using this page..  https://www.sacbee.com/  just click on a few news articles and you can see the cookie count go up    chrome://settings/siteData  just search for bee..

**Comment by kennethtran93** [comment]
To fully mimic what you had set up could you tell me what your expression option was?

**Comment by Keystonecop** [comment]
![2020-07-27-0001](https://user-images.githubusercontent.com/69061234/89091267-28e90300-d35d-11ea-94d5-4e26cc39c098.jpg)

**Comment by Keystonecop** [comment]
![image20](https://user-images.githubusercontent.com/69061234/89091290-52a22a00-d35d-11ea-8246-d00671dc9913.png)

**Comment by kennethtran93** [comment]
Any other cad settings that was changed from the default?

**Comment by Keystonecop** [comment]
here they are..
![bitmap](https://user-images.githubusercontent.com/69061234/89092371-18895600-d366-11ea-8e92-17626014cee9.png)

**Comment by Keystonecop** [comment]
works in firefox not in chrome..  looks like the setting are shared between the two..

**Comment by kennethtran93** [comment]
Yeah the function to remove cookies through autoclean is the same for the two - we first query the cookie API for cookies matching that domain, then filters it though the expressions.  If it is deemed that it needs to be cleaned, then that cookie object is passed into the browser for removal.

**Comment by kennethtran93** [comment]
Hmmm... I cannot seem to fully reproduce it.

I had the settings that you had enabled, plus debug mode.
For expressions I added all the greylist expressions you had `*.account.sacbee.com`, `*.sacbee.com`, `account.sacbee.com`, `sacbee.com` to the Greylist.  (a word of note - `*.sacbee.com` already includes `sacbee.com` so there wasn't really a need to have it).  Each expression also has the `keep all cookies...` unchecked, which then really means remove all cookies from those site when the browser tab closes, to which it does, and all I was left with was this:
![Screenshot_20200801_004515](https://user-images.githubusercontent.com/6724477/89097062-497e8080-d390-11ea-94d6-03bcebfab4e2.png)

and this was part of the cleanup logs:
![Screenshot_20200801_004547](https://user-images.githubusercontent.com/6724477/89097072-5f8c4100-d390-11ea-84aa-9b42e19d3962.png)

There wasn't even a need for me to restart the browser.  Mind you, if you had restore previous tabs on startup enabled, and that tab is opened, it will not be cleaned unless the `clean open tabs on startup` is enabled.

Though I was using Version 85.0.4183.39 (Official Build) beta (64-bit)

UPDATE:  I just tried it with the public release Version 84.0.4147.105 (Official Build) (64-bit) and still didn't get your results.

**Comment by kennethtran93** [comment]
The only thing on Chrome at this point, because you had mentioned that it works fine on Firefox, is that is if you had changed this Chrome setting on either sacbee.com and/or account.sacbee.com:
![Screenshot_20200801_005559](https://user-images.githubusercontent.com/6724477/89097215-d544dc80-d391-11ea-8874-9eb1a9ab1f1f.png)

or even the Extension global option from Chrome:
![Screenshot_20200801_010625](https://user-images.githubusercontent.com/6724477/89097374-3e791f80-d393-11ea-87a1-bf9957de6158.png)


Changing this option is actually a Chrome restriction (not one of our webextension option), and will not allow the webextension to properly do its job.  It MUST be kept at 'on all sites'.

**Comment by kennethtran93** [comment]
...and that site certainly sets a lot of cookies (including third-party cookies that is)
![Screenshot_20200801_010258](https://user-images.githubusercontent.com/6724477/89097315-d0345d00-d392-11ea-8afa-4d25c329835a.png)

This was just from testing out your settings on a relatively fresh profile. (I don't use Chrome that often so it is relatively fresh.  I did run the autocleanup before even opening that site for the first time).

**Comment by Keystonecop** [comment]
If I delete the 3 cookies...  using chrome to delete
account.sacbee.com, sacbee.com, www.sacbee.com I can then read new articles..

I changed to just those 3 deleting data and cookies..  the cookies still show in Chrome and firefox after the delete.. 

Firefox is working just fine. 4 am here..  will try later today to narrow it down... sorry to take up so much of your time.

I apologize.. I should have started out telling you what I wanted to do vs trying to explain why it was not working.  Firefox works because It deletes all the cookies..

**Comment by kennethtran93** [comment]
> If I delete the 3 cookies... using chrome to delete
> account.sacbee.com, sacbee.com, [www.sacbee.com](http://www.sacbee.com) I can then read new articles..
> 
> I changed to just those 3 deleting data and cookies.. the cookies still show in Chrome and firefox after the delete..

We don't have a blacklist yet, so to remove those specific cookies just make sure that those cookies are NOT checked.

> Firefox is working just fine. 4 am here.. will try later today to narrow it down... sorry to take up so much of your time.

Haha seems we're the same timezone.

**Comment by kennethtran93** [comment]
If you don't care about anything on that site, just don't have any expressions, and if autoclean is enabled, all those cookies from that site will be cleaned up if the final tab of that domain is closed.

**Comment by Keystonecop** [comment]
I did not get this to work.. I will share with you what my last try was..  only one cookie was deleted on a restart not all of them. I have found a workaround for me.. Probably just me not understanding the lingo... old mainframe operating system programmer here. never was good with the applications.  anyway 3 in greylist thought all cookies would be deleted on restart.  
![Screenshot (1)](https://user-images.githubusercontent.com/69061234/89126103-ed068880-d497-11ea-9a85-afc4e886664e.png)

![Screenshot (2)](https://user-images.githubusercontent.com/69061234/89126108-f7c11d80-d497-11ea-9a97-6d1bb2b31094.png)


![Screenshot (3)](https://user-images.githubusercontent.com/69061234/89126109-fdb6fe80-d497-11ea-8279-f792925cbb9a.png)

here is what I am doing........
![Screenshot (4)](https://user-images.githubusercontent.com/69061234/89126116-0ad3ed80-d498-11ea-8617-2626549876d8.png)

**Comment by kennethtran93** [comment]
There's online documentation that you most likely haven't throughly read through yet, but here's the important parts of it.

If you're using the greylist, then **CHECK** the `Keep All Cookies` option or specific cookie names to _REMOVE them on browser restart_, provided that you are not restoring session/tabs on startup in Chrome settings. If those are **UNCHECKED**, then _cookies will be removed when all tabs related to that domain are closed_. In your case these cleanups happen 15 seconds after the last tab closed. On Browser restart you'll need to wait at least a few seconds before opening up that domain again as we need to reinitialize our configuration each time. 

If you want all the cookies from that site removed after you have left the site, probably best to NOT have expressions set so they can be removed on tab close, as long as you're not logged into it.

Each cleanup log entry can be clicked upon to show the reason why CAD removed that cookie, could range from browser restart or tab close. 

You're final screenshot has nothing to do with CAD, other than the fact that Chrome itself should be removing those cookies before exit or on browser restart. That is out of our hands.

Before we keep going in a circular pattern, could you explain what you had wanted to achieve with the cookies and site data from that site? Remove when last tab with that domain is closed, or on browser restart AND that domain is not part of any opened tabs during that time?

**Comment by Keystonecop** [comment]
I was trying to remove all the cookies for the 3 areas, every 15  and to keep all the the other cookies for all my other sites
..   so to delete i need to say keep? I really am confused...

**Comment by kennethtran93** [comment]
> I was trying to remove all the cookies for the 3 areas, every 15  and to keep all the the other cookies for all my other sites

We don't have any blacklist/specific site cleaning yet, so you'll need to wither greylist or whitelist everything else. 

We also don't have an autoclean trigger every X seconds yet. The only triggers we have are: on tab close, on domain change, on browser restart. With the exception of the last one the cleanup triggers sets the delay of 15 seconds that is configurable. 


> ..   so to delete i need to say keep? I really am confused... 

I've reworded the string a bit in the next upcoming version to say `keep all cookies until restart` for greylist. Before I started contributing to this it was the same string for both greylist and whitelist, probably to save on translation and coding time/cost. 

This is what happens in greylist: check to remove on restart, uncheck to remove on next cleanup trigger (provided the domain is not in any open tabs). 

Whitelist is similar: check to keep forever (until it expires on its own at least), uncheck to remove on next cleanup trigger.

**Comment by Keystonecop** [comment]
OK since I was backwards I have now set a whitelist for about 15 sites.  
when I reload chrome  a popup says 1 cookie from sacbee deleted  
It is not removing the cookies for the BEE sites

![Screenshot (8)](https://user-images.githubusercontent.com/69061234/89129680-f9004380-d4b3-11ea-8aec-37af5297a2dd.png)

![Screenshot (6)](https://user-images.githubusercontent.com/69061234/89129594-53e56b00-d4b3-11ea-81b0-323f1d94d492.png)

![Screenshot (7)](https://user-images.githubusercontent.com/69061234/89129599-5a73e280-d4b3-11ea-8863-4682cb090af8.png)


sacbee.com (DigiTrust.v1.identity, GED_PLAYLIST_ACTIVITY): Clean because sacbee.com is not in the White or Grey lists

I can quit if you wish and you can delete this entire thread.. at This Point since you tried to help I can keep going but only if you want..

**Comment by kennethtran93** [comment]
Did you refresh that page or access it after the cleanup? If you were on that page after the cleanup happened you'll need to reload that site Data page.

There's also debug mode in the setting, if you know how to access the extension console for copy-pasting into a text file. That would possibly help me in debugging your issue. Just make sure that was enabled before browser restart. If you're going to include that you can also include the exported settings from the settings page. The export of Expressions is optional but would help. 

Alternatively try a fresh Chrome profile.

**Comment by Keystonecop** [comment]
Ok tried with a different account.. installed your app. imported both files. did not have the bee site up kept clicking clean.
got messages.. nothing got cleaned.


![Screenshot (10)](https://user-images.githubusercontent.com/69061234/89134209-016a7580-d4d8-11ea-976d-2bd63f431025.png)


![Screenshot (11)](https://user-images.githubusercontent.com/69061234/89134227-32e34100-d4d8-11ea-8cf0-705b8a8c4109.png)


<EDIT 08/05:  Removed Expression configuration as non-relevant to issue at hand>

{
  "settings": [
    {
      "name": "activeMode",
      "value": true
    },
    {
      "name": "cleanCookiesFromOpenTabsOnStartup",
      "value": true
    },
    {
      "name": "contextMenus",
      "value": true
    },
    {
      "name": "contextualIdentities",
      "value": false
    },
    {
      "name": "debugMode",
      "value": false
    },
    {
      "name": "delayBeforeClean",
      "value": 15
    },
    {
      "name": "discardedCleanup",
      "value": true
    },
    {
      "name": "domainChangeCleanup",
      "value": true
    },
    {
      "name": "enableGreyListCleanup",
      "value": true
    },
    {
      "name": "enableNewVersionPopup",
      "value": false
    },
    {
      "name": "greyCleanLocalstorage",
      "value": false
    },
    {
      "name": "keepDefaultIcon",
      "value": false
    },
    {
      "name": "localstorageCleanup",
      "value": false
    },
    {
      "name": "notificationOnScreen",
      "value": 3
    },
    {
      "name": "showNotificationAfterCleanup",
      "value": true
    },
    {
      "name": "showNumOfCookiesInIcon",
      "value": true
    },
    {
      "name": "sizePopup",
      "value": 16
    },
    {
      "name": "sizeSetting",
      "value": 16
    },
    {
      "name": "statLogging",
      "value": true
    },
    {
      "name": "whiteCleanLocalstorage",
      "value": false
    }
  ]
}

**Comment by kennethtran93** [comment]
In both your recent screenshots, you have the sacbee domain open in a tab, thus why they don't get cleaned.  I had mentioned multiple time that they **MUST** be closed in order for them to be cleaned.  Tabs open in the background (non-active) are still considered open.

However...if you want to trigger the cleanup while those tabs are open, then from the popup, click on the dropdown next to the clean button and click `clean, include open tabs`.  That will clean the open sacbee domain as well.

**Comment by kennethtran93** [comment]
I've attached a gif showcasing what I did to replicate what you had intended CAD to do.
I've left most of the default settings and used no expressions as it is a relatively fresh profile.  The only settings that I have adjusted was to enable autoclean, and enable localstorage, and to set a short delay simply to make this gif as short as possible.

This starts on the CAD Settings screen to show you the settings used, as well as the empty expression table and cleanup log.

![Peek 2020-08-02 18-12](https://user-images.githubusercontent.com/6724477/89137138-d1c56880-d4eb-11ea-8bb5-b5e10c203505.gif)

Mind you I was running linux, but the OS shouldn't matter at all as it is a browser webextension.

**Comment by Keystonecop** [comment]
I have spent hours checking what you have done, I have tried and failed,, It never deletes more than 1 or 2 cookies.
I need to walk away and start over with this.  I will use a different google account with chrome, and do everything from scratch.


what did you use to create the GIF...?   (I can run my mothers computer remotely.. I will try that in a day or so

**Comment by kennethtran93** [comment]
> I have spent hours checking what you have done, I have tried and failed,, It never deletes more than 1 or 2 cookies.
> I need to walk away and start over with this. I will use a different google account with chrome, and do everything from scratch.

Because we don't have any sync capabilities yet, you don't necessarily need to sign in with a google account to use Chrome.  Maybe that may be the reason why - Chrome's cookie sync is somehow at fault?  It's just a thought.  What other extensions do you have running?


> what did you use to create the GIF...? (I can run my mothers computer remotely.. I will try that in a day or so

It's a linux program called Peek (https://github.com/phw/peek).  Don't think they have it for windows yet but I'm sure there's alternatives.

I apologize if I wasn't quite as helpful as you would have liked.

**Comment by Keystonecop** [comment]
This is way over my head but version 84 of chrome made a change of how cookies work.. https://venturebeat.com/2020/07/14/google-chrome-84/

**Comment by kennethtran93** [comment]
Not really relevant to us - but more for website developers and maintainers.

As a webextension, we utilize the Cookies API that Chrome has for webextensions, and call `getAll` with the current cookieStoreId (which in Chrome's case is always `0`, with `1` being for private browsing).  In Chrome, this essentially returns ALL cookies in Chrome (most likely except the ones that the API cannot remove).  As long as the domain name and/or cookie name is not in one of the matching expressions (or matching greylist on browser restart) then it is removed.

If you're interested in Chrome's Cookie API it is here:  https://developer.chrome.com/extensions/cookies

**Comment by Keystonecop** [comment]
If you can please delete this thread as I see no value for anyone else..  I do think it is me and not your app. Thank you for you time .

**Comment by kennethtran93** [comment]
No worries.  We'll keep it in a closed state just in case others may have similar issues.
