### ISSUE TITLE
[BUG] After Update to v3.5.0 the counter and Icon does no more working

### ISSUE THREAD

**Issue by Alpengreis** [mrdokenny/Cookie-AutoDelete#839]
[BUG] After Update to v3.5.0 the icon counter and icon itself does no more working. It shows always 0 cookies and icon remains blue, except after deleting an expression for the current site or while loading the page yet ...

 - Win 10 Pro x64
 - Firefox Developer 80.0b8 x64
 - 3.5.0

Here my setting:
![CAD_Pref_01a](https://user-images.githubusercontent.com/11355601/90660223-ec1a7880-e245-11ea-8852-e724db43f53d.png)
![CAD_Pref_01b](https://user-images.githubusercontent.com/11355601/90660236-ee7cd280-e245-11ea-83d9-e45d8f9ab92a.png)

**Comment by kennethtran93** [comment]
Ahh whoops.  I was testing for the new firstPartyIsolation settings and forgot to reset and test it without.  It does work if firstPartyIsolation is turned on.

**Comment by Alpengreis** [comment]
Ahh, yep, I have now enabled the firstPartyIsolation for testing and it runs again as you said.

Thank you for fast answering and your great extension!

**Comment by kennethtran93** [comment]
Work in progress, though pushing it out for release may take a while as I am waiting for Chrome and Edge to have the extension reviewed first.

**Comment by kennethtran93** [comment]
can you see if https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/releases/tag/v3.5.1-alpha also work for you?

**Comment by Alpengreis** [comment]
Sure: tested in non-firstPartyIsolation mode and it works again!

**Comment by Mautzimann** [comment]
> 
> 
> Work in progress, though pushing it out for release may take a while as I am waiting for Chrome and Edge to have the extension reviewed first.

As I mentioned in #852 : I did test CAD 3.5.0 in Chrome with default Cookie settings, there it works fine, thank you! Or did you mean, the Chrome developer team must review it too?
BTW: When I turn on firstPartyIsolation in FF about:config, it works here too. But thats no way for me, because e.g. a paypal transaction then never will work, and I never want to install the 1000. addon ;-) or switch it manually each time.

**Comment by kennethtran93** [comment]
> As I mentioned in #852 : I did test CAD 3.5.0 in Chrome with default Cookie settings, there it works fine, thank you! Or did you mean, the Chrome developer team must review it too?

Whenever we push new versions to the respective extension stores, they all must go through human reviews and validations.  As such I cannot upload new versions until the current one has been reviewed.


> BTW: When I turn on firstPartyIsolation in FF about:config, it works here too. But thats no way for me, because e.g. a paypal transaction then never will work, and I never want to install the 1000. addon ;-) or switch it manually each time.

The new code was designed around the fact that there was a new way to doing firstPartyIsolation in the backend, with the usage of 'use_site' which then further isolated the cookies to its protocol (http/https/file) as well as its port number.
