### ISSUE TITLE
Google whitelisted cookies not working in Firefox

### ISSUE THREAD

**Issue by pinellaschuck** [mrdokenny/Cookie-AutoDelete#84]
### Your settings 

- OS/version: 
- Browser/version: 
- Cookie AutoDelete version:

**Comment by pinellaschuck** [comment]
Using Windows 7 Home Premium 64bit and Firefox 54.0.1
I am randomly logged out of Google websites even though they are in my white list.  Do not seem to have this problem with other websites.  Any assistance greatly appreciated as I really like this add-on.

**Comment by mrdokenny** [comment]
Can you take a screenshot of your google cookies in `about:preferences`? If you are in another country you might want to whitelist manually in the settings google.ca or google.de for example.

**Comment by pinellaschuck** [comment]
The delay in my reply caused by the issue happening again. Not sure if it makes any difference by I used pinned tabs for Google mail and Google Play Music


![googlecookies](https://user-images.githubusercontent.com/30220892/28290508-b41770d8-6b14-11e7-8e21-a728bf19aeae.png)

**Comment by mrdokenny** [comment]
Not sure if you still need anything but if you have subdomain check on, you can manually whitelist `google.com`

**Comment by pinellaschuck** [comment]
I seem to have resolved the problem by white-listing Google In uBlock Origin.
