### ISSUE TITLE
[BUG] Missing documentation on setting Enable Cleanup for Discarded/Unloaded Tabs

### ISSUE THREAD

**Issue by kaistian** [mrdokenny/Cookie-AutoDelete#840]
**Describe the bug**

Documentation on `Enable Cleanup for Discarded/Unloaded Tabs` doesn't exist.

In CAD settings the question mark links to https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/Documentation#enable-cleanup-on-discarded-tabs but `#enable-cleanup-on-discarded-tabs` nor the explanation exist on that page.

CookieAutoDelete Version 3.4.0

**Comment by kennethtran93** [comment]
Whoops thanks.  This was probably one of my late night coding fun that I forgot about the doc for it.

**Comment by kennethtran93** [comment]
New link is this: https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/Documentation#enable-cleanup-for-discardedunloaded-tabs

**Comment by redactedscribe** [comment]
["Clean All Expired Cookies" also links to a non-existent anchor](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/Documentation#clean-expired-cookies) (no documentation present).

I just search engined this to find out that [browsers store expired cookies indefinitely](https://superuser.com/a/1225453) unless visiting the site in question again.

**Comment by kennethtran93** [comment]
> ["Clean All Expired Cookies" also links to a non-existent anchor](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/Documentation#clean-expired-cookies) (no documentation present).

Thanks - added, though usually self-explanatory.

> I just search engined this to find out that [browsers store expired cookies indefinitely](https://superuser.com/a/1225453) unless visiting the site in question again.

Yes this was mentioned in previous issues here as well.  Hence why this feature is added.

**Comment by kennethtran93** [comment]
New link for that as well: https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/Documentation#clean-all-expired-cookies

**Comment by redactedscribe** [comment]
> > ["Clean All Expired Cookies" also links to a non-existent anchor](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/Documentation#clean-expired-cookies) (no documentation present).
> 
> Thanks - added, though usually self-explanatory.

I consider myself computer savvy, though I had never considered how the browser handles expired cookies. You're deep in the technicals of how browsers handle site data (and as someone who values privacy, I appreciate that) so the obvious to you may not be as obvious to CAD users.

Thanks for the quick fixes.

**Comment by kennethtran93** [comment]
> I consider myself computer savvy, though I had never considered how the browser handles expired cookies. You're deep in the technicals of how browsers handle site data (and as someone who values privacy, I appreciate that) so the obvious to you may not be as obvious to CAD users.

And that's why issues like these appear - to help us help you.
