### ISSUE TITLE
[FEATURE REQUEST] Documentation examples for the site data types

### ISSUE THREAD

**Issue by redactedscribe** [mrdokenny/Cookie-AutoDelete#843]
**Is your feature request related to a problem? Please describe.**

Lack of documentation.

**Describe the solution you'd like**

Documentation for the [site data types](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/Documentation#enable-cache-support). Some simple examples of what kind of data each type includes. Nowhere does it tell the user what these things are used for and so knowing whether to check them or not isn't clear.

**Additional context**

Most would likely understand what Cache Cleanup will do, but what exactly does Plugin Data clean and when would a site typically use/set it? Service Workers may not be common knowledge either. I had to look up what IndexDB was (from my understanding: a faster, potentially unlimited, LocalStorage). But then, "what's LocalStorage?"…

Also, maybe it's just me but the section "Other Browsing Data Cleanup Options" isn't clear as to when it occurs. Perhaps the docs (or the UI itself) could mention that it occurs both on manual and automatic cleaning (if I've understood it correctly).

Thanks!

**Comment by kennethtran93** [comment]
I'd reference this in the doc but probably not user friendly much either:  https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browsingData/DataTypeSet#Type

> Also, maybe it's just me but the section "Other Browsing Data Cleanup Options" isn't clear as to when it occurs. Perhaps the docs (or the UI itself) could mention that it occurs both on manual and automatic cleaning (if I've understood it correctly).

It affects automatic clean only, as the manual clean will always clean it regardless of these settings (thus 'manual').

**Comment by kennethtran93** [comment]
I'm only going to link to other sites for these things.  Why reinvent the wheel here :D (and it's done).

**Comment by redactedscribe** [comment]
Yes, the link doesn't illuminate much new.

Perhaps "Other Browsing Data Cleanup Options" -> "Other Automatic Data Cleanup Options"? The horizontal dividers make it look separate from "Automatic Cleaning Options", i.e. separate from things-that-happen-automatically. I've never actually used CAD in manual mode so that may be where the confusion is coming from.

To be clear (and sorry for the stupid question), the "Clean" button will clean all site data types excluding both open tabs and enabled types for whitelisted sites?

**Comment by kennethtran93** [comment]
> Perhaps "Other Browsing Data Cleanup Options" -> "Other Automatic Data Cleanup Options"? The horizontal dividers make it look separate from "Automatic Cleaning Options", i.e. separate from things-that-happen-automatically. I've never actually used CAD in manual mode so that may be where the confusion is coming from.

Perhaps, but this extension originally started off as automatic cookie removal, then expanded to include other browsing data.  It was called that way as the [browsingData API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browsingData) was separate from the [cookies API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies)

I might go for 'Other Automatic Browsing Data Cleanup Options' though.


> To be clear (and sorry for the stupid question), the "Clean" button will clean all site data types excluding both open tabs and enabled types for whitelisted sites?

No questions are stupid.  
The 'Clean' button essentially triggers the automatic cleanup function.
The 'Clean, include open tabs' trigger the automatic cleanup and cleans open tabs (like the option to clean open tabs on startup).
These 'automatic' cleanups will take your configured grey and whitelist into account, and remove the rest.

**Comment by redactedscribe** [comment]
Perfect. Thanks Kenneth!
