### ISSUE TITLE
[BUG]  v3.5.0 Cleanup Log is spammed by CookieAutoDeleteBrowsingDataCleanup even for whitelisted sites.

### ISSUE THREAD

**Issue by Fanolian** [mrdokenny/Cookie-AutoDelete#846]
### Describe the bug
After updating to v3.5.0 I see a lot more notifications popping up even for my whitelisted sites.
It turns out something called `CookieAutoDeleteBrowsingDataCleanup` is cleaned(?) and logged every time a tab for a whitelisted site is closed.

### To Reproduce

1. In a brand new Firefox profile, install CAD v3.5.0.
2. In **CAD settings**:
    **Automatic Cleaning Options**
    ✔ *Enable Automatic Cleaning*
    *1 second Delay Before Automatic Cleaning*
   
    **Other Browsing Data Cleanup Options**
     ✔ *Enable Service Workers Cleanup*

    **Extension Options**
    ✔ *Enable Cleanup Log and Counter*
3. In **List of Expressions**:
    Whitelist `*.whatsapp.com`.
    Keep all the stuff for `*.whatsapp.com`.
4. In a new tab, open https://web.whatsapp.com/. (You don't need an account). 
   Open _about:serviceworkers_ and make sure a Service Worker for WhatsApp is registered.
5. Close the WhatsApp tab.
6. Wait for 1 second.

### Expected behavior
No logs should be generated, since nothing should be deleted by CAD.

### Actual behavior
A log is generated which says:
`web.whatsapp.com (CookieAutoDeleteBrowsingDataCleanup): Clean to trigger Site Data cleaning for web.whatsapp.com.`

In _about:serviceworkers_ the WhatsApp service worker is still present, which is expected.

### Screenshots
![image](https://user-images.githubusercontent.com/771216/90757182-e6896500-e30f-11ea-918f-7b4a0b466cb2.png)
![image](https://user-images.githubusercontent.com/771216/90756924-84c8fb00-e30f-11ea-85b7-24b365b50324.png)
![image](https://user-images.githubusercontent.com/771216/90757266-028d0680-e310-11ea-906a-bc2776dc40c1.png)

**Your System Info (please complete the following information):**

 - OS: Windows 10 Pro 1909
 - Browser Info: Firefox 79.0; Nightly 2020-08-19 (build ID: 20200819212829)
 - CookieAutoDelete Version: 3.5.0

**Additional context**
The issue is the same for other **Other Browsing Data Cleanup Options**, even for `LocalStorage` which was already supported in v3.4.0. When none of the other browsing data is selected, no logs are generated.
In v3.4.0 the issue (for LocalStorage) is not exhibited.

**Comment by kennethtran93** [comment]
Guess I should find a way to check if any browsingdata needs to be cleared before I send that cookie off for cleaning.  Reason being is that we cannot enumerate anything else other than cookies, so if any of the CAD settings for browsingData is enabled, and no cookies were set for that site, we set one up ourselves as a trigger.  That trigger then goes through each specific browsing data to check if it should be cleaned.

**Comment by Mautzimann** [comment]
In my opinion: the deletion of CAD own cookie also should not appear in the notifications, because it is very confusing. Some inexperienced users maybe scared about this.

**Comment by kennethtran93** [comment]
> In my opinion: the deletion of CAD own cookie also should not appear in the notifications, because it is very confusing. Some inexperienced users maybe scared about this.

We have noted in the documentation about an internal cookie and reasons for it. (https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/Documentation#other-browsing-data-cleanup-options)

I could try and filter it out in the meantime.

**Comment by kennethtran93** [comment]
While filtering out the CAD Internal cookie from being shown as removed (it will be removed but most likely re-generated if need be), it has come to my attention that the initial cookies stored by whatsapp do NOT include the 'web.whatsapp.com' domain, thus it cannot remove the service workers properly.  I guess now I need to actually create a cookie with that specific domain as they access it...

**Comment by Fanolian** [comment]
I can verify this is fixed in v3.5.1. Thanks a lot!
