### ISSUE TITLE
[BUG]  Update 3.5.0 deletes all the LocalStorage data

### ISSUE THREAD

**Issue by imtbl** [mrdokenny/Cookie-AutoDelete#847]
**Describe the bug**

Updating to 3.5.0 apparently deletes all the LocalStorage data, even for whitelisted sites, if the LocalStorage cleanup had previously been turned on in a prior version.

**To Reproduce**

1. Have LocalStorage cleanup enabled, but have some sites whitelisted
2. Update to 3.5.0

**Expected behavior**

The description in the plugin says:

> WARNING: Upon enabling any of the following site data cleanup options, ALL existing data for that type will be cleared.

Maybe this should rather say something along the lines of _enabling any of the options or updating to a new version of Cookie-AutoDelete while the option is enabled_ so the user has some warning? Or is this deletion a one-time unavoidable side effect with 3.5.0 in particular and won't happen with future updates?

If it's a one time issue, I would have expected the update to ignore the setting (and reset it to its default _off_ state). As it stands, most people will get the update automatically from the Chrome Web Store and lose all their LocalStorage data, even from whitelisted sites, which can be rather annoying.

**Your System Info (please complete the following information):**

 - OS: Arch Linux
 - Browser Info: Brave 1.12.114 (Chromium 84.0.4147.135)
 - CookieAutoDelete Version 3.5.0

**Comment by cryzed** [comment]
This happened to me too, directly after the update.

**Comment by kennethtran93** [comment]
Ahh... That's my bad.  The one logic I had forgotten.

This should only be a one-time thing (unless constantly going between 3.4.0 and 3.5.0) as I had to rename the localStorage setting to match up with the other browsing data cleanup format.

While I had migrated the setting over, I had forgotten to make it so that it should not be cleaned, as the default for enabling any of those setting is to remove all.

**Comment by kennethtran93** [comment]
Good thing I'm making bug patches for 3.5.1 as we speak with all other found bugs.

It really takes an official non-alpha/beta build for people to actually raise bugs (even though I had alpha builds generated before the official one).  Nobody bothers with trying to test out things that I usually miss out on until it affects them.

**Comment by imtbl** [comment]
Thanks for the clarification and the swift response!
