### ISSUE TITLE
[BUG]  No warning about commas or multiple domains in expressions through existing rule

### ISSUE THREAD

**Issue by anewuser** [mrdokenny/Cookie-AutoDelete#849]
**Describe the bug**

I misunderstood https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/pull/652 and moved multiple domains to the same existing rule. There was no warning that the rule was invalid.

**To Reproduce**

1. Replace an existing rule with `example.org, example.com`

**Expected behavior**

The user should be told that this rule is invalid.

**Your System Info (please complete the following information):**

 - OS: Windows 10
 - Browser Info: Firefox 79
 - CookieAutoDelete 3.5.0

**Comment by kennethtran93** [comment]
whoops.  Yeah existing rules are only supposed to be either one domain or a regex expression.

**Comment by kennethtran93** [comment]
If you want to test it out feel free to check out the PR for a build of it.
