### ISSUE TITLE
Toggle Notifications?

### ISSUE THREAD

**Issue by Dolcio** [mrdokenny/Cookie-AutoDelete#85]
I could be missing something obvious, but is there a way to toggle the extension's notifications? I'm using Firefox 54.0.1 on OS X 10.11 and have it set to delete cookies without delay as soon as I close a tab. I'm getting a lot of notifications and would rather disable them, but the only solution I have been able to find so far is to disable all Firefox notifications, which I'd rather not do.

Thanks for your help, and great work on the extension—really glad to have it in my arsenal.

**Comment by mrdokenny** [comment]
Not sure why people miss this but it's in the settings.

![settings 1](https://user-images.githubusercontent.com/17077613/28379741-96ae499e-6c69-11e7-94a2-31a57b2d40ab.png)

**Comment by Dolcio** [comment]
Ah, how embarrassing. Thank you for the reply!
