### ISSUE TITLE
[BUG]  Wrap long expressions

### ISSUE THREAD

**Issue by anewuser** [mrdokenny/Cookie-AutoDelete#850]
**Describe the bug**

If you add a long regex to your list of expressions, it breaks the layout of the settings page and the extension popup.

**Expected behavior**
Lengthy strings should be wrapped.

**Screenshots**

![wrap](https://user-images.githubusercontent.com/6733770/90925140-2a8b7100-e3c7-11ea-8b4b-03e34108db6d.png)

**Your System Info:**

 - OS: Windows 10
 - Browser Info: Firefox 79
 - CookieAutoDelete 3.5.0

**Comment by kennethtran93** [comment]
While I'm sure that regular expression can be simplified, I'll see what I can do.  Normally I'd say to have them into separate entries such that the cookie handling won't overlap as if the cookie names are the same in multiple websites, then they are considered as one with that expression entry, so it's either keep or remove all cookies of that name from matching domains

**Comment by anewuser** [comment]
Thank you for the reply. I didn't know that this could cause problems. I'm going to revert back to separate rules for each host.

**Comment by kennethtran93** [comment]
Going to reopen this as it is a valid issue and may get worked upon in the future.
