### ISSUE TITLE
Manual clean all does not always work in CAD 3.5.1 [BUG]  

### ISSUE THREAD

**Issue by Cromemco** [mrdokenny/Cookie-AutoDelete#860]
I'm on a site that's not whitelisted and CAD says there are 32 cookies. I click on clean all for this domain and the number of cookies does not drop to zero as I've seen happen. Sometimes, even a domain change does not clear all. 3.5.1 just seems to be much buggier than previous releases.

**Comment by kennethtran93** [comment]
Please follow the bug report template.  In addition site you were on as well as the debug logs would be helpful.

**Comment by kennethtran93** [comment]
Manually closing as stale after a reasonable amount of time with no response.
