### ISSUE TITLE
[BUG] Cleanup log summary too large.

### ISSUE THREAD

**Issue by Pathduck** [mrdokenny/Cookie-AutoDelete#864]
**Describe the bug**

Not actually sure if it's a bug, but it's certainly something new in 3.5.1 and it seems very unnecessary.

The issue is that for every manual clean I get a massive list of all whitelisted domains/hosts, like this:

`26/08/2020, 15:28:05 CEST - Some site data, including 0 Cookie(s), removed from: bbc.com, www.bbc.com, account.bbc.com, www.discogs.com, www.last.fm, web.archive.org ... [rest of 200 entries]`

Is this expected behaviour, and if it is, is there a setting to just have it write what it removed?

**To Reproduce**

1. Click on extension icon
2. Click on Clean
3. The huge list gets generated in the log

**Expected behavior**

I would expect it to only show the domains it clean, not the full whitelist.

**Screenshots**

n/a

**Your System Info (please complete the following information):**

 - Windows 10 Pro x64 build 2004
 - Browser Info: Vivaldi 3.3.2020.3 (Chrome/85.0.4183.80)
 - CookieAutoDelete Version: 3.5.1

**Additional context**

Might be a Vivaldi issue, I will check in older versions too.

**Comment by Pathduck** [comment]
Update: I cleaned all my cookies, and now the list is smaller, but it will keep growing as I visit more of my whitelisted sites.

I made a recording of what happens:
https://imgur.com/rUkBexx
Hope that makes it clearer?

Here's how the log looked like before I cleaned up the cookies, for perspective. I suspect it will be the same once I visit these whitelisted sites again.
![image](https://user-images.githubusercontent.com/1493836/91329208-2d6fd280-e7c8-11ea-87dd-208bb966c7f4.png)

**Comment by Pathduck** [comment]
Update: I think I figured out what makes it happen; If I select to not keep for instance Service Workers for a *whitelisted* domain, it will log the domain in the cleaning log *every time*. 

Example: 
![image](https://user-images.githubusercontent.com/1493836/91342205-f9ea7380-e7da-11ea-911e-914cfdbb2bfc.png)

**Comment by kennethtran93** [comment]
> The issue is that for every manual clean I get a massive list of all whitelisted domains/hosts[...]

While that takes away the 'auto' from CookieAutoDelete, that choice is up to you, and thus why you see massive lists instead of smaller ones from the true 'auto' cleaning.

> Is this expected behaviour, and if it is, is there a setting to just have it write what it removed?

As you figure it out, this is the expected behavior.  A domain will appear if either cookies or a part of the browsing data is cleaned up.

> Update: I think I figured out what makes it happen; If I select to not keep for instance Service Workers for a _whitelisted_ domain, it will log the domain in the cleaning log _every time_.

This should only occur if there is an internal cookie that CAD created when you revisit that site.  Reason being is that is how we clean browsing data items, otherwise there is no other way clean them by domain.

I suppose I just need to shrink the summary lines down a bit so it doesn't take up too much space as everything else is in the details.

**Comment by kennethtran93** [comment]
Reworded this as a request to limit the number of characters shown in the summary line.

**Comment by Pathduck** [comment]
Hi @kennethtran93 thanks for the reply!

> While that takes away the 'auto' from CookieAutoDelete, that choice is up to you, and thus why you see massive lists instead of smaller ones from the true 'auto' cleaning.

I understand this, and usually I just rely on auto cleaning. Sometimes I like to hit the clean button anyway.

My main issue is that it logs the same list on *every* trigger of the cleaning (as shown in the screen recording) - even the auto ones. For instance I just closed a tab from a non-whitelisted domain, waited 10 seconds and it logged the following:

`26/08/2020, 22:15:26 CEST - Some site data, including 3 Cookie(s), removed from: theregister.co.uk, theregister.com, www.theregister.com,... [rest of list followed]`

These other sites that are logged are white-listed, so why would it log anything at all? And even though "Keep Service Workers" is  deselected for them, I strongly doubt they've managed to register a SW in the meantime after the last clean.

> This should only occur if there is an internal cookie that CAD created when you revisit that site. Reason being is that is how we clean browsing data items, otherwise there is no other way clean them by domain.

I understand this, but say for instance: I have 2 cookies from `www.ecosia.org` which is whitelisted, no SW or local storage - why does it then need to log this domain at all? There is nothing there to be cleaned.

> I suppose I just need to shrink the summary lines down a bit so it doesn't take up too much space as everything else is in the details.

Sure this would work, but I still believe this is something new to this version which does not behave like it used to in the older versions. I could try to do the same in an older version and see what results I get.

By the way, I really appreciate your work and this extension is great, I just think this seems more like a bug than a missing feature.

**Comment by kennethtran93** [comment]
> These other sites that are logged are white-listed, so why would it log anything at all? And even though "Keep Service Workers" is deselected for them, I strongly doubt they've managed to register a SW in the meantime after the last clean.

This is because we cannot enumerate any of those browsing data, so we blindly execute the clean function for those domains which was queried from the cookies/internal cookie.

> > This should only occur if there is an internal cookie that CAD created when you revisit that site. Reason being is that is how we clean browsing data items, otherwise there is no other way clean them by domain.
> 
> I understand this, but say for instance: I have 2 cookies from `www.ecosia.org` which is whitelisted, no SW or local storage - why does it then need to log this domain at all? There is nothing there to be cleaned.

See point above.  From 3.5.1 I need to create an internal cookie (with subdomain if it has one) regardless if there's existing cookies from that site as some sites only set the main/root domain and not the subdomain itself.  (Only applies if at least one of the browsing data needs to be cleaned).  Cookies are the only item we can enumerate for domain checking.  The other alternative is to completely clean all the individual browsing types which would wipe it all away, regardless of domain.  This is already being accomplished when you enable the browsing data cleanup option in CAD Settings.

> Sure this would work, but I still believe this is something new to this version which does not behave like it used to in the older versions. I could try to do the same in an older version and see what results I get.

This is because prior to 3.5.0 there was no way of knowing if browsing data got cleaned properly or was executed to be cleaned by CAD or something else.

> 
> By the way, I really appreciate your work and this extension is great, I just think this seems more like a bug than a missing feature.

And thus why I left it as bug again with the intent to limit the summary lines.

**Comment by Pathduck** [comment]
> This is because we cannot enumerate any of those browsing data, so we blindly execute the clean function for those domains which was queried from the cookies/internal cookie.

OK I think I understand it now, and I'm sure there are good technical reasons for why it has to work this way. My issue was that this was very different for how 3.4.0 logged its cleaning. Even with Local Storage cleaning on.

Since I was already in the process of replying anyway, here's another screen recording, of how it worked in 3.4.0. Opened a bunch of tabs, closed them again, and triggered a clean:
https://imgur.com/Uyq5lRj

Notice there are 31 deleted cookies from various domains, and subsequent triggers of Clean do not log anything else. There is also no log entry from `github.com`, even though it's set to not keep Local Storage - because there is no Local Storage so why would it log.

But now that I've read your reply I *think* I understand it. To be honest, like I said above I usually rely on the auto-clean, and rarely look at the log (I've even disabled clean notifications). I use the manual clean to test if CAD still works as expected, especially after an update with new features, hence this issue 😄
