### ISSUE TITLE
[BUG]  use of comma in regexp didn't Export and Import correctly

### ISSUE THREAD

**Issue by bzdzz** [mrdokenny/Cookie-AutoDelete#865]
**Describe the bug**
Use of comma in regexp didn't Export and Import correctly.

**To Reproduce**
1. Add Greylist regexpr:   /\w\.[a-z]{2,3}$/
2. Click on Export Expressions
3. Click on Import Expressions
4. See error, it created two entries of weird expressions from  /\w\.[a-z]{2,3}$/
--1st line entry:  /\w\.[a-z]{2
--2nd line entry:  3}$/

Seems the comma between 2 and 3 in original regexp caused the issue.

**Expected behavior**

Should not be two entries on two lines, should just be one line showing:  /\w\.[a-z]{2,3}$/

**Your System Info (please complete the following information):**
CAD 3.5.1
on chrome Version 85.0.4183.83 (Official Build) (64-bit)
windows 10 Version	10.0.14393 Build 14393

**Comment by kennethtran93** [comment]
This is primarily because we allow multiple expressions from one entry (either via Importing or through the settings) comma-separated.  I suppose I'll need to check if there's an actual regex slash before and after and re-combine them up again.

**Comment by bzdzz** [comment]
Yes, thanks, you got it, all inside of regex delimiter should be parse as regex.  And why does the export and import slice comma into two entries?  If you allow commas separated expr on one entry then that one entry should 'survive' the export and import, no? Thanks again!

**Comment by kennethtran93** [comment]
> And why does the export and import slice comma into two entries? If you allow commas separated expr on one entry then that one entry should 'survive' the export and import, no?

Each expression entry in CAD is only for ONE expression (regex or domain), thus why I initially separate it by comma is because you can do the following:  `github.com, gitlab.com, example.com` and it would automatically parse it into separate entries.  This logic followed through to the import.  Thus while hostnames do not have commas, the regex does (to which I forgot to account for).
