### ISSUE TITLE
[SUPPORT]  Grey-/Whitelist entries aren't saved anymore. Changes reset after restart. Only in one FF Profile

### ISSUE THREAD

**Issue by LtqxWYEG** [mrdokenny/Cookie-AutoDelete#866]
Hi :)

**Please describe what you need support with.**

CAD doesn't save the grey- and whitelist entries anymore. Old entries are still there, but new ones are disregarded after I restart Firefox.
CAD saves new entries when I use a different Profile. (One where I don't use my user.js) CAD is the only addon that has issues saving things.

**Describe the solution you'd like**

A reason and at best the setting, that stops CAD from being able to write to whatever file the lists are saved in. (As this is presumably the issue)

**Additional context**

Firefox 80, I use ghacks user.js and these addons: (Maybe it's one of them, like Temp. Container?)
CanvasBlocker	extension	1.3	true	
ClearURLs	extension	1.19.0	true	
Cookie AutoDelete	extension	3.5.1	true	
Decentraleyes	extension	2.0.14	true
HTTPS Everywhere	extension	2020.8.13	true	
Nano Defender for Firefox	extension	15.0.0.205	true
New Tab Suspender	extension	1.5	true
Session Sync	extension	3.1.12	true
Site Bleacher	extension	1.2.1	true	
Stylus	extension	1.5.13	true
Temporary Containers	extension	1.9.1	true	
uBlock Origin	extension	1.29.2	true	
uMatrix	extension	1.4.0	true

I don't remember when CAD stopped saving new entries to the lists. It was about a year ago. That's why I am testing "Site Bleacher", but that addon is not very good. (Though, if I remember correctly, it does clean more than CAD)

I assume the culprit is a setting in my user.js, but I have no idea which it is or why it would only cause an issue with CAD.

Thank you very much. :)

**Comment by kennethtran93** [comment]
> I don't remember when CAD stopped saving new entries to the lists. It was about a year ago. 

LOL that's around the time I started contributing and releasing updates myself.

> That's why I am testing "Site Bleacher", but that addon is not very good. (Though, if I remember correctly, it does clean more than CAD)

As of 3.5.1 CAD cleans most of the browsing data stuff (at least, those clearable by hostname), with the exception of data in the 'protectedWeb' category, to which Extension APIs do not have the ability to clean them yet.

> I assume the culprit is a setting in my user.js, but I have no idea which it is or why it would only cause an issue with CAD.

As I do not use that I cannot say what to do there.

What I will say is that we use the browser extension's localstorage to store data to persist between sessions/restarts.  Upon any change, it sets a delay of 1 second before saving it as a JSON string.

```js
// Delay saving to disk to queue up actions
let delaySave = false;
const saveToStorage = () => {
  if (!delaySave) {
    delaySave = true;
    setTimeout(() => {
      delaySave = false;
      return browser.storage.local.set({
        state: JSON.stringify(store.getState()),
      });
    }, 1000);
  }
};
```

If a fresh profile uses CAD and the user.js, what happens?
In your existing profile, try disabling one extension at a time to see if that is the culprit (yes some extension CAN remove other extension data...)

Note that this extension may not work properly in Private Browsing mode, and thus will not get full support at this time.

The only other thing that comes to mind is a partially corrupted profile, seeing that your fresh profile works for now.

Now is a great time to ensure that you have exported the backups for CAD Settings and Expressions (they will be in two separate files).

**Comment by LtqxWYEG** [comment]
> As I do not use that I cannot say what to do there.
It's basically a file where you can put all the settings from about:config, like "privacy.resistFingerprinting". I use these settings with a couple exceptions: https://github.com/ghacksuserjs/ghacks-user.js/blob/master/user.js
MY Firefox does not run in Private Browsing mode. But it's similar or better.


**### Ooooh**, it turns out there is an issue with CAD when used together with Temporary Containers addon - and it's one the CAD settings, because it works fine with the other profile, but default CAD settings. Anyway, here take a look: https://imgur.com/a/YZl3QGq

Don't tell me it's the option _"Enable Support for Firefox's Container Tabs"_ that's messing with me here. xD
I thought it would mean that CAD works together with Temp. Container and otherwise would not work. Hahaha omg... more than a YEAR and it turns out I'm just stupid. Damn it. XD
412 times did I try to add sites to the lists, but only did so for a temporary container that got deleted after closing...

But to be fair, even though I never clicked the question mark by the side of the setting before, like an idiot, the description wouldn't tell me that this is what's going to happen. Maybe you should add a note to it in the documentation. :)

Thank you anyway for your time. :)

**Comment by LtqxWYEG** [comment]
> As I do not use that I cannot say what to do there.
It's basically a file where you can put all the settings from about:config, like "privacy.resistFingerprinting". I use these settings with a couple exceptions: https://github.com/ghacksuserjs/ghacks-user.js/blob/master/user.js
MY Firefox does not run in Private Browsing mode. But it's similar or better.


**### Ooooh**, it turns out there is an issue with CAD when used together with Temporary Containers addon - and it's one the CAD settings, because it works fine with the other profile, but default CAD settings. Anyway, here take a look: https://imgur.com/a/YZl3QGq

Don't tell me it's the option _"Enable Support for Firefox's Container Tabs"_ that's messing with me here. xD
I thought it would mean that CAD works together with Temp. Container and otherwise would not work. Hahaha omg... more than a YEAR and it turns out I'm just stupid. Damn it. XD
412 times did I try to add sites to the lists, but only did so for a temporary container that got deleted after closing...

But to be fair, even though I never clicked the question mark by the side of the setting before, like an idiot, the description wouldn't tell me that this is what's going to happen. Maybe you should add a note to it in the documentation. :)

Thank you anyway for your time. :)

**Comment by LtqxWYEG** [comment]
> As I do not use that I cannot say what to do there.
It's basically a file where you can put all the settings from about:config, like "privacy.resistFingerprinting". I use these settings with a couple exceptions: https://github.com/ghacksuserjs/ghacks-user.js/blob/master/user.js
MY Firefox does not run in Private Browsing mode. But it's similar or better.


**### Ooooh**, it turns out there is an issue with CAD when used together with Temporary Containers addon - and it's one the CAD settings, because it works fine with the other profile, but default CAD settings. Anyway, here take a look: https://imgur.com/a/YZl3QGq

Don't tell me it's the option _"Enable Support for Firefox's Container Tabs"_ that's messing with me here. xD
I thought it would mean that CAD works together with Temp. Container and otherwise would not work. Hahaha omg... more than a YEAR and it turns out I'm just stupid. Damn it. XD
412 times did I try to add sites to the lists, but only did so for a temporary container that got deleted after closing...

But to be fair, even though I never clicked the question mark by the side of the setting before, like an idiot, the description wouldn't tell me that this is what's going to happen. Maybe you should add a note to it in the documentation. :)

Thank you anyway for your time. :)

**Comment by LtqxWYEG** [comment]
> As I do not use that I cannot say what to do there.
It's basically a file where you can put all the settings from about:config, like "privacy.resistFingerprinting". I use these settings with a couple exceptions: https://github.com/ghacksuserjs/ghacks-user.js/blob/master/user.js
MY Firefox does not run in Private Browsing mode. But it's similar or better.


**### Ooooh**, it turns out there is an issue with CAD when used together with Temporary Containers addon - and it's one the CAD settings, because it works fine with the other profile, but default CAD settings. Anyway, here take a look: https://imgur.com/a/YZl3QGq

Don't tell me it's the option _"Enable Support for Firefox's Container Tabs"_ that's messing with me here. xD
I thought it would mean that CAD works together with Temp. Container and otherwise would not work. Hahaha omg... more than a YEAR and it turns out I'm just stupid. Damn it. XD
412 times did I try to add sites to the lists, but only did so for a temporary container that got deleted after closing...

But to be fair, even though I never clicked the question mark by the side of the setting before, like an idiot, the description wouldn't tell me that this is what's going to happen. Maybe you should add a note to it in the documentation. :)

Thank you anyway for your time. :)

**Comment by LtqxWYEG** [comment]
> As I do not use that I cannot say what to do there.
It's basically a file where you can put all the settings from about:config, like "privacy.resistFingerprinting". I use these settings with a couple exceptions: https://github.com/ghacksuserjs/ghacks-user.js/blob/master/user.js
MY Firefox does not run in Private Browsing mode. But it's similar or better.


**### Ooooh**, it turns out there is an issue with CAD when used together with Temporary Containers addon - and it's one the CAD settings, because it works fine with the other profile, but default CAD settings. Anyway, here take a look: https://imgur.com/a/YZl3QGq

Don't tell me it's the option _"Enable Support for Firefox's Container Tabs"_ that's messing with me here. xD
I thought it would mean that CAD works together with Temp. Container and otherwise would not work. Hahaha omg... more than a YEAR and it turns out I'm just stupid. Damn it. XD
412 times did I try to add sites to the lists, but only did so for a temporary container that got deleted after closing...

But to be fair, even though I never clicked the question mark by the side of the setting before, like an idiot, the description wouldn't tell me that this is what's going to happen. Maybe you should add a note to it in the documentation. :)

Thank you anyway for your time. :)

**Comment by LtqxWYEG** [comment]
> As I do not use that I cannot say what to do there.

It's basically a file where you can put all the settings from about:config, like "privacy.resistFingerprinting". I use these settings with a couple exceptions: https://github.com/ghacksuserjs/ghacks-user.js/blob/master/user.js
MY Firefox does not run in Private Browsing mode. But it's similar or better.


**### Ooooh**, it turns out there is an issue with CAD when used together with Temporary Containers addon - and it's one the CAD settings, because it works fine with the other profile, but default CAD settings. Anyway, here take a look: https://imgur.com/a/YZl3QGq

Don't tell me it's the option _"Enable Support for Firefox's Container Tabs"_ that's messing with me here. xD
I thought it would mean that CAD works together with Temp. Container and otherwise would not work. Hahaha omg... more than a YEAR and it turns out I'm just stupid. Damn it. XD
412 times did I try to add sites to the lists, but only did so for a temporary container that got deleted after closing...

But to be fair, even though I never clicked the question mark by the side of the setting before, like an idiot, the description wouldn't tell me that this is what's going to happen. Maybe you should add a note to it in the documentation. :)

Thank you anyway for your time. :)

**Comment by kennethtran93** [comment]
When the container option is unchecked, we only check the default/non-container one.  If you added the expression via the popup then it will not have any effect on new containers due to the fact that it has been put under that container.  That function will not change.  

There is no 'global' option for containers - each container must be configured separately.

If you're using temporary containers that will be removed, using CAD along side that is kind of useless.

Closing as you seem to have resolved it yourself.
