### ISSUE TITLE
[SUPPORT] Local Storage not being removed. MacOS 10.13.6. Firefox 68.12/Firefox 78.2. CAD 3.5.1. Have checked open/closed issues + FAQ and instructions for use. Steps to reproduce: 1. Enable LocalStorage Cleanup. 2. go to site: newyorker.com. 3. Leave domain 4. Go to Manage Data in Preferences Privacy/Security. 5. See newyorker cookies have been removed, but still seeing 48KB Local Storage for newyorker.com. https://i.postimg.cc/FzTxqTC6/local-storage-48-KB.jpg  

### ISSUE THREAD

**Issue by 9jkh** [mrdokenny/Cookie-AutoDelete#872]
**Please describe what you need support with.** 

A clear and concise description of what you need support with.

**Describe the solution you'd like** 

**Additional context**

**Comment by kennethtran93** [comment]
Not sure how you managed to not follow the instructions when writing bug reports.

Your answer remains within the FAQ section https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/FAQ:-Common-Questions-and-Issues#why-do-i-still-see-storage-being-used-after-cad-cleans-cookies-and-localstorage-data.

Try enabling cleanup for indexedDB and see if that helps.  That storage column is NOT just localStorage, but possibly indexedDB and/or cache or other browsing site data as well.  From another finding, it seems that for some reason the residual storage may be an empty indexedDB database as well.  That may be a bug in Firefox's area and not ours.  As far as this extension goes, we pass on the domain to be cleaned to the firefox webextension APIs, and then they take care of the rest.  We have no way of checking if those other browsing data types get cleaned or not.

**Comment by 9jkh** [comment]
Only checked for this behavior from one site known to leave local storage, newyorker.com, so small chance this might be tentative, but enabling cleanup for IndexedDB appears to have done the job.

Thanks.
