### ISSUE TITLE
[FEATURE REQUEST] Backup settings to Cloud

### ISSUE THREAD

**Issue by robahearts** [mrdokenny/Cookie-AutoDelete#882]
Hi. Can we get the option to back up the settings to the clouds like ublock origin instead of exporting the settings ? See - https://github.com/gorhill/uBlock/wiki/Cloud-storage

**Comment by kennethtran93** [comment]
Duplicate of #30.

I do agree that when sync is implemented that it should not overwrite anything automatically.
