### ISSUE TITLE
New Feature: Change cookie name then put it back

### ISSUE THREAD

**Issue by cosminv6u** [mrdokenny/Cookie-AutoDelete#89]
### When the cookies are deleted from Facebook for example, I need to login again next time I open Facebook

Instead of deleting the cookies from Facebook, when I close the Facebook tab => change the name (and/or domain property) of the cookies by adding a prefix.
Then when a new tab is opened with facebook.com => remove the prefix of the Cookie (restore the original name).

**Comment by mrdokenny** [comment]
I don't think this is the right addon for you since the name has "autodelete". Anyways if you are trying to prevent other sites from reading cookies, you best block third party cookies in the browser.
