### ISSUE TITLE
[SUPPORT] Umbrella issue for unsupported chromiums

### ISSUE THREAD

**Issue by Hadden89** [mrdokenny/Cookie-AutoDelete#897]
**Is your feature request related to a problem? Please describe.** I know only Chrome, Firefox and Edge are supported but would be nice to have an opened umbrella issue for people which are using unsupported browsers.

For example, the popup is broken with Vivaldi 3.3.2022.35 (and 3.4 too) but the interesting thing is it works fine if you don't add any rule (red badge) while its broken when a rule is add (blue badge) and is this way since CAD 2.0 Final to last version. Probably even Opera Browser (and Brave) have this issue.

**Describe the solution you'd like** A fallback mechanism for the popup which could increase the compatibility and the popularity on minor browsers too.

Allow people to discuss (politely) on **this** issue to see if something could be made for solve (some) issues. 
The extension should show a warning on unsupported browser pointing to this feature/issue only. 

**Describe alternatives you've considered** Not using CAD is the only alternative, I fear, as I won't switch the browser.

**Missing solution for feature request.** Community interaction which could provide some solutions/workarounds. I know this probably won't happen, but asking don't hurt :)

**Comment by Hadden89** [comment]
@kennethtran93

**Comment by Hadden89** [comment]
For some reason the bot seems to still close this :(

**Comment by kennethtran93** [comment]
Ah yes you had modified that specific section title. Try copying the one from the template again and replacing that section header.

**Comment by Hadden89** [comment]
But the feature request template itself don't have the "Missing solution for feature request".
I've only removed the optional parts (additional context/screenshots).
I think the bot is too sensitive for some reason.

**Comment by kennethtran93** [comment]
Ahh `A clear and concise description of what you want to happen ` and the other `a clear and... ` are not headings. They're there as something you replace with your own text. Remove those and you should be fine.

**Comment by Hadden89** [comment]
Thanks, probably now the bot won't close it.

**Comment by kennethtran93** [comment]
> I know only Chrome, Firefox and Edge are supported but would be nice to have an opened umbrella issue for people which are using unsupported browsers.
> For example, the popup is broken with Vivaldi 3.3.2022.35 (and 3.4 too) but the interesting thing is it works fine if you don't add any rule (red badge) while its broken when a rule is add (blue badge) and is this way since CAD 2.0 Final to last version.

People are free to create issues, but if it works in Chrome, Firefox, and/or Edge but not the other browsers , then that's where I draw the line at.

As it stands the popup works fine when I'm using it on my regular profile as well as in Chrome, so as it stands I won't be able to dive too much deeper into this.


> A fallback mechanism for the popup which could increase the compatibility and the popularity on minor browsers too.

Not sure what fallback mechanism for the popup were you intending - all popups are done through the browser itself, loading our html/javascript page which uses bootstrap.


> Allow people to discuss (politely) on the issue to see if something could be made for solve (some) issues.

As said above, one can create issues, but if it cannot be replicated on Firefox, Chrome, and/or Edge Chromium then that's where I draw the line at.  HOWEVER, that doesn't mean that I won't accept any Pull Requests for them as long as it doesn't affect the main browsers.

> The extension should show a warning on unsupported browser pointing to this feature/issue only.

This may be hard to differentiate between the main and minor ones as there's no decent way of doing this - even Vivaldi browser's user agent is trying to mimic chrome browser's user agent.  We're only using duck typing to differentiate between Firefox, Firefox Android, and Chrome for certain functionalities.

> Not using CAD is the only alternative, I fear, as I won't switch the browser.
> 
> Community interaction which could provide some solutions/workarounds. I know this probably won't happen, but asking don't hurt :)

Mentioned above, but Pull Requests that may resolve the issue of that browser but not affect the main one may be accepted.

**Comment by kennethtran93** [comment]
Converting this to a support issue as it currently stands.

**Comment by Hadden89** [comment]
The relevant bug on Vivaldi is **VB-39040**, which is confirmed. 
Would be interesting to read something from other browser devs/users (Opera/Brave) to see if this issue can be mitigated. Or if it happens at all.

**Comment by Hadden89** [comment]
I leave a potential workaround here for [Vivaldi Users](https://forum.vivaldi.net/post/431823). Almost any CAD [cleaning] function seems to work correctly. =)
