### ISSUE TITLE
[SUPPORT] Keep selected cookies for a domain only?

### ISSUE THREAD

**Issue by JustMyGithub** [mrdokenny/Cookie-AutoDelete#926]
**Please describe what you need support with.** 

Is there a way to delete more fine-grained than on domain level?

(Thanks to God and the EU for this ....)

**Describe the solution you'd like** 

I ask because I would like to keep some cookie consent cookies without keeping other (identifying) cookies of the same domain, where possible.

**Comment by JustMyGithub** [comment]
I dared to remove the headlines after reading them and filling out, so it was locked .... @kennethtran93

**Comment by kennethtran93** [comment]
Yes.

Simply whitelist the domain while on that site, and uncheck `Keep All Cookies`. Then you will need to figure out which is the cookie(s) you want to keep. Check the ones you want to keep, then perform a cleanup and refresh page to see if you selected the right one. If you have cleanup log and counter enabled, then you can undo the removal of the cookies done by CAD.

**Comment by JustMyGithub** [comment]
Ah, If I unselect "keep all" the known cookies are presented for selection - didnt know/notice. awesome, thank you.

**Comment by kennethtran93** [comment]
You're welcome.

Closing as resolved.
