### ISSUE TITLE
popup not shown at all when clicking icon (whiteList is undefined)

### ISSUE THREAD

**Issue by breunigs** [mrdokenny/Cookie-AutoDelete#93]
### Describe the Bug/Feature

I'm using Firefox 55.0b2 on Linux. The popup when clicking the icon is completely empty. When starting Firefox I can see the following error message:
```
Extension error: TypeError: whiteList is undefined moz-extension://60a272eb-63a1-476c-8cff-657ca60b8dfb/background-webpack.js 833
[[Exception stack
checkIfProtected@moz-extension://60a272eb-63a1-476c-8cff-657ca60b8dfb/background-webpack.js:833:1
exposedFunctions</<@moz-extension://60a272eb-63a1-476c-8cff-657ca60b8dfb/background-webpack.js:847:3
Current stack
runSafeSyncWithoutClone@resource://gre/modules/ExtensionUtils.jsm:54:129
runSafeWithoutClone@resource://gre/modules/ExtensionCommon.jsm:176:38
receiveMessage@resource://gre/modules/ExtensionChild.jsm:763:61
_callHandlers/<@resource://gre/modules/MessageChannel.jsm:585:17
_callHandlers@resource://gre/modules/MessageChannel.jsm:584:14
_handleMessage/deferred.promise<@resource://gre/modules/MessageChannel.jsm:649:7
_handleMessage@resource://gre/modules/MessageChannel.jsm:646:24
receiveMessage@resource://gre/modules/MessageChannel.jsm:163:5
]]
```
The error message does not appear when I enable the extension in a running Firefox or click the toolbar icon. 

### Screenshot in which the bug can be seen

![2017-08-05-113021_1920x1080_scrot](https://user-images.githubusercontent.com/307954/28994571-97540756-79d1-11e7-89d7-c38cf0aa904a.png)

### Steps for anyone to reproduce the bug

I'm new to CAD, so I guess this is a 55+ bug?

### Your settings 

- OS/version: Linux aard 4.11.0-1-amd64 #1 SMP Debian 4.11.6-1 (2017-06-19) x86_64 GNU/Linux
- Browser/version: Firefox 55.0b2 from the Debian sid repository
- Cookie AutoDelete version: 1.4.1

**Comment by mrdokenny** [comment]
`Extension error: TypeError: whiteList is undefined` 

Interesting, not sure why the whitelist failed to load. CAD works fine for me on 55+ so you might want to try a new profile.

**Comment by breunigs** [comment]
Hrm, I thought my profile was fairly fresh. Maybe some weird leftovers from an intermediate better. In any case a new profile does work and I have not yet figured out what feature/setting broke CAD to begin with. If I find it, I will reopen this ticket. Thanks for the support!

**Comment by breunigs** [comment]
Ha, figured it out: The error message shows for me when I set Preferences → General → When Firefox Starts → Show Windows and Tabs from Last Time

**Comment by mrdokenny** [comment]
So the error only happens on startup and when clicking on the popup correct?

**Comment by breunigs** [comment]
No, only on startup. The pop up works, even with "show tabs from last time" enabled. That the popup didn't work is probably some other unrelated bug.

**Comment by breunigs** [comment]
yes, even with "show tabs from last time" CAD deletes non-whitelisted cookies on startup ("Clean Cookies from Open Tabs on StartUp" is checked). It also normally deletes cookies of non-whitelisted domains after closing the tab and waiting for the timeout.

**Comment by mrdokenny** [comment]
I do remember something like this happening and added a delay for it in this code

https://github.com/mrdokenny/Cookie-AutoDelete/blob/master/src/background.js#L188

but it's kinda random if it works or not. 

If that error doesn't interfere with the operation of C-AD, then it might be just the browser.

**Comment by mrdokenny** [comment]
I think people said that the solution here is to enable e10s.
