### ISSUE TITLE
do not fail when deleting cookies without host

### ISSUE THREAD

**Issue by breunigs** [mrdokenny/Cookie-AutoDelete#94]
### Describe the Bug/Feature

Apparently some website/extension managed to have cookies set without host. Looking at their expiry dates in Firefox' own cookie manager, it says something like 2016. My best guess is something went wrong during the profile refresh. Either way CAD shouldn't fail if there's some weird cookies like this.

When the CAD "delete old cookies" routine runs, it iterates over all cookies and tries to parse their hostname. These weird cookies have none, and Firefox returns "http://", leading to a "TypeError: http:// is not a valid URL."

The error message then points to https://github.com/mrdokenny/Cookie-AutoDelete/blob/master/src/services/UsefulFunctions.js#L65 . Well, the webpacked equivalent anyway.

### Screenshot in which the bug can be seen

I believe the site you can see in the screenshot is unrelated.

![2017-08-05-172744_1920x1080_scrot](https://user-images.githubusercontent.com/307954/28996693-8e81f884-7a05-11e7-8ccb-001bf38d2f74.png)
![2017-08-05-173720_1920x1080_scrot](https://user-images.githubusercontent.com/307954/28996639-e6631b92-7a04-11e7-93db-2d864e3f8e6f.png)

### Steps for anyone to reproduce the bug

I am not sure how these cookies were added/generated.

### Your settings 

*    OS/version: Linux aard 4.11.0-1-amd64 #1 SMP Debian 4.11.6-1 (2017-06-19) x86_64 GNU/Linux
*    Browser/version: Firefox 55.0b2 from the Debian sid repository
*    Cookie AutoDelete version: 1.4.1

**Comment by mrdokenny** [comment]
Thanks for the bug report. My first thought is maybe add a test for an empty hostname and make that return an empty string?

https://github.com/mrdokenny/Cookie-AutoDelete/blob/master/test/UsefulFunction-spec.js#L113

**Comment by JadedTuna** [comment]
@mrdokenny it seems like this is the reason CAD may stop working after a while. I manually removed cookies without host and CAD started working again.

**Comment by mrdokenny** [comment]
That should fix it, but it's going to be hard to test because I'm not sure how to set a cookie without a hostname. I tried using the console in the settings page of C-AD (just found out you can do that) but the [webext cookie API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/cookies/set) does not allow for an empty string. Feel free to test 1.4.2 when it shows up in Releases.

**Comment by Erlotinib** [comment]
Hello,

I can confirm v1.4.3 fix the problem: the blank cookie is still here (not deleted) but it doesn't prevent others to be deleted.

**Comment by breunigs** [comment]
Awesome, thanks everyone! I guess this can be closed now.
