### ISSUE TITLE
[SUPPORT]  How does cookie autodelete interact with Firefox containers?

### ISSUE THREAD

**Issue by yololftw** [mrdokenny/Cookie-AutoDelete#951]
**Please describe what you need support with.** 

Hi, I have been using cookie auto delete for a while now and love what it does, it has made my life very easy wrt cleaning up 

This week I enabled firefox multi container extension which keeps things separated (I was using just the Facebook container before). Now what I want to know is how the cookies auto delete works with Firefox containers 

**Describe the solution you'd like** 

When I whitelist something I am assuming the settings are global, are there any recommendations for this new setup with containers.

**Additional context**

**Comment by kennethtran93** [comment]
The only setting that is somewhat global are the other browsing data cleanup, as well as any other settings configured in CAD settings.  A warning is given in the settings (and documentation) about its side effects. 

Each container has its own list.  To see all configured expressions you'll need to go to list of Expressions. If you have recently enabled containers, then the previous expressions simply fall under the 'no container' list.  Each container requires you to set its own expressions.

There is no 'global' list that affects all container when it comes to cookie removal.

**Comment by yololftw** [comment]
Makes sense, thanks for the info. Ill close this and re open if I find any issues
