### ISSUE TITLE
[BUG] local storage gets deleted for whitelisted domains (Firefox containers)

### ISSUE THREAD

**Issue by gingerlime** [mrdokenny/Cookie-AutoDelete#952]
**Describe the bug** 

If I have a whitelisted domain in one container, and I open it in another container, after I close the other container tab, local storage will be deleted even for the whitelisted container

**To Reproduce** 

1. Set up a domain as whitelisted in container X
2. browse the domain in container X will generate some local storage data
3. open the same domain in container Y (not whitelisted)
4. close container Y - local storage in container X will be deleted

**Expected Behavior** 

It should ideally honor the whitelist for container X and keep local storage in that container

**Your System Info** 

- OS: MacOS Mojave
- Browser Info: Firefox 82.0.2
- CookieAutoDelete Version: 3.5.1

**Comment by gingerlime** [comment]
Thanks for CAD ! It's awesome :) hope I didn't miss any old/existing issues but I did search read the FAQ etc.

**Comment by kennethtran93** [comment]
You didn't read the documentation where it notes this (and it is also noted in CAD settings).  This is a browser limitation at this time.

https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/Documentation#other-browsing-data-cleanup-options

**Comment by gingerlime** [comment]
Hi @kennethtran93 sorry about that. Do you mean this note? 

> WARNING: Upon enabling any of the following site data cleanup options, ALL existing data for that type will be cleared.

I guess it wasn't clear to me that it applies across containers and even whitelisted containers.

**Comment by kennethtran93** [comment]
Not that one, should be the one near the containers option.

The browser api isn't fine tuned to remove only a certain piece of site data per container - only cookies at this time can be removed depending on the container.

There is nothing we can do at this point in time. When they revise it then we'll see.

If you're curious the browser api in question is this: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browsingData which takes care of everything else except cookies.

**Comment by gingerlime** [comment]
Thanks a lot for the info. I can now better understand why this limitation exists... 

Is there a way to work around it though, e.g. can CAD run some custom JS just before clean-up? and then you could potentially run something like `localStorage.clear()` inside the container, and this should have limited impact only inside the specific container, right?

**Comment by kennethtran93** [comment]
> Is there a way to work around it though, e.g. can CAD run some custom JS just before clean-up? and then you could potentially run something like `localStorage.clear()` inside the container, and this should have limited impact only inside the specific container, right?

There's no specific webextension API that does this at this time.  We try not to hog resources too much by using listeners on certain triggers, such as `tabs.onRemoved`, `tabs.onUpdated`, `cookies.onChanged`, etc.

You're thinking of using `tab.executeScript` to inject a cleanup function into `window.onbeforeunload` or `window.onunload` to clean up that domain's site data.  While that is doable, if a user decides to add/modify a rule for that domain, I don't think it would be easy to undo the function removal.  In addition, this would also trigger "on unload" which would most likely mean either on tab close or domain change.  Our extension allows domain change in the same tab without triggering cleanups.

Alternatively we could open a port connection via [`runtime.connect()`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/Port) when the page is unloaded and process rules then, but that may delay the closing of the tab, and even then we cannot check if the domain has changed.

`localStorage.clear()` would only affect that domain, not its whole container.  There is nothing that will affect the container itself, aside from the removal of cookies per container which I'm tackling at the moment.

**Comment by gingerlime** [comment]
Thanks again @kennethtran93. I have no experience with those things, and it's obvious that you have lots of in-depth experience and knowledge. I appreciate sharing the details. It seems like a tough nut to crack. Hope the API evolves or someone comes with a clever workaround. Thank you for creating and maintaining CAD. It's extremely valuable for privacy.
