### ISSUE TITLE
[SUPPORT]  Need explanation of google cookie with value "CookieAutoDeleteBrowsingDataCleanup"

### ISSUE THREAD

**Issue by 9jkh** [mrdokenny/Cookie-AutoDelete#955]
**Please describe what you need support with.** 

Want to understand meaning of google cookie with value "CookieAutoDeleteBrowsingDataCleanup"

**Describe the solution you'd like** <Solution would be an explanation of this behavior.>

**Additional context**

**Comment by 9jkh** [comment]
Doesn't seem all that complicated. Just want to know if this is expected/normal CAD behavior. A reply would be appreciated. Thank you.

**Comment by kennethtran93** [comment]
This is explained had you read the documentation.  https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/Documentation#other-browsing-data-cleanup-options

This is normal if you have enabled at least one of the 'other browsing data options' as there is no way to enumerate any of those site data types (cache, indexedDB, localStorage, pluginData, ServiceWorkers), so we rely on cookies for that.

**Comment by 9jkh** [comment]
>>This is explained _had you read_ the documentation....

Want to point out to you that github is listed as the support site for CAD at Firefox Add-ons, and as you would prefer not to answer support questions at the add-ons site, I have to come here for help. You should understand that not everyone visiting github from Firefox Add-ons is as technically advanced as you seem to assume. There may be quite a few, myself included, with only some rudimentary understanding of the technical issues involved. I may have read that passage to which you linked many times without a clear or even beginning understanding of its implications for my question. 

My point being that you seem to display a rather contemptuous attitude here to those who may not be as advanced as you would like. Your add-on is available to many, not just those with an advanced understanding of the underlying programming technicalities. 
  
I found the "had you read...." to be a particularly snide and offensive comment, which could have been omitted. Why don't you just offer help without the needlessly snarky tone?

I have also visited github for other support issues, not just your add-on, and never found any difficulty asking for help. As others here seem to have noticed, the required template is not at all intuitive, not easily understood. Could be made a lot clearer. I had to make two passes with it before my request for help was accepted, and not summarily rejected by the bot. After the second try I was quite ready to give up. To put it simply, getting help here can be a huge pain in the ass.

Otherwise, I appreciate the excellent work you have done with CAD, and you should know that I already donated in the past, but will have to think twice before I ask for help again.

**Comment by kennethtran93** [comment]
Apologies there - looks like part of my personal mood at that time got reflected here.  I typed up that answer on my mobile device using the GitHub App while on the go.

Looks like I should get in touch with Kenny to see what the donation status is for the past year or so at as it seems that the majority of contributions were done by yours truly with reviews by Kenny.

**Comment by 9jkh** [comment]
I appreciate the gracious reply. Any chance that the templates might be simplified, made more intuitive, at least for the Support requests? Can understand bug report/feature request needing all that, but perhaps just let users ask for support on their own terms? As currently written, the template is needlessly confusing.

Without your template, I could originally have just marked the comment "Support" and written everything that appears under _"Additional context <!--"_  more simply instead under _"Please describe what you need support with."_ Don't really think anything else would have been needed to write a coherent support request.

Also, for any template just where to place text, using <!-- isn't very clear. At least I haven't come across that before.

**Comment by kennethtran93** [comment]
> I appreciate the gracious reply. Any chance that the templates might be simplified, made more intuitive, at least for the Support requests? Can understand bug report/feature request needing all that, but perhaps just let users ask for support on their own terms? As currently written, the template is needlessly confusing.
> 
> Without your template, I could originally have just marked the comment "Support" and written everything that appears under _"Additional context <!--"_ more simply instead under _"Please describe what you need support with."_ Don't really think anything else would have been needed to write a coherent support request.
> 
> Also, for any template just where to place text, using <!-- isn't very clear. At least I haven't come across that before.

Thanks for the feedback.  You can probably tell the support template was, for the most part, a copy of the feature request template.  I've simplified the support issue template and added some instructions to all templates to clarify which part should be replaced with their own response.  The GitHub action that monitors new/reopened issue requests have been updated to reflect the changes in support template.

I've also added a legacy issue template for those what bypassed the whole issue type selection page `/issues/new/choose` as well as it seems that users can directly access the `/issues/new` page even if I have `blank_issues_enabled: false` in the page config.
