### ISSUE TITLE
[BUG]  localStorage cleanup displays "Error" notification in Firefox Nightly

### ISSUE THREAD

**Issue by ghost** [mrdokenny/Cookie-AutoDelete#959]
**Describe the bug** 

Few days ago Cookie AutoDelete started displaying "Error" notification when cleaning is triggered.

**To Reproduce** 

- Set `dom.storage.next_gen` option in `about:config` to `false` (not sure if this was changed by bug 1670811 i had this set for long time, probably "next_gen" causes storage issues)
- Enable cleaning
- enable localStorage support
- (not sure about this one) enable support for Firefox containers
- open few pages in tabs and close them

**Expected Behavior** 

Storeage cleaned without issues.

**Screenshots** 

![image](https://user-images.githubusercontent.com/886325/98305402-1288be00-1fc2-11eb-8641-2edca20d842f.png)

![image](https://user-images.githubusercontent.com/886325/98305372-043aa200-1fc2-11eb-8a29-9c208a70e6ae.png)

**Your System Info** 

- OS: Manjaro KDE
- Browser Info: Firefox Version 	84.0a1 Build ID 	20201105045247
- CookieAutoDelete Version: 3.5.1

**Additional context** 

Started after https://bugzilla.mozilla.org/show_bug.cgi?id=1670811 Confirmed by mozregression 

```
26:34.74 INFO: Running autoland build built on 2020-11-03 19:45:20, revision 12e386f1
26:47.08 INFO: Launching /tmp/tmp7ck8w5a5/firefox/firefox
26:47.08 INFO: Application command: /tmp/tmp7ck8w5a5/firefox/firefox --allow-downgrade --allow-downgrade -profile /home/rdk/.mozilla/firefox/4gucti37.dev-edition-default
26:47.09 INFO: application_buildid: 20201103183559
26:47.09 INFO: application_changeset: 12e386f1f5413415698dddd8cce87b00086b1279
26:47.09 INFO: application_name: Firefox
26:47.09 INFO: application_repository: https://hg.mozilla.org/integration/autoland
26:47.09 INFO: application_version: 84.0a1
Was this integration build good, bad, or broken? (type 'good', 'bad', 'skip', 'retry', 'back' or 'exit' and press Enter): bad
27:34.40 INFO: Narrowed integration regression window from [0db0e6a3, a0678795] (3 builds) to [0db0e6a3, 12e386f1] (2 builds) (~1 steps left)
27:34.40 INFO: No more integration revisions, bisection finished.
27:34.40 INFO: Last good revision: 0db0e6a3f8f01d3060adeaaa0aa599b169811f24
27:34.40 INFO: First bad revision: 12e386f1f5413415698dddd8cce87b00086b1279
27:34.40 INFO: Pushlog:
https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=0db0e6a3f8f01d3060adeaaa0aa599b169811f24&tochange=12e386f1f5413415698dddd8cce87b00086b1279
```

Filed Firefox issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1675643

**Comment by kennethtran93** [comment]
Thank you for the heads up on a potential bug.

I'll wait and see what gets pushed down to Developer Edition (which is currently sitting at version 83).

For the time being my next_gen setting is already set to false, and it is the default one on both the general and developer edition one.

At this time I'm not very clear on what exactly are the changes between the next_gen usage, other than it seems to be a QuotaManager thing and maybe a physical file change? As long as the API calls do not need to change it shouldn't be a bug on our end yet.  I suspect once they implement cleaning site data by container this will definitely be an adjustment, though whether or not this `next_gen` issue is related to that is another thing.

**Comment by ghost** [comment]
Fixed on Firefox side.

**Comment by kennethtran93** [comment]
If and when I implement cleanup of localstorage and indexedDB on Firefox 84+ (maybe chrome as well) by cookieStoreId, I should ensure I wrap it around a try/catch block to silently ignore the disabled `next_gen` option.
