### ISSUE TITLE
Wildcard domains aren't properly evaluated

### ISSUE THREAD

**Issue by dzm06** [mrdokenny/Cookie-AutoDelete#97]
### Describe the Bug/Feature

If I use a text editor to create wildcard domains (*.google.com), then import this file, the domain does not get correctly evaluated. Rather than implicitly white listing

foo.google.com
www.google.com
google.com

I instead have cookies from ALL the Google domains deleted regularly (i.e. NO domains are matched by the wildcard).

**Comment by mrdokenny** [comment]
C-AD doesn't support the wildcard. The default behavior is "google.com" will match *.google.com as per the cookie spec.

https://github.com/mrdokenny/Cookie-AutoDelete/issues/3#issuecomment-304912809

Currently the whitelist/greylist architecture of this extension does not support for a wildcard, so a lot of this stuff will have to be redone.

**Comment by dzm06** [comment]
I see. My confusion, then, stems from the ToolTip text:

`When enabled, *.example.com will match example.com. Turning this off gives you more granular control over your lists.`

Thanks!
