### ISSUE TITLE
[BUG]  Harmful language

### ISSUE THREAD

**Issue by AO-LocLab** [mrdokenny/Cookie-AutoDelete#973]
Describe the bug

**Harmful language**

Throughout Cookie Autodelete, we find the term “White List”, a term which should no longer be used and be replaced. 

**To Reproduce**

**Expected Behavior**

**Replace “white list” with an appropriate term**

An appropriate replacement term should be chosen, possibly from:
https://inclusivenaming.org/language/word-list/

**Your System Info**

- CookieAutoDelete Version: 3.5.1

**Comment by kennethtran93** [comment]
Closing as Duplicate of #754.
