### ISSUE TITLE
[BUG] “Invalid Containers” cannot be deleted

### ISSUE THREAD

**Issue by ghost** [mrdokenny/Cookie-AutoDelete#985]
**Describe the bug**

Since version 3.5.0 was released, any list stored in CAD that does not match a Firefox container is replaced by the words "invalid container” in red. Unfortunately, there appears to be no way to delete these lists: the only buttons are to remove all expressions globally or all expressions from a selected list. Deleting all expressions from a list does not delete the list, meaning that the CAD Expressions page progressively fills with an increasing number of "invalid containers” that cannot be deleted.

**To Reproduce**

1. Create container in Firefox
2. Add preferences using CAD for this container
3. Check that it appears in “List of Expressions”
4. Delete the container
5. Container is now marked as invalid in CAD
6. Invalid container cannot be removed from CAD

**Expected Behavior** 

Whenever a container is deleted within Firefox, CAD should either delete it automatically from its own lists or allow the user to remove it manually.

**Your System Info** 

- OS: macOS 10.15.7
- Browser Info: Firefox 84.0
- CookieAutoDelete Version: 3.5.1

**Comment by ts1a** [comment]
It's a known bug: https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/891

**Comment by kennethtran93** [comment]
#904 partially fixes the issue with list not being removed if last expression is deleted.  It just hasn't been pushed out yet as it was merged with the code that will be pushed out as 3.6.0 which has some additional translations. I'm going to try and get a newer beta pushed out on the repo, if one hasn't been made yet.

**Comment by kennethtran93** [comment]
#820 and others houses the feature to remove expression list if its corresponding container is removed (new setting option).

**Comment by kennethtran93** [comment]
Going to close this as the relevant bugs have been fixed, albeit not pushed out to users yet.

**Comment by kennethtran93** [comment]
3.6.0 alpha is out for testing if you would like - https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/releases/tag/v3.6.0-alpha
